### ISSUE TITLE
Some providers have been discarded due to unexpected errors: opensubtitles

### ISSUE THREAD

**Issue by andradadad** [Diaoul/subliminal#1008]
Have been using "subliminal download -l en C:\Folder" for years, and Subliminal now stopped working for a long time.

Tried setting "subliminal --opensubtitles Login Pass" unsuccessfully.  Don't recall setting a profile credential, but it's obvious there was some somewhere just not in every commandline I have had used.

```
 "subliminal --opensubtitles X X"
Usage: subliminal [OPTIONS] COMMAND [ARGS]...
Error: Missing command.
```
Tried with other software, and it works. By downloading with the commandline and the login and pass gives:
`0 video collected / 1 video ignored / 0 error`

Is there any python file I can edit to manually insert the login?
Strange it worked perfectly for years.
Windows 7 64bit.

**Comment by andradadad** [comment]
```
subliminal --debug download -l nl "G:\movie\"
Collecting videos  [####################################]  100%  G:\movie"DEBUG:subliminal.cli:
Collecting path G:\movie
 [YTS.MX]"
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
INFO:subliminal.core:Refining video with omdb
ERROR:subliminal.core:Failed to refine video
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\subliminal\core.py", line 542, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "c:\python27\lib\site-packages\subliminal\refiners\omdb.py", line 155, in
 refine
    results = search(video.title, 'movie', video.year)
  File "c:\python27\lib\site-packages\dogpile\cache\region.py", line 1231, in de
corate
    should_cache_fn)
  File "c:\python27\lib\site-packages\dogpile\cache\region.py", line 833, in get
_or_create
    async_creator) as value:
  File "c:\python27\lib\site-packages\dogpile\lock.py", line 154, in __enter__
    return self._enter()
  File "c:\python27\lib\site-packages\dogpile\lock.py", line 87, in _enter
    value = value_fn()
  File "c:\python27\lib\site-packages\dogpile\cache\region.py", line 788, in get
_value
    value = self.backend.get(key)
  File "c:\python27\lib\site-packages\dogpile\cache\backends\file.py", line 220,
 in get
    with self._dbm_file(False) as dbm:
  File "c:\python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "c:\python27\lib\site-packages\dogpile\cache\backends\file.py", line 215,
 in _dbm_file
    "w" if write else "r")
  File "c:\python27\lib\anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
  File "c:\python27\lib\dumbdbm.py", line 253, in open
    return _Database(file, mode, flag)
  File "c:\python27\lib\dumbdbm.py", line 77, in __init__
    self._update()
  File "c:\python27\lib\dumbdbm.py", line 91, in _update
    key, pos_and_siz_pair = _ast.literal_eval(line)
  File "c:\python27\lib\ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "c:\python27\lib\ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    subliminal.providers.legendastv:get_archives|13660 1', (857088, 5777)
                                   ^
SyntaxError: invalid syntax
Collecting videos  [####################################]  100%

1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  movie"INFO:subliminal.core:Skipping provider 'l
egendastv': no language to search for
INFO:subliminal.core:Skipping provider 'shooter': no language to search for
INFO:subliminal.core:Listing subtitles with provider 'podnapisi' and languages s
et([<Language [nl]>])
INFO:subliminal.core:Skipping provider 'tvsubtitles': not a valid video
INFO:subliminal.core:Initializing provider podnapisi
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languag
es set([<Language [nl]>])
INFO:subliminal.core:Skipping provider 'addic7ed': not a valid video
INFO:subliminal.core:Skipping provider 'subscenter': no language to search for
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.providers.podnapisi:Searching subtitles {'sK': u'The Rental', 's
XML': 1, 'sY': 2020, 'sL': 'nl'}
INFO:subliminal.core:Skipping provider 'thesubdb': not a valid video
INFO:subliminal.providers.opensubtitles:Logging in
ERROR:subliminal.core:Unexpected error in provider 'opensubtitles'
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\subliminal\core.py", line 118, in list_sub
titles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "c:\python27\lib\site-packages\subliminal\core.py", line 68, in __getitem
__
    provider.initialize()
  File "c:\python27\lib\site-packages\subliminal\providers\opensubtitles.py", li
ne 138, in initialize
    'subliminal v%s' % __short_version__))
  File "c:\python27\lib\site-packages\subliminal\providers\opensubtitles.py", li
ne 278, in checked
    raise Unauthorized
Unauthorized
DEBUG:subliminal.providers.podnapisi:No subtitles found
INFO:subliminal.core:Discarding provider opensubtitles
Downloading subtitles  [####################################]  100%

Some providers have been discarded due to unexpected errors: opensubtitles
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider podnapisi
Downloaded 0 subtitle
```

**Comment by joseph-giron** [comment]
My version doesn't even have the option for --debug. And yeah, its borked. Won't download nothing now. RIP.

**Comment by andradadad** [comment]
> 
> 
> My version doesn't even have the option for --debug. And yeah, its borked. Won't download nothing now. RIP.

It's not downloading available subtitles on opensubtitles.
Other softwares are fetching them fine.

**Comment by matiasg** [comment]
Same problem here.
```sh
$ subliminal --version
subliminal, version 2.1.0
```

**Comment by timonoj** [comment]
Any news? I installed it recently and I'm getting errors for all these:
`Some providers have been discarded due to unexpected errors: podnapisi, opensubtitles, legendastv`

**Comment by Rouzax** [comment]
Same here with OpenSubtitle

```
DEBUG:subliminal.cli:Collecting path C:\TEMP\Torrent\Downloads\Avatar.The.Last.Airbender.S01.REPACK.1080p.Fan.RM.DD2.0.x264-PetaHD
DEBUG:subliminal.core:Walking directory 'C:\\TEMP\\Torrent\\Downloads\\Avatar.The.Last.Airbender.S01.REPACK.1080p.Fan.RM.DD2.0.x264-PetaHD'
INFO:subliminal.core:Scanning video 'Avatar.The.Last.Airbender.S01E01.The.Boy.in.the.Iceberg.1080p.BluRay.AAC2.0.x264-PetaHD.mkv' in 'C:\\TEMP\\Torrent\\Downloads\\Avatar.The.Last.Airbender.S01.REPACK.1080p.Fan.RM.DD2.0.x264-PetaHD'
DEBUG:subliminal.core:Size is 524077334
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with hash
DEBUG:subliminal.refiners.hash:Computing hashes for 'C:\\TEMP\\Torrent\\Downloads\\Avatar.The.Last.Airbender.S01.REPACK.1080p.Fan.RM.DD2.0.x264-PetaHD\\Avatar.The.Last.Airbender.S01E01.The.Boy.in.the.Iceberg.1080p.BluRay.AAC2.0.x264-PetaHD.mkv'
DEBUG:subliminal.refiners.hash:Computed hashes {'opensubtitles': '9716784e4f6c030c'}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found resolution 1080p
DEBUG:subliminal.refiners.metadata:Found video_codec H.264
DEBUG:subliminal.refiners.metadata:Found audio_codec AAC
DEBUG:subliminal.refiners.metadata:MKV has no subtitle track
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series ['Avatar The Last Airbender', 'Fan']
ERROR:subliminal.utils:Unexpected error. Failed to refine video 'C:\\TEMP\\Torrent\\Downloads\\Avatar.The.Last.Airbender.S01.REPACK.1080p.Fan.RM.DD2.0.x264-PetaHD\\Avatar.The.Last.Airbender.S01E01.The.Boy.in.the.Iceberg.1080p.BluRay.AAC2.0.x264-PetaHD.mkv'
Traceback (most recent call last):
  File "c:\github\subliminal\lib\site-packages\subliminal\core.py", line 549, in refine
    refiner_manager[refiner].plugin(video, **dict((refiner_configs or {}).get(refiner, {}), **kwargs))
  File "c:\github\subliminal\lib\site-packages\subliminal\refiners\tvdb.py", line 275, in refine
    results = search_series(video.series.lower())
AttributeError: 'list' object has no attribute 'lower'
INFO:subliminal.core:Refining video with omdb
WARNING:subliminal.refiners.omdb:No apikey. Skipping omdb refiner.
1 video collected / 0 video ignored / 0 error
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [en]>, <Language [nl]>}
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging in
DEBUG:subliminal.providers.opensubtitles:Logged in with token 'tQdSMDhFQNmMx9o4BV2d00qP33a'
ERROR:subliminal.utils:Unexpected error. Provider opensubtitles
Traceback (most recent call last):
  File "c:\github\subliminal\lib\site-packages\subliminal\core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "c:\github\subliminal\lib\site-packages\subliminal\providers\opensubtitles.py", line 214, in list_subtitles
    query=query, season=season, episode=episode, tag=os.path.basename(video.name))
  File "c:\github\subliminal\lib\site-packages\subliminal\providers\opensubtitles.py", line 157, in query
    criteria.append({'query': query.replace('\'', ''), 'season': season, 'episode': episode})
AttributeError: 'list' object has no attribute 'replace'
INFO:subliminal.core:Discarding provider opensubtitles
Some providers have been discarded due to unexpected errors: opensubtitles
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
0 subtitle downloaded for Avatar.The.Last.Airbender.S01E01.The.Boy.in.the.Iceberg.1080p.BluRay.AAC2.0.x264-PetaHD.mkv
```

**Comment by joseph-giron** [comment]
To anyone still in this thread, use this instead https://github.com/emericg/OpenSubtitlesDownload

**Comment by Rouzax** [comment]
Weird the same folder that did not work yesterday now runs fine

**Comment by timonoj** [comment]
Thanks

> To anyone still in this thread, use this instead https://github.com/emericg/OpenSubtitlesDownload and be sure to fill in lines 61 and 62 with your opensubtitles account user / pass. It actually works unlike subliminal.

Thanks joseph-giron, but I believe it's not a very good recommendation to a bug report to just use a different program that works in a different way. Also, albeit that program claims to work on KDE, it provides zero information on how to make it work on KDE.

**Comment by marcotollini** [comment]
You need to provide a login like this:

`subliminal --debug --opensubtitles "username" "password" download -p opensubtitles -l en .`

Please, do not use long passwords or it will not work (with 64 does not work, with 16 it works just fine)

**Comment by ComputingFroggy** [comment]
Indeed, providing a login/password for _opensubtitles_ does the trick ... but it is a pain that will fail the program for all providers. That should fail on _opensubtitles_ and should work for others providers.

**Comment by kuntau** [comment]
> You need to provide a login like this:
> 
> `subliminal --debug --opensubtitles "username" "password" download -p opensubtitles -l en .`
> 
> Please, do not use long passwords or it will not work (with 64 does not work, with 16 it works just fine)

Thank you for discovering this... I do have 65 char password and have been wondering for months why it didn't work!!

**Comment by RaXorX** [comment]
I thought this was a bug myself earlier, had a little suspicion that maybe open subtitles stopped providing access to the API for non-logged users. But thought maybe if that were the case it wouldn't be for too long or if it's a bug it'll be resolved. Turns out yes, they have stopped access for non-logged users via the API. https://forum.opensubtitles.org/viewtopic.php?f=11&t=17110

Let's just hope one day they bring back access to it once again. Seems like the issues with other providers might be similar.

**Comment by cclauss** [comment]
@Diaoul Can we please get a new release to unblock Homebrew/homebrew-core#86671

**Comment by johnwuelk** [comment]
I changed my password in opensubtitles.org then it worked! The reason why it didn't work was because I had special signs like exclamation mark in my initial pw, escaping that sign (like `\!` ) fixed it as well but I ended up changing my pw. Thanks for the hints you gave me!

**Comment by Blasg2** [comment]
> I changed my password in opensubtitles.org then it worked! The reason why it didn't work was because I had special signs like exclamation mark in my initial pw, escaping that sign (like `\!` ) fixed it as well but I ended up changing my pw. Thanks for the hints you gave me!

How did you change it? I tried changing it now and they only allow password that have a special character...

**Comment by garoto** [comment]
Opensubtitles.org has been hacked and everyone needs to reset their passwd: https://forum.opensubtitles.org/viewtopic.php?f=1&t=17685&p=46818

**Comment by johnwuelk** [comment]
> > I changed my password in opensubtitles.org then it worked! The reason why it didn't work was because I had special signs like exclamation mark in my initial pw, escaping that sign (like `\!` ) fixed it as well but I ended up changing my pw. Thanks for the hints you gave me!
> 
> @johnwuelk How did you change it? I tried changing it now and they only allow passwords that have a special character...
> or how do you do this "escaping the sign" ? 

I could reset it via the "forget password" option. It's not every special character but only some, my previous password that failed was "4movs!@#", escaping the exclamation mark like 4movs**\!**@# worked. My current password that works, only has one special sign: `[`, the rest are letters. But like Garoto mentioned, you would have to change your password anyway because the site has been hacked. I'm using subliminal via this mpv script https://github.com/davidde/mpv-autosub which is very handy.

**Comment by garoto** [comment]
> I changed my password in opensubtitles.org then it worked! The reason why it didn't work was because I had special signs like exclamation mark in my initial pw

btw, it didn't worked because logins were blocked, not because you had special chars on your passwd string. I had special chars  (`\!`)  on my passwd for years and it always worked flawlessly once you learn what chars needs escaping.

I also use subliminal exclusevely via a mpv script.
