### ISSUE TITLE
First time usage- error being generated. print(f.filename, file=file) = Invalid Syntax?

### ISSUE THREAD

**Issue by 420pootang69** [Diaoul/subliminal#1010]
First time trying Subliminal and I'm getting the following:

> isabell@isabell-MS-7C52:~$ subliminal --debug download -l en "/XMBC/TV shows/Schitt's Creek/Schitts.Creek.S05.1080p.WEBRip.x264-TBS"
> Traceback (most recent call last):
>   File "/usr/local/bin/subliminal", line 5, in <module>
>     from subliminal.cli import subliminal
>   File "/usr/local/lib/python2.7/dist-packages/subliminal/__init__.py", line 11, in <module>
>     from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
>   File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 13, in <module>
>     from rarfile import BadRarFile, NotRarFile, RarCannotExec, RarFile, Error, is_rarfile
>   File "/usr/local/lib/python2.7/dist-packages/rarfile.py", line 811
>     print(f.filename, file=file)
>                           ^
> SyntaxError: invalid syntax

I've tried reinstalling both Subliminal and python, but no go. Any ideas?

EDIT: I can't get the test to line up like it is in the terminal, the invalid syntax is point at the equals in "file=file".

**Comment by 420pootang69** [comment]
No ideas? My dad's deaf and this could have been very useful...

**Comment by h3llrais3r** [comment]
This is not a subliminal issue, but an issue with `rarfile` library.
You are probably running subliminal with python 2?
Latest version of rarfile is python 3 only, so you might try to install a previous version of rarfile through pip (version 3.1 is last one with support for python 2) and see if it fixes the issue.

**Comment by 420pootang69** [comment]
Ah you absolute legend, that fixed it thanks so much!!

For Linux newbies like myself, the full command to downgrade is pip install 'rarfile==3.1'
