### ISSUE TITLE
How to download multiple subtitles from opensubtitles without having video path

### ISSUE THREAD

**Issue by kunalkhadilkar** [Diaoul/subliminal#1016]
I have a list of film names in csv format, and I want to download opensubtitle subtitles for those films. For example, 
subliminal --debug --opensubtitles "username" "password" download -p opensubtitles -l en 'Don' gives:

DEBUG:subliminal.cli:Collecting path Don
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with hash
ERROR:subliminal.utils:Unexpected error. Failed to refine video 'Don'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/subliminal/core.py", line 549, in refine
    refiner_manager[refiner].plugin(video, **dict((refiner_configs or {}).get(refiner, {}), **kwargs))
  File "/opt/anaconda3/lib/python3.7/site-packages/subliminal/refiners/hash.py", line 26, in refine
    if video.size <= 10485760:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
INFO:subliminal.core:Refining video with metadata
INFO:subliminal.core:Refining video with omdb
WARNING:subliminal.refiners.omdb:No apikey. Skipping omdb refiner.
1 video collected / 0 video ignored / 0 error
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging in
ERROR:subliminal.utils:Service unavailable. Provider opensubtitles
INFO:subliminal.core:Discarding provider opensubtitles
Some providers have been discarded due to unexpected errors: opensubtitles
DEBUG:subliminal.core:Terminating initialized providers
Downloaded 0 subtitle

How to solve this error 'Some providers have been discarded due to unexpected errors: opensubtitles'

**Comment by kunalkhadilkar** [comment]
opensubtitles always shows 'service unavailable' error. the username and password are correct, as I can log into opensubtitles.org successfully.

**Comment by euphoria360** [comment]
me too.

```
someuser@host:~# subliminal --debug --opensubtitles myopensibtitle_user my_opensubtitle pass download -l de -p opensubtitles "/loc_to_my_Movies/News of the World (2020)/News of the World (2020).mp4"'
DEBUG:subliminal.cli:Collecting path /loc_to_my_Movies/News of the World (2020)/News of the World (2020).mp4
INFO:subliminal.core:Scanning video 'News of the World (2020).mp4' in '/loc_to_my_Movies/News of the World (2020)'
DEBUG:subliminal.core:Size is 2341929226
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with hash
DEBUG:subliminal.refiners.hash:Computing hashes for '/loc_to_my_Movies/News of the World (2020)/News of the World (2020).mp4'
DEBUG:subliminal.refiners.hash:Computed hashes {'opensubtitles': '6c185d0b28c81e36'}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Unsupported video extension .mp4
INFO:subliminal.core:Refining video with omdb
WARNING:subliminal.refiners.omdb:No apikey. Skipping omdb refiner.
Collecting videos  [####################################]  100%  /loc_to_my_Movies/News of the World (2020)/News of the World (2Collecting videos  [####################################]  100%                                                                                                                                     
1 video collected / 0 video ignored / 0 error
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [de]>}
INFO:subliminal.core:Initializing provider opensubtitles
**INFO:subliminal.providers.opensubtitles:Logging in**
**ERROR:subliminal.utils:Service unavailable. Provider opensubtitles**
INFO:subliminal.core:**Discarding provider opensubtitles**
Downloading subtitles  [####################################]  100%
Some providers have been discarded due to unexpected errors: opensubtitles
DEBUG:subliminal.core:Terminating initialized providers
Downloaded 0 subtitle
```
