### ISSUE TITLE
A method to download an alternate sub if the intially downloaded sub is no good

### ISSUE THREAD

**Issue by Rabcor** [Diaoul/subliminal#1018]
Sometimes subliminal will download subs that are bad, for instance I have this movie, white snake, and the downloaded sub for it is 
_White.Snake.2019.1080p.BluRay.x264.AAC5.1-[YTS.LT].en.srt_

It's (entire) content:

```
`1
00:00:30,000 --> 00:00:36,000
Provided by YTS.LT

2
00:00:36,500 --> 00:00:42,000
Find the official YIFY movies site at
https://YTS.LT

3
00:30:30,000 --> 00:30:36,000
Downloaded from YTS.LT

4
01:00:30,000 --> 01:00:36,000
Download more movies for free
from YTS.LT
`
```

Nevermind being a mistimed subtitle file which can sometimes happen, it's just not a real subtitle at all.

I'd like to have the ability to make subliminal look for an alternative subtitle file instead of the one it first downloaded for a file.

Additionally perhaps an automated feature that checks if the filesize of the subtitle file targeted for download is at least over 1kb and rejects the file if it isn't to prevent this specific scenario might be nice.

**Comment by getzze** [comment]
Since https://github.com/Diaoul/subliminal/pull/1160, you can skip a subtitle with the CLI option --ignore-subtitles=5gth4dh, where 5gth4dh is the subtitle id, that appears in the command line output with the debug option.
