### ISSUE TITLE
subliminal doesnt download

### ISSUE THREAD

**Issue by speeskeek** [Diaoul/subliminal#1024]
I am a great fan of subliminal, it works Wonderfull, but since a few weeks (did I do a new install on my system?) It doesnt download any subtitles.

Am I doing sth wrong? Or is subliminal not having write permissions (its run as root !)

`subliminal download -v -l nl -l en Bridgerton.S01E0*
Collecting videos  [##################------------------]   50%  Bridgerton.S01E
Collecting videos  [######################--------------]   62%  Bridgerton.S01E
Collecting videos  [###########################---------]   75%  Bridgerton.S01E
Collecting videos  [###############################-----]   87%  00:00:00  Bridg
Collecting videos  [####################################]  100%  Bridgerton.S01E
Collecting videos  [####################################]  100%                                                         
8 videos collected / 0 video ignored / 0 error
Downloading subtitles  [####--------------------------------]   12%  00:01:10  B
Downloading subtitles  [#########---------------------------]   25%  00:01:00  B
Downloading subtitles  [#############-----------------------]   37%  00:00:50  B
Downloading subtitles  [##################------------------]   50%  00:00:40  B
Downloading subtitles  [######################--------------]   62%  00:00:30  B
Downloading subtitles  [###########################---------]   75%  00:00:20  B
Downloading subtitles  [###############################-----]   87%  00:00:10  B
Downloading subtitles  [####################################]  100%  Bridgerton.
Downloading subtitles  [####################################]  100%                
                                         
Some providers have been discarded due to unexpected errors: podnapisi, thesubdb, opensubtitles
0 subtitle downloaded for Bridgerton.S01E01.1080p.HEVC.x265-MeGusta.mkv
0 subtitle downloaded for Bridgerton.S01E02.720p.HEVC.x265-MeGusta.mkv
0 subtitle downloaded for Bridgerton.S01E03.1080p.HEVC.x265-MeGusta.mkv
0 subtitle downloaded for Bridgerton.S01E04.1080p.HEVC.x265-MeGusta.mkv
0 subtitle downloaded for Bridgerton.S01E05.1080p.HEVC.x265-MeGusta.mkv
0 subtitle downloaded for Bridgerton.S01E06.1080p.HEVC.x265-MeGusta.mkv
0 subtitle downloaded for Bridgerton.S01E07.1080p.HEVC.x265-MeGusta.mkv
0 subtitle downloaded for Bridgerton.S01E08.1080p.HEVC.x265-MeGusta.mkv`

**Comment by MartenBE** [comment]
I'm having the same problem
