### ISSUE TITLE
podnapisi.net stopped working Sep 29 due to Let's Encrypt chain issue, anyone have a contact there?

### ISSUE THREAD

**Issue by gene1wood** [Diaoul/subliminal#1037]
The [Let's Encrypt root cert expiration occurred last week](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/) and podnapisi.net, one of the subliminal subtitle providers, is [serving that expired root cert in their chain](https://www.ssllabs.com/ssltest/analyze.html?d=www.podnapisi.net&s=91.185.203.249&latest).

The result is this error from subliminal

> requests.exceptions.SSLError: HTTPSConnectionPool(host='www.podnapisi.net', port=443): Max retries exceeded with url: /subtitles/search/old?sXML=1&sL=en&sK=Example&sY=2021 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))

Does anyone have a contact at podnapisi.net to let them know (I couldn't find one)?

(Apologies for this GitHub issue which isn't calling out a bug in the subliminal code base but instead a tangential issue)

**Comment by gene1wood** [comment]
> https://www.podnapisi.net/forum

Sadly it's a closed forum and you have to know somebody with an account to register. Maybe someone here has an account on their forum and can pass the word along?

**Comment by MasterMind2k** [comment]
Hi.

Problem was resolved.

**Comment by gene1wood** [comment]
Confirmed, the certificate chain now contains the Let's Encrypt R3 intermediate cert which is not expired.
