### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by h3llrais3r** [Diaoul/subliminal#1046]
@Diaoul , @ratoaq2 
Are you still maintaining this repo?
We haven't seen any activity lately and it would be a pitty if a nice library like `subliminal` would no longer be supported/maintained.

**Comment by Diaoul** [comment]
A new maintainer would be welcome as I have limited time to make contributions indeed. I can add collaborators or, if things get serious enough, create an org for better visibility.

**Comment by h3llrais3r** [comment]
Would be great if there was a new maitainer. What about @ratoaq2? Haven't seen him here also in the last months?

**Comment by getzze** [comment]
see #1064
