### ISSUE TITLE
Wizdom provider returns Connection aborted

### ISSUE THREAD

**Issue by Amit86** [Diaoul/subliminal#1050]
Hello,

Per [recommendation ](https://github.com/pymedusa/Medusa/issues/10781 )on the medusa project, I was advised to share this log here as it relates to an issue with subliminal, hope you can help!

Log provided:
> 2022-06-28 09:09:47 WARNING	Thread :: [ee1b898] Unexpected error. Provider wizdom
> Traceback (most recent call last):
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 597, in urlopen
>     httplib_response = self._make_request(conn, method, url,
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 384, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 2, in raise_from
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 380, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.9/http/client.py", line 1371, in getresponse
>     response.begin()
>   File "/usr/lib/python3.9/http/client.py", line 319, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.9/http/client.py", line 280, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.9/socket.py", line 704, in readinto
>     return self._sock.recv_into(b)
> ConnectionResetError: [Errno 104] Connection reset by peer
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/app/medusa/ext/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 637, in urlopen
>     retries = retries.increment(method, url, error=e, _pool=self,
>   File "/app/medusa/ext/urllib3/util/retry.py", line 367, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/app/medusa/ext/urllib3/packages/six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 597, in urlopen
>     httplib_response = self._make_request(conn, method, url,
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 384, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 2, in raise_from
>   File "/app/medusa/ext/urllib3/connectionpool.py", line 380, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.9/http/client.py", line 1371, in getresponse
>     response.begin()
>   File "/usr/lib/python3.9/http/client.py", line 319, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.9/http/client.py", line 280, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.9/socket.py", line 704, in readinto
>     return self._sock.recv_into(b)
> urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/app/medusa/ext/subliminal/core.py", line 115, in list_subtitles_provider
>     return self[provider].list_subtitles(video, provider_languages)
>   File "/app/medusa/medusa/subtitle_providers/wizdom.py", line 193, in list_subtitles
>     return [s for s in self.query(title, season, episode, year, filename, imdb_id) if s.language in languages]
>   File "/app/medusa/medusa/subtitle_providers/wizdom.py", line 144, in query
>     r = self.session.get(url)
>   File "/app/medusa/ext/requests/sessions.py", line 555, in get
>     return self.request('GET', url, **kwargs)
>   File "/app/medusa/ext/requests/sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/app/medusa/ext/requests/sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "/app/medusa/ext/requests/adapters.py", line 498, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
> 2022-06-28 09:09:47 INFO	Thread :: [ee1b898] Manual searching subtitles for: xxx
> 2022-06-28 09:09:47 INFO	Thread :: [ee1b898] Starting to manual searching subtitles

**Comment by p0psicles** [comment]
Sorry, just noticed. This is a medusa custom provider. So it'll be picked up by us.
