### ISSUE TITLE
Skipping movies with subtitles

### ISSUE THREAD

**Issue by alandefreitas** [Diaoul/subliminal#1053]
Is there a way to skip the movie files that already have subtitles?

I've been running subliminal with

```bash
subliminal --opensubtitles alan ******** --addic7ed alan ***** --legendastv alan ****** --legendastv alan ******* --omdb ******* download -l en -l pt-BR -l pt --max-workers 32 /home/alan/Videos
```

and it's taking a long time as I have more and more movie files.

**Comment by getzze** [comment]
Subliminal skips subtitles for languages that were already downloaded or are embedded in the movie (except if `--force` is used).
Alternatively, you can use the CLI option `--age=1w2d` to skip files older than 1 week and 2 days.
