### ISSUE TITLE
Some providers have been discarded due to unexpected errors: opensubtitles

### ISSUE THREAD

**Issue by squadjot** [Diaoul/subliminal#1058]
Hi, newbie here..

I'm on windows 10

Subliminal finds the movie.. but get the error "Some providers have been discarded due to unexpected errors: opensubtitles"
Is there something wrong with my command?
`subliminal --opensubtitles MYNAME MYPASS download -p opensubtitles -l en "E:\MyMovieFile.mkv"`

If i turn on debug i get:

subliminal --debug --opensubtitles MYUSERNAME MYPASSWORD download -p opensubtitles -l en 
...
...

StackHD.mkvINFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging in
ERROR:subliminal.utils:Unexpected error. Provider opensubtitles
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\subliminal\core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
           ~~~~^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\subliminal\core.py", line 67, in __getitem__
    provider.initialize()
  File "C:\Python311\Lib\site-packages\subliminal\providers\opensubtitles.py", line 129, in initialize
    response = checked(self.server.LogIn(self.username, self.password, 'eng', self.user_agent))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\subliminal\providers\opensubtitles.py", line 278, in checked
    raise Unauthorized
subliminal.providers.opensubtitles.Unauthorized
INFO:subliminal.core:Discarding provider opensubtitles
Downloading subtitles  [####################################]  100%
Some providers have been discarded due to unexpected errors: opensubtitles
DEBUG:subliminal.core:Terminating initialized providers
Downloaded 0 subtitle

**Comment by garoto** [comment]
Your password might have reserved chars that need to be properly escaped. Try enclosing your password in double-quotes and see if that works.

**Comment by squadjot** [comment]
Thanks for reply, my password quite simple and short, no special characters

**Comment by squadjot** [comment]
We agree that the user / pass is simply the same as when you log into the opensubtitles as a user..  should i put in my API key somewhere?

**Comment by squadjot** [comment]
Wow... i changed i password, and then it worked! -  But really my password was just numbers, and i just registered the account a couple of days ago!
