### ISSUE TITLE
opensubtitles API change

### ISSUE THREAD

**Issue by yardenac** [Diaoul/subliminal#1060]
opensubtitles.org will shut down its API in the next month or two, and is telling people to use opensubtitles.com REST API instead:

   https://trac.opensubtitles.org/projects/opensubtitles
   https://opensubtitles.stoplight.io/docs/opensubtitles-api/e3750fd63a100-getting-started

Subliminal needs to be updated to stay compatible. Due to bitrot, this is one of the only built-in providers which still works in 2023. When the change happens, without a fix subliminal will become almost useless.

**Comment by Andrews54757** [comment]
Unfortunately, OpenSubtitles will begin to restrict the REST API in 2024. Only VIP (paid) members will be able to access the API.

https://forum.opensubtitles.org/viewtopic.php?f=1&t=18389

**Comment by the-solipsist** [comment]
As of today (January 1, 2024), `subliminal` no longer works with OpenSubtitles.  It downloads a 104-byte file, which is an ad for OpenSubtitles.

**Comment by Lovecraft-github** [comment]
so addic7ed.com doesn't work because need a Captcha, legengastv is down and now opensubtitles is locked behind a VIP account. Is there any option available to download subtitles?

**Comment by ptrcnull** [comment]
- gestdown ( mentioned in #1055 ) seems to work for addic7ed without a captcha
- subdl.com seems to have scraped opensubtitles for a really long time, and now allows to download all that ( although the next.js api isn't too pleasant to work with )
- subscene.com, but the UX is terrible, not even talking about automated downloading9
- opensubtitles seems to still work, with workarounds such as changing the user agent and some headers, but i'm not 100% sure about that

**Comment by getzze** [comment]
closed in favor of #1063
