### ISSUE TITLE
Many tests fail due to a json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by doronbehar** [Diaoul/subliminal#1062]
On NixOS, we suddenly started to experience the following test failures:

https://gist.github.com/doronbehar/020ad71cbaaaa4b187af05e9cb46d09b

It might be due to one of the dependencies' updates, but I'm not sure which at the moment.

**Comment by getzze** [comment]
Check with the `develop` branch, this can be closed. Open a new issue if the problem persists.
