### ISSUE TITLE
Raise an exception on using a non-initialized provider

### ISSUE THREAD

**Issue by ptrcnull** [Diaoul/subliminal#1070]
> That would be better, you are right!
> Although that is a problem that is present in all the providers, so it would be better to create a specific `Exception` for it and correct all the provider. I think this is out of scope of this PR.

_Originally posted by @getzze in https://github.com/Diaoul/subliminal/pull/1069#discussion_r1590966799_

**Comment by getzze** [comment]
It's done after adding type hints to the providers.
