### ISSUE TITLE
Fixup NapiProjekt subtitles encoding

### ISSUE THREAD

**Issue by ptrcnull** [Diaoul/subliminal#1112]
sometimes the subtitles are getting returned as Windows-1250 instead of UTF-8; detect those cases and automatically convert them to UTF-8 whenever possible

marking as enhancement because it's NapiProjekt who's being silly and marking non-Unicode subtitles as UTF-8

**Comment by getzze** [comment]
Good idea, you can use the new [`reencode`](https://github.com/Diaoul/subliminal/blob/develop/subliminal/subtitle.py#L170C9-L170C17) method for that :wink:

**Comment by ptrcnull** [comment]
ah, i just realised - 10647da49d5e67c5561c6b24c681ecde2eb83e20 introduced a regression in handling Windows-1250 subtitles, they get decoded as ISO-8859-2, which is very much incorrect here ( but succeeds, because they're similar extended-ASCII encodings, just shuffled )

**Comment by getzze** [comment]
Ohhh, that's bad.
We can re-order the encodings to guess to put the windows encodings first (also for other languages).

**Comment by ptrcnull** [comment]
nah, it's alright, i already thought of a fix - hopefully one that can last

**Comment by getzze** [comment]
I just realized there is one regression introduced by #1113, `test_core.py::test_save_subtitles_single_directory_encoding` is currently failing due to the forced reencoding to 'utf-8'.

**Comment by ptrcnull** [comment]
ah, drat; what was the original purpose of that test? i can't imagine saving subtitles in non-Unicode encoding very useful..

**Comment by getzze** [comment]
The test seems for testing non-utf8 encoding actually. But I think it should pass, I don't understand why it fails.

**Comment by getzze** [comment]
I found the bug, it's in the `reencode` method actually, the first line should read:
`text = self.text`
Without the underscore. Otherwise `self._text` is empty...

Still, do we really need to use `reencode` in `save_subtitles` ? I mean, there is the `encoding` argument that forces saving the subtitle in the specified encoding ('utf8' in the failing test), and if `encoding=None`, it is saved in the original encoding.

**Comment by ptrcnull** [comment]
the issue is, when using the CLI saving the subtitle with the original encoding is pretty much useless most of the time - after all, in our code we know ( or guess with *educated guesses* ) the encoding, but the video player might either guess incorrectly or not try at all

**Comment by getzze** [comment]
Yes I agree!
I think it's still nice to leave the option to not force utf-8, though. But then maybe we can change the default `encoding` value in `save_subtitles` from `None` to `utf-8`, I agree that it makes more sense.
This change needs to be documented, as it can be a breaking change for some people.

**Comment by getzze** [comment]
NapiProjekt is working fine now, no? this can be closed maybe?
