### ISSUE TITLE
Too many results from opensubtitlescom provider

### ISSUE THREAD

**Issue by h3llrais3r** [Diaoul/subliminal#1146]
First of all, thank you for taking up this repo again.
While I was migrating to the newest version (2.2.1), I noticed that the opensubtitlescom provider returns too many results.
![image](https://github.com/Diaoul/subliminal/assets/1945295/9663aad2-dbe4-4158-930c-0c8c0a6362d1)

When enabling the debug logs, it seems that multiple requests are made?
![image](https://github.com/Diaoul/subliminal/assets/1945295/daa026dd-8da6-409f-8c63-b5f5dc2ddaf9)

Any idea why this is done?
Because there are actually only 3 records available for the provider.
![image](https://github.com/Diaoul/subliminal/assets/1945295/0ad59faf-b08f-4611-8403-6b49568561d0)

Shouldn't it be limited to 1 call?
If not, then I would propose to filter out the duplicate subtitles (you can that by checking the id) before returning the result.

**Comment by getzze** [comment]
Hey, thanks for reporting!

OpenSubtitles search feature is buggy, sometimes it doesn't report any match if too much information is provided. For instance, searching by name would give a good result, searching by hash would give the same result, but searching with the name **AND** the hash returns no result...

So just in case we make multiple searches, that can be redundant. It's probably too conservative.

**Comment by h3llrais3r** [comment]
What about filtering out duplicates based on their id?

`subtitles = [s1 for i, s1 in enumerate(subtitles) if not any(s1.id == s2.id for s2 in subtitles[:i])]`
![image](https://github.com/Diaoul/subliminal/assets/1945295/95c635b3-efee-4d1e-9fdb-bbb8a3323879)

![image](https://github.com/Diaoul/subliminal/assets/1945295/c059fa8c-1a4f-49e6-a56c-aefbdc94cfa3)

**Comment by h3llrais3r** [comment]
Thanks!
