### ISSUE TITLE
Is the video hash taken into account when downloading subtitles with `download_best_subtitles()`?

### ISSUE THREAD

**Issue by wujekbogdan** [Diaoul/subliminal#1158]
I'm considering using Subliminal as a backend for an Streamio subtitles plugin. Streamio doesn't provide movie titles via its plugins SDK [sic!]; they only provide Open Subtitles hashes. Based on the hash, I can retrieve a movie title from the Open Subtitles API. So all the information I'm going to have is the movie title and its hash.

The question I have is whether the hash is taken into account when refining the results.

See the code below:

``` python
from babelfish import Language
from subliminal import *


def with_hash(os_hash: str = None):
    video = Video.fromname('Big Lebowski')

    if os_hash:
        video.hashes = {'opensubtitles': os_hash}

    subs = download_best_subtitles({video}, {Language('pol')}, providers=None, only_one=True)
    found = subs[video]

    if not len(found):
        print('No subtitles found')

        return

    sub = found[0]

    print({
        'id': sub.subtitle_id,
        'name': sub.movie_name,
        'page_link': sub.page_link,
    })


if __name__ == '__main__':
    with_hash()
    with_hash('e7801448f23d36e2')
    with_hash('4d05dd8d8ca70ba7')
```

Gives me:

``` json
{
    "id": 1954859290,
    "name": "The Big Lebowski",
    "page_link": "http://www.opensubtitles.org/en/subtitles/6278421/sid-pQ1jYS7XnO-BhKvu7lr-IeKz4Y4/the-big-lebowski-pl"
}
{
    "id": 1954859290,
    "name": "The Big Lebowski",
    "page_link": "http://www.opensubtitles.org/en/subtitles/6278421/sid-pvROh0QJAB01l,CZdNHIJ,wHA95/the-big-lebowski-pl"
}
{
    "id": 1954859290,
    "name": "The Big Lebowski",
    "page_link": "http://www.opensubtitles.org/en/subtitles/6278421/sid-ta1antoKq54e-,CjuFu3OBC,jUf/the-big-lebowski-pl"
}
```

From what I see, no matter what hash I provide, I'm always getting the same result. This makes me wonder if Subliminal is a good tool for what I'm trying to achieve and if hashes make any difference when calling `download_best_subtitles()`.

Or maybe I'm simply doing something wrong?

**Comment by getzze** [comment]
`subliminal` uses a scoring function to get the best subtitle, that takes into account matching to hash and to title. Here it seems it's mainly matching the title (given with `Video.fromname`).
Instead you can use the `query` method of the `Provider`.

```
from subliminal.providers.opensubtitlescom import OpenSubtitlesComProvider

with OpenSubtitlesComProvider() as p:
    list_subtitles = p.query({Language('pol')}, moviehash='e7801448f23d36e2')
list_subtitles
```

Opensubtitles hash does not seem to be unique though, see https://github.com/Diaoul/subliminal/issues/828

**Comment by getzze** [comment]
Let's close this issue, feel free to reopen if you have more doubts
