### ISSUE TITLE
Module AttributeError: 'NoneType' object has no attribute 'cache_dir'

### ISSUE THREAD

**Issue by niklerus** [Diaoul/subliminal#140]
Sorry if I'm a bit "wordy" here..

Now that subliminal works so great I tried to get it working with Sickbeard and Sabnzbd again (the Subliminal fork of SickBeard is not really usable anymore) by calling my own post posting script (not python, .cmd ) from SABnzbd (replacing sabToSickbeard.py)
Works fine when I call it from a command prompt but not when calling it from Sabnzbd it works only halfway, doesn't seem to have the rights to download the subtitle to the directory.
Anyway, I thought I might create a .py script to see if I had better luck with that but I can't seem to get Subliminal to work from module, only from CLI.
If I open a IDLE Python shell, import Subliminal and for instance try the exemple provided on this page:

> > > subliminal.list_subtitles('The.Big.Bang.Theory.S05E18.HDTV.x264-LOL.mp4', ['en'])
> > > I get a long error message ending with "Module AttributeError: 'NoneType' object has no attribute 'cache_dir'"

Why is that, is it not strange since CLI works fine?
Running on Win7 x64 (Python 2.7 win32)

On another note, are there any plans to to tie Sickbeard and Subliminal together again (updated patterns.py, adding Addic7ed service (where most of the subtitles seem to stem from))?

Also want to say I am SO impressed with the skills you and other members here display!

**Comment by Stevestar** [comment]
I have the same problem and I tried your solution but it did't work. Can you please help me?
This is my error code:


2015-03-16 17:47:26 FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/usr/local/share/sickbeard/sickbeard/tv.py", line 1194, in downloadSubtitles
    subtitles = subliminal.download_subtitles([self.location], languages=need_languages, services=sickbeard.subtitles.getEnabledServiceList(), force=force, multi=True, cache_dir=sickbeard.CACHE_DIR)
  File "/usr/local/share/sickbeard/lib/subliminal/api.py", line 95, in download_subtitles
    subtitles_by_video = list_subtitles(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/usr/local/share/sickbeard/lib/subliminal/api.py", line 54, in list_subtitles
    tasks = create_list_tasks(paths, languages, services, force, multi, cache_dir, max_depth, scan_filter)
  File "/usr/local/share/sickbeard/lib/subliminal/core.py", line 80, in create_list_tasks
    logger.debug(u'Created task %r' % task)
  File "/usr/local/share/sickbeard/lib/subliminal/tasks.py", line 45, in __repr__
    return 'ListTask(%r, %r, %s, %r)' % (self.video, self.languages, self.service, self.config)
  File "/usr/local/share/sickbeard/lib/subliminal/services/__init__.py", line 259, in __repr__
    return 'ServiceConfig(%r, %s)' % (self.multi, self.cache_dir)
AttributeError: 'NoneType' object has no attribute 'cache_dir'
