### ISSUE TITLE
Subliminal 0.8

### ISSUE THREAD

**Issue by Diaoul** [Diaoul/subliminal#268]
API Changes
-------------------
- [x] Add `content` and encoding related stuff to the `Subtitle` class
- [x] Add a `save_subtitles` function that will save the subtitles on the filesystem based on the `Video` name, the `single` parameter and the `directory` parameter
- [x] Add a `page_link` attribute to the `Subtitle` class that links to the page where the subtitle can be downloaded manually (if applicable, `None` otherwise)
- [x] Add a `ProviderManager` that handle multiple providers, filtering (by name, video_types and languages), initialization, termination and retrying
- [x] Add a `year` to `Episode`, make sure no year is a match
- [x] Refactor current API with the above changes
- [x] Refactor Exceptions
- [x] Add timeout to ServerProxy #254
- [x] Add a `format` to `Video` and use it for matching
- [x] Use babelfish 0.5.0
- [x] Make the equivalent of ConverterManager in babelfish for Provider

**Comment by Diaoul** [comment]
This year. :laughing:

**Comment by h3llrais3r** [comment]
hehe :

**Comment by Diaoul** [comment]
Joke aside, I'm doing a lot of bug fixing and unit testing. There won't be any 0.8.0 version, jumping directly to 1.0 as I think the API is stabilized and the code battletested.

About Hearing Impaired, I think the proper place is in `compute_matches`, the priority is to have best matching subtitles so HI will be the lowest on the scale.

I'll update the code accordingly.

**Comment by h3llrais3r** [comment]
Nice te hear that a stable 1.0 version will be released! ;)

About the hearing impaired: are you talking about https://github.com/Diaoul/subliminal/pull/361/files?
If yes, will you be adding a score for HI?
With my pull request, the user can decide himself wether he wants HI subtitles or not or does not care about it.
-> perhaps it's better to discuss in the PR?
