### ISSUE TITLE
Add legendasfree.com

### ISSUE THREAD

**Issue by felipesalomao** [Diaoul/subliminal#291]
Hi, these are 2 biggest website for portuguese subtitles.
Please add support for provider:
~~www.legendas.tv~~
or 
www.legendasfree.com

Have to many apis in github for these providers.. Thanks
##

**Comment by Diaoul** [comment]
Legendas.tv added with 9785bc9746c24c8c28c4ed20812f103a070ca357

**Comment by ratoaq2** [comment]
Legendasfree doesn't exist anymore
