### ISSUE TITLE
[addic7ed] Some subtitles arent downloaded

### ISSUE THREAD

**Issue by mac1202** [Diaoul/subliminal#302]
Using latest git version. Most of time subliminal working perfectly like this : 

subliminal -p addic7ed -l fr -v -s --addic7ed-username xxxxx --addic7ed-password xxxxx "/home/mac/Videos/TV/The Vampire Diaries/Season 5/The Vampire Diaries - S05E06 - HDTV x264-LOL.mp4"
INFO     [subliminal.video] Scanning video u'The Vampire Diaries - S05E06 - HDTV x264-LOL.mp4' in u'/home/mac/Videos/TV/The Vampire Diaries/Season 5'
INFO     [subliminal.api] Listing subtitles for <Episode [u'The Vampire Diaries', 5x6]>
INFO     [subliminal.providers.addic7ed] Logged in
INFO     [subliminal.providers] Listing subtitles with provider 'addic7ed' and languages set([<Language [fr]>])
INFO     [subliminal.providers] Found 1 subtitles
INFO     [subliminal.api] Found 1 subtitles total
INFO     [subliminal.subtitle] Computed score 66 with matches set([u'series', u'year', u'episode', u'release_group', u'season'])
INFO     [subliminal.api] Downloading subtitle <Addic7edSubtitle [fr]> with score 66
INFO     [subliminal.providers.addic7ed] Logged out
INFO     [subliminal.api] Saving <Addic7edSubtitle [fr]> to u'/home/mac/Videos/TV/The Vampire Diaries/Season 5/The Vampire Diaries - S05E06 - HDTV x264-LOL.srt'
1 subtitle downloaded

But sometime the subtitle isnt downloaded with no error message like this : 

subliminal -p addic7ed -l fr -v -s --addic7ed-username xxxx --addic7ed-password xxxxxx "/home/mac/Videos/TV/Lost Girl/Season 4/Lost Girl - S04E01 - HDTV x264-2HD.mp4"
INFO     [subliminal.video] Scanning video u'Lost Girl - S04E01 - HDTV x264-2HD.mp4' in u'/home/mac/Videos/TV/Lost Girl/Season 4'
INFO     [subliminal.api] Listing subtitles for <Episode [u'Lost Girl', 4x1]>
INFO     [subliminal.providers.addic7ed] Logged in
INFO     [subliminal.providers] Listing subtitles with provider 'addic7ed' and languages set([<Language [fr]>])
INFO     [subliminal.providers] Found 1 subtitles
INFO     [subliminal.api] Found 1 subtitles total
INFO     [subliminal.subtitle] Computed score 60 with matches set([u'series', u'year', u'episode', u'season'])
INFO     [subliminal.providers.addic7ed] Logged out
No subtitles downloaded

Using the -m option to lower the minimum score doesnt make a difference and I have still free download slot on my addic7ed account.

**Comment by Diaoul** [comment]
See #343
