### ISSUE TITLE
Subtitle encoding detection fail

### ISSUE THREAD

**Issue by queeup** [Diaoul/subliminal#315]
Hello,

subliminal converting subtitles to UTF-8 and for some players not a good idea. For example XBMC using user interface language for determine subtitles language. In my case my XBMC is Turkish and my subtitles downloaded from subliminal showing wrong characters.

Debug of subliminal: http://pastebin.com/raw.php?i=FDKCxZzw

I download same subtitle. This is compare of subliminal vs. opensubtitles web download:

``` bash
$ charade downloaded_by_subliminal.srt downloaded_from_opensubtitles_website.srt 
downloaded_by_subliminal.srt: utf-8 with confidence 0.99
downloaded_from_opensubtitles_website.srt: ISO-8859-2 with confidence 0.874910791543
$ 
```

I am going to paste sneak peek of this two subtitles. You can see differences:
http://pastebin.com/raw.php?i=5bE7YZJJ

**Comment by defji** [comment]
Hi, i have the same problems, with hungarian lang..

**Comment by discoHR** [comment]
Same problem with croatian language. Croatian subtitles are always CP1250 no matter where they get downloaded from so I don't see a reason for subliminal to recode anything. My media player doesn't support UTF-8 anyway.

**Comment by Koxx3** [comment]
same problem in french :/

**Comment by Diaoul** [comment]
Please provide examples.

**Comment by Koxx3** [comment]
serie : 
true.detective.s02e03.720p.hdtv.x264-0sec.mkv

log:
INFO: Listing subtitles with provider 'opensubtitles' for video <Episode [u'true detective', 2x3]> with languages set([<Language [fr]>])
INFO: Found 1 subtitle(s) on opensubtitles
INFO: Listing subtitles with provider 'thesubdb' for video <Episode [u'true detective', 2x3]> with languages set([<Language [fr]>])
INFO: Found 1 subtitle(s) on thesubdb
INFO: Listing subtitles with provider 'podnapisi' for video <Episode [u'true detective', 2x3]> with languages set([<Language [fr]>])
INFO: Found 3 subtitle(s) on podnapisi
INFO: Listing subtitles with provider 'addic7ed' for video <Episode [u'true detective', 2x3]> with languages set([<Language [fr]>])
INFO: Found 5 subtitle(s) on addic7ed
INFO: Listing subtitles with provider 'tvsubtitles' for video <Episode [u'true detective', 2x3]> with languages set([<Language [fr]>])
INFO: Found 0 subtitle(s) on tvsubtitles
INFO: Downloading subtitle <OpenSubtitlesSubtitle [fr]> with score 46 into u'/mnt/pchome-mydatas/series/true.detective.s02e03.720p.hdtv.x264-0sec.fr.srt'
1 subtitle downloaded

contenu :
2
00:01:50,580 --> 00:01:52,165
<i>Est une rivičre</i>

19
00:03:11,286 --> 00:03:12,621
Je suis lŕ.

60
00:06:02,862 --> 00:06:04,543
Deux côtes fęlées.

68
00:06:22,936 --> 00:06:24,730
Burris est ŕ l'intérieur.

**Comment by Koxx3** [comment]
chardet /mnt/pchome-mydatas/series/true.detective.s02e03.720p.hdtv.x264-0sec.fr.srt
/mnt/pchome-mydatas/series/true.detective.s02e03.720p.hdtv.x264-0sec.fr.srt: utf-8 (confidence: 0.99)

charade /mnt/pchome-mydatas/series/true.detective.s02e03.720p.hdtv.x264-0sec.fr.srt
/mnt/pchome-mydatas/series/true.detective.s02e03.720p.hdtv.x264-0sec.fr.srt: utf-8 with confidence 0.99

file -bi  /mnt/pchome-mydatas/series/true.detective.s02e03.720p.hdtv.x264-0sec.fr.srt
text/plain; charset=utf-8

**Comment by skorokithakis** [comment]
Why is subliminal not always just using chardet's encoding? I'm having a problem where it thinks Greek characters decode cleanly with latin-1, where chardet is properly returning Greek.

What's the reason between the complicated encoding detection scheme, over just trusting whatever chardet thinks (which is correct pretty much all of the time, in my experience)?

**Comment by Diaoul** [comment]
Subliminal doesn't use any encoding detection by default. It is only triggered when using the `-e` argument of the CLI.

In the previous versions, subliminal used the detected encoding to decode the subtitle and write it on the filesystem using utf-8. Due to many bug reports without the required information to make the detection algorightm better I decided to deactivate it by default and leave encoding detection to media players.

**Comment by skorokithakis** [comment]
Sorry, that's what I mean. I use `-e UTF8` but I get invalid subtitle encodings (Latin1 encoded to UTF8, so everything looks broken). Overriding the built-in detection with just `return chardet.detect(self.content)["encoding"]` works every time.

Is there a reason for the convoluted encoding detection that only uses chardet if it fails, over just always using chardet when `-e` is specified?

**Comment by Diaoul** [comment]
I just explained the reason. I don't have enough data to fix encoding for every languages. This code was introduced because chardet wasn't accurate enough and resulted in a lot of garbage for most user. I'm glad chardet works fine in *your* language but that doesn't help at all.

For that part to be improved I need at least one test case per language per (popular) encoding (for *that* language), then I will decide how to do to improve that part, most likely it will be a mix of chardet + a way to supply chardet with language information (see https://github.com/chardet/chardet/issues/19#issuecomment-33596664). I will likely use chardet to decide between a limited, language-based set of possible encodings.

**Comment by skorokithakis** [comment]
Hmm, I see. It's odd that chardet wasn't accurate enough, it's always worked properly for me.

This is the subtitle file that's not working for me, by the way:

http://www.opensubtitles.org/en/subtitles/4910656/total-recall-el

**Comment by Diaoul** [comment]
I just created #528, if you want to contribute more test cases please provide the file encoding and the subtitle file.

**Comment by skorokithakis** [comment]
Will do, I'll add them as they find them.

**Comment by DDamian** [comment]
I also have a problem with subtitles downloaded from NapiProjekt. When I open the file in text editor, it shows UTF-8 encoding, but polish characters are displayed incorrectly. What can I do to help ?

**Comment by DDamian** [comment]
My problem is actually in SickRage, just noticed they added such line recently, and this probably breaks it, as it was working before: 

if subtitle.language.alpha3 == 'pol':
                setattr(subtitle, 'encoding', 'utf-8')

So the subtitles downloaded by subliminal are in windows-1250, but for unknown reasone SickRage mark them (not convert) as utf-8, which is not working.

**Comment by Diaoul** [comment]
SickRage uses a custom version of subliminal, any issue related to SickRage must be reported there.
