### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by ghost** [Diaoul/subliminal#318]
Hello,
I'm getting the following error messages when I try to search subtitles for newly downloaded series(My series are downloaded with deluge)
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 9, in <module>
    load_entry_point('subliminal==0.8.0-dev', 'console_scripts', 'subliminal')()
  File "/usr/local/lib/python2.7/dist-packages/subliminal-0.8.0_dev-py2.7.egg/subliminal/cli.py", line 182, in subliminal
    save_subtitles(subtitles, single=args.single, directory=args.directory, encoding=args.encoding)
  File "/usr/local/lib/python2.7/dist-packages/subliminal-0.8.0_dev-py2.7.egg/subliminal/api.py", line 131, in save_subtitles
    with io.open(subtitle_path, 'w', encoding=encoding) as f:
IOError: [Errno 13] Permission denied: '/home/***_/NASVD/**_**/****.S02E11.720p.HDTV.X264-****_/**_**.S02E11.720p.HDTV.X264-******.en.srt'

Is there some sort of command or cronjob that can prevent this from happening???

**Comment by jbrains** [comment]
For the next person who reads this: if you install `subliminal` as a **snap**, then you might need to give it explicit permission to your removable media, since many of us probably store video files somewhere other than the built-in primary drive on the machine. :)

This isn't an issue with `subliminal` itself, but I could see people bumping into this problem for the first time while trying to get `subliminal` working.

```
sudo snap connect subliminal-subtitles:removable-media core
```

**Comment by makiritare** [comment]
> For the next person who reads this: if you install `subliminal` as a **snap**, then you might need to give it explicit permission to your removable media, since many of us probably store video files somewhere other than the built-in primary drive on the machine. :)
> 
> This isn't an issue with `subliminal` itself, but I could see people bumping into this problem for the first time while trying to get `subliminal` working.
> 
> ```
> sudo snap connect subliminal-subtitles:removable-media core
> ```

you are a life saver i have quit using subliminal for many years till i read your comment

**Comment by garoto** [comment]
Thanks for the useless notification and issue bump, as usual on this shit platform...
