### ISSUE TITLE
Use imdbID to get subtitles when hash query fails

### ISSUE THREAD

**Issue by getzze** [Diaoul/subliminal#338]
I am using the opensubtitles provider and sometimes (specially for series), subliminal cannot find subtitles, whereas I find them on opensubtitles.org.
The search for subtitles in subliminal is done by hash, but sometimes it does not give results, and even false results when the hash are wrong on opensubtitles.org.
As the opensubtitles api does not match correctly with movie title sometimes, I thought about using imdbID, which gives good results usually.

I implemented the query of imdbID (and thetvdbID for series) :
https://github.com/getzze/subliminal/blob/develop-imdb/subliminal/video.py

Now that there is a proper provider manager, I guess it is possible to make another query by imdbID if the hash query does not give good results.

**Comment by Diaoul** [comment]
I think this should be implemented as part of `scan_video` which goal is to get as much information as possible on the video itself.
This behavior should be optional, unit tested and cached.

**Comment by getzze** [comment]
I decided to make a python module to do that:
https://github.com/getzze/imdbfetcher
It uses an online database, http://omdbapi.com/ by default but the search can be much improved by installing other modules, like `tmdbsimple`.
I modified video.py to include the changes:
https://github.com/getzze/subliminal/commit/395b57ceaccde2b2624a24a60e2aa36651f2fd2a

The methods in the Video classes were renamed to `get_imdb` and `fromimdb`.

**Comment by getzze** [comment]
Made it optional - but an option should be added to the command line to enable it.
Added test file - and modified test_video.py because scan_videos has now and extra argument `use_imdbfetcher`
https://github.com/getzze/subliminal/tree/imdbfetcher/subliminal

**Comment by getzze** [comment]
I don't know what you mean by caching. How do you do that and for which purpose?

**Comment by Diaoul** [comment]
https://pypi.python.org/pypi/imdbpie vs https://pypi.python.org/pypi/IMDbPY

**Comment by Diaoul** [comment]
http://omdbapi.com/ seems more suited

**Comment by getzze** [comment]
ombdapi gives the best results in general, the problem is that they are willing to add an apikey, I hope this will not prevent from using the service. Otherwise, it is trying to get the IMDB id from five different sources (including ImdbPy). For now the five services are tested one after the other until it matches. the best would be to set up a system of rating of the different ways of getting the id.

**Comment by Diaoul** [comment]
I've implemented "refiners" in subliminal and will push this soon. Currently tvdb and omdb are implemented but if others can be useful why not add them.

**Comment by Diaoul** [comment]
This is not limited to get the imdbID, it gets the whole information about the video too. Proper title, year, and so on.

**Comment by Diaoul** [comment]
Here is the commit: b0bd236b40ff438756ca386d5d30ec80336b800f
I have not decided yet how this will play with multiple refiners. Ideas are welcome.
/cc @pannal

**Comment by getzze** [comment]
https://www.themoviedb.org/ works quite well also, see (https://github.com/getzze/imdbfetcher/blob/master/imdbfetcher/services/tmdb_api.py). I would say this is the best actually.
I found a few problems with non-English movies, the title was totally changed. This should be tested.

**Comment by Diaoul** [comment]
This is implemented with refiners.
