### ISSUE TITLE
Download hearing impaired subtitles optionally

### ISSUE THREAD

**Issue by h3llrais3r** [Diaoul/subliminal#343]
Is is possible to change the logic for the hearing impaired?
Now the hearing impaired flag of the subtitle must match the hearing impaired flag specified in the download_best_subtitles(...)

<code>
if subtitle.hearing_impaired != hearing_impaired:
&nbsp;&nbsp;logger.debug('Skipping subtitle: hearing impaired != %r', hearing_impaired)
&nbsp;&nbsp;continue
</code>

Could this be adapted as mentioned hereunder:
hearing_impaired == False -> download only subtitles with hearing_impaired == False
hearing_impaired == True -> download subtitles with both hearing_impaired == False AND hearing_impaired == True

I you want to keep the possibility to dowload only hearing_impaired subtitles, it could also be adapted to an int (0, 1, 2) instead of a boolean (False and True).

**Comment by olfway** [comment]
Any news on this?

**Comment by h3llrais3r** [comment]
Waiting for merging of PR https://github.com/Diaoul/subliminal/pull/361...
