### ISSUE TITLE
How can I get Subliminal to work and then integrate it with a file?

### ISSUE THREAD

**Issue by alanjeremy** [Diaoul/subliminal#350]
How can I get Subliminal to work and then integrate it with a file?
I have downloaded Subliminal which is a program that downloads movie subtitles.But there are several problems: (1) when I test it at the console with a movie that I know has an English subtitle, I get an unsatisfactory response:

alan@alan-Latitude-D530:~$ subliminal -l en --La.Fin.Du.Jour.avi
usage: subliminal -l LANGUAGE [LANGUAGE ...] [-s] [-c CACHE_FILE]
                  [-p PROVIDER [PROVIDER ...]] [-m MIN_SCORE] [-a AGE] [-h]
                  [-f] [--addic7ed-username USERNAME]
                  [--addic7ed-password PASSWORD] [-q | -v]
                  [--log-file LOG_FILE] [--color] [--debug] [--version]
                  [--help]
                  PATH [PATH ...]
subliminal: error: too few arguments
(2) I loaded a bash script into Nautilus so that I could download subtitles by a right-click on a movie file instead of having to go to a console. But I could not get a successful download!:

 #!/bin/bash
 # NAME:         Get_subtitles
 # AUTHOR:       (c) 2014 Glutanimate
 # DEPENDENCIES: subiminal (https://github.com/Diaoul/subliminal)
 # LICENSE:      MIT license (http://opensource.org/licenses/MIT)

 LANGUAGE="en"

 while [ $# -gt 0 ]; do
     MOVIE="$1"
     subliminal "$MOVIE" -l "$LANGUAGE"
     shift
 done
(3) Finally,In another attempt to download the subtitle with a right-click on the movie file, I opened Thunar File Management and loaded a command into its Custom Action:

subliminal -f -l en --%N
 This did not work either!

My objective here is:

(1) make sure that Subliminal actually is working i.e.downloads subtitles

(2) integrate Subliminal with a file system so that it operates with a right-click on a movie file without having to work at the terminal

**Comment by Diaoul** [comment]
Try latest stable 0.7.5
