### ISSUE TITLE
opensubtitles doesn't find any subtitles with full path

### ISSUE THREAD

**Issue by jmichiel** [Diaoul/subliminal#356]
if I use this cmdline:

subliminal -s -l eng -f -p=opensubtitles /volume1/video/Movies/About\ Time\ \(2013\)/About\ Time\ \[2013\]\ 1080p\ BluRay\ AAC\ x264-tomcat12
\[ETRG\].mp4

pointing the the real file, nothing is downloaded. However, if I remove the full path (and I'm not in the right directory), it does find subtitles.

Apparently, if the file is found, the file size, and moviehash is used instead of the file name to perform the query on opensubtitles, which yields no results.

If you remove this check in OpenSubtitlesProvider.list_subtitles, and always add the query parameter, together with the moviehash and it works.

EDIT : using 0.7.4

**Comment by Diaoul** [comment]
Always adding the query could be a solution however that might result in a lot of noise in the result.

**Comment by Diaoul** [comment]
This issue doesn't seem to have a lot of traction. Opensubtitles is hash centric so this is kind of an edge case.
I will reopen if there are more files with that issue.
