### ISSUE TITLE
File renaming option

### ISSUE THREAD

**Issue by azmeuk** [Diaoul/subliminal#358]
Hi,
It is not strictly about dealing with subtitles, but it would be great if subliminal has an option to rename video files using user-defined patterns. For instance ```%s - %n - %t``` for ```show name```, ```episode number``` and ```episode title```.

**Comment by Diaoul** [comment]
Not a job for subliminal I'm afraid, subliminal deals with subtitles. You can implement the extra logic by creating your own CLI script using the subliminal library.
