### ISSUE TITLE
Add option to provide OpenSubtitles credentials

### ISSUE THREAD

**Issue by lucianf** [Diaoul/subliminal#365]
There is currently no way to instruct the OpenSubtitles provider to login to the XML RPC using a custom account. Subliminal authenticates as guest in providers/opensubtitles.py (LogIn('', '', ...). An option to supply user/password should be added, just like for Addic7ed. This can help with the download limitation of 200 reqs/day.

**Comment by sv2241** [comment]
any update on this?

**Comment by h3llrais3r** [comment]
See https://github.com/Diaoul/subliminal/pull/452
