### ISSUE TITLE
Add provider Napiprojekt

### ISSUE THREAD

**Issue by DDamian** [Diaoul/subliminal#384]
Hello

In Poland none of already available subliminal providers do a good job, even open subtitles can't fine correct subtitles.

We have here provied called NapiProjekt. 

Here is available Synology package which uses pynapi (python).
http://subtitlessh.no-ip.biz Unfortunately it uses MediaInfo lib, which is not available for Intel Atom which is in DS214play.

There are also multiple bash scripts to do that.

I would love to help with integration, as some of docs are only in polish language.

Please let me know if its possible.
Regards
Damian

**Comment by MichalE7** [comment]
please show some love to Polish people :) :+1:
