### ISSUE TITLE
"Skipping badly encoded directory" Error in api script

### ISSUE THREAD

**Issue by Pretagonist** [Diaoul/subliminal#386]
I get a long row of these kind of errors with basically the standard script that is on the page
(i have corrected the age-error in download_best_subtitles.) 

    25221:2014-06-14 18:11:03,792:ERROR->Skipping badly encoded directory u'/data/rar2media/news/Last.Week.Tonight.With.John.Oliver.S01E06.720p.HDTV.x264-BATV'

if i instead run 
```python
video = subliminal.scan_video('dir-to-file.mkv', subtitles=True, embedded_subtitles=True)
```
it works. But then i'd have to step through all the files myself.

As far as i know everything on my system is set to UTF-8. The CLI works fine as well.
I am using rar2fs to expose the video-files inside rar-archives so it's possible that's interfering 

I have tried checking the source myself but i just can't get a handle on what 
```python
if isinstance(dirpath, bytes):
``` 
actually does as i'm not a good python coder.

I'm using subliminal 0.8.0-dev

**Comment by Diaoul** [comment]
Please try latest stable 0.7.5
