### ISSUE TITLE
"Skipping video: Insufficient data to process the guess"

### ISSUE THREAD

**Issue by krank** [Diaoul/subliminal#389]
Updated to latest version in git repo; gives this error on every search:

"Skipping video: Insufficient data to process the guess"

subliminal -l en -v --debug Continuum.S03E13.720p.HDTV.x264-2HD.mkv gives this log:

INFO     [subliminal.video-scan_video:202] Scanning video u'Continuum.S03E13.720p.HDTV.x264-2HD.mkv' in u'/var/downloads/rTorrent/finished/tvshows'
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_idnumber = guessit.transfo.guess_idnumber:GuessIdnumber')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_bonus_features = guessit.transfo.guess_bonus_features:GuessBonusFeatures')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_date = guessit.transfo.guess_date:GuessDate')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('split_path_components = guessit.transfo.split_path_components:SplitPathComponents')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_properties = guessit.transfo.guess_properties:GuessProperties')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_release_group = guessit.transfo.guess_release_group:GuessReleaseGroup')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('split_explicit_groups = guessit.transfo.split_explicit_groups:SplitExplicitGroups')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_episodes_rexps = guessit.transfo.guess_episodes_rexps:GuessEpisodesRexps')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_weak_episodes_rexps = guessit.transfo.guess_weak_episodes_rexps:GuessWeakEpisodesRexps')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_episode_info_from_position = guessit.transfo.guess_episode_info_from_position:GuessEpisodeInfoFromPosition')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('split_on_dash = guessit.transfo.split_on_dash:SplitOnDash')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_movie_title_from_position = guessit.transfo.guess_movie_title_from_position:GuessMovieTitleFromPosition')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_video_rexps = guessit.transfo.guess_video_rexps:GuessVideoRexps')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_episode_special = guessit.transfo.guess_episode_special:GuessEpisodeSpecial')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_country = guessit.transfo.guess_country:GuessCountry')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_language = guessit.transfo.guess_language:GuessLanguage')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_website = guessit.transfo.guess_website:GuessWebsite')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_year = guessit.transfo.guess_year:GuessYear')
DEBUG    [stevedore.extension-_load_plugins:156] found extension EntryPoint.parse('guess_filetype = guessit.transfo.guess_filetype:GuessFiletype')
DEBUG    [guessit.matcher-log_found_guess:171] Property found: type=episode (confidence=1.00)
DEBUG    [guessit.matcher-log_found_guess:171] Property found: mimetype=video/x-matroska (confidence=1.00)
DEBUG    [guessit.matcher-log_found_guess:171] Property found: container=mkv (confidence=1.00)
DEBUG    [guessit.matcher-log_found_guess:171] Property found: format=HDTV (confidence=1.00)
DEBUG    [guessit.matcher-log_found_guess:171] Property found: screenSize=720p (confidence=1.00)
DEBUG    [guessit.matcher-log_found_guess:171] Property found: videoCodec=h264 (confidence=1.00)
DEBUG    [guessit.matcher-log_found_guess:171] Property found: container=mkv (confidence=0.30)
DEBUG    [guessit.language-__init__:205] The given string "downloads" could not be identified as a language
DEBUG    [guessit.language-__init__:205] The given string "rtorrent" could not be identified as a language
DEBUG    [guessit.language-__init__:205] The given string "finished" could not be identified as a language
DEBUG    [guessit.language-__init__:205] The given string "tvshows" could not be identified as a language
DEBUG    [guessit.language-__init__:205] The given string "continuum" could not be identified as a language
DEBUG    [guessit.language-__init__:205] The given string "s03e13" could not be identified as a language
DEBUG    [guessit.language-__init__:205] The given string "2hd" could not be identified as a language
DEBUG    [guessit.matcher-log_found_guess:171] Property found: season=3 (confidence=1.00)
DEBUG    [guessit.matcher-log_found_guess:171] Property found: episodeNumber=13 (confidence=1.00)
DEBUG    [guessit.matcher-log_found_guess:171] Property found: releaseGroup=2HD (confidence=1.00)
DEBUG    [GuessEpisodeInfoFromPosition-log_found_guess:171] Property found: series=Continuum (confidence=0.70)
DEBUG    [GuessEpisodeInfoFromPosition-log_found_guess:171] Property found: series=tvshows (confidence=0.30)
DEBUG    [guessit.matcher-__init__:111] Found match tree:
0111 222222222 33333333 44444444 5555555 66666666666666666666666666666666666 777
0000 000000000 00000000 00000000 0000000 00000000000000000000000000000000000 000
                                         00000000000000000000001111222222222 000
                                         0000000000000000011112    011112222
                                         00000000001111112              0111
/var/downloads/rTorrent/finished/_______/________________.____.____.____-___.___
                                 TTTTTTT TTTTTTTTTTEEEEEE ssss ffff vvvv rrr ccc
/var/downloads/rTorrent/finished/tvshows/Continuum.S03E13.720p.HDTV.x264-2HD.mkv
DEBUG    [guessit.guess-_merge_similar_guesses_nocheck:351] Updating matching property 'series' with confidence 0.40
DEBUG    [guessit.guess-_merge_similar_guesses_nocheck:351] Updating matching property 'container' with confidence 1.00
DEBUG    [guessit.matchtree-matched:437] Final result: {
    [1.00] "mimetype": "video/x-matroska",
    [1.00] "episodeNumber": 13,
    [1.00] "videoCodec": "h264",
    [1.00] "container": "mkv",
    [1.00] "format": "HDTV",
    [0.40] "series": "Continuum",
    [1.00] "releaseGroup": "2HD",
    [1.00] "screenSize": "720p",
    [1.00] "season": 3,
    [1.00] "type": "episode"
}
INFO     [guessit-_guess_camel_string:137] "rTorrent" is camel cased. Try to detect more properties.
DEBUG    [GuessFiletype-guess_filetype:185] Nothing characteristic found, assuming type = unknown
DEBUG    [guessit.matcher-log_found_guess:171] Property found: type=unknown (confidence=1.00)
DEBUG    [guessit.language-__init__:205] The given string "r" could not be identified as a language
DEBUG    [guessit.language-__init__:205] The given string "torrent" could not be identified as a language
DEBUG    [guessit.matcher-__init__:111] Found match tree:
000000000
000000000
r torrent

r torrent
DEBUG    [guessit.matchtree-matched:437] Final result: {
    [0.60] "type": "movie"
}
ERROR    [subliminal.video-scan_videos:311] Skipping video: Insufficient data to process the guess
No subtitles downloaded

**Comment by tvb** [comment]
Having the same issue but no cameCase directory here:

```bash
DEBUG:subliminal.video:Walking directory /mnt/data/completed
DEBUG:subliminal.video:Walking directory /mnt/data/completed/Trainwreck.2015.V2.READNFO.HDRip.XviD.AC3-EVO
INFO:subliminal.video:Scanning video u'Trainwreck.2015.V2.READNFO.HDRip.XviD.AC3-EVO.avi' in u'/mnt/data/completed/Trainwreck.2015.V2.READNFO.HDRip.XviD.AC3-EVO'
ERROR:subliminal.video:Error scanning video
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 460, in scan_videos
    video = scan_video(filepath, subtitles=subtitles, embedded_subtitles=embedded_subtitles)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 302, in scan_video
    video = Video.fromguess(path, guess_file_info(path))
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 104, in fromguess
    return Episode.fromguess(name, guess)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 174, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
```

**Comment by tvb** [comment]
Another one:

```
DEBUG:subliminal.video:Walking directory /mnt/data/complete
DEBUG:subliminal.video:Walking directory /mnt/data/complete/Focus.2015.WEB-DL.720p.x264.AC3
INFO:subliminal.video:Scanning video u'Focus.2015.WEB-DL.720p.x264.AC3.mkv' in u'/mnt/data/complete/Focus.2015.WEB-DL.720p.x264.AC3'
ERROR:subliminal.video:Error scanning video
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 460, in scan_videos
    video = scan_video(filepath, subtitles=subtitles, embedded_subtitles=embedded_subtitles)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 302, in scan_video
    video = Video.fromguess(path, guess_file_info(path))
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 104, in fromguess
    return Episode.fromguess(name, guess)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 174, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
```
