### ISSUE TITLE
Is there a default configuration file?

### ISSUE THREAD

**Issue by dlmarston** [Diaoul/subliminal#390]
Is there a configuration file in which we can specify our default command line options for subliminal?

My thought here is to avoid having to type in the same command line options (e.g. addic7ed username and passwords) each time I run subliminal.

I've looked through the documentation, but I can't find anything like this in there.

Regards - Dave

**Comment by Diaoul** [comment]
Nope, configuration is left for the library users, you can easily create yours with a few lines of python code.
