### ISSUE TITLE
Different Score Scale for TV shows and Movies (--min-score)

### ISSUE THREAD

**Issue by fdotta** [Diaoul/subliminal#392]
Hi Guys,

First of all great job on the subliminal, the project is awesome.

When I was automating the use of the subliminal on the servers, I've noticed the score scale (--min-score opt) are different for movies and tv shows. It's could be a little annoying when you automating the subs downloading process (that my case). So, I would like to propose a change on that. I understand the scales are from the  subs providers  (like opensubtitles.com), so my suggestion is parametrizing this values 0-100 and internally the subliminal recalculates the scores 0-74 for tv shows and 0-34 for movies. 
That is the ez part the hard one is discovery with file are movie or tv show, maybe that information could be get from the providers.

Thanks

**Comment by Diaoul** [comment]
Done https://github.com/Diaoul/subliminal/blob/master/subliminal/cli.py#L149-L150
