### ISSUE TITLE
Encode Error

### ISSUE THREAD

**Issue by tonybolzan** [Diaoul/subliminal#393]
`subliminal -s -l pt-br -- Under.the.Dome.S02E03.HDTV.x264-LOL.mp4`
Get file with encode errors
`http://www.opensubtitles.org/pt/subtitles/5755905/under-the-dome-force-majeure-pb`

**Comment by thevtm** [comment]
Same here it is happening in all pt-BR subtitles.

**Comment by tonybolzan** [comment]
Usually texts pt-BR are encoded in ISO 8859-1

**Comment by Diaoul** [comment]
Please provide more details: provider used, language and subtitle download link

**Comment by ratoaq2** [comment]
Is this issue still valid? I have no issues here:

```subliminal download -p opensubtitles -l pt-br Under.the.Dome.S02E03.HDTV.x264-LOL.mp4```

My env:
```
Subliminal 1.01
Ubuntu 15.04

locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_CH.UTF-8
LC_TIME=de_CH.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_CH.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_CH.UTF-8
LC_NAME=de_CH.UTF-8
LC_ADDRESS=de_CH.UTF-8
LC_TELEPHONE=de_CH.UTF-8
LC_MEASUREMENT=de_CH.UTF-8
LC_IDENTIFICATION=de_CH.UTF-8
LC_ALL=
```

**Comment by tonybolzan** [comment]
No, it is no longer valid.

I teste on Python 2.7.8 and 3.4.2
Subliminal 1.0.1
LANG=pt_BR.UTF-8

Everything all right.

**Comment by Diaoul** [comment]
This is still valid if you use the `-e` flag and try to convert it to some other encoding.

**Comment by ratoaq2** [comment]
I tried this file above (it's ISO-8859-1) using

```-e utf-8```
```-e utf-16```

and no problems found.
