### ISSUE TITLE
Podnapisi download error : Cannot find the download link

### ISSUE THREAD

**Issue by Crupuk** [Diaoul/subliminal#408]
Since a few day i have this error for a episode : 

    Search subtitle for Greys Anatomy/S11/Greys.Anatomy.S11E02.720p.HDTV.X264-DIMENSION.mkv
    INFO: Skipping provider 'bierdopje': no language to search for
    INFO: Listing subtitles with provider 'podnapisi' for video <Episode [u'Greys Anatomy', 11x2]> with languages set([<Language [fr]>])
    INFO: Found 1 subtitles
    INFO: Listing subtitles with provider 'opensubtitles' for video <Episode [u'Greys Anatomy', 11x2]> with languages set([<Language [fr]>])
    INFO: Found 0 subtitles
    INFO: Listing subtitles with provider 'addic7ed' for video <Episode [u'Greys Anatomy', 11x2]> with languages set([<Language [fr]>])
    INFO: Found 0 subtitles
    INFO: Listing subtitles with provider 'thesubdb' for video <Episode [u'Greys Anatomy', 11x2]> with languages set([<Language [fr]>])
    INFO: Found 0 subtitles
    INFO: Listing subtitles with provider 'tvsubtitles' for video <Episode [u'Greys Anatomy', 11x2]> with languages set([<Language [fr]>])
    INFO: Found 0 subtitles
    INFO: Downloading subtitle <PodnapisiSubtitle [fr]> with score 37 into u'/dlna/shows/en/Greys Anatomy/S11/Greys.Anatomy.S11E02.720p.HDTV.X264-DIMENSION.srt'
    ERROR: Unexpected error in provider u'podnapisi'
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/subliminal/api.py", line 250, in download_best_subtitles
        subtitle_text = provider.download_subtitle(subtitle)
      File "/usr/lib/python2.7/site-packages/subliminal/providers/podnapisi.py", line 149, in download_subtitle
        raise ProviderError('Cannot find the download link')
    ProviderError: Cannot find the download link
    No subtitles downloaded

Thanks

**Comment by jeby** [comment]
Is there a workaround? I can't download any sub!

**Comment by TrueOsiris** [comment]
workaround is to use the --provider parameter and list all other providers.
