### ISSUE TITLE
Should handle non existing ~/.config directory gracefully

### ISSUE THREAD

**Issue by tdi** [Diaoul/subliminal#413]
When you do not have ~/.config directory, subliminal terminates with message:

subliminal: error: argument -c/--cache-file: directory u'/home/pi/.config' for cache file does not exist

I think this should be handled more gracefully, not every system is a desktop system. On servers you do not have .config. 

Either create the directory or just warn and continue with downloading subs.

**Comment by tdsmith** [comment]
My two cents is I was surprised to see that subliminal does not just create ~/.config if it doesn't already exist; that seems like standard behavior to me. Thanks!
