### ISSUE TITLE
guessing extensions

### ISSUE THREAD

**Issue by Fenisu** [Diaoul/subliminal#414]
Hi,
I realised that you have hardcoded the extensions of file types on video.py. These extensions are already found in guessit, maybe to remove them and use the extensions directly from guessit to avoid redundancy?

**Comment by Diaoul** [comment]
Both libraries have different jobs, I don't want to rely on guessit's internals to tell me what's a video and what's not, same for subtitles.
This gives more flexibility to add more extensions later on.
