### ISSUE TITLE
add support for rar archives

### ISSUE THREAD

**Issue by djbijo** [Diaoul/subliminal#416]
is it possible to scan for subtitles for videos that are inside archives?
as xbmc supports rar there is no need to extract archives so it seems logical that subliminal will work with archives.
i'm not a python coder but i ran into rarfile https://rarfile.readthedocs.org/en/latest/api.html , maybe this is the answer? or even search by file/dirname and skip the embedded sub check at this case.

**Comment by Diaoul** [comment]
So about this, why not extract the RAR? Compression ratio is bad anyway on videos isn't it?
This seems like a really custom need.

**Comment by renini** [comment]
Its only rarred because it is split in mulitple files for downloading reasons, no compression is being used.

I'd like to keep them as i got them.

**Comment by brp-david** [comment]
I'd like to chime in on this one too. I play my content via a media server that of course handles playing videos from packed files and I need to keep the rars around for torrent seeding either way so it's very redundant to unpack the files. Today I trick subliminal to download with this oneliner: 
`find <tvshows-path> -iname "*.rar" -type f -mmin -720 -not -iname "*sample*" -print0 | sed -e 's/rar/mkv/g' | xargs -0 subliminal download -v -l en`

This however has the issue of subliminal not being able to detect that the subtitle already exists and it gets downloaded multiple times. Subliminal being able to detect videos in rars would make my life complete!

**Comment by Diaoul** [comment]
We can close this now
