### ISSUE TITLE
subliminal is not launching as cronjob

### ISSUE THREAD

**Issue by SeeDborg** [Diaoul/subliminal#422]
I'm on Banana Pi, I can launch Subliminal in the terminal, but it won't work in cronjob.

I have this : 

0 19 * * * subliminal -f --age 1d -l fr -p addic7ed -s --addic7ed-username xxxx--addic7ed-password xxxxx /Path_to_tvshows_directory/

The exact same expression is working in the terminal ! Is there a way to fix this ?

**Comment by SeeDborg** [comment]
I tried it too, same result...

**Comment by AlexBoogaard** [comment]
what I did is make a shellscript and make cron run that shellscript.

Shellscript Subs.sh:
    #!/bin/bash

    /usr/local/bin/subliminal -l nl -p addic7ed --addic7ed-username XXXXX --addic7ed-password XXXXX -m 27 -- /PATH_TO_SHOWS/*/*.mkv

The two * are blindcards for the shows name and episode name.

My Cronjob is:

    27 6 * * * /PATH_TO_SCRIPT/Subs.sh

**Comment by SeeDborg** [comment]
Seems to be working, thanks !

**Comment by AlexBoogaard** [comment]
Instead of using the wildcards for the file it is also possible to just give the path to the folder. Subliminal searches in folders as well. There is not need to point to the file.

**Comment by discoHR** [comment]
Had same issue with subliminal not downloading anything from cron job. Used script as mentioned above but that doesn't work either. Result is always the same:

>Collecting videos
>Collecting videos
>0 video collected / 0 video ignored / 0 error

My script:
>#!/bin/bash
>PATH=/bin:/usr/bin:/usr/local/bin
>subliminal download -l hr -l bs -l sr -p addic7ed -p podnapisi -p opensubtitles -- /mnt/share/_incoming/

It works fine when executing directly in shell but it never finds any video when run from a cron job or shell script called from a cron job.

Subliminal v1.0.1
Ubuntu 14.04.3 LTS
