### ISSUE TITLE
Dead project ?

### ISSUE THREAD

**Issue by hadim** [Diaoul/subliminal#425]
Hi,

Is the project dead ? Do you have any ETA for the next release ?

If you're too busy maybe you should think about creating an organization on github for subliminal and work with others devs with write access on main repo. This kind of governance will speed up subliminal development.

Best

**Comment by h3llrais3r** [comment]
@Diaoul any idea if you'll manage to find some time to continue this project?

**Comment by Diaoul** [comment]
I want to and I think I'll manage.

**Comment by sioban** [comment]
Great !

**Comment by dlmarston** [comment]
@Diaoul any further thoughts on adding contributors to this project? There are some people doing some pretty cool things in their forks.

**Comment by Diaoul** [comment]
Recently reviewed #404 and made a few comments. I'm going to merge this and make a bugfix release on 0.7.x branch during the week if I find the time or this weekend.

**Comment by dlmarston** [comment]
@Diaoul thanks for the reply. any work on the continued development is greatly appreciated. #404 is a great one to work on (I'm a happy plex user).

**Comment by oxan** [comment]
Any news on e.g. #372, #401 and #405? Doesn't seem too hard to merge and fixes a few significant issues.

**Comment by martinp** [comment]
@Diaoul If you still can't find time, I'm sure there are several others who can keep maintaining the project. :-)

**Comment by hadim** [comment]
Enough. Let's fork it!

**Comment by Diaoul** [comment]
I'm not against forks, I forked periscope back in the old days. If you feel you can do a meaningful contribution other than complaining please go ahead. I see no PR from you and currently no PR is rework-free except maybe #404 that focuses on 0.7.x which I just merged because something is better than nothing at all.

**Comment by oxan** [comment]
As I mentioned earlier, #372, #401 and #405 are ready to merge in my eyes. If you think they need work to merge, then please comment with what you're expecting to be changed about it.

Forking isn't ideal as that doesn't allow us to update the package on e.g. pypi, and there's always wasted effort in a fork. It'd be ideal if you would add a trusted contributor to the project.

**Comment by hadim** [comment]
I agree. Glad to see is alive !

PS: giving write access to more contributors should help a lot I think !!!
