### ISSUE TITLE
Addic7ed : Provider Error code 304

### ISSUE THREAD

**Issue by sioban** [Diaoul/subliminal#428]
Hi, recently I get this error with Addic7ed :

INFO     [subliminal.video] Scanning video u'gotham.1x11-rogues.gallery-sd.tv-lol.mp4' in u'/media/nas/z-archives/Medias/series'
INFO     [subliminal.api] Listing subtitles for <Episode [u'gotham', 1x11]>
INFO     [subliminal.providers.addic7ed] Logged in
INFO     [subliminal.providers] Listing subtitles with provider 'addic7ed' and languages set([<Language [fr]>])
ERROR    [subliminal.providers] Unexpected error in provider 'addic7ed', discarding it
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/subliminal/providers/__init__.py", line 292, in list_subtitles
    provider_subtitles = provider.list_subtitles(video, provider_languages)
  File "build/bdist.linux-i686/egg/subliminal/providers/addic7ed.py", line 195, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "build/bdist.linux-i686/egg/subliminal/providers/addic7ed.py", line 180, in query
    soup = self.get(link)
  File "build/bdist.linux-i686/egg/subliminal/providers/addic7ed.py", line 119, in get
    raise ProviderError('Request failed with status code %d' % r.status_code)
ProviderError: Request failed with status code 304
INFO     [subliminal.api] Found 0 subtitles total
INFO     [subliminal.providers.addic7ed] Logged out
No subtitles downloaded
/!\ ended with error : 1

It still works with other provider.
Any idea ?

**Comment by dima-vy** [comment]
I just get this with Addic7ed:
Provider 'addic7ed' is not available, discarding it
Yesterday everything worked fine. May be it's connected errors?

**Comment by jtwill** [comment]
HTTP status code 304 means:

If the client has done a conditional GET and access is allowed, but the document has not been modified since the date and time specified in If-Modified-Since field, the server responds with a 304 status code and does not send the document body to the client.

I'm guessing, but maybe Addic7ed never used to return a 304 status code when the page was not modified, but now the server will return 304. And apparently the module subliminal is using does not know how to handle it.

**Comment by dima-vy** [comment]
It's working today fine, at least for me

**Comment by sioban** [comment]
Still not working there, same error.

**Comment by SeeDborg** [comment]
Not working for me too, same error since 2 days.

**Comment by Exo99** [comment]
Not working for me.
In the last days http://www.addic7ed.com post this:
3 days ago: Scheduled maintenance will start in a few hours. Signup, upload and a few other bugs should be fixed when it's all over. Sorry for any inconvenience.
2 days ago: We are back online. Some features are still not fixed yet, (forum, sign up), we're working on those now.
1 days ago: The sign up feature is now fixed. All those who tried to create an account in the last two weeks, you have to re-create it. -- As written in the sign up form, there is no email activation. Once you've hit "Join", you can log in directly. And you can change your password in My Panel > Edit Profile
Maybe they are still working on some problem

**Comment by sioban** [comment]
It's still not working...

Is this project still alive ?
We do not get any news from the owner...

**Comment by Nikoli** [comment]
> Is this project still alive ?

https://github.com/Diaoul/subliminal/issues/425#issuecomment-68001146
