### ISSUE TITLE
Add most used portuguese brazil subtitle provider (Legendas.tv)

### ISSUE THREAD

**Issue by felipesalomao** [Diaoul/subliminal#432]
Hi there, most used subtitle provider in brazil is legendas.tv, it has only perfect subtitles and fast. 98% of brazilians use it.. Also make too many portuguese (portugal) subtitles, all with awesome quality and fast. Would be awesome support it on sickrage.

Already exist API wich make development more easy, if need i can ask git hub url owner to support you if have some kind of doubt

https://github.com/gustavosf/api.legendas.tv

Here is script to download subtitles for this website (not know if its working because last updated 3 months ago):
https://github.com/fjcaetano/legendas.tv-downloader

it would be awesome to have legendas.tv as a subtitle provider... it always has the right subtitle, unlike opensubtitles that is always a struggle to get the right one, generally out of sync or its a english subtitle translated with google tranlator (or both) :s

Really thanks for your awesome work !

**Comment by thiagoperes** [comment]
+1

**Comment by gabrielalmeida** [comment]
+1

**Comment by lucianoshl** [comment]
+1

**Comment by acdesouza** [comment]
Duplicated of: #291 and #383.

**Comment by Diaoul** [comment]
Duplicate #383
