### ISSUE TITLE
Subliminal 0.7.5 or 0.8.0

### ISSUE THREAD

**Issue by sioban** [Diaoul/subliminal#435]
Hi,

This is not really an issue but regarding the latest changes I'm wondering if I should stick with the branch 0.8.0-dev or go for 0.7.5 as some correction have been made on this branch.

Are you planning to merge the two branch (or at least the changes) ?

Regards

**Comment by Diaoul** [comment]
Yes, I plan to merge and maybe do some other major changes on 0.8.0 if need be.
