### ISSUE TITLE
not downloading subtitle even with -f flag

### ISSUE THREAD

**Issue by Enrico68** [Diaoul/subliminal#440]
Whenever I try to download a subtitle I have the following problem 

`````
/Volumes/MyShare/Movies/The perverts guide to cinema%=> subliminal -l it -f The_Perverted_Guide_to_Cinema.avi                                           16:37
INFO: Listing subtitles for <Movie [u'The Perverted Guide to Cinema']>
INFO: Found 1 subtitles total
INFO: Downloading subtitle <PodnapisiSubtitle [it]> with score 13
No subtitles downloaded
`````

Is this a normal behaviour?

**Comment by Enrico68** [comment]
Subliminal 0.8.0

**Comment by romaincout** [comment]
Probably not since you have the '-f' options enabled, 
but you could try to add "-m 0" :
subliminal -m 0 -l it -f The_Perverted_Guide_to_Cinema.avi

**Comment by h3llrais3r** [comment]
There's a problem with the podnapisi provider.
You'll need to update to the latest version with my pull request (c1972ab26f60203b518545f4cdb2d6ab3b80480d) to get it working again.

**Comment by Enrico68** [comment]
@h3llrais3r
Updated. Still remain the problem
@romaincout 
No difference.

**Comment by h3llrais3r** [comment]
Actually, when I test it I get 0 subtitles...

INFO: Listing subtitles for <Movie [u'The Perverted Guide to Cinema']>
INFO: Found 0 subtitles total
No subtitles downloaded

**Comment by Enrico68** [comment]
h3llrais3r <notifications@github.com> writes:

> Actually, when I test it I get 0 subtitles...
>
> INFO: Listing subtitles for <Movie [u'The Perverted Guide to Cinema']>
> INFO: Found 0 subtitles total
> No subtitles downloaded
Yes. Problem is that all providers are giving the subtitle for the
movie. 

> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Diaoul/subliminal/issues/440#issuecomment-103140087

-- 
Dr. Enrico Pirani
Medico Chirurgo
Specialista in Chirurgia Toracica
FMH Chirurgia Cardiaca 
Via Matteotti 7
35042 Este (Padova)

Cell:392-6224668
Tel: 0429-17660135

  Ai sensi del D.Lgs. 196/2003 si precisa che le informazioni contenute in
  questo messaggio sono riservate ed a uso esclusivo del destinatario.
  Qualora il messaggio Le fosse pervenuto per errore, La invitiamo ad
  eliminarlo senza copiarlo e a non inoltrarlo a terzi, dandocene gentilmente
  comunicazione. Grazie.

  Pursuant to Legislative Decree No. 196/2003, you are hereby informed that
  this message contains confidential information intended only for the use of
  the addressee. If you are not the addressee, and have received this message
  by mistake, please delete it and immediately notify us. You may not copy or
