### ISSUE TITLE
Convert suite to pytest

### ISSUE THREAD

**Issue by nicoddemus** [Diaoul/subliminal#441]
Hi,

In April the pytest team is holding "adopt pytest month" to encourage projects to consider using pytest, by pairing open source projects with experienced pytest helpers (myself included). The idea is to create some PRs in a fork to port some of your xUnit test suite (which seems pretty complete btw), while discussing and explaining some of pytest's features, like automatic test discovery, plain asserts (no need to use `self.assertX` methods), parametrized tests, plugins, etc.

Since pytest can run standard xUnit tests, you can convert tests to use the full power of pytest in any pace you like.

Check out http://pytest.org/latest/adopt.html if you are interested. :smile:

Cheers! :beers:

**Comment by Diaoul** [comment]
I'm currently working on it, I might need your feedback when I'm done ;)

**Comment by nicoddemus** [comment]
Sure thing, glad to. :smile:

**Comment by Diaoul** [comment]
@nicoddemus: I need some help with autouse fixtures. It seems the directory structure of the conftest.py doesn't matter for autouse fixtures. Once imported, the fixture is always autoused even if the tested directory is different.
a/conftest.py
b/conftest.py

directory a/ will be tested with autouse fixtures from both conftest.py files instead of just the ones from a/conftest.py.

Another issue is that module level defined variables (like after import) are not reset after each test. So for example if in my case I change the state of the cache region in a test (.configure the region) I'll have an error whenever in another test I try again to .configure the region. Is there a way to elegantly workaround this limitation?

**Comment by nicoddemus** [comment]
Hi @Diaoul,

> I need some help with autouse fixtures. It seems the directory structure of the conftest.py doesn't matter for autouse fixtures

Hmm that's strange, this works for me:

```
xx/
  a/
    __init__.py
    conftest.py
    test_a.py
  b/
    __init__.py
    conftest.py
    test_b.py
```

```python
#contents of a/conftest.py
import pytest
@pytest.fixture(autouse=True)
def fix_a():
    print('fix a')
```

```python
# contents of a/test_a.py
def test_a(): pass
```

(And similar logic for files in `b/`).

When I execute `py.test -s` from the directory `xx`, I get:

```
collected 2 items

a\test_a.py fix a
.
b\test_b.py fix b
.

========================== 2 passed in 0.04 seconds ===========================
```

So the autouse fixture is being executed for each test as expected. Can you provide a reproducible example and what you were expecting?

> Another issue is that module level defined variables (like after import) are not reset after each test. 

pytest doesn't reset global variables, as to do so would involve a lot of hackery plus introduce a lot of side effects that might bring more trouble than it is worth; in fact, no Python test framework attempts this out of the box (I found this [nose plugin](http://nose.readthedocs.org/en/latest/plugins/isolate.html) which attempts to do this, but it's for nose only).

But there are other ways to reset global state that you can use, for example [mock](https://travis-ci.org/pytest-dev/pytest-mock) or pytest's own `monkeypatch` fixture. For example:

```python
import module

def test_module(monkeypatch):
    monkeypatch.setattr(module, 'global_config', {'region': 12, ...})
    # after the end of the test, module.global_config is restored to its original value
```

**Comment by Diaoul** [comment]
Thanks, unfortunately monckeypatch doesn't work with methods affecting the object itself like it's the case here with dogpile.cache's region. You have to change the reference.

Strangely I couldn't replace subliminal's region with a new configured one, that didn't produce good results like if the object wasn't configured properly.
One more particularity is that I need to prevent further calls to the configure function as I want to mock this in my doctests.

Also when I said it didn't work it was for a particular layout involving doctests. I've narrowed down one of my issues to ``--doctest-modules`` that seems to break things. Try to pull latest master and revert 0df19e300f9133fa7ec1cfca751afb361eb4afdd you will see some stuff that break.

See that error: https://travis-ci.org/Diaoul/subliminal/jobs/71840516

**Comment by Diaoul** [comment]
I'll make a dedicated branch tomorrow to explore all the weirdness of this and let travis show all kind of errors.

**Comment by Diaoul** [comment]
OK I couldn't wait till tomorrow, here is the branch: https://github.com/Diaoul/subliminal/tree/pytest wait for the travis build :)

**Comment by nicoddemus** [comment]
Hmmm there was a bug related to doctest and session-scoped fixtures that was fixed in master: https://github.com/pytest-dev/pytest/issues/768

I will take a look on the travis build later. :smile:

**Comment by nicoddemus** [comment]
Hmm the failures seem OK to me. I see that your session fixture `mkv` downloads files from source forge... is that reliable?

**Comment by Diaoul** [comment]
I'm getting rid of the download from sourceforge using travis cache now.
Check this one: https://travis-ci.org/Diaoul/subliminal/jobs/71888052
I did completely change the object so I don't know why I have that error: https://github.com/Diaoul/subliminal/blob/pytest/tests/conftest.py#L20

**Comment by nicoddemus** [comment]
I see that you merged that into master, so I assume all worked out in the end. :smile:

Sorry I couldn't be of more help!

**Comment by Diaoul** [comment]
It seems related to how dogpile.cache and monkeypatch work (import mechanism). I couldn't get it done properly so I went another way. Not really as clean as I would've wanted but that works.

I've also disabled --doctest-modules, don't know if that would work with the option enabled.
