### ISSUE TITLE
Save subtitle without the language code in the filename

### ISSUE THREAD

**Issue by tdkl** [Diaoul/subliminal#448]
As most of the Bluray players and TV's support external subtitles only when using the same name as the source video, it would be really beneficial to set subliminal to skip adding the language code to the subtitle filename when downloaded.

Currently: 
video.mp4, subtitle is now downloaded as video.en.srt for English language.

proposition: 
video.mp4, subtitle downloads as video.srt.

**Comment by Diaoul** [comment]
Use `-s`, see [the documentation](http://subliminal.readthedocs.org/en/latest/api/cli.html#subliminal)
