### ISSUE TITLE
 podnapisi  username and password 

### ISSUE THREAD

**Issue by xmenxmen** [Diaoul/subliminal#449]
Is it possible to wright my username and password to podnapisi.

**Comment by MartinAyla** [comment]
I have the same question.

Is Podnapisi supposed to work with the latest release or do they maybe require a username/password now?

Subliminal never downloads from Podnapisi and gives this error:
´´´
INFO: Found 4 subtitle(s) on podnapisi
INFO: Downloading subtitle <PodnapisiSubtitle [en]> with score 24 into u"/Movies/snow-the.devils.hand.2014.limited.1080p.bluray.x264.en.srt"
WARNING: Provider u'podnapisi' is not available, discarding it
No subtitles downloaded
´´´

**Comment by xmenxmen** [comment]
When I use it from Kodi,it require a username/password,to work.

**Comment by Diaoul** [comment]
The fix will come in the next major release. I'm currently working on the test suite and improving global stability.

**Comment by Diaoul** [comment]
Why do you need a username and password? Podnapisi works fine without it.
