### ISSUE TITLE
Preferred order of services

### ISSUE THREAD

**Issue by eltismerino** [Diaoul/subliminal#450]
I've seen that in an older version of subliminal it was possible to select the preferred order of services: http://subliminal.readthedocs.org/en/0.5.1/user.html

Is there anything like this in the current version of subliminal? I almost always want an addic7ed subtitle if there is one available.

**Comment by Diaoul** [comment]
The provider order isn't a criteria anymore.
Here is the set of equations that determines how the score is computed: https://github.com/Diaoul/subliminal/blob/master/subliminal/score.py

**Comment by Diaoul** [comment]
As an alternative you can run subliminal 2 times, once with only addic7ed and the other time with the others. Don't use the -f flag of course.
