### ISSUE TITLE
Implement search by hash for opensubtitle if parameter is an existing file

### ISSUE THREAD

**Issue by romaincout** [Diaoul/subliminal#453]
Idling on the web, I found about https://github.com/exebetche/vlsub
Turns out this VLC plugins can search on opensubtitles using a specific "hash".
It probably gives better and faster results ?

About these opensubtitle hashes :
http://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes

Something like: if the file given to subliminal as a parameter exists and opensubtitle module is in use, extract hash and search by hash

**Comment by Diaoul** [comment]
That's already the case since first version of subliminal.
