### ISSUE TITLE
Can get results with cli, but not via api

### ISSUE THREAD

**Issue by miigotu** [Diaoul/subliminal#456]
https://gist.github.com/miigotu/00d8af46d072bfad3def/raw/eb5f380f36adb1749fd3c5753e512d106e366925/gistfile1.txt

I have tried to do it so many ways, but my code can never find a subtitle using the api in 0.7.5 or current master.

If I use the cli `subliminal -l es -- samefilename` it finds it

Can you help me out on what I might be missing or doing wrong? There are no error/info logged when I force the logger to file on debug.

**Comment by miigotu** [comment]
Guess you cant see from those logs that I do configure the cache also, with
`subliminal.cache_region.configure('dogpile.cache.memory')`

**Comment by miigotu** [comment]
Enabled some more logging and found this:

```
INFO     [lib.subliminal.providers-list_subtitles:280] Skipping provider 'podnapisi': not a valid video
INFO     [lib.subliminal.providers-list_subtitles:280] Skipping provider 'tvsubtitles': not a valid video
INFO     [lib.subliminal.providers-list_subtitles:280] Skipping provider 'addic7ed': not a valid video
INFO     [lib.subliminal.providers-list_subtitles:280] Skipping provider 'thesubdb': not a valid video
INFO     [lib.subliminal.providers-list_subtitles:280] Skipping provider 'opensubtitles': not a valid video
```

**Comment by fernandog** [comment]
@miigotu 

https://github.com/Diaoul/subliminal/blob/0.7.x/subliminal/providers/__init__.py#L91

        The video is considered invalid if not an instance of :attr:`video_types` or if the :attr:`required_hash` is
        not present in :attr:`~subliminal.video.Video`'s `hashes` attribute.
        :param video: the video to check
        :type video: :class:`~subliminal.video.Video`
        :return: `True` if the `video` and `languages` are valid, `False` otherwise
        :rtype: bool
        """

**Comment by miigotu** [comment]
Yes I know, but it is an Episode object returned by the Video class, which inherits Video.

My video object I am passing is given back by subliminal.scan_video.  I will patch it to work correctly and make a PR here.

**Comment by miigotu** [comment]
INFO     [lib.subliminal.providers-list_subtitles:282] Skipping provider 'thesubdb': not a valid video
ERROR    [lib.subliminal.providers-list_subtitles:283] Type <class 'lib.subliminal.video.Episode'>

LOL

**Comment by miigotu** [comment]
If I comment line 83 and 84 of subliminal/providers/__init__.py it starts working. Even though my passed object is of type Episode, isinstance does not match it because it is a user defined type. I think this only becomes a problem when we are not in the normal python path (ie: we have it in libs of our project dir)

**Comment by Diaoul** [comment]
For any python project, even applications, I suggest you use the package dependencies provided by a requirements.txt rather than using a lib folder. You can hardcode version numbers in there and even use your forks if you made any modifications to the code of the libraries.
You can install a fresh virtualenv and start working in that. A setup.py provides the same features plus a lot of others. You can take a look at flexget that uses that approach: https://github.com/Flexget/Flexget

**Comment by fernandog** [comment]
@Diaoul so we don't need to upload the libs in our repo?

**Comment by Diaoul** [comment]
OK for SickRage it's a little bit different as it has some SickBeard history so to avoid breaking everything I just suggest to add your lib folder in sys.path. I believe that's already the case so you can just use `subliminal` instead of `lib.subliminal` and everything should work fine.

**Comment by fernandog** [comment]
thanks. will try

**Comment by miigotu** [comment]
@Diaoul not providing a static version in our lib folder isn't an option for us because there are systems that have no package manager and pip doesnt work at all (example openelec). They have no distutils or compiler.

And yes lib is in our sys.path, just have to change the import from lib. if we have that anywhere.

Thanks for answering.

**Comment by miigotu** [comment]
And to verify, I changed all `from lib import subliminal` to `import subliminal` and it works without the change to the instance check.  Idk why they started using that type of import to begin with when we insert it in the beginning of sys.path.
