### ISSUE TITLE
Add HD flag to Addic7edSubtitle

### ISSUE THREAD

**Issue by Diaoul** [Diaoul/subliminal#457]
Match computation can be tricky:
1. Against resolution? (720p, 1080p/i)
2. Against format? (HDTV, BluRay)

I think the first one would be better.
##

**Comment by Diaoul** [comment]
HD is definitely a format, not a resolution. Ref [guessit possible values for format](https://github.com/wackou/guessit/blob/master/guessit/transfo/guess_properties.py#L67-L83)

**Comment by miigotu** [comment]
In SR, we use a combination of resolution and "format". By scene standards it's not really the format, it is the source of the video. Just hdtv for example in the file name is considered sdtv as the hdtv tag just means it was ripped from a cable or ota tv channel (which most commonly is not at hd resolution), hdtv.720[pi] is hdtv and hdtv.1080[pi] is hdtv 1080.
