### ISSUE TITLE
Use click for CLI, features of 1.0

### ISSUE THREAD

**Issue by Diaoul** [Diaoul/subliminal#458]
http://click.pocoo.org/4/

**Comment by Diaoul** [comment]
@caronc, @h3llrais3r: I'm rewriting the CLI with click and I want to split subliminal in subcommands:
* list: will list all subtitles and print the output nicely with scores, indentation etc.
* download: will download one subtitle based on the provider name and the given id that user got from a previous list command
* download_best: will have the same behavior as the current CLI

I'm not very happy with the names, download seems misleading and download_best is too long. Other names I have in mind are get or get_subtitle instead of download. Any ideas?

Splitting in subcommands will allow to add more in the future if need be without having to deal with a huge amount of arguments in the main command.
For example when you notice a subtitle is bad, maybe a report command that will report the subtitle as bad/good.
And something like download_other that will try to download another subtitle than the one you currently have.

What do you think about this new CLI?

**Comment by caronc** [comment]
I think it sounds like a fantastic idea.  That said, I think that the majority of people who use your tool configure it _once_ as a cron (or service) that is called in an automated fashion of some sort. So all these bells and whistles may not be fully get exposed or utilized.

But where your idea really excels is: if you make those 3 separate options easily accessible and callable in the form of a library too, i can see people and their systems integrating with it a lot more. 

Consider having a switch --json or --xml to dump the output (of each option) into something that could be easily passed back as a web request to servers too?  Or am i thinking too outside of the box with this one? :)

**Comment by Diaoul** [comment]
Drop me an email with your thoughts :)

I hit a couple of issues with click due to my lack of knowledge of this fantastic tool but I think I can get something working by tomorrow, at least with the same features as the previous CLI.

Each time I get close to the end of my TODO list I end up adding some more items to it...

**Comment by Diaoul** [comment]
List / Get workflow is somewhat interactive:

1. ~~List returns the subtitles on one video per language (indenting by 2 spaces by section) ordered by score and with associated provider. The resulting subtitles will be given an id for display and serialized in the cache directory.~~
2. ~~Get will take one id or more as parameter, deserialize subtitles and download the ones matching the id.~~

The goal is to provide a quick way to download a subtitle by giving the opportunity to the user to select the subtitle he wants.

Writing this made me think of something that could be better, use a prompt instead of two commands + serialize/deserialize. I believe click also provide a pager for displaying long data. Now, should I use a flag to trigger interactive (`-i`) or provide a separate subcommand? Should this interactive mode support multiple videos? If so I can use click.clear to clear the terminal when iterating over videos and click also has a progress bar and color support.

Thoughts?

**Comment by h3llrais3r** [comment]
@Diaoul Actually I don't use the CLI interface.
I'm using the library functions to download the best subtitle available with a minimum score. (subliminal.download_best_subtitles)
I'm also using the list subtitles (subliminal.list_subtitles) to search for all the available subtitles, download them (subliminal.download_subtitles) and manually select the one I want.

The only thing I see is that the list subtitles does not contain the score yet, so perhaps it's better to enrich the list_subtitles with the score info so it can be displayed nicely?

Like mentioned by @caronc I think that most people use it as a cron or service, so I wouldn't invest to much in a nice CLI. But that are just my thoughts. ;)

**Comment by Diaoul** [comment]
Well, given the amount of work I already recently put in all other things (especially unit tests) in subliminal, designing a nice CLI with click is a drop in the ocean.
It also gives a concrete application workflow use case which helps designing a better API I think.

I agree with displaying the score in the CLI but how would you return it in list_subtitles? Currently we return a dict of video > list of subtitles. Computing scores is an extra step.

**Comment by h3llrais3r** [comment]
I know it's an extra step... but I think we always need a score in order to detect the best subtitle. Perhaps we can make it an attribute on te Subtitle class, which is set when the list_subtitles is executed by calling the  compute_score function?

**Comment by Diaoul** [comment]
That was my initial thought but a subtitle is relative to a video and without a video a score means nothing.
Should we also add a video property to the subtitle class?

Or create a Score class that associates a Video and a Subtitle + extra score features.

**Comment by h3llrais3r** [comment]
Good point :)
I would go for the second proposal:
A separate Score class which requires a Video and a Subtitle to do the score calculations (+ extra score features)

But I would create a separate function (f.e. score_subtitles) which uses the result of list_subtitles as input for the score calculations and returns an ordered list of Score objects.

What do you think?

**Comment by Diaoul** [comment]
Good idea, separation of concerns. Should score_subtitles work on a single video + its subtitles or the whole dict result ?

```python
for video, subtitles in list_subtitles(...):
    for score in score_subtitles(video, subtitles):
        # do something with score
```

If on the whole dict of video + subtitles, it would be hard to consume as in the end one will want to sort by video anyway. Don't you think?

**Comment by caronc** [comment]
Scoring is probable the least of the overhead of the entire Subliminal processing.  You're calling Guessit against everything anyway to determine if the video/show matches the query anyway. Why not continue to calculate it then and there anyway? Just don't filter the results unless you want scoring in play.

Honestly, scoring things separately (and then intentionally choosing not to score your results) will shave at most 0.03s off the processing time (estimations of course).
```python
# Keep it simple and built in
if use_scoring:
    for video, subtitles in [ (v,s) for (v,s) in \
           list_subtitles(...) if s.score > user_defined_score ]:
            # this sub is good
```

**Comment by h3llrais3r** [comment]
the function score_subtitles should score all the subtitles for 1 video in my opinion.
This is more flexible and can be reused in the api if we you want to do that for a single video file as well.

**Comment by h3llrais3r** [comment]
@caronc why wouldn't you want a scoring? In my opinion this is part of the core of subliminal in order to define a good subtitle. But adding the use_score flag is indeed a good idea if for some kind of reason this shouldn't be needed. ;)

**Comment by Diaoul** [comment]
Performance is not the issue here. The problem is separation of concerns. I added `hearing_impaired` in the score equations in my local branch but `list_subtitles` does not take a `hearing_impaired` argument and shouldn't IMO. If one wants to implement custom scoring that could be also done with the current design and not with a score inside the subtitle.

**Comment by h3llrais3r** [comment]
For me, hearing_impaired should not be taken into account in the score equations. It's just a flag on a subtitle, and the user should just be able to decide if he wants it or not or doesn't care about it. My PR is implemented in this way ;)

**Comment by caronc** [comment]
Your 100% right @h3llrais3r ! :).   My comment must have gotten misinterpreted (sometimes i don't explain myself properly).  I thought you guys were discussing separating scoring into it's own class and processing.  I'm kind of just saying: that's a lot of extra work for very little gain.  I understand the need to not score at times (in the new design @Diaoul is proposing) to display all matches.  But I'm just trying to say: don't do this... do the scoring always and every time right away.  But then choose to filter the results on demand (from a functional purpose).

@Diaoul: I honestly can't think of a use case where anyone would ever want to write a custom scoring feature especially since some sites return more or less information (addicted vs podnapisi for example). Subliminal is solid as it is; it's best feature is allowing people to write their own subliminal scraper for their own favorite site (and new ones that pop up).  That is just my two cents though :).

On a slightly different topic: I've been looking through the documentation of click().  It's really cool! Thanks for sharing it; I'm 100% behind you migrating that into subliminal :).

**Comment by Diaoul** [comment]
@h3llrais3r: If you use it as a flag during post processing you cannot tweak its weight. For example, I don't mind hearing impaired but I'd like the non-hearing impaired first if available.

Say now you want hearing impaired subtitles, I think it's better to have a synced non-hearing impaired subtitle rather than an out-of sync hearing impaired one. At least it's watchable :)

**Comment by h3llrais3r** [comment]
I would also always apply the score, so we are on the same page. :)

So my proposition is (in the download_best_subtitles):
```
# list
logger.info('Listing subtitles for %r', video)
video_subtitles = pp.list_subtitles(video, languages)
logger.info('Found %d subtitles total', len(video_subtitles))

# scoring
logger.info('Scoring subtitles for %r', video)
video_subtitles_scores = score_subtitles(video, video_subtitles)
# video_subtitles_scores is a list of Score objects witch contains a video and a subtitle and a score (and perhaps other scoring related stuff)

# download
...
```

**Comment by h3llrais3r** [comment]
@Diaoul about the hearing impaired.
I understand your concern, but this only applies when you have 2 subtitles with the same weight, and one of them is hearing impaired. So perhaps you can pass the hearing impaired flag in the score_subtitles to indicate if they are more important or not?

**Comment by caronc** [comment]
With respect to hearing impaired subtitles; I'm with @h3llrais3r with this one.  This is how I implemented it for [my wrapper](https://github.com/caronc/nzbget-subliminal) of your tool:

snip from the docs:
The script can operate in one of 5 modes:

*    __ImpairedOnly__: Only attempt to fetch subtitles that are identified as supporting the hearing impaired. Note: This is not an enhancment and exists in the current version of subliminal.
*    __StandardOnly__: Only attempt to fetch subtitles that are NOT identified as supporting the hearing impaired. Note: This is not an enhancment and exists in the current version of subliminal.
*    __BestScore__: Just download the best matched subtitles reguardless of whether they are for the hearing impaired or not. Note: This is the default option.
*    __ImpairedFirst__: This is similar to the BestScore mode above; except the script scores (weighs) the hearing impaired matches a bit higher in efforts to make them be priority over any other subtitles matched.
*    __StandardFirst__: This is similar to the BestScore mode above; except the script scores (weighs) the hearing impaired matches a bit lower in efforts to make them be the last to be considered as a match.

**Comment by h3llrais3r** [comment]
My PR only provides the first 3.
The last 2 should indeed only apply to the best score, but in case there are 2 subs with the same score. Here it should be possible to decide if you give priority to hearing impaired or not. But I wouldn't affect the score because imho the hearing impaired is not score related. 
That's why I would provide a sort of method that sorts the subtitles on score and hearing impaired.

**Comment by Diaoul** [comment]
I'll push my branch hopefully this evening (CEST) and you will see the changes I made and if that fits your need.
I implemented the last 3, the first 2 can be implemented easily by adjusting the scores.

The idea of the scores is to provide powerful sorting of all sort of things including preferences. This is to avoid another sorting downstream. For example you might want `hearing_impaired` first but how bad? Would you prefer a subtitle with `release_group` but not `hearing_imaired` or a `hearing_impaired` subtitle? That's what scoring solves.

Scoring is not always just an ordering matter (hearing impaired > audio codec > video codec > release group > ... > hash), for example all other matches are equivalent to hash so providers that don't use hash can still get a reasonably high score.

**Comment by h3llrais3r** [comment]
Actually the last 3 should be fine also.
Because I don't care if they are hearing impaired or not, I can use the standardFirst option  ;)

I'm looking forward to your new branch :+1:

**Comment by Diaoul** [comment]
OK, this has been delayed as I made a few last minutes changes to the API and finished the CLI. I'm pretty happy with both and I hope you will like it too. A lot of code deduplication and easier API while still providing flexibility.

I need to add a few unit tests and we should be ready for the first RC.

**Comment by Diaoul** [comment]
And... done. :cake:

**Comment by Diaoul** [comment]
I've improved the documentation: http://subliminal.readthedocs.org/en/latest
I'd appreciate if you can have a quick look, report typos, bad English and other errors.

Thanks

**Comment by caronc** [comment]
Dude, you've spent a ridiculous amount of time on this; congratulations (seriously!) and well done!  I don't have time to click on every link tonight. But your tool is rewarding so  I'll peak at it overtime and let you know if i find anything.  No news is good news of course!
