### ISSUE TITLE
please add new provider shooter (Chinese subtitle)

### ISSUE THREAD

**Issue by ghost** [Diaoul/subliminal#459]
thanks a lot for this great tool, please also consider to add a new provider for shooter.cn, which is commonly used for Chinese subtitles. The code has been ready and I've been using for myself. Can't find a way to attach them here so was sent to you for review.

Thanks again for considering it.
##

**Comment by bcse** [comment]
I had a PR to add shooter.cn provider, too. #398
Just out of curious... AFAIK, shooter.cn was shut down by the end of 2014. Why do you need a shooter.cn provider in 2015?

**Comment by ratoaq2** [comment]
It's already supported in latest release
