### ISSUE TITLE
Problem when using subliminal in api mode

### ISSUE THREAD

**Issue by h3llrais3r** [Diaoul/subliminal#471]
When using subliminal in api mode (without an 'install' of subliminal) I have problems with the providers.
I can register the providers as entry point myself, but they are always empty because the import of subliminal in my application always triggers the following code from 'api.py' before I can register them myself:
```
provider_manager = ExtensionManager('subliminal.providers')
```
The provider manager uses a cache, so they remain empty.
As workaround, I now pop the 'subliminal.providers' from the ExtensionManager CACHE so it will be read again.
What's the proper way to re-initialize the provider_manager?

**Comment by Diaoul** [comment]
See https://github.com/Diaoul/subliminal/tree/no_setup
I accept PRs to maintain this patch and extend the logic to the ProviderPool manager.

**Comment by h3llrais3r** [comment]
Thanks for your modification, but I would rather not have a separate branch ;)
I just succeeded in reloading the provider_manager by:
- register the 'subliminal.providers' entry point myself at runtime
- re-initializing the provider.manager in subliminal.api

```
    distribution = pkg_resources.Distribution(location=os.path.dirname(current_path),
                                              project_name='fake_entry_points', version='1.0.0')
    # Add entry points here if needed
    # Add subliminal entry points (since subliminal 1.0)
    entry_points = {
        'subliminal.providers': [
            'addic7ed = subliminal.providers.addic7ed:Addic7edProvider',
            'opensubtitles = subliminal.providers.opensubtitles:OpenSubtitlesProvider',
            'podnapisi = subliminal.providers.podnapisi:PodnapisiProvider',
            'thesubdb = subliminal.providers.thesubdb:TheSubDBProvider',
            'tvsubtitles = subliminal.providers.tvsubtitles:TVsubtitlesProvider'
        ],
        'babelfish.language_converters': [
            'addic7ed = subliminal.converters.addic7ed:Addic7edConverter',
            'tvsubtitles = subliminal.converters.tvsubtitles:TVsubtitlesConverter'
        ]
    }
    distribution._ep_map = pkg_resources.EntryPoint.parse_map(entry_points, distribution)
    pkg_resources.working_set.add(distribution)


    # Clear subliminal providers from provider manager entry point cache because they were empty at startup
    # Entry point is set by our own fake_entry_points, so they need to be reloaded
    provider_manager.ENTRY_POINT_CACHE.pop('subliminal.providers')
    provider_manager.__init__('subliminal.providers')
```

Perhaps you can provide a helper method in the api to re-initialize the provider_manager in a similar way?

**Comment by Diaoul** [comment]
I believe if you do all that *before* importing subliminal you shouldn't need any hack.

**Comment by h3llrais3r** [comment]
You're right. I played a bit with my imports and now I manage to create the entry points at runtime before the provider_manager is loaded!
The clearing is not longer needed. :+1:

**Comment by Diaoul** [comment]
Glad you found a proper way to make it work :)

**Comment by h3llrais3r** [comment]
PS: I just saw that the readme.rst for the save_subtitles method is not up to date ;)

# save them to disk, next to the video
save_subtitles(subtitles)

**Comment by Diaoul** [comment]
Can you make a PR with the appropriate change?
