### ISSUE TITLE
Addic7ed : invalid provider ??

### ISSUE THREAD

**Issue by SeeDborg** [Diaoul/subliminal#472]
I'm on 1.0.1. My old problem is solved, but I've got a new one :

subliminal --addic7ed *USERNAME* *PASSWORD* --debug download -l fr -s -v -p addic7ed /media/RASPI-HDD2/Video/Series
Usage: subliminal download [OPTIONS] PATH...

Error: Invalid value for "-p" / "--provider": invalid choice: addic7ed. (choose from )

**Comment by Diaoul** [comment]
Try `subliminal download --help`, you should have a list of providers. If not, uninstall then reinstall subliminal, there might be something broken from previous install.

**Comment by SeeDborg** [comment]
subliminal download --help                                                              :(
Usage: subliminal download [OPTIONS] PATH...

  Download best subtitles.

  PATH can be an directory containing videos, a video file path or a video file name. It can be
  used multiple times.

  If an existing subtitle is detected (external or embedded) in the correct language, the
  download is skipped for the associated video.

Options:
  -l, --language LANGUAGE        Language as IETF code, e.g. en, pt-BR (can be used multiple
                                 times).  [required]
  -p, --provider []              Provider to use (can be used multiple times).
  -a, --age AGE                  Filter videos newer than AGE, e.g. 12h, 1w2d.
  -d, --directory DIR            Directory where to save subtitles, default is next to the video
                                 file.
  -e, --encoding ENC             Subtitle file encoding, default is to preserve original encoding.
  -s, --single                   Save subtitle without language code in the file name, i.e. use
                                 .srt extension.
  -f, --force                    Force download even if a subtitle already exist.
  -hi, --hearing-impaired        Prefer hearing impaired subtitles.
  -m, --min-score INTEGER RANGE  Minimum score for a subtitle to be downloaded (0 to 100).
  -v, --verbose                  Increase verbosity.
  --help                         Show this message and exit.



No list of providers. Tried pip uninstall subliminal && pip install subliminal. Something else to do ? I will try manual installation.

**Comment by SeeDborg** [comment]
It seems to work with manual installation.
I won't be able to upgrade with pip, will have to do it manually, but at least it works !
Thanks for the help.

**Comment by Diaoul** [comment]
I tried a fresh install on windows on a virtualenv and didn't have any issue.
