### ISSUE TITLE
ignoring video files

### ISSUE THREAD

**Issue by discoHR** [Diaoul/subliminal#477]
Can't figure out why is subliminal ignoring all MKVs it finds.

disco@lenovo subliminal-master$ subliminal --version
subliminal, version 1.0.1
disco@lenovo subliminal-master$ subliminal --debug download -l hr -l bs -l sr -p podnapisi -p opensubtitles -s /mnt/share/_incoming/The\ 100/Season\ 1/
Collecting videos
Collecting videos
DEBUG:subliminal.cli:Collecting path /mnt/share/_incoming/The 100/Season 1/
DEBUG:subliminal.video:Walking directory /mnt/share/_incoming/The 100/Season 1/
INFO:subliminal.video:Scanning video u'The.100.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv' in u'/mnt/share/_incoming/The 100/Season 1'
DEBUG:subliminal.video:Size is 1649499423
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'7af31616549810a3', u'thesubdb': '338a5ef1522b46a90477cf7292f748b0'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
INFO:subliminal.video:Scanning video u'The.100.S01E02.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv' in u'/mnt/share/_incoming/The 100/Season 1'
DEBUG:subliminal.video:Size is 1725875182
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'0a3aaf00a4ea7adc', u'thesubdb': '5e5d596cfc035976cbeb6b8d135448e0'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
INFO:subliminal.video:Scanning video u'The.100.S01E03.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv' in u'/mnt/share/_incoming/The 100/Season 1'
DEBUG:subliminal.video:Size is 1600145071
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'6f9577ec26b31dee', u'thesubdb': 'ea0574af70803d5fea602dd750a22526'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
INFO:subliminal.video:Scanning video u'The.100.S01E04.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv' in u'/mnt/share/_incoming/The 100/Season 1'
DEBUG:subliminal.video:Size is 1659676776
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'd96c5a5d9f3cb662', u'thesubdb': '7e7eadc9757e7e51eae44e01a8f016d9'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
INFO:subliminal.video:Scanning video u'The.100.S01E05.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv' in u'/mnt/share/_incoming/The 100/Season 1'
DEBUG:subliminal.video:Size is 1583447687
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'7c8e3596dc9e0e9e', u'thesubdb': '9103ab37add1c24a9d910ae0b609bd45'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
INFO:subliminal.video:Scanning video u'The.100.S01E06.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv' in u'/mnt/share/_incoming/The 100/Season 1'
DEBUG:subliminal.video:Size is 1642551966
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'8c74b4070a7c85dd', u'thesubdb': 'cf7207db3a0e091920f3212256d19aa8'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
INFO:subliminal.video:Scanning video u'The.100.S01E07.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv' in u'/mnt/share/_incoming/The 100/Season 1'
DEBUG:subliminal.video:Size is 1642135508
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'0e35a48313ed7296', u'thesubdb': '9778704af71c985332fa2c70e9d490a6'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
INFO:subliminal.video:Scanning video u'The.100.S01E08.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv' in u'/mnt/share/_incoming/The 100/Season 1'
DEBUG:subliminal.video:Size is 1634471457
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'35b5353b6777acbf', u'thesubdb': '18cf88f2bc6c446a71049bb63b1027dc'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
INFO:subliminal.video:Scanning video u'The.100.S01E09.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv' in u'/mnt/share/_incoming/The 100/Season 1'
DEBUG:subliminal.video:Size is 1594208900
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'6733befc7913fc6a', u'thesubdb': 'd9c9a75a2b76184c110c6c9b9c28c8ec'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
INFO:subliminal.video:Scanning video u'The.100.S01E10.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv' in u'/mnt/share/_incoming/The 100/Season 1'
DEBUG:subliminal.video:Size is 1741190230
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'94fb8920724c17ef', u'thesubdb': '701657eda73880f2c34946de0ea7e21c'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
INFO:subliminal.video:Scanning video u'The.100.S01E11.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv' in u'/mnt/share/_incoming/The 100/Season 1'
DEBUG:subliminal.video:Size is 1638597245
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'87f667a0fad096aa', u'thesubdb': '5b66ac6b2c2b73af53db67d06ae5e0e0'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
INFO:subliminal.video:Scanning video u'The.100.S01E12.1080p.WEB-DL.DD5.1.H.264-KiNGS[rarbg].mkv' in u'/mnt/share/_incoming/The 100/Season 1'
DEBUG:subliminal.video:Size is 1657876279
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'16c45bdd8d558f91', u'thesubdb': '3b986ea5415fa94e30713657cc41ddbd'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
INFO:subliminal.video:Scanning video u'The.100.S01E13.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv' in u'/mnt/share/_incoming/The 100/Season 1'
DEBUG:subliminal.video:Size is 1652718107
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'18f3722011ea5d2f', u'thesubdb': '4f999942f2c1de81d4b6d4685e2399dd'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
DEBUG:subliminal.api:Undefined language found
DEBUG:subliminal.api:Undefined language found
DEBUG:subliminal.api:Undefined language found
DEBUG:subliminal.api:Undefined language found
DEBUG:subliminal.api:Undefined language found
DEBUG:subliminal.api:Undefined language found
DEBUG:subliminal.api:Undefined language found
DEBUG:subliminal.api:Undefined language found
DEBUG:subliminal.api:Undefined language found
DEBUG:subliminal.api:Undefined language found
DEBUG:subliminal.api:Undefined language found
DEBUG:subliminal.api:Undefined language found
DEBUG:subliminal.api:Undefined language found
0 video collected / 13 videos ignored / 0 error

**Comment by discoHR** [comment]
I guess subliminal ignores them because embedded subtitles exist. Using -f forces download anyway. It would be better not to treat embedded subtitle of unknown language as existing subtitle. In this case embedded were english and I requested different languages. This worked fine before (v0.7.x, v0.8.x), looks like it was introduced in v1.0.x.

**Comment by Diaoul** [comment]
You use -s switch so it saves subtitles as .srt which is Unknown language when scanned. This is a safety to avoid constantly redownloading subtitles.

I don't see any embedded subtitles in your logs, it's more likely that a .srt already exist.

This is not new, even if it was it's here to stay.

**Comment by discoHR** [comment]
No, there were no .srt files, I'm 100% sure.

For each file with embedded subtitle the following lines are visible in the log above:
DEBUG:subliminal.video:Found embedded subtitle set([]) with enzyme
DEBUG:subliminal.api:Undefined language found

The mediainfo output confirms there is an embedded subtitle of unknown language in each file:
Text
ID                                       : 1
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Default                                  : Yes
Forced                                   : No

**Comment by Diaoul** [comment]
The log clearly says there are no embedded subtitles detected by enzyme. Here is the relevant portion of code: https://github.com/Diaoul/subliminal/blob/master/subliminal/video.py#L367-L385
If there were any, even undefined, it would have shown in the log, something like:

    DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme

It also clearly says there are no external subtitles:

    DEBUG:subliminal.video:Found subtitles {}

So I don't explain the logs:

    DEBUG:subliminal.api:Undefined language found

As the relevant portion of code seems OK: https://github.com/Diaoul/subliminal/blob/master/subliminal/api.py#L253-L256

**Comment by Diaoul** [comment]
I cannot reproduce

**Comment by Diaoul** [comment]
Can you try to add verbosity with `-vv` instead of `--debug`? It should display why the video is ignored.

**Comment by discoHR** [comment]
Sure, here it is:

> disco@lenovo Season 1$ subliminal download -vv -l hr -l bs -l sr -p podnapisi -p opensubtitles -s .
> Collecting videos  [####################################]  100%
> The.100.S01E01.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv ignored - subtitles: und / age: 0 day
> The.100.S01E02.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv ignored - subtitles: und / age: 0 day
> The.100.S01E03.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv ignored - subtitles: und / age: 0 day
> The.100.S01E04.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv ignored - subtitles: und / age: 0 day
> The.100.S01E05.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv ignored - subtitles: und / age: 0 day
> The.100.S01E06.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv ignored - subtitles: und / age: 0 day
> The.100.S01E07.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv ignored - subtitles: und / age: 0 day
> The.100.S01E08.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv ignored - subtitles: und / age: 0 day
> The.100.S01E09.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv ignored - subtitles: und / age: 0 day
> The.100.S01E10.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv ignored - subtitles: und / age: 0 day
> The.100.S01E11.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv ignored - subtitles: und / age: 0 day
> The.100.S01E12.1080p.WEB-DL.DD5.1.H.264-KiNGS[rarbg].mkv ignored - subtitles: und / age: 0 day
> The.100.S01E13.1080p.WEB-DL.DD5.1.H.264-KiNGS.mkv ignored - subtitles: und / age: 0 day
> 0 video collected / 13 videos ignored / 0 error

There are no SRT subtitles present.
> disco@lenovo Season 1$ ls *.srt
> ls: cannot access *.srt: No such file or directory

**Comment by Diaoul** [comment]
OK so there is Undefined language detected but it doesn't show in the debug log. There must be some obvious error somewhere here that I don't see: https://github.com/Diaoul/subliminal/blob/master/subliminal/video.py#L365-L387

**Comment by discoHR** [comment]
I'm not into Python (I'm a Java guy) but line 383 is where it is added without logging and line 385 is where embedded undefined language is applied to video.subtitle_languages. My point is: embedded subtitles with undefined language should not be applied to video.subtitle_languages, only defined languages should be applied.

**Comment by Diaoul** [comment]
I was talking about the log message not showing correctly in your logs.

By ignoring und, we risk downloading a subtitle that already exist, embedded in the video. You wouldn't have that problem without the `-s` switch and I recommend not using it as it is the only way to have language information in SubRip file format (no comments allowed in the file).

**Comment by discoHR** [comment]
I already updated the firmware on my media player to support multiple external subtitles and moved away from the -s switch. Feel free to close it.

**Comment by Diaoul** [comment]
May I ask what media player you are using?
I'll leave it open to update this section of the documentation: http://subliminal.readthedocs.org/en/latest/user/cli.html?highlight=external#subliminal-download

**Comment by discoHR** [comment]
I'm using WDTV Live HD (v1), switched from official firmware to WDLXTV. It
selects proper external subtitle automatically and I can still manually
switch to another in case something is wrong with it.

**Comment by tvb** [comment]
By the looks of it I am having the same problem. Can anyone tell me why my videos are ignored?

the cron:
```
5 * * * * /usr/local/bin/subliminal --debug download -l nl -v -s -a 1w /mnt/data/ > /tmp/subliminal.log 2>&1
```

the logs:
```
Collecting videos
Collecting videos
DEBUG:subliminal.cli:Collecting path /mnt/data/
DEBUG:subliminal.video:Walking directory /mnt/data/
DEBUG:subliminal.video:Walking directory /mnt/data/movies
DEBUG:subliminal.video:Walking directory /mnt/data/series
DEBUG:subliminal.video:Walking directory /mnt/data/series/How I Met Your Mother
DEBUG:subliminal.video:Walking directory /mnt/data/series/How I Met Your Mother/Season 9
INFO:subliminal.video:Scanning video u'How.I.Met.Your.Mother.-.S09E12.-.The.Rehearsal.Dinner.WEBDL-1080p.mkv' in u'/mnt/data/series/How I Met Your Mother/Season 9'
DEBUG:subliminal.video:Size is 831195077
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'cf244c230d38e383', u'thesubdb': 'a839d03e9df2f9ed13e787bdfa8f83ff'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Embedded subtitle track name u'CC' is not a valid language
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
DEBUG:subliminal.video:Walking directory /mnt/data/series/Game of Thrones
DEBUG:subliminal.video:Walking directory /mnt/data/series/Game of Thrones/Season 5
INFO:subliminal.video:Scanning video u"Game.of.Thrones.-.S05E10.-.Mother's.Mercy.WEBDL-1080p.mkv" in u'/mnt/data/series/Game of Thrones/Season 5'
DEBUG:subliminal.video:Size is 2311766286
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'45f63c66659136cf', u'thesubdb': 'cf2a0147a5baf219aaa1503ee3f277b6'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
DEBUG:subliminal.api:Undefined language found
DEBUG:subliminal.api:Undefined language found
0 video collected / 2 videos ignored / 0 error
```

**Comment by tvb** [comment]
@Diaoul any clue?

**Comment by Diaoul** [comment]
Well, same error, same reason.
Your video is ignored because it already contains embedded subtitles.
```
DEBUG:subliminal.video:Found embedded subtitle set([<Language [und]>]) with enzyme
```

I will complete the `--force` option with an `--ignore-embedded-subtitles` flag somehow.

**Comment by DTrace001** [comment]
Having similar issues. Don't think it has embedded subtitles though.
```python
# subliminal --debug download . -l en
 Collecting videos  [####################################]  100%  .DEBUG:subliminal.cli:Collecting path .
DEBUG:subliminal.video:Walking directory .
DEBUG:subliminal.video:Walking directory ./Killjoys.S01E10.720p.HDTV.x264-IMMERSE
INFO:subliminal.video:Scanning video 'Killjoys.S01E10.720p.HDTV.x264-IMMERSE.mkv' in './Killjoys.S01E10.720p.HDTV.x264-IMMERSE'
DEBUG:subliminal.video:Size is 1144266381
DEBUG:subliminal.video:Computed hashes {'opensubtitles': 'f56a661b776c6896', 'thesubdb': '5c2e212f58bd7b67563adf7d2a25d657', 'napiprojekt': 'c49ec1df849ddcb5f89f89541e68aa87'}
DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found resolution 720p with enzyme
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Found embedded subtitle set([<Language [en]>]) with enzyme
DEBUG:subliminal.api:All languages set([<Language [en]>]) exist
Collecting videos  [####################################]  100%
0 video collected / 1 video ignored / 0 error
```

```python
# subliminal  download -vv . -l en
Collecting videos  [####################################]  100%
Killjoys.S01E10.720p.HDTV.x264-IMMERSE.mkv ignored - subtitles: en / age: 5 days
0 video collected / 1 video ignored / 0 error
```

**Comment by Diaoul** [comment]
It has:
```
DEBUG:subliminal.video:Found embedded subtitle set([<Language [en]>]) with enzyme
DEBUG:subliminal.api:All languages set([<Language [en]>]) exist
```

**Comment by Diaoul** [comment]
I'm not sure about he solution I mentioned above. The `--force` flag is already there to enforce downloading if anything goes wrong. This kind of thing happens it's inevitable and it's unlikely you will find subtitles for a video already containing embedded subtitles so skipping is the correct action.

Adding a new flag will just add confusion and will not guarantee that it'll work anyway. The use of `--single` flag is discouraged because it hides the language of the subtitle from subliminal when scanning for existing subtitles. I will add documentation about this.

**Comment by tvb** [comment]
Hmm ok so embedded subs are making subliminal ignoring it completely? I would think the `--force` flag would download them anyway.

I need the `--single` flag because otherwise my video player of my smart tv won't pick up the subtitle, it has to have the same name as the video file with only the extension being .srt.

**Comment by Diaoul** [comment]
Yes the `--force` flag will download them anyway. Never use the `--force` flag in a cron job though, that would result in a lot of queries to providers.

**Comment by tvb** [comment]
Just tested this:

```
pi@raspberrypi /mnt/data/movies $ /usr/local/bin/subliminal --debug download -l nl -f -v -s -a 1w /mnt/data/movies
Collecting videos  [####################################]  100%  /mnt/data/moviesDEBUG:subliminal.cli:Collecting path /mnt/data/movies
DEBUG:subliminal.video:Walking directory /mnt/data/movies
DEBUG:subliminal.video:Walking directory /mnt/data/movies/Focus.2015.WEB-DL.720p.x264.AC3
INFO:subliminal.video:Scanning video u'Focus.2015.WEB-DL.720p.x264.AC3.mkv' in u'/mnt/data/movies/Focus.2015.WEB-DL.720p.x264.AC3'
DEBUG:subliminal.video:Size is 3801416156
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'd51a1d6446035b42', u'thesubdb': '042bfca76b13aa0b430af9f5b8a53699'}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Walking directory /mnt/data/movies/Godfather.Part.III,.The.(1990)
INFO:subliminal.video:Scanning video u'The.Godfather.Part.III.mp4' in u'/mnt/data/movies/Godfather.Part.III,.The.(1990)'
DEBUG:subliminal.video:Size is 1412791709
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'bc1015dc23cb63a3', u'thesubdb': '51d018cfc4a90aecdb05db3501d787dc'}
DEBUG:subliminal.video:Walking directory /mnt/data/movies/Godfather.Part.II,.The.(1974)
INFO:subliminal.video:Scanning video u'The.Godfather.Part.II.mp4' in u'/mnt/data/movies/Godfather.Part.II,.The.(1974)'
DEBUG:subliminal.video:Size is 3191589591
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'861a8fdc42d29d32', u'thesubdb': 'be7c494bca7032bc953a3320ee427651'}
DEBUG:subliminal.video:Walking directory /mnt/data/movies/Godfather,.The.(1972)
INFO:subliminal.video:Scanning video u'The.Godfather.mkv' in u'/mnt/data/movies/Godfather,.The.(1972)'
DEBUG:subliminal.video:Size is 20145980365
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'9933a458d94e58a6', u'thesubdb': '71ea044a1abcb8765bc16d3a0a3b65d2'}
DEBUG:subliminal.video:Found resolution 1080p with enzyme
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:Walking directory /mnt/data/movies/Mad.Max.Fury.Road.(2015)
INFO:subliminal.video:Scanning video u'Mad.Max.Fury.Road.mkv' in u'/mnt/data/movies/Mad.Max.Fury.Road.(2015)'
DEBUG:subliminal.video:Size is 3371871665
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'c0a09517dbce5af8', u'thesubdb': 'c1d0be0c7c66ae89c9ca8bfc7dca2f34'}
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:MKV has no subtitle track
DEBUG:subliminal.video:Walking directory /mnt/data/movies/Insurgent 2015 1080p HDRip x264 AC3-JYK
INFO:subliminal.video:Scanning video u'Insurgent 2015 1080p HDRip x264 AC3-JYK.mkv' in u'/mnt/data/movies/Insurgent 2015 1080p HDRip x264 AC3-JYK'
DEBUG:subliminal.video:Size is 2951986914
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'b3b3f9017cedbda7', u'thesubdb': '0ad4b6194b651bab14ead5108362f7f2'}
DEBUG:subliminal.video:Found resolution 1080p with enzyme
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:MKV has no subtitle track
DEBUG:subliminal.video:Walking directory /mnt/data/movies/Chappie.(2015)
INFO:subliminal.video:Scanning video u'Chappie.mkv' in u'/mnt/data/movies/Chappie.(2015)'
DEBUG:subliminal.video:Size is 1315869470
DEBUG:subliminal.video:Computed hashes {u'opensubtitles': u'cbe986d808b43980', u'thesubdb': '69125da6bd0f1c217e2b659699b026e3'}
DEBUG:subliminal.video:Found resolution 1080p with enzyme
DEBUG:subliminal.video:Found audio_codec AAC with enzyme
DEBUG:subliminal.api:Video is older than datetime.timedelta(7)
DEBUG:subliminal.api:Video is older than datetime.timedelta(7)
DEBUG:subliminal.api:Video is older than datetime.timedelta(7)
DEBUG:subliminal.api:Video is older than datetime.timedelta(7)
DEBUG:subliminal.api:Video is older than datetime.timedelta(7)
DEBUG:subliminal.api:Video is older than datetime.timedelta(7)
DEBUG:subliminal.api:Video is older than datetime.timedelta(7)
Collecting videos  [####################################]  100%
0 video collected / 7 videos ignored / 0 error
```
It seems the `-a 1w` flag will overrule the `--force` flag.

**Comment by Diaoul** [comment]
Yes, this is the expected behavior. `--force` does not override other flags, it just enforce downloading subtitles even of some already exist.

**Comment by tvb** [comment]
@Diaoul seen my edit?

**Comment by Diaoul** [comment]
What is wrong? I see a normal behavior here.

**Comment by tvb** [comment]
@Diaoul sorry for my lack of understanding :blush: Why is subliminal not downloading these titles?

```
0 subtitle downloaded for Chappie.mkv
0 subtitle downloaded for The.Godfather.Part.II.mp4
0 subtitle downloaded for The.Godfather.mkv
0 subtitle downloaded for The.Godfather.Part.III.mp4
0 subtitle downloaded for Mad.Max.Fury.Road.mkv
0 subtitle downloaded for Insurgent 2015 1080p HDRip x264 AC3-JYK.mkv
```

**Comment by Diaoul** [comment]
Because it didn't find any `nl` subtitle for those. Multiple reasons for this:
* Not all providers provide `nl` subtitles for movies
* opensubtitles is discarded (server down?): `ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Service Not Available>`
* podnapisi is discarded because of an unexpected error: `ProviderError: More than one file to unzip`

For the first one there is nothing to do sadly, server is down. For the second error in Podnapisi you can open a new issue and maybe I can improve how zip containing multiple files are dealt with.

**Comment by Diaoul** [comment]
`subliminal download --help` already shows that *limitation*. What can I do to make it more obvious? See http://subliminal.readthedocs.org/en/latest/user/cli.html#subliminal-download

**Comment by paranoidi** [comment]
> What can I do to make it more obvious?

Maybe add more explicit message in -v output? Something along "Video ignored because of embedded subtitle exists" or so.
