### ISSUE TITLE
Please bring back -q (quiet) switch

### ISSUE THREAD

**Issue by discoHR** [Diaoul/subliminal#478]
It's very useful in cron jobs, torrent done scripts etc.

**Comment by Diaoul** [comment]
It was deleted because the alternative to silent anything is to redirect output `> /dev/null 2>&1`. Unless there is a good reason. Same goes for the log file, redirecting output creates a log file.

Tell me if that works for you.

**Comment by discoHR** [comment]
I guess that's one way to do it. It's not elegant but it works. :)

**Comment by Diaoul** [comment]
It's indeed not as elegant as `-q` but a hell lot easier to implement and a lot safer for you as you don't depend on a switch to set the output level.
