### ISSUE TITLE
is there a little bit easier way to drop-in provider when hash is needed?

### ISSUE THREAD

**Issue by ghost** [Diaoul/subliminal#479]
when I'm writing an extra provider, involved with hash, I had to modify at least three files: entry_points.txt, video.py, and new provider in providers folder. Upon subliminal upgrade, the first two gets upgraded and overridden. I used a script to change back, but video.py isn't that safe to modify because of python indentation. 

So I am wondering if there could be an easier way to write a drop-in provider when hash is required.

**Comment by Diaoul** [comment]
What are you trying to achieve? You want to reuse a provider you created pre 1.0 in 1.0? You are creating a new one from scratch?

Which subliminal upgrade are you talking about? 1.0? 1.0.1? Your dev version?

You don't need to modify entrypoints.txt, this is managed by python packaging tools (namely setuptools).

Did you check the [documentation section about writing providers](http://subliminal.readthedocs.org/en/latest/user/provider_guide.html)?

**Comment by TimLuo** [comment]
Sorry, the information wasn't quite clear. 

I was trying to create a new one provider from scratch, and put inside provider directory. so I  The version was pre 1.0, (0.7.4). It complains that couldn't find the the provider, when I invoke the CLI. so I manually modified the entrypoints.txt. And added another hash function at the end of video.py, also an extra line below "video.hashes['thesubdb'] = hash_thesubdb(path)"

Now I just upgrade the subliminal, changes in video.py and entrypoints.txt are of course gone. Did i do things wrong?

**Comment by TimLuo** [comment]
my bad, it looks like the 1.0 doesn't support extra provider any more in CLI, except those predefined. 

in 0.7.4 by modify entrypoints.txt, I could run something like
subliminal -p myprovider '/path/to/video/'

I think I will roll back to 0.7.4 for now til figure out how to use subliminal's new API like a module instead. 
But still wondering when is there an easier way to add the hash function, instead of modifying the video.py file?

**Comment by Diaoul** [comment]
What's wrong with modifying video.py? You can fork subliminal, make your changes and submit a pull request. This way everyone could benefit the provider you're adding.

If you want to extend subliminal with some private provider, you can do so by registering your provider using an entry point in your application's setup.py. This is what subliminal uses to register converters to babelfish (see [here](https://github.com/Diaoul/subliminal/blob/master/setup.py#L88-L91)).
There is plenty documentation on the topic on internet.

**Comment by Diaoul** [comment]
Any updates on this?

**Comment by t4lwh** [comment]
sorry deleted my account by accident. I will fork subliminal and add my provider as you suggested. 
Thanks
