### ISSUE TITLE
ERROR:subliminal.video:Skipping badly encoded directory

### ISSUE THREAD

**Issue by papou-github** [Diaoul/subliminal#480]
Hi,
When using subliminal from a Bash script executed by Nautilus on a directory, I have this message : ERROR:subliminal.video:Skipping badly encoded directory
When I launch the script directly from an xterm with parameter it work
Do you have any clue ?
Version used :1.01
OS : Ubuntu 14.04

Script :
!/bin/bash
/usr/local/bin/subliminal --debug download -l fr -s "$PWD/$1" >> /tmp/sub 2>&1

Error example on /Windows/Series/Arrow

ERROR:subliminal.video:Skipping badly encoded directory u'/Windows/Series/Arrow'
ERROR:subliminal.video:Skipping badly encoded directory u'/Windows/Series/Arrow/S02'
ERROR:subliminal.video:Skipping badly encoded directory u'/Windows/Series/Arrow/S03'

Any clue ?

**Comment by Diaoul** [comment]
That's Python not correctly listing directories. Check the environment variables, especially encoding related ones, like LANG and LC_ALL.
Try with Python3, it might help.

**Comment by papou-github** [comment]
Thank you Diaoul, i will continue to investigate on those directions.

**Comment by tvb** [comment]
I am having the same issue and are unable to solve it. Tried everything I know to set the encoding variables. Through cron, .profile, /etc/environment but none fixes it.. any tips?

**Comment by Diaoul** [comment]
Thanks for sharing. Did you try python3?

**Comment by papou-github** [comment]
I confirm It work with tvb solution for Nautilus in case you are trying to scan a directory.

#!/bin/bash
# Nautilus Script to Get Srt 
export PYTHONIOENCODING=utf8
/usr/local/bin/subliminal download -l "fr" -s "$PWD/$1" && zenity --info --title "Info" --text "Subtitle downloaded successfully" || zenity --error --title "Error" --text "Subtitles not downloaded successfully" >> /tmp/sub 2>&1

@Diaoul : I will try with Python3 as my current version is 2.7.6

**Comment by Diaoul** [comment]
I edited the syntax so it displays nicely on GitHub. That could be nice to ship examples on how to use subliminal in that kind of ways (example cron jobs, right click context menu, etc.)

**Comment by tvb** [comment]
I agree, the documentation is lacking here and there.
