### ISSUE TITLE
Is there a way to force downloading subtitle?

### ISSUE THREAD

**Issue by matbee** [Diaoul/subliminal#482]
I have movie files that most of the times works with yify/yts subtitles. But Subliminal never grabs these subs, Is there a way to always grab a subtitle, even it doesn't fully match.

**Comment by Diaoul** [comment]
Using CLI or API?

**Comment by matbee** [comment]
Uhm, I have used couchpotato/sickrage built-in and subliminal plex plugin.

**Comment by Diaoul** [comment]
You have to check with those applications owners then because subliminal allows all kind of overrides within its library.

**Comment by matbee** [comment]
Ok, but your standalone version is supporting this?

**Comment by Diaoul** [comment]
There's just a command line interface (CLI) that's shipped with subliminal and it doesn't support adding extra information about videos. I'm open to ideas on how to implement this in the command line.
