### ISSUE TITLE
Library doesn't work for me right now

### ISSUE THREAD

**Issue by badescuga** [Diaoul/subliminal#486]
ok, so i've tried using the example provided in the README with no luck. I've installed subliminal using pip and am currently using v1.0.1. 

first of all, i'm new to python, i'm picking up as i go. So let's start.

 TypeError: save_subtitles() takes at least 2 arguments (1 given)

looking thourgh the code on github, indeed, there is no save_subtitles that takes 1 param(min 2 params). I've commented this out to test the rest. When i use scan_videos, i get that the videos dict has 0 items, although i have a lot of mkv, mp4 etc files in that specific folder. 

i'm trying a go-around using this:

video = scan_video('/Users/badescuga/Downloads/Suits.S05E05.Toe.to.Toe.1080p.WEB-DL.DD5.1.H.264-S.mkv')
videos = {video}

videos now indeed has one item in it. 

I then use this:

subtitles = download_best_subtitles(videos, {Language('eng'), Language('fra')})
print len(subtitles)
for subt in subtitles:
	print '--------subt type: ' + str(type(subt))

the print indeed shows '1' but the type of the subt is 'subliminal.video.Episode''

Hope this helped. Keep me up to speed, i'm interested in working on this project. There may be things i've missed (in terms of python lang)

**Comment by Zopieux** [comment]
`subtitles` is a dictionnary. Keys are instances of `Episode` (hence what you get with `type()`) and associated values are lists of downloaded subtitles (that you can later save on disk with `save_subtitles()`).

I can't see the issue there. If all you need is download subtitles for your movies, you can use the [CLI tool](https://subliminal.readthedocs.org/en/latest/user/usage.html#cli).

**Comment by MaverickChaser** [comment]
cli works perfectly.

But I face issues with python api.

    >>> videos
    [<Movie ['Blood Diamond']>, <Movie ["Cafe Don's Plam"]>, <Movie ['The Wolf of Wall Street']>]
    >>> subtitles = download_best_subtitles(videos, {Language('eng'), Language('rus')})
    >>> subtitles
    defaultdict(<class 'list'>, {<Movie ['Blood Diamond']>: [<PodnapisiSubtitle 'qa05' [en]>], <Movie ["Cafe Don's Plam"]>: []})

It skipped The Wolf of Wall Street! How did that happen ?

Ok, let's try to save downloaded subtitles. 
      >>> save_subtitles(subtitles)
      Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: save_subtitles() missing 1 required positional argument: 'subtitles'

That's because `save_subtitles` requires 2 arguments -- video and subtitles. We need to retrieve the values from `defaultdict`.
But in <b>Usage</b> section:

    #save them to disk, next to the video
    save_subtitles(subtitles)

which magically works for the author.

**Comment by Diaoul** [comment]
The README isn't doctested so it can contain some error due to recent API
changes.

Please refer to the full documentation for now.

I'll fix it when I got some time available. Pull requests are always
welcome.

**Comment by MaverickChaser** [comment]
Diaoul, thanks for your answer.

**Comment by Diaoul** [comment]
Fixed with 38c86b4cf1059e13240f5bab547cda645be79a65
