### ISSUE TITLE
Some downloaded subtitles are incomplete (for example they only are for the first 30 min of the movie) then cut off.

### ISSUE THREAD

**Issue by jobrien2001** [Diaoul/subliminal#493]
C:\Users\Administrator\Desktop>subliminal --addic7ed user pw download -l en -l es -m 35 "d:\Movies1"
C:\Python27\lib\site-packages\subliminal-1.0.1-py2.7.egg\subliminal\cli.py:115:Warning: Click detected the use of the unicode_literals **future** import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
C:\Python27\lib\site-packages\subliminal-1.0.1-py2.7.egg\subliminal\cli.py:145: Warning: Click detected the use of the unicode_literals **future** import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
C:\Python27\lib\site-packages\subliminal-1.0.1-py2.7.egg\subliminal\cli.py:172: Warning: Click detected the use of the unicode_literals **future** import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/

Downloading subtitles  [####################################]  100%  hannibal.s03e12.720p.hdtv.x264-2hd.mkvC:\Python27\lib\site-packages\beautifulsoup4-4.4.0-py
2.7.egg\bs4\builder_htmlparser.py:167: RuntimeWarning: Python's built-in HTMLParser cannot parse the given document. This is not a bug in Beautiful Soup. The best solution is to install an external parser (lxml or html5lib), and use Beautiful Soup with that parser. See http://www.crummy.com/software/BeautifulSoup/bs4/
doc/#installing-a-parser for help.
Downloading subtitles  [####################################]  100%
##

**Comment by Diaoul** [comment]
Please include debug logs.

**Comment by jobrien2001** [comment]
http://pastebin.com/Sj5KhLNy

The log file option on the cli from previous versions was awesome.

**Comment by Diaoul** [comment]
You can use the debug switch and redirect stderr to the log file it does
the same thing. This 'needs to be documented in the contributing section.

**Comment by Diaoul** [comment]
I updated the contributing section with 168004dc89c53e1ada6ba8ff42b3ebba56d69bbc.

As for your issue, one possible solution would be to compare the movie duration with subtitles duration to determine if the subtitle file is suitable. Currently we trust the provider on that part.
