### ISSUE TITLE
Use of the unicode_literals __future__ import.

### ISSUE THREAD

**Issue by tutabeier** [Diaoul/subliminal#495]
Every time I ran some subliminal command I receive this
```
/usr/local/lib/python2.7/dist-packages/subliminal/cli.py:114: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.pass_context
/usr/local/lib/python2.7/dist-packages/subliminal/cli.py:144: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.pass_context
/usr/local/lib/python2.7/dist-packages/subliminal/cli.py:171: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @click.pass_obj
```
I just added to the beginning of cli.py
```
click.disable_unicode_literals_warning = True
```
And the problem stopped. Is there something wrong with Python in my computer?

**Comment by Diaoul** [comment]
This is already fixed with 79fb0442dd30ab4207f4a52fae9c3e8efb1eb451

**Comment by Diaoul** [comment]
This is due to click >= 5.0

**Comment by homegreewn** [comment]
@Diaoul forgive my ignorance but when you say it is already fixed is this something that it's automatically fixed in your release, or something I should manually add to a file to fix, because I just downloaded version 1.0.1 today and I am still getting this error in Ubuntu 14.04

**Comment by h3llrais3r** [comment]
Commit 79fb044 is fixed in develop, not yet merged in master (which is version 1.0.1). :wink:

**Comment by Diaoul** [comment]
Next release will fix this. Check milestone 1.1 to see what's left to do for that release.

**Comment by homegreewn** [comment]
Ok thank you for the reply, I am getting it now :smile:

**Comment by herrbischoff** [comment]
@tutabeier: Thanks for the hint, I have done the same and gone is the pesky warning.
