### ISSUE TITLE
nemo integration

### ISSUE THREAD

**Issue by skypce** [Diaoul/subliminal#501]
Will be great if you add nemo integration. many people change from nautilus to nemo by the lot of features that it has. Thank you in advance.

**Comment by Diaoul** [comment]
What are the specificities of nemo compared to nautilus? It should be pretty similar as nemo is a fork of nautilus.

**Comment by skypce** [comment]
in nemo you have many personalizable other features.check the video:
https://www.youtube.com/watch?v=fQhihnb2PV0 .

2015-09-07 8:07 GMT-03:00 Antoine Bertin <notifications@github.com>:

**Comment by queeup** [comment]
Love to have nemo integration :)

**Comment by Diaoul** [comment]
I won't maintain a separate nemo version of this. Integrators can patch nautilus integration to achieve nemo integration.
