### ISSUE TITLE
add subdivx.com as repo for latine people

### ISSUE THREAD

**Issue by skypce** [Diaoul/subliminal#502]
Will be great if in your app features add subdivx.com as subtitle source too. Best regards.

**Comment by Diaoul** [comment]
Duplicate of #279

**Comment by nMaib0** [comment]
Hello, is there a possibility this could get made? Honestly, without a subdivx plugin subliminal is basically useless for latin people. SubDivx has hundreds of people actively uploading subtitles that exist only on that site.
