### ISSUE TITLE
Contributing with little fixes for ubuntu 14.04

### ISSUE THREAD

**Issue by skypce** [Diaoul/subliminal#503]
Hello i want contribute with littles fixes:
For install python pip:
sudo apt-get install python-pip;
For install latest develop version:
sudo pip install https://github.com/Diaoul/subliminal/archive/develop.zip
For install stable version: 
sudo pip install subliminal
For work in Ubuntu 14.04:
edit /subliminal-develop/examples/ui/  both .glade elements: and change:
requires lib="gtk+" version="3.12"
to 
requires lib="gtk+" version="3.10"

If you want that work instead of nautilus with nemo : 
edit
/subliminal-develop/examples/nautilus.py
and replace all instances of "Nautilus" with "Nemo".
save the script as you want and place it in:
.local/share/nemo-python/extensions
place "ui" and "i18n" folders in:
/home/shezar/.local/share/nemo-python/extensions/subliminal
dont forget before this install python-nemo (or python-nautilus if you have nautilus)
install python nemo: sudo apt-get install python-nemo;

**Comment by Diaoul** [comment]
This shouldn't be necessary anymore. If it is, please report to https://github.com/Diaoul/nautilus-subliminal
