### ISSUE TITLE
TheSubDB pt is actually pt-BR

### ISSUE THREAD

**Issue by ratoaq2** [Diaoul/subliminal#507]
TheSubDB website API supports only alpha2 codes for languages and the code *pt* represents the language *pt-BR*

When trying to use Subliminal API (inside flexget application) we're able to specify languages and providers to use. Consider the following scenario:

Given that both websites, Opensubtitles and TheSubDB, support Portuguese (Brazilian)
And I'm searching for subtitles in Portuguese (Brazilian)
```
languages: pt-BR
providers: thesubdb, opensubtitles
```
Then I expect to be get subtitles in brazilian portuguese from any of these sites.

**Actual Result:**
Only opensubtitles works.

I was expecting that TheSubDB provider would consider pt-BR as a valid language and execute the query using only pt (as defined by the website API) and return the subtitles.

**Comment by Diaoul** [comment]
TheSubDb only supports pt as language AFAIK, not pt-BR.

**Comment by ratoaq2** [comment]
TheSubDB supports the following languages (http://thesubdb.com/):

> We have 368272 subtitles in our database, distributed between the languages:
> 
> English: 110922
> Español: 20882
> Français: 5270
> Italiano: 421
> Nederlands: 3418
> Polski: 394
> Português (Brazil): 224995
> Român: 927
> Svenska: 311
> Türkçe: 732

And here you can check [here](http://subdb.tumblr.com/post/8835404358/n-gram-based-text-categorization) the supported languages :

> To make this possible, we now support only a small subset of languages: Dutch, English, French, Italian, Polski, Portuguese (Brazil), Romanian, Spanish, Swedish e Turkish.

The site uses the 2 letter code representation (ISO 639-1) that, as you know, is a more generic way to represent the world's major languages. TheSubDB does not support any other Portuguese variation other than Brazilian portuguese.

Subliminal does support IETF language representation (https://subliminal.readthedocs.org/en/latest/user/cli.html#cli)

```
Options:
  -l, --language LANGUAGE         Language as IETF code, e.g. en, pt-BR (can be used multiple times).  [required]
```

Given that, my use case/scenario is described as follow:
> I want to download subtitles in Portuguese (Brazil) using 2 or more providers.

So, I know that Portuguese (Brazil) is represented in IETF as pt-BR.
When I try the following:
```
subliminal download -l pt-BR -p thesubdb -p opensubtitles <some media file>
```
**Result:** It will never download subtitles using thesubdb (even though thesubdb has the correct brazilian portuguese subtitles)


And when I try the following:
```
subliminal download -l pt -p thesubdb -p opensubtitles <some media file>
```
**Result:** It could download the correct brazilian portuguese from thesubdb, but it could also download the portuguese (Portugal) from opensubtitles.


I fully understand that there isn't a single correct answer to that and it's up to Subliminal's design principles. As I described before, my expectation was: *To give subliminal the IETF language code, and it would translate it to the proper language code used by the provider.*

If you think that Subliminal shouldn't handle this kind of situation, then I could workaround it in my code by just calling it twice: one for each provider, using the own provider's language representation in each call.

BTW,
Thanks for this great software.

**Comment by Diaoul** [comment]
As per the [API documentation](http://thesubdb.com/api/), this is the response for http://api.thesubdb.com/?action=languages:

```
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Type: text/html
Date: Wed, 16 Sep 2015 08:35:36 GMT
Server: nginx/1.6.0
Transfer-Encoding: chunked

en,es,fr,it,nl,pl,pt,ro,sv,tr
```

Do you have an example hash where thesubdb returns pt-BR subtitles?

**Comment by ratoaq2** [comment]
If you're talking only about codes, TheSubDB uses only 2 letter codes. And the code *pt* represents portuguese brazilian. For any valid hash, you will get a brazilian portuguese subtitle:

```
GET /?action=download&hash=9803efc44fc70ddd976f902d604db244&language=pt HTTP/1.1
Connection: keep-alive
Host: api.thesubdb.com
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent:  SubDB/1.0 (ratoaq2)

HTTP/1.1 200 OK
Server: nginx/1.6.0
Date: Wed, 16 Sep 2015 18:39:19 GMT
Content-Type: text/plain
Content-Length: 32344
Last-Modified: Mon, 14 Sep 2015 20:08:22 GMT
Connection: keep-alive
Content-Disposition: attachment; filename=bdc0f0d21b869094283331496d557e87.srt
ETag: "55f72936-7e58"
Accept-Ranges: bytes
```

```
GET /?action=download&hash=9f726256c6de2011b69dd66f694b3669&language=pt HTTP/1.1
Connection: keep-alive
Host: api.thesubdb.com
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent:  SubDB/1.0 (ratoaq2)

HTTP/1.1 200 OK
Server: nginx/1.6.0
Date: Wed, 16 Sep 2015 18:44:35 GMT
Content-Type: text/plain
Content-Length: 33187
Last-Modified: Mon, 02 Feb 2015 00:40:20 GMT
Connection: keep-alive
Content-Disposition: attachment; filename=be75725d7937112648ced8e3a56620dd.srt
ETag: "54cec774-81a3"
Accept-Ranges: bytes
```
Brazilian portuguese and portuguese (Portugal) subtitles are completely different among themselves. Every single phrase is constructed in a different way. For us, it looks too formal and it uses words that are uncommon/unknown.

I know that opensubtitles uses ISO 639 + pb/pob for brazilian portuguese. 
In TheSubDB, pt means Portuguese (Brazilian). TheSubDB owners are brazilians and Brazil is the biggest community.

When I use subliminal with opensubtitles, I do not use the code *pb* or *pob* and I was expecting the same mapping to happen with thesubdb.

Using subliminal with `-l pob` in opensubtitles will give me error
Using subliminal with `-l pb` in opensubtitles will give me error
Using subliminal with `l pt-BR` in thesubdb will give me 404
Using subliminal with `-l pt-BR` in opensubtitles will give me pt-BR subtitles

And the inconsistence is here:
Using subliminal with `-l pt` in opensubtitles will give me pt-PT subtitles
Using subliminal with `l pt` in thesubdb will give me pt-BR subtitles


As I said before, you have your own design principles and don't know if you agree that subliminal should handle this mapping corner case (user's input IETF language code to providers language code)

Regards

**Comment by Diaoul** [comment]
I just didn't know they were using pt as code for pt-BR. That's rather misleading. I will fix this in next release, thanks.
