### ISSUE TITLE
Language converters removed

### ISSUE THREAD

**Issue by pannal** [Diaoul/subliminal#510]
I'm currently merging subliminal 1.0.1 into the plex agent which has been around for a while, and download_best_subtitles is erroring madly with those providers.

Please enlighten me, ```babelfish.language_converters.register('addic7ed = subliminal.converters.addic7ed:Addic7edConverter')``` never happens in your codebase, or am I missing something?

Thanks!

**Comment by Diaoul** [comment]
Providers are registered at install time, not runtime: https://github.com/Diaoul/subliminal/blob/master/setup.py#L88-L91

**Comment by pannal** [comment]
OK, then my monkeypatching is the only way, as the Plex-Plug-In sandbox doesn't seem to allow me to load eggs from Plug-Ins.

Thank you!
