### ISSUE TITLE
Windows CLI Questions

### ISSUE THREAD

**Issue by Nvious1** [Diaoul/subliminal#512]
I just recently upgrade from 0.80 to 1.0.1 and realized there were some different changes on the cli I had to sort out for my scheduled task to work properly.  One thing that I noticed and not sure if I am just missing the obvious here but it seems like the --log-file parameter has been dropped.  Can anyone confirm this or maybe it is just undocumented.  I liked sending each run out to a log for issue checking one a particular video (within the age param) didn't get a sub.

Here was my syntax on 0.8 (changing to a working directory first)
subliminal.exe -l=en -m=60 -p=addic7ed --addic7ed-user=USER --addic7ed-password=PASS -a=48h --log-file=d:\subliminal.log ./

Now in 1.0.1 it looks more like this but no log option it seems
subliminal.exe --addic7ed='user pass' download -l en -m 60 -p addic7ed -a 48h ./

Any feedback anyone can provide on the log option?

**Comment by Diaoul** [comment]
`--log-file` has been removed in favor of stdout/stderr redirections. See #478
