### ISSUE TITLE
Swedish character Å and å is incorrectly parsed into srt files

### ISSUE THREAD

**Issue by Guson79** [Diaoul/subliminal#515]
A bit unsure if I get this right.
I am using subliminal for swedish subs, and I can see that the Swedish characters do not fully perform in the output .srt files.
We have ÅÄÖ åäö , and Å and å gets replaced like below:
Hur mĺnga minuter tar det
att fĺ in din lilla häck i bilen?

Shoud say:
Hur många minuter tar det
att få in din lilla häck i bilen?

Is there something I can do sort this out or is it a bug that you need to fix?

best Peter

**Comment by Diaoul** [comment]
Sounds like an encoding issue. Do you use the `-e` flag? Please also include debug logs.

**Comment by Diaoul** [comment]
Closing in favor of #528
