### ISSUE TITLE
How to Ignore Trailer Video Files

### ISSUE THREAD

**Issue by imadunatic** [Diaoul/subliminal#518]
Hello, 

Is there any way to ignore trailer files? Subliminal found all my trailer files and downloaded subs for it. Not a big deal, but I would like to prevent it in the future if possible. 

Thanks for a great program.

**Comment by Diaoul** [comment]
Using the CLI right? There is no way to do that right now, you can use a bash script to filter small files and then call subliminal on those files.

**Comment by imadunatic** [comment]
Affirmative on the CLI. Very new to this so I'll probably just let it download subs for trailers for now (I can write basic scipts, but using a script to build a list, then using another script to trigger subliminal is above my paygrade) I don't add that many movies to my collection it's just the initial run that seemed kind of daunting. 

Thanks again.

**Comment by imadunatic** [comment]
As an aside, where might I find the log files on a Windows 7 install? Sorry if I missed it in the documentation. I'm trying to set up a scheduled task and I want to be able to check in on Subliminal occasionally and make sure I don't have something off.

**Comment by Diaoul** [comment]
Redirect stdout / stderr to a log file manualy if you want logs.

**Comment by imadunatic** [comment]
Thanks @Diaoul

**Comment by Diaoul** [comment]
I'm not sure adding the filter on the CLI is a good idea, this is kinda out of scope.

**Comment by Diaoul** [comment]
I'm closing since I consider this out of scope. Subliminal's job is to download subtitles, features focus on downloading subtitles for videos without subtitles.

**Comment by imadunatic** [comment]
Thanks Diaoul. I deleted all my local trailers and Subliminal has been working great.
