### ISSUE TITLE
Danish characters comes up wrong

### ISSUE THREAD

**Issue by Dohnerd** [Diaoul/subliminal#519]
Im guessing its because the subs are not dl'ed as UTF-8.

But how can i change that ?

Im getting wrong characters for danish æ, ø and å.

Instead of "å" im getting "ĺ"
Instead of "ø" im getting "ř"
Instead of "æ" im getting "ć"
In some instances their coming up as blanks (especially from podnapisi)...

When i do a manual DL with encoding UTF-8 they come up fine with other encoding either as signs or blanks as described.

**Comment by Diaoul** [comment]
Please see https://github.com/Diaoul/subliminal/blob/develop/CONTRIBUTING.md

**Comment by Dohnerd** [comment]
I have no idea how to do that.... command gives:
-sh: subliminal: command not found

**Comment by Diaoul** [comment]
Well, how is this related to subliminal then?

**Comment by Dohnerd** [comment]
'cause SR uses subliminal...

Subliminal is not a command form on a QNAP NAS, therefore it can't execute the given command :)

I'll be happy to give you a debug log if you explain how to do it on a QNAP nas :)

**Comment by Diaoul** [comment]
Subliminal downloads subtitles as they are on the website, if anything's wrong, either report to the website or SR.

Subliminal offers an encoding guessing feature but that should be used carefully.
