### ISSUE TITLE
issues with the unicode_literals __future__ import

### ISSUE THREAD

**Issue by snippetManiac** [Diaoul/subliminal#524]
On Mac OS X El Capitan, I get the following message:

/Library/Python/2.7/site-packages/subliminal/cli.py:115: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/

While it's just a warning, it causes the Automator workflow to abort.

**Comment by Diaoul** [comment]
See #495
