### ISSUE TITLE
[FR] Add export option to specify subtitle directory/location

### ISSUE THREAD

**Issue by HazCod** [Diaoul/subliminal#525]
My media is available on a read-only mount and I have to upload things manually.
Using an export command could help me download subs afterwards.

Thanks!

**Comment by Diaoul** [comment]
Like the `-d` argument?

**Comment by HazCod** [comment]
Ahh, I'm running 0.7.4 on Ubuntu 15.04 and I did not see that feature.
Installing from source. Thanks!

**Comment by Diaoul** [comment]
The Debian/Ubuntu package needs an update. You can raise the issue to the package maintainer.
