### ISSUE TITLE
Avoid Hearing Imperaid

### ISSUE THREAD

**Issue by greatvc** [Diaoul/subliminal#530]
Bare with me as i'm new to all this and subliminal. It seams that the downloaded subtitles -not always but mostly- it downloads the HI version even though the --hi option is not selected.

How can i avoid completely those ?

thank you

**Comment by Diaoul** [comment]
If your questions is about the CLI then there is no way to do that currently. At the library level however you can change the scores to your liking.

**Comment by greatvc** [comment]
Yes its for the CLI. Thanks for the feedback
