### ISSUE TITLE
Multiple warnings due unicode_literals __future__ import

### ISSUE THREAD

**Issue by ericoporto** [Diaoul/subliminal#531]
I'm getting some warnings everytime I use subliminal from the command-line. I'm using Raspbian from NOOBS on a Raspberry Pi 2.

I installed using pip from the command line:

    pi@raspberrypi ~/ $ sudo pip install subliminal

My system:

    pi@raspberrypi ~/ $ cat /etc/debian_version
    7.8
    pi@raspberrypi ~/ $ uname --all
    Linux raspberrypi 4.1.6-v7+ #810 SMP PREEMPT Tue Aug 18 15:32:12 BST 2015 armv7l GNU/Linux

The warnings I'm getting:

    pi@raspberrypi ~/ $ subliminal download --help
    /usr/local/lib/python2.7/dist-packages/subliminal/cli.py:115: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
      @click.pass_context
    /usr/local/lib/python2.7/dist-packages/subliminal/cli.py:145: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
      @click.pass_context
    /usr/local/lib/python2.7/dist-packages/subliminal/cli.py:172: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
      @click.pass_obj
    Usage: subliminal download [OPTIONS] PATH...

      Download best subtitles.

      PATH can be an directory containing videos, a video file path or a video file name. It can be
      used multiple times.

      If an existing subtitle is detected (external or embedded) in the correct language, the
      download is skipped for the associated video.

    Options:
      -l, --language LANGUAGE        Language as IETF code, e.g. en, pt-BR (can be used multiple
                                     times).  [required]
      -p, --provider []              Provider to use (can be used multiple times).
      -a, --age AGE                  Filter videos newer than AGE, e.g. 12h, 1w2d.
      -d, --directory DIR            Directory where to save subtitles, default is next to the video
                                     file.
      -e, --encoding ENC             Subtitle file encoding, default is to preserve original encoding.
      -s, --single                   Save subtitle without language code in the file name, i.e. use
                                     .srt extension.
      -f, --force                    Force download even if a subtitle already exist.
      -hi, --hearing-impaired        Prefer hearing impaired subtitles.
      -m, --min-score INTEGER RANGE  Minimum score for a subtitle to be downloaded (0 to 100).
      -v, --verbose                  Increase verbosity.
      --help                         Show this message and exit.

**Comment by alotofshit** [comment]
https://github.com/Diaoul/subliminal/issues/495
