### ISSUE TITLE
Distribution not found

### ISSUE THREAD

**Issue by iCHAIT** [Diaoul/subliminal#534]
When I try to use subliminal it throws me an error - 

![screen shot 2015-11-06 at 10 36 35 pm](https://cloud.githubusercontent.com/assets/8472314/11003206/18051cd8-84d7-11e5-87a8-13289cfc3e3d.png)

What could be possibly wrong here?

Here is my pbr version - 

![screen shot 2015-11-06 at 10 40 27 pm](https://cloud.githubusercontent.com/assets/8472314/11003271/701f4330-84d7-11e5-9dbe-04d0ba3ca646.png)

**Comment by Diaoul** [comment]
How did you install it?

**Comment by iCHAIT** [comment]
I installed it few months back using pip.

**Comment by Diaoul** [comment]
Have you tried reinstalling? It seems that something else you installed upgraded pbr to a more recent version.

**Comment by iCHAIT** [comment]
Yeah, I tried reinstalling, but it gives me some Error that I am unable to figure out :(

Here is the Traceback - 

http://dpaste.com/1AJQ6DJ

**Comment by Diaoul** [comment]
I don't know this error. I suggest you create a virtualenv and install subliminal in it. There is plenty documentation on how to do that.

**Comment by iCHAIT** [comment]
Okay.

**Comment by dufferzafar** [comment]
@iCHAIT Have a look at [pipsi](https://github.com/mitsuhiko/pipsi) and try installing subliminal using that. That's how I have it installed.

**Comment by iCHAIT** [comment]
Sure @dufferzafar .
Thanks
