### ISSUE TITLE
Year-match isn't treated equally among providers

### ISSUE THREAD

**Issue by pannal** [Diaoul/subliminal#537]
Hey,

When comparing the match determination of OpenSubtitles to other providers, there seems to be a huge difference: OpenSubtitles provider only adds the year match to the matches list [if the video had a year (bool(video.year)) and both the video and the subtitle have the same year set](https://github.com/Diaoul/subliminal/blob/develop/subliminal/providers/opensubtitles.py#L76)  (and it's a movie).

In comparison to that, [let's say Addic7ed](https://github.com/Diaoul/subliminal/blob/develop/subliminal/providers/addic7ed.py#L55): It blindly compares the value of `video.year` with the value of `subtitle.year` - which adds `year` to the matches list, if both values are None.

~~If I'm not wrong, this results in a pretty distinct behaviour: All other providers besides OpenSubtitles match 44 points too high - or OpenSubtitles generally matches 44 points too low, if the year isn't set on the video.~~
Edit: not really, because Addic7ed only matches for TV series. Still, when I look at podnapisi, the year attribute isn't checked at all and doesn't get added to the matches list even for movies.

I'd expect consistent behaviour, and I think the OpenSubtitles provider is wrong, because a None-year should match if both the video and the subtitles have it.

**Comment by Diaoul** [comment]
I agree for consistent behavior.
* `None` should be a match on tvshows that's clear.
* Should it be a match for movies? Movies usually have an associated year. You might end up matching None (Video object year) with None (provider year) due to the provider having poor information on the movie although I don't have a concrete case of that.

**Comment by eltismerino** [comment]
Well, if movies usually have an associated year, and in this specific case, neither do the video (no year in filename) nor the provider, year should be a match.

In my experience it's not the provider but the filename that lacks important information, such as the year.

**Comment by pannal** [comment]
Well, if movies usually have an associated year, and in this specific case, neither do the video (no year in filename) nor the provider, year should be a match.

In my experience it's not the provider but the filename that lacks important information, such as the year.

I don't know whether it would be wise to trying to guess the proper year in case of movies with the lack of year info - you might end up with more bad matches than no matches, which tends to piss the users of way more.

**Comment by Diaoul** [comment]
Question is, do all provider (current and future) have the year information about a movie? If not, this will introduce some bias as a provider that doesn't support the year information will always return `None` and it'll get wrongfully picked by subliminal.

Current behavior for movies is to say, hey we don't have the year in the video (filename) so let's treat all subtitles equally and pick the best using other matches. The reason is year has quite a big impact on movie scoring so we don't want to mess up with it.

For series it's different, hey we don't have the year in the video (filename) so it must be the original series (no remake) and the provider shouldn't give the year information either so `None` for year should be a match.

Is there a flaw in that logic?

**Comment by pannal** [comment]
The logic is flawless, but the real-world-example is not. If a provider doesn't provide "year", and we know that, we should normalize the score and add the year score nevertheless.

**Comment by pannal** [comment]
My last comment isn't really accurate. That behaviour would possibly generate massive mismatches. I think good provider-picking is needed here - not compromises on matching.

**Comment by Diaoul** [comment]
Of course if a provider doesn't **ever** send the proper "year" it shouldn't be added for movies.

My concern is more about the way providers individually send the year information. Some might always send it, some not always. As a result we will be priviledging one provider over the other. Maybe a provider will send the correct year for our movie (but we don't know, it's not in the filename) but it will score less than a provider that didn't send the year at all.

Treating them equally forces subliminal to use other means to do the matching and not rely on the year anymore.

Also, if you don't know the year of the movie, you can't seriously expect subtitles to be correct unless you have a hash match.

**Comment by pannal** [comment]
> Also, if you don't know the year of the movie, you can't seriously expect subtitles to be correct unless > you have a hash match.
Or a filename match :)

I agree. The field you're attacking with subtitles is one of the harder ones. As you have to do the Van Damme-split between what the user expects, what you think the user wants, and what the provider gives you.

That's the beauty of Sub-Zero: I can specificly rely on what the user wants: Correct matches are better than more matches, at any time. But I don't have to be as generic as subliminal wants to be, and I can priviledge providers *and I do*.

Sorry for that :)

**Comment by Diaoul** [comment]
> Correct matches are better than more matches

I don't get that part, it's always the case, depending on the defined scores.

I don't mind priviledging providers, but that should be the user deciding or the calling application (CLI, Sub-Zero, etc), not subliminal.

**Comment by pannal** [comment]
That's my fault in explaining it wrongly. You got it right.

**Comment by Diaoul** [comment]
I'm not sure what needs to be done here, implementing `year=None` match for movies may lead to a lot of inconsistent results. Anyway, with the filename lacking the information one cannot expects good results from a poor filename.

Additionally, when we have a *rich* filename (lets say at least 2 elements in the guess object of the filename) we can add trigger an additional filename match. What do you think?

**Comment by Diaoul** [comment]
Thoughts?

**Comment by Diaoul** [comment]
It now is even though the two commits didn't change anything. Both the providers return the actual year of the series even though it's the original one. No match on `None` possible except by `guess_matches` on the release names.
"Fixed" with 89a2f7aaef4536d59d532604460fbcf7d70ad4af and f245383c2897b4b8a3236cfd7bd733963602dc75

**Comment by Diaoul** [comment]
See #572 for the `release` match.

**Comment by Diaoul** [comment]
I'm not exactly satisfied with the solution. `None` year won't match for OpenSubtitles as they give the original year of the series. It should match.
One way around this is to query imdb during scan_video to get the `series_year` and match that as well as `year`. See #338
