### ISSUE TITLE
Subliminal -- redirecting output to file

### ISSUE THREAD

**Issue by mtzro2003** [Diaoul/subliminal#541]
Subliminal is working fine (many, many thanks Diaoul), but I'm seeing some strange phenomenon...
When I try to re-direct the output to a log file is gives an error:

> #> subliminal download -l en /share/Download/TV\ Series/Homeland/Homeland.S05E10.720p.HDTV.x264-0SEC.mkv
Collecting videos  [####################################]  100%  /share/DownloadCollecting videos  [####################################]  100%                 
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Homeland.S0Downloading subtitles  [####################################]  100%             
Downloaded 1 subtitle

> #> subliminal download -l en /share/Download/TV\ Series/Homeland/Homeland.S05E10.720p.HDTV.x264-0SEC.mkv >> subliminal.log
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Python/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/site-packages/subliminal/cli.py", line 190, in download
    with click.progressbar(path, label='Collecting videos', item_show_func=lambda p: p or '') as bar:
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/site-packages/click/_termui_impl.py", line 94, in __enter__
    self.render_progress()
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/site-packages/click/_termui_impl.py", line 222, in render_progress
    buf.append(' ' * (clear_width - line_len))
UnboundLocalError: local variable 'line_len' referenced before assignment

I'm using subliminal version 1.0.1 installed through pip.
What could be the problem?
I used subliminal 0.7, 0.8 and I redirected the output to a log file without any issues...

Thanks

**Comment by Diaoul** [comment]
Seems like there is an issue with click. Can you provide a `pip freeze`?

**Comment by mtzro2003** [comment]
Sure thing:

	> pip freeze
	aniso8601==1.1.0
	APScheduler==3.0.4
	babelfish==0.5.5
	beautifulsoup4==4.3.2
	boto==2.38.0
	chardet==2.3.0
	CherryPy==3.8.0
	click==6.1
	cssmin==0.2.0
	Cython==0.22
	dogpile.cache==0.5.7
	dogpile.core==0.4.1
	enum34==1.0.4
	enzyme==0.4.1
	feedparser==5.2.1
	Flask==0.10.1
	Flask-Assets==0.11
	Flask-Compress==1.3.0
	Flask-Login==0.3.2
	Flask-RESTful==0.3.4
	flask-restplus==0.7.2
	FlexGet==1.2.395
	functools32==3.2.3.post2
	futures==3.0.3
	guessit==0.10.3
	html5lib==0.9999999
	itsdangerous==0.24
	Jinja2==2.8
	jsonschema==2.5.1
	lxml==3.5.dev0
	MarkupSafe==0.23
	ordereddict==1.1
	path.py==8.1.2
	pathlib==1.0.1
	pbr==1.8.1
	plumbum==1.6.0
	progressbar==2.3
	pynzb==0.1.0
	pyparsing==2.0.6
	PyRSS2Gen==1.1
	pyScss==1.3.4
	pysrt==1.0.1
	python-dateutil==2.4.2
	pytvmaze==1.3.4
	pytz==2015.7
	PyYAML==3.11
	requests==2.8.1
	rpyc==3.3.0
	six==1.10.0
	SQLAlchemy==1.0.9
	stevedore==1.9.0
	subliminal==1.0.1
	tmdb3==0.7.2
	transmissionrpc==0.11
	tvdb-api==1.10
	tvnamer==2.3
	tzlocal==1.2
	webassets==0.11.1
	Werkzeug==0.11.2

Maybe something is interfering?
Should I use virtualenv?

**Comment by Diaoul** [comment]
Try another click version maybe? The error seems to come from there.

**Comment by mtzro2003** [comment]
solved by installing click==4.0

thank you very much, Diaoul

**Comment by mtzro2003** [comment]
Well... still having problems and I can't figure out why...
I solved the problem with the output to file, no worries there...
But running subliminal from cron with output to file it's not working. Other jobs run perfectly, but not subliminal.
I have a subliminal.sh script  and If I run from command line I get the following output in the log (as well as on console if I don't redirect the output):

	Searching for subtitles for video files in /share/Download/TV Series/
	Collecting videos  [####################################]  100%
	1 video collected / 97 videos ignored / 0 error
	Downloading subtitles  [####################################]  100%  The.Walking.Dead.S06E00.Next.Chapter.Downloading subtitles  [####################################]  100%                                       
	0 subtitle downloaded for The.Walking.Dead.S06E00.Next.Chapter.Prologue.720p.HDTV.x264-BATV.mkv

EXACTLY the same command ran through cron gives the following output:

	Searching for subtitles for video files in /share/Download/TV Series/
	Collecting videos
	Collecting videos
	0 video collected / 0 video ignored / 0 error
	*********************************************************************

It seems that it cannot find any movies in that path...
I invoke subliminal with the following command:

    subliminal --cache-dir /share/scripts/subliminal/ --addic7ed ******** ******** download --verbose --single --language ro --language en --provider addic7ed --provider opensubtitles --hearing-impaired "/share/Download/TV Series/" >> /share/scripts/subliminal/subliminal.log

**Comment by Diaoul** [comment]
Cron doesn't define the needed environment variables python AFAIK. Try setting your locale.

**Comment by mtzro2003** [comment]
I crontab file I have the following:

    SHELL=/bin/sh
    LANG=en_US.UTF-8
    LANGUAGE=en
    LC_CTYPE=en_US.UTF-8

Still not working.
In my sh script I hvae full patch so there is not a problem of path...
WTF?!

**Comment by Diaoul** [comment]
Add debug logging.

**Comment by mtzro2003** [comment]
OK, I have to apologize... 
How the hell didn't I think of the --debug switch???
Running with --debug was pretty clear and a Google search reveal the solution...
I had:

    ERROR:subliminal.video:Skipping badly encoded directory

As stated in issue #422 it was enough to add the following line in my script:

    export PYTHONIOENCODING=utf8

This really has to be on the wiki/faq/examples/etc.
Diaoul, once again thank you and apologies... I should've tried harder before posting...

**Comment by Diaoul** [comment]
The docs are lacking. I see you're using subliminal as a cronjob, I'd appreciate if you can help with #483 about cron jobs with a PR. [Here](http://subliminal.readthedocs.org/en/latest/user/cli.html) would be the right place I think.
