### ISSUE TITLE
Cli doesn't download from opensubtitles when file is exact match

### ISSUE THREAD

**Issue by fernandog** [Diaoul/subliminal#542]
@Diaoul can you help me understand why subliminal-cli doesn't downloaded this sub when there's a exact match in opensubtitles?

the link to opensubtitles is in the end of the log
https://gist.github.com/fernandog/f479cc96163b7d7536d1

I runned this:
subliminal "{filename-redacted}.mkv" -m 132 -p opensubtitles -l 'pt-br' --debug

**Comment by fernandog** [comment]
At SickRage log it's shows the score found was 138:

`14:44:27 DEBUG::Thread-15 :: [opensubtitles] Subtitle score for 1954625859 is: 138 (min=132)`
https://gist.github.com/fernandog/b6fe93810d6b2e6b20ee

This is the code that generate that log:

```
score = subliminal.subtitle.compute_score(matches, video)
 logger.log(u"[%s] Subtitle score for %s is: %s (min=%s)"
```

**Comment by fernandog** [comment]
@Diaoul please??

**Comment by fernandog** [comment]
Invalid subtitle?

```
17:40:43 INFO::Downloading subtitle <OpenSubtitlesSubtitle '1954625859' [pt-BR]> with score 138
17:40:43 INFO::Downloading subtitle <OpenSubtitlesSubtitle '1954625859' [pt-BR]> with score 138
17:40:43 INFO::Downloading subtitle <OpenSubtitlesSubtitle '1954625859' [pt-BR]>
17:40:43 INFO::Downloading subtitle <OpenSubtitlesSubtitle '1954625859' [pt-BR]>
17:40:43 INFO::Downloading subtitle <OpenSubtitlesSubtitle '1954625859' [pt-BR]>
17:40:43 INFO::Downloading subtitle <OpenSubtitlesSubtitle '1954625859' [pt-BR]>
17:40:43 ERROR::Invalid subtitle
17:40:43 ERROR::Invalid subtitle
17:40:43 INFO::Score 115 is below min_score (132)
17:40:43 INFO::Score 115 is below min_score (132)
17:40:43 DEBUG::Thread-25 :: 83462: No subtitles downloaded for Castle (2009) S07E14

```

**Comment by fernandog** [comment]
@Diaoul seems the sub is a .rar file not .srt

http://www.opensubtitles.org/pt/subtitles/6046402/castle-resurrection-pb

**Comment by Diaoul** [comment]
Is that allowed by OpenSubtitles? More likely a bug in OS than subliminal.
