### ISSUE TITLE
1.1 no debug option

### ISSUE THREAD

**Issue by CyberMew** [Diaoul/subliminal#546]
subliminal --debug
Usage: subliminal [OPTIONS] COMMAND [ARGS]...

Error: Missing command.

I was trying to see where the cache folder is. My last version is 0.8.0 so I was wondering where are the config stored in. Same with "--addic7ed user pass" too. I installed via the wheel file using pip 7.1.2 and my python installed is 2.7.9. Am I doing something wrong?

**Comment by Diaoul** [comment]
`subliminal --help` will show you where the cache folder is.
Configuration is never stored in cache, only requests to providers to speed things up.
See [the docs](http://subliminal.readthedocs.org/en/latest/user/cli.html)

**Comment by CyberMew** [comment]
![Photo of my problem](http://i.imgur.com/CiyeBlK.png)

Any idea where I went wrong?

**Comment by Diaoul** [comment]
The new CLI has 2 subcommands: `subliminal download` and `subliminal cache`. `subliminal download --help` will print you the help of the download subcommand which is pretty much the same as the old CLI. It should be fairly easy.

There is no configuration file, nothing is persisted, the command you run contains all the information subliminals needs to run (addic7ed credentials).

**Comment by CyberMew** [comment]
So since you mentioned that it has now 2 subcommands (ignoring cache here), I attempted to try something like this:
subliminal --addic7ed myuser mypass download /mnt/user/TV/ -a 5d -l en

and I got this:
0 video collected / 0 video ignored / 1 error

granted I don't have any downloaded file in the last 5 days (iirc), is the error normal? I can't view the error since there doesn't seem to be a log output option now.

**Comment by Diaoul** [comment]
Add `-v` for à more verbose output. Double it for even more

**Comment by CyberMew** [comment]
Weird, mine just says in red: /mnt/user/TV Shows/US/Series errored

With so many stuff not working yet I think it's better to stick with 0,8,0 first for now.. thanks for the help and happy 2016!

**Comment by Diaoul** [comment]
Add `--debug` like this `subliminal --debug [...] download [...]` and send the result here.

**Comment by CyberMew** [comment]
There's lots of stuff so I'm going through the later ones

DEBUG:subliminal.video:Found subtitles {}
DEBUG:subliminal.video:Found resolution 720p with enzyme
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:MKV has no subtitle track
DEBUG:subliminal.video:Walking directory /mnt/user/TV Shows/US/Series/Alphas/Alphas - 1x10 - The Unusual Suspects
INFO:subliminal.video:Scanning video 'Alphas.S01E10.720p.HDTV.x264-IMMERSE.mkv' in '/mnt/user/TV Shows/US/Series/Alphas/Alphas - 1x10 - The Unusual Suspects'
DEBUG:subliminal.video:Size is 1085893911
DEBUG:subliminal.video:Computed hashes {'opensubtitles': 'a10ffb29d9aeb27e', 'thesubdb': '6125bf8ceab17c037edaee7a8de026ca', 'napiprojekt': '2a4fcc85198bacff2176f94ee63f8f53'}
DEBUG:subliminal.video:Found subtitles {'Alphas.S01E10.720p.HDTV.x264-IMMERSE.srt': <Language [und]>}
DEBUG:subliminal.video:Found resolution 720p with enzyme
DEBUG:subliminal.video:Found video_codec h264 with enzyme
DEBUG:subliminal.video:Found audio_codec AC3 with enzyme
DEBUG:subliminal.video:MKV has no subtitle track
DEBUG:subliminal.video:Walking directory /mnt/user/TV Shows/US/Series/Alphas/Alphas - 1x03 - Anger Management
INFO:subliminal.video:Scanning video 'Alphas.S01E03.720p.HDTV.x264-IMMERSE.mkv' in '/mnt/user/TV Shows/US/Series/Alphas/Alphas - 1x03 - Anger Management'
DEBUG:subliminal.video:Size is 1265699292
DEBUG:subliminal.video:Computed hashes {'opensubtitles': '3a336ee06b231f33', 'thesubdb': 'fe03d0ccd1992b7b8a9feec5ad977fc0', 'napiprojekt': '2b781fb9da12dd66efc1da1963dae52f'}
DEBUG:subliminal.video:Found subtitles {'Alphas.S01E03.720p.HDTV.x264-IMMERSE.srt': <Language [und]>}
ERROR:subliminal.cli:Unexpected error while collecting directory path /mnt/user/TV Shows/US/Series/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/subliminal/cli.py", line 311, in download
    subtitles_dir=directory)
  File "/usr/lib64/python2.7/site-packages/subliminal/video.py", line 447, in scan_videos
    subtitles_dir=subtitles_dir)
  File "/usr/lib64/python2.7/site-packages/subliminal/video.py", line 322, in scan_video
    mkv = MKV(f)
  File "/usr/lib64/python2.7/site-packages/enzyme/mkv.py", line 54, in __init__
    self._parse_seekhead(seek_head, segment, stream, specs)
  File "/usr/lib64/python2.7/site-packages/enzyme/mkv.py", line 74, in _parse_seekhead
    self.video_tracks.extend([VideoTrack.fromelement(t) for t in tracks if t['TrackType'].data == VIDEO_TRACK])
TypeError: 'Element' object is not iterable
Collecting videos  [####################################]  100%                 
0 video collected / 0 video ignored / 1 error

**Comment by Diaoul** [comment]
This is because your MKV is broken in some way. This is similar to https://github.com/Diaoul/enzyme/issues/13
The error causes subliminal to stop and shouldn't, I'll fix that part.

**Comment by CyberMew** [comment]
Oh hmm weird how it worked with the old version somehow. In fact, the file is not 5 days old so not sure why it's looking through the file?

Btw is the detection for marvels agents of shield fixed yet? I always had a problem on 0.8.0 not being able to detect and download subs.

**Comment by Diaoul** [comment]
Age check is done *after* scanning the video, along with some other checks (subtitles exist).
I don't know about marvels agents, it depends on your specific use case. Try it out and let me know.

**Comment by CyberMew** [comment]
Weird... Did the way of doing it change since 0.8.0? Wouldn't it be faster in processing if the file attributes are looked up first and early rejected before going through the entire video?

Ok! I'll try out marvels agents when it comes out again. Btw I appreciate your help so far! Thanks!

**Comment by Diaoul** [comment]
I've just released 1.1.1 which resolves your issue. You can update subliminal and scan your whole library again.
Yes, it would be faster but it would couple the `scan_video` function with filtering functions (`age`). I like the separation of concerns. If performance is really a problem I will reconsider but parsing metadata is really fast and collecting videos isn't the bottleneck compared to listing/downloading subtitles.

**Comment by CyberMew** [comment]
Just installed 1.1.1 via pip install. One thing I've noticed aside from the difference in cmd line args is that it takes a lot more time to get back the results. With 0.8.0dev it only took a couple of mins, max 6-7 mins to tell me how many subtitles has been successfully download. But with 1.1.1, it has been taking me ~12 mins. I think this is a big problem, since my media folder contains ~3000 video files (and probably another 1k+ in misc files) and it seems to be doing extra processing on 2900 files except the only few files that matter, unless it's preprocessing to cache the information so that it is faster on the next run, but that does not seems to be the case. This waiting time will only grow in the future as the file count grow. The age argument is, imho, suppose to do a trivial reject so that it doesn't have to go through the contents of each and every file and I think this was what has been done in 0.8.0dev which was great (Lots of Skipping video due to older datetime).

Assuming we ignore the waiting time, This was my first result:
Collecting videos  [####################################]  100%  /mnt/user/TV Sh       Collecting videos  [####################################]  100%                        
4 videos collected / 2928 videos ignored / 0 error
Downloading subtitles  [#########---------------------------]   25%  Supergirl.S       Downloading subtitles  [##################------------------]   50%  0d 00:00:13       Downloading subtitles  [###########################---------]   75%  0d 00:00:07       Downloading subtitles  [####################################]  100%  Brooklyn.Ni       Downloading subtitles  [####################################]  100%                    
0 subtitle downloaded for Supergirl.S01E09.720p.HDTV.X264-DIMENSION.mkv
0 subtitle downloaded for Brooklyn.Nine-Nine.S03E11.720p.HDTV.x264-KILLERS.mkv
0 subtitle downloaded for Limitless.S01E12.720p.HDTV.X264-DIMENSION.mkv
0 subtitle downloaded for L406-FoV.avi

3 issues here.. 1, that supergirl already has a subtitle (just that it doesn't have a language code in it), 2, L406-FoV.avi is definitely not a 5 day old file, and 3, no subtitles was downloaded. (there's a 4th issue about the 0d 00:00:07 thing but that's a visual thing probably just on my side)

For 1, I did drop the language code -s, but is there a way for it to ignore files with existing subtitles (if the subtitle with the same file name as the video already exists)? Or do I just have to make do with it? 


Assuming it's just some glitch, I reran it again, this time adding back the -s and --debug, just to see if it attempts to redownload for supergirl file.
This is my command line:
subliminal --debug --addic7ed user pass download /mnt/user/TV\ Shows/US/Series/ -p addic7ed -l en -v -hi -a 5d  -s
This is the output:
Collecting videos
2 videos collected / 2930 videos ignored / 0 error
Downloading subtitles
0 subtitle downloaded for Limitless.S01E12.720p.HDTV.X264-DIMENSION.mkv
0 subtitle downloaded for Brooklyn.Nine-Nine.S03E11.720p.HDTV.x264-KILLERS.mkv

Which "solves" my previous problem. So ok, I'm stuck without language code in my subtitle filename, which is acceptable (for now), at least I don't have (2) weird files telling me they don't have subtitles.
Here's the log towards the end:
INFO:subliminal.api:Listing subtitles with provider 'addic7ed' and languages set([<Language [en]>])
INFO:subliminal.api:Initializing provider addic7ed
INFO:subliminal.providers.addic7ed:Logging in
DEBUG:subliminal.providers.addic7ed:Logged in
DEBUG:subliminal.providers.addic7ed:Getting show id
WARNING:subliminal.providers.addic7ed:Series not found in show ids
ERROR:subliminal.providers.addic7ed:No show id found for u'Limitless (US)' ({'country': None, 'year': None})
INFO:subliminal.api:Listing subtitles with provider 'addic7ed' and languages set([<Language [en]>])
DEBUG:subliminal.providers.addic7ed:Getting show id
WARNING:subliminal.providers.addic7ed:Series not found in show ids
ERROR:subliminal.providers.addic7ed:No show id found for u'Brooklyn Nine-Nine (US)' ({'country': None, 'year': None})
DEBUG:subliminal.api:Terminating initialized providers
INFO:subliminal.api:Terminating provider addic7ed
INFO:subliminal.providers.addic7ed:Logging out
DEBUG:subliminal.providers.addic7ed:Logged out

I don't know why they couldn't be found. I'm hoping it could be some version mismatch (if that's the case then pip side need to update the appropriate version minimum requirements and I'm not sure who manages that)
Here's my pip list:
babelfish (0.5.5)
beautifulsoup4 (4.4.1)
chardet (2.3.0)
click (6.2)
dogpile.cache (0.5.7)
dogpile.core (0.4.1)
enzyme (0.4.1)
guessit (1.0.2)
html5lib (0.9999999)
pbr (1.8.1)
pip (7.1.2)
pyOpenSSL (0.15.1)
pysrt (1.0.1)
python-dateutil (2.4.2)
pyxdg (0.25)
requests (2.9.1)
setuptools (18.2)
six (1.10.0)
stevedore (1.10.0)
subliminal (1.1.1)

That aside, I also found from the logs that despite me setting addic7ed as the only provider, it seems to be searching online with other providers to get a hash code or something as well?

**Comment by Diaoul** [comment]
0. So it takes 12 min instead of 6? That's not a big difference. The ability to scan a folder in subliminal is a convenience, subliminal can't do much better than this (I do not consider x2 a big optimization). I suggest you run your own scanning function and pass the resulting filenames to subliminal for example using [find](http://stackoverflow.com/questions/552724/how-do-i-check-in-bash-whether-a-file-was-created-more-than-x-time-ago) in bash. It should drastically reduce the processing time. For you it should be `find /mnt/user/TV\ Shows/US/Series/ -type f -mtime 5 -exec subliminal --addic7ed user pass download -p addic7ed -l en -v -hi -a 5d -s {} \+`. Please share the performance results.
1. Supergirl already has a subtitle (just that it doesn't have a language code in it). You said it yourself, it doesn't have language code in it so it's detected as "unknown" language and thus assumes its language is incorrect and download a new one with correct language.
2. L406-FoV.avi may be older but that's not what the file information says. The code [is pretty simple](https://github.com/Diaoul/subliminal/blob/master/subliminal/video.py#L86-L92), I have no idea why it doesn't work for that particular video. Open a Python console and try it out. (It should also be returned by the `find` command mentioned in 0.)
3. Open another issue with those filenames so I can take a closer look
4. This is a weird glitch, not likely an issue with subliminal itself but click
5. Hashes are computed when scanning the videos despite the associated providers not being used

**Comment by CyberMew** [comment]
1. 6mins is like when the filesystem is really busy with multiple streams going on and hundreds of torrents running. Usually it is less than a min, especially if there's only a couple of new videos in the past week. I get home, run the cmd line, Alternate back to my plex, boom, it's there. No waiting for 10 mins. Instant happiness. In fact I just ran it and surprising it took like less than 5 seconds to tell me 1 subtitle downloaded. Unfortunately I am not an expert in nix so I appreciate the command given but I have already gone back to 0.8.0 for now because of how lean and mean 0.8.0 is for my use case.
2.Yea, I think a better way would be for me to rename all my filename.srt files to filename.en.srt files for example. But then again would subliminal mark a video as subtitle missing if say I removed -s and filename,en.srt is already there? Assuming -l en is provided?
3. That's weird, because when I add back the -s the file was no longer detected. Maybe something to do with that instead of the age function. Unfortunately I have no knowledge of python to help out with that :(
4. Are you referring to Limitless.S01E12.720p.HDTV.X264-DIMENSION.mkv and Brooklyn.Nine-Nine.S03E11.720p.HDTV.x264-KILLERS.mkv? If it is I'll open an issue. Just to let you know running 0.8.0 detects it. It could have been a glitch with addic7ed at the time I tested it but I didn't see any errors in the console log as far as I could tell. However, my theory is that the minimal requirements is set too low and hence it wasn't compatible with the latest subliminal.
5. Do you mean the visual glitch? Yes I agree it's a weird visual glitch probably to do with PuTTY or something, when I rerun the same command the 0d00 thing were no longer there and displayed the filenames normally as I think it should.
6. So it connects to the different providers anyway even though one provider was already explicitly requested? May I know the use case for that?

For reference this is my current dependencies and their versions:
babelfish (0.5.5)
beautifulsoup4 (4.4.1)
chardet (2.3.0)
click (6.2)
dogpile.cache (0.5.7)
dogpile.core (0.4.1)
enzyme (0.4.1)
guessit (0.7.1)
html5lib (0.9999999)
pbr (1.8.1)
pip (7.1.2)
pyOpenSSL (0.15.1)
pysrt (1.0.1)
python-dateutil (2.4.2)
pyxdg (0.25)
requests (2.9.1)
setuptools (18.2)
six (1.10.0)
speedtest-cli (0.3.4)
stevedore (1.10.0)
subliminal (0.8.0.dev0)

**Comment by Diaoul** [comment]
1. I will implement a way to skip old files when scanning a directory, that should save up some processing time indeed. I'm not a fan of the implementation of the solution as it's not very DRY but it's just a few lines of duplicated code so I can live with that.
2. Regarding existing subtitles detection, assuming `-l en`:
   * `-s` and existing `.srt`: no download
   * `-s` and existing `.en.srt`: no download (not sure about that one)
   * `-s` and no `.srt`: download
   * no `-s` and `.en.srt`: no download
   * no `-s` and no `.en.srt`: download
3. Yes, open an issue with this two filenames
4. Yes this is purely visual, nothing I can do here
5. It doesn't connect to anything, it reads the file to compute the hashes, it's like a md5sum but specialized for video files and faster to compute

**Comment by Diaoul** [comment]
Fixed with 163115da88ad803ce035b982f925e27a112701b9

**Comment by CyberMew** [comment]
Sorry for the lack/delay in replies, I haven't been touching subliminal much. I just installed the develop branch, and it seems to be working great now! No visual issues, the search is much faster, and everything else I had a problem with is gone, thank you! But I'm getting too many requests error (for addic7ed) which is weird because I'm a VIP which allows me to download 80 subtitles within 24 hours and I've only hit 28 in the past 24 hours. AFAIK non members are limited to 15 files, registered members are limited to 40 files. I think the reason I can't download the 2 files (mentioned last month) then is because of the error too. Is this a addic7ed issue?
Also, I think that if a toomanyrequest error is encountered, we should terminate the rest of the request for that provider to prevent requesting from them again - imagine if each request extends the 'ban' by 5 minutes, it would take a long time for it to be back to normal.

Here is my current pip list for reference:
appdirs (1.4.0)
babelfish (0.5.5)
beautifulsoup4 (4.4.1)
chardet (2.3.0)
click (6.2)
dogpile.cache (0.5.7)
dogpile.core (0.4.1)
enzyme (0.4.1)
futures (3.0.5)
git-remote-helpers (0.1.0)
guessit (2.0.4)
html5lib (0.9999999)
pbr (1.8.1)
pip (8.0.2)
pyOpenSSL (0.15.1)
pysrt (1.0.1)
python-dateutil (2.4.2)
pyxdg (0.25)
rebulk (0.7.1)
requests (2.9.1)
setuptools (18.2)
six (1.10.0)
speedtest-cli (0.3.4)
stevedore (1.11.0)
subliminal (2.0.dev0)

Also, is it possible if there is no `-s` and no `.en.srt`, don't download if `.srt` already present? I ran the wrong command by mistake and all my videos have both `.en.srt` and `.srt` ...

**Comment by Diaoul** [comment]
1. Upon failed request the provider is discarded and never used again, if that's not the case please provide debug logs.
2. `.srt` doesn't carry language information so I don't think it's wise to assume the correct subtitle is present when `-s` isn't provided and `.srt` exists.

**Comment by CyberMew** [comment]
1. I couldn't repro it again, but I definitely saw it the couple of times I did it. I'm not sure how that happened. Maybe something to do with their endpoint?
2. I understand, got it. Thank you :)

I now have series that can't be matched, I'll open another issue or tack it to someone elses
