### ISSUE TITLE
Allready downloaded subs  no interface

### ISSUE THREAD

**Issue by sollie78** [Diaoul/subliminal#547]
When i download subs wit nautlus and try to open the subluminal interface again it wont work. I had to delete de subs first.

**Comment by Diaoul** [comment]
1. The menu appears you click on it and it displays the window
2. When you repeat 1. with existing subs, the menu is here but when clicked nothing happens

Did I understand your issue correctly?
I'm considering moving the nautilus stuff to another repository to decouple it from subliminal itself.

**Comment by sollie78** [comment]
Yes. This is correct.

Mvg,

Harm de Vries

0626130414
________________________________
Van: Antoine Bertin<mailto:notifications@github.com>
Verzonden: ‎1-‎1-‎2016 14:54
Aan: Diaoul/subliminal<mailto:subliminal@noreply.github.com>
CC: sollie78<mailto:harmdevries@gmail.com>
Onderwerp: Re: [subliminal] Allready downloaded subs  no interface (#547)

1. The menu appears you click on it and it displays the window
2. When you repeat 1. with existing subs, the menu is here but when clicked nothing happens

Did I understand your issue correctly?
I'm considering moving the nautilus stuff to another repository to decouple it from subliminal itself.

---

**Comment by Diaoul** [comment]
I just created https://github.com/Diaoul/nautilus-subliminal through cd10f3f07adf30b43d9173ad71b1ad5527c7609f.

Let's discuss this issue from there.
