### ISSUE TITLE
Commands to change config didnt work for me

### ISSUE THREAD

**Issue by sollie78** [Diaoul/subliminal#548]
When i use the following command i get an error:

subliminal --addic7ed USERNAME PASSWORD

Error: 
Usage: subliminal [OPTIONS] COMMAND [ARGS]...
Error: Missing command.

**Comment by Diaoul** [comment]
Subliminal CLI changed with 1.0, please read the docs to adapt your command.
Old `subliminal` should be replaced with `subliminal download`, there may be a few other adjustments to do.

**Comment by kchr** [comment]
But the docs still suggest that provider config is done without/before the command verb. It is unclear whether or not it is possible to save that config for future `download` commands, or if it has to be passed along every time.

Example:
https://github.com/Diaoul/subliminal/blob/e85c21f40e47399039982f3bdba7c4e2247d3c67/docs/user/cli.rst

```
$ subliminal --help
Usage: subliminal [OPTIONS] COMMAND [ARGS]...

  Subtitles, faster than your thoughts.

Options:
  --addic7ed USERNAME PASSWORD    Addic7ed configuration.
  --opensubtitles USERNAME PASSWORD
                                  OpenSubtitles configuration.
[...]
```

Maybe the provider config parameters should be moved to the `download` command, or the help docs changed to reflect that they are to be sent along with every `download`?

**Comment by Diaoul** [comment]
The rationale behind this is that I plan to add other subcommands that will also inherit the provider configuration so this is kind of a global setting from a CLI standpoint.

I will add a `-c` option that will load configuration from a config file to shorten the command line.

**Comment by kchr** [comment]
Fair enough!

**Comment by jonaswindey** [comment]
does this mean that the current command to download with credentials is
```subliminal --opensubtitles USER PASS download -l nl The.Big.Bang.Theory.S05E18.HDTV.x264-LOL.mp4 -p opensubtitles``` ?

And what if I want to downoad from multiple providers with different credentials?

**Comment by Diaoul** [comment]
`subliminal --opensubtitles USER PASS --addic7ed USER PASS download -l nl -p opensubtitles -p addic7ed The.Big.Bang.Theory.S05E18.HDTV.x264-LOL.mp4`

**Comment by jonaswindey** [comment]
Thanks, good job on this tool btw (y)

**Comment by sollie78** [comment]
Ok i get it. Is it possible to put this in gui,

**Comment by Diaoul** [comment]
You mean the configuration for providers? That's difficult because
providers are dynamic for subliminal. I will try to come up with something,
some dynamic GUI from the code.
