### ISSUE TITLE
Add info in subtitle class

### ISSUE THREAD

**Issue by Diaoul** [Diaoul/subliminal#549]
This would be a property implemented by providers that returns a string (or a list of strings) about the subtitle for GUI rendering.
This would be a good place for releases or filenames. Anything that can help the user decide.
##

**Comment by Diaoul** [comment]
Could be solved by a release property with #572

**Comment by fernandog** [comment]
Fixed with `get_subtitle_description(subtitle)`

**Comment by ratoaq2** [comment]
It's still a valid feature to be added to subliminal. I wouldn't close it.

**Comment by fernandog** [comment]
Sorry! I was to close https://github.com/Diaoul/subliminal/issues/581 which is already closed!

**Comment by ratoaq2** [comment]
Fixed by 99384476ec62ec9f2769b4dc79ea38ed14c16def
