### ISSUE TITLE
Feature Request - Make all API calls return a error_code(http error?) and error_message

### ISSUE THREAD

**Issue by fernandog** [Diaoul/subliminal#551]
- maybe not all, but some.

so when you call "download_subtitles" for example and provider is down or 503 (opensubtitle has that a lot) we can known we had connectivity issue or another issue so we can better inform user

I know this can be complex but would be good for third party apps to handle better the code as we can't keep reading LOG

**Comment by Diaoul** [comment]
Use the lower level API, either by implementing your own [ProviderPool](https://github.com/Diaoul/subliminal/blob/develop/subliminal/api.py#L105) or by directly using the [ProviderManager](https://github.com/Diaoul/subliminal/blob/develop/subliminal/api.py#L19)
