### ISSUE TITLE
Parallellize searching providers

### ISSUE THREAD

**Issue by Avinem** [Diaoul/subliminal#560]
Would it be possible to parallelize the search? Sequentially searching each provider seems to be taking about the same time as manually googling and finding the subs

**Comment by Diaoul** [comment]
You're comparing picking the first sub that comes with a Google search to a
thorough search of many providers. That's not really the same thing.

I'm guessing you use the CLI? Parallelization isn't currently supported but
I plan to add this feature soon and this would be the default for the CLI.

**Comment by 0verrider** [comment]
Yes, you're right, and this feature would be great if implemented. Looking forward to it, and great work btw!

**Comment by Diaoul** [comment]
I will add an `AsyncProviderPool` based on the original [ProviderPool](https://github.com/Diaoul/subliminal/blob/develop/subliminal/api.py#L105) but with one thread per provider. This should greatly speed up the CLI.

**Comment by Diaoul** [comment]
I've started implementing this in a dedicated branch. So far it gives good results. https://github.com/Diaoul/subliminal/tree/async

**Comment by Diaoul** [comment]
Implemented in develop.

**Comment by Crupuk** [comment]
Hi @Diaoul 

Could you please tell me what i'm doing wrong ?

`
from babelfish import Language
from subliminal import list_subtitles,download_subtitles, region, save_subtitles, scan_video, compute_score, get_scores
from subliminal.core import AsyncProviderPool
video = scan_video("/dlna/shows/en/The Big Bang Theory/S10/The.Big.Bang.Theory.S10E22.PROPER.720p.HDTV.x264-FLEET.mkv")
pool = AsyncProviderPool()

print pool.list_subtitles([video],{Language('eng')})
Test for provider legendastv
0 Subs found
Test for provider shooter
0 Subs found
Test for provider podnapisi
0 Subs found
Test for provider tvsubtitles
0 Subs found
Test for provider opensubtitles
0 Subs found
Test for provider addic7ed
0 Subs found
Test for provider subscenter
0 Subs found
Test for provider thesubdb
0 Subs found
[]
print list_subtitles([video],{Language('eng')})
defaultdict(<type 'list'>, {<Episode ['The Big Bang Theory', 10x22]>: [<PodnapisiSubtitle 'p-ZD' [en]>, <OpenSubtitlesSubtitle '1955542864' [en]>, <OpenSubtitlesSubtitle '1955542864' [en]>, <OpenSubtitlesSubtitle '1955542864' [en]>, <OpenSubtitlesSubtitle '1955542865' [en]>, <OpenSubtitlesSubtitle '1955542958' [en]>, <OpenSubtitlesSubtitle '1955546811' [en]>, <OpenSubtitlesSubtitle '1955546810' [en]>, <OpenSubtitlesSubtitle '1955542956' [en]>, <TheSubDBSubtitle '81f72b25cac269c47ae6e0172ee8de2a-en' [en]>]})
`

Thanks
