### ISSUE TITLE
subliminal run failing on Synology NAS

### ISSUE THREAD

**Issue by raspap** [Diaoul/subliminal#561]
Hi,

I have been able to install Subliminal through the Synocommunity channel on my NAS, but trying to run it from the Package Center gives an error: "Failed to run the package service".

I am using:
subliminal 0.7.5-12
python 2.7.11-15
DSM 6.0 beta 2

Any idea on how to debug this?

Thanks!

**Comment by Diaoul** [comment]
Please report to SynoCommunity
