### ISSUE TITLE
CLI parameters --age , -a

### ISSUE THREAD

**Issue by zannanikeb** [Diaoul/subliminal#571]
Sorry, i got some troubles on my CLI command, i always use "-a 5d" as argument but as i can see from debug takes all the files in my folders, even the older ones.

is there something i'm doing wrong?

here is my CLI command:
subliminal --debug download -l it -a 5d -- /home/...../tvfolder >> /home/logSub.txt

Thanks

**Comment by Diaoul** [comment]
Can you post the debug log?

**Comment by zannanikeb** [comment]
Hi

Here's the log

`matteo@SERVER:~$ subliminal --debug download -l it -a 5d /home/matteo/Disco/Telefilm2/Billions > /home/matteo/logFile.txt
DEBUG:subliminal.cli:Collecting path /home/matteo/Disco/Telefilm2/Billions
DEBUG:subliminal.video:Walking directory /home/matteo/Disco/Telefilm2/Billions
DEBUG:subliminal.video:Walking directory /home/matteo/Disco/Telefilm2/Billions/Serie.01
INFO:subliminal.video:Scanning video 'Billions.S01E03.mp4' in '/home/matteo/Disco/Telefilm2/Billions/Serie.01'
DEBUG:subliminal.video:Size is 294343537
DEBUG:subliminal.video:Computed hashes {'opensubtitles': '611503669cc08087', 'thesubdb': 'f1a12058b484fce197a2e3456c94d76a', 'napiprojekt': 'b9b60885c08fa81482731b8f6242cd9b'}
DEBUG:subliminal.video:Found subtitles {}
INFO:subliminal.video:Scanning video 'Billions.S01E01.mp4' in '/home/matteo/Disco/Telefilm2/Billions/Serie.01'
DEBUG:subliminal.video:Size is 363312720
DEBUG:subliminal.video:Computed hashes {'opensubtitles': '47652222d8192cff', 'thesubdb': '0aa5df9804d5f22a3c04462c86a5e345', 'napiprojekt': 'd499ae56e916717fc55c2463693f615f'}
DEBUG:subliminal.video:Found subtitles {'Billions.S01E01.it.srt': <Language [it]>}
INFO:subliminal.video:Scanning video 'Billions.S01E02.mp4' in '/home/matteo/Disco/Telefilm2/Billions/Serie.01'
DEBUG:subliminal.video:Size is 333623597
DEBUG:subliminal.video:Computed hashes {'opensubtitles': 'b1d0a27aaf3d07e1', 'thesubdb': '035da0d45cf6409c04cfe138cc2e5e19', 'napiprojekt': 'cd1392626a66e26a7fdcaf81c433a342'}
DEBUG:subliminal.video:Found subtitles {'Billions.S01E02.it.srt': <Language [it]>}
DEBUG:subliminal.api:All languages set([<Language [it]>]) exist
DEBUG:subliminal.api:All languages set([<Language [it]>]) exist
INFO:subliminal.api:Listing subtitles with provider 'podnapisi' and languages set([<Language [it]>])
INFO:subliminal.api:Initializing provider podnapisi
INFO:subliminal.providers.podnapisi:Searching subtitles {'sK': u'Billions', 'sTE': 3, 'sXML': 1, 'sTS': 1, 'sL': 'it'}
DEBUG:subliminal.providers.podnapisi:No subtitles found
INFO:subliminal.api:Listing subtitles with provider 'tvsubtitles' and languages set([<Language [it]>])
INFO:subliminal.api:Initializing provider tvsubtitles
INFO:subliminal.providers.tvsubtitles:Getting the page for episode 59379
ERROR:subliminal.api:Unexpected error in provider 'tvsubtitles', discarding it
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/api.py", line 116, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/tvsubtitles.py", line 188, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.episode, video.year) if s.language in languages]
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/tvsubtitles.py", line 174, in query
    language = Language.fromtvsubtitles(row.h5.img['src'][13:-4])
  File "/usr/local/lib/python2.7/dist-packages/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/usr/local/lib/python2.7/dist-packages/babelfish/converters/__init__.py", line 240, in __getitem__
    self.converters[ep.name] = ep.load()()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2087, in load
    if require: self.require(env, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2100, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
VersionConflict: (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9.0'))
INFO:subliminal.api:Listing subtitles with provider 'opensubtitles' and languages set([<Language [it]>])
INFO:subliminal.api:Initializing provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging in
DEBUG:subliminal.providers.opensubtitles:Logged in with token 'thfcgao17dtpf3og223i0tnf12'
INFO:subliminal.providers.opensubtitles:Searching subtitles [{'moviebytesize': '294343537', 'sublanguageid': u'ita', 'moviehash': '611503669cc08087'}, {'query': u'Billions', 'sublanguageid': u'ita', 'episode': 3, 'season': 1}]
DEBUG:subliminal.providers.opensubtitles:No subtitles found
INFO:subliminal.api:Listing subtitles with provider 'addic7ed' and languages set([<Language [it]>])
INFO:subliminal.api:Initializing provider addic7ed
DEBUG:subliminal.providers.addic7ed:Getting show id
INFO:subliminal.providers.addic7ed:Getting the page of show id 5520, season 1
ERROR:subliminal.api:Unexpected error in provider 'addic7ed', discarding it
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/api.py", line 116, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/addic7ed.py", line 259, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/addic7ed.py", line 224, in query
    raise TooManyRequests()
TooManyRequests
INFO:subliminal.api:Skipping provider 'subscenter': no language to search for
DEBUG:subliminal.api:Terminating initialized providers
INFO:subliminal.api:Terminating provider podnapisi
INFO:subliminal.api:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
INFO:subliminal.api:Terminating provider tvsubtitles
INFO:subliminal.api:Terminating provider addic7ed
matteo@SERVER:~$ 
`

I know is not so readable, but i can tell you that in in this folders there are 3 video files, 2 with subtitles (older than a week) and one file that match the age criteria that doesn't have subtitles ready yet.
In the log output i can see:

> Collecting videos
> 3 videos collected / 2 videos ignored / 0 error
> Downloading subtitles
> Downloaded 0 subtitle

If there's something i can provide you, please tell.

Thanks

**Comment by zannanikeb** [comment]
After some other tests i can tell that in a very big big folder it downloads ONLY the subs about the videos with the correct age.

What i would like to know is...why it keeps analyzing every single file, even if it's not in the right age?
In my folder i have more than 800 episodes so it takes from 8 to 10 minutes every time this runs on the top folder

In the past versions (the last was 0.8.0) it tooks less  than 30 seconds.

**Comment by Diaoul** [comment]
Fixed with 163115da88ad803ce035b982f925e27a112701b9.
Please try develop branch, it should be much faster.

**Comment by zannanikeb** [comment]
Works perfectly.
Thank you very much.
