### ISSUE TITLE
Guessit dependency collinding with Flexget (feature request?)

### ISSUE THREAD

**Issue by niawag** [Diaoul/subliminal#573]
Hi and thanks for your great work!

I'm using Subliminal with Flexget (https://github.com/Flexget/Flexget) and there is a conflict in GuessIt dependency (<2.0 for Subliminal and 2.0.4 for Flexget).

I don't know what it implies to move to Guessit 2.0.4 but I'd love (and think other flexget user too) if it is possible without breaking anything!

**Comment by Diaoul** [comment]
It's already done in develop branch along with major new enhancements.

**Comment by niawag** [comment]
Thanks a lot, I installed dev branch and it's working again!
