### ISSUE TITLE
Feature Request - Remove non-release words from release groups

### ISSUE THREAD

**Issue by fernandog** [Diaoul/subliminal#574]
KILLERS[ettv]
KILLERs[rarbg]
LOL[brassetv]
ETC...

Opensubtitles:
http://dl.opensubtitles.org/pt/download/file/1955011332

LTV:
http://legendas.tv/download/55e50f377ac8a/Narcos/Narcos_S01_720p_WEBRip_x264_TASTETV_ettv

This is how we do at SickRage
https://github.com/SickRage/SickRage/blob/develop/sickbeard/helpers.py#L108

as @ratoaq2 said, guess it won't do it

IMO we should match both `KILLERS[ettv]` and `KILLERS` and use the best score from both. So we can handle subs with and without non-release words in release groups

**Comment by fernandog** [comment]
@Diaoul I joined #subliminal

**Comment by Diaoul** [comment]
Fixed with b6ed77a56cd4bb12c87f00744f1fbd22c944c55a
