### ISSUE TITLE
Video.fromname crash for miniseries

### ISSUE THREAD

**Issue by NigelRook** [Diaoul/subliminal#577]
Video.fromname crashes with The.Jinx-The.Life.and.Deaths.of.Robert.Durst.E05.BDRip.x264-ROVERS:

  File ".../subliminal/video.py", line 118, in fromname
    return cls.fromguess(name, guess_file_info(name))
  File ".../subliminal/video.py", line 104, in fromguess
    return Episode.fromguess(name, guess)
  File ".../subliminal/video.py", line 174, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess

Seem that, since it's an HBO miniseries with only one season, the season has been omitted, and subliminal doesn't cope. partX may be affected too, haven't tested.

Maybe setting season to 1 in fromguess if it's missing but series and episode are present is the answer, looks like that's how providers store them anyway.

**Comment by Diaoul** [comment]
If season can be missing for a valid reason (and this is the case here) then subliminal should handle it.

**Comment by Diaoul** [comment]
Fixed with a732b0c75b53edb72378690512e4982336d61399
