### ISSUE TITLE
'Episode' object has no attribute 'scores'

### ISSUE THREAD

**Issue by effemmeffe** [Diaoul/subliminal#578]
I'm using subliminal as flexget plugin to download subtitles of movies and episodes.
To have subliminal work with flexget I had to install a developement version:

```
fmf@kodi:~$ subliminal --version
subliminal, version 1.2.dev0
```

In the flexget log I get this:

```
2016-02-08 15:48 INFO     subtitles     download-subtitles Name computed for /media/Tera/Library/TV/Younger/S02/Younger - S02E05 - Jersey, Sure - [720p hdtv h264].mkv was Younger
2016-02-08 15:48 ERROR    entry         download-subtitles Failed Younger - S02E05 - Jersey, Sure - [720p hdtv h264] ('Episode' object has no attribute 'scores')
```

What does it means?

**Comment by cvium** [comment]
As I have written on our own discussion board, it is related to https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/output/subtitles_subliminal.py#L127, so this issue should be closed as it is a Flexget specific issue with the dev-branch of Subliminal.

**Comment by effemmeffe** [comment]
Sorry, I don't get it: is there something I can do to fix this?
Because on flexget forum they say this is a subliminal issue, you are saying this is a flexget specific issue and I'd just like to have it work.
Is there some editing in some file on my system that'll fix this or should I report this on some other place?
Plus, shold I close this issue or will someone take care of that?
Thanks in advance.

**Comment by cvium** [comment]
Yes, you should close this. http://discuss.flexget.com/t/subliminal-error/2023/4

**Comment by effemmeffe** [comment]
Ah, lol, I didn't recognize you from the other forum.
I'll close that, don't know if I should close this too.

**Comment by cvium** [comment]
I meant you should close this issue and keep the discussion open at our own forum.

**Comment by effemmeffe** [comment]
Ok, I messed up a little, sorry for that.
