### ISSUE TITLE
addic7ed:No show id found for u'The X-Files'

### ISSUE THREAD

**Issue by mtzro2003** [Diaoul/subliminal#579]
Hello Diaoul.

subliminal 1.1.1 cannot find the show id for the new season of The X-Files.
Here's the debug log:

> Downloading subtitles  [####################################]  100%  The.X-Files.S10E02.HDTV.x264-KILLERS.mp4
> INFO:subliminal.api:Initializing provider addic7ed
> INFO:subliminal.providers.addic7ed:Logging in
> DEBUG:subliminal.providers.addic7ed:Logged in
> DEBUG:subliminal.providers.addic7ed:Getting show id
> WARNING:subliminal.providers.addic7ed:Series not found in show ids
> ERROR:subliminal.providers.addic7ed:No show id found for u'The X-Files' ({'country': None, 'year': None})

**Comment by Diaoul** [comment]
#563
