### ISSUE TITLE
Ignore samples

### ISSUE THREAD

**Issue by d-lindahl** [Diaoul/subliminal#580]
Something I noticed recently is that subliminal downloads subtitles for samples. Does one ever want this? (what surprises me more though is that people upload subs for samples...)

Should be easy to filter out with just a "sample" not in filename-check, if it's a reasonable request. Otherwise just close! I'll survive!
##

**Comment by Diaoul** [comment]
Sample might as well be part of the title. I'm not sure just finding "sample" in the filename is enough.

**Comment by brp-david** [comment]
True enough, didn't think that far. Though atleast excluding the "standard" scene-naming with filename.sample.mkv should take care of most of them. Though the rules only state that the sample should be in a subdirectory called sample. Might just be too much effort for something very little.

**Comment by brp-david** [comment]
Looked through my library (and read some more scene-rules) and the only "sure" way to detect them seems to be that they're located in a subdirectory called sample. The names are all over the place with sample-filename.mkv filename.sample.mkv filename.[sample].mkv

**Comment by magnub** [comment]
Instead of sample filename filtering why not making it possible to filter on the directory name ([Ss]ample) ?
