### ISSUE TITLE
Question: What's your opinion about supporting subtitle providers without API?

### ISSUE THREAD

**Issue by bcse** [Diaoul/subliminal#582]
There are some popular subtitle providers doesn't have an API.
Is subliminal willing to support -- or opening to accept PR for -- those kind of subtitle providers by parsing HTML?

**Comment by Diaoul** [comment]
Yes, it's already the case for most providers. You can take inspiration from the Addic7ed provider.
One requirement however is to never hide subliminal's activity by setting the correct User-Agent.

**Comment by bcse** [comment]
Thank you. I didn't know that Addic7ed doesn't have API.
