### ISSUE TITLE
Increase performance by filtering sooner

### ISSUE THREAD

**Issue by nvdweem** [Diaoul/subliminal#587]
I might be using Subliminal wrong but I have an issue when I run it over my TV show library that contains 2700 episodes. I run subliminal locally and the TV shows are on my NAS.
When I run subliminal it takes a very long time to scan over all folders and inspect the files only to ignore nearly all of them later (I use '-a 7d').

I'm able to bring down the run time significantly by adding the age check in the scan_videos method before it calls scan_video. The difference is somewhere along the lines of 30+ minutes without the check to ~15 seconds with the check.

**Comment by Diaoul** [comment]
It's already fix in develop branch.
