### ISSUE TITLE
Unable to match series

### ISSUE THREAD

**Issue by CyberMew** [Diaoul/subliminal#588]
ERROR:subliminal.providers.addic7ed:No show id found for 'Marvels Agents of S H I E L D' ({'country': None, 'year': None})
ERROR:subliminal.providers.addic7ed:No show id found for 'Marvels Daredevil' ({'country': None, 'year': None})

Managed to solve these by adding the year/extra information in their main folder name (to match Addic7ed's show names)
ERROR:subliminal.providers.addic7ed:No show id found for 'House of Cards' ({'country': None, 'year': None}) 
ERROR:subliminal.providers.addic7ed:No show id found for 'Resurrection' ({'country': None, 'year': None})
ERROR:subliminal.providers.addic7ed:No show id found for 'Proof' ({'country': None, 'year': 2015})

Any idea why the two agents series are not working?

edit: small request, can you show the total number of subtitles downloaded after everything? (this is from 0.8.0dev). Some videos doesn't have subtitles, but they count them in anyway, so if I know today there has been 4 new downloads, I would know out of 4 videos how many subs were downloaded (sometimes if you run subliminal again it redls the missing ones)

**Comment by Diaoul** [comment]
Try searching like [this](http://www.addic7ed.com/search.php?search=Marvels+Agents+of+S+H+I+E+L+D&Submit=Search), there are no suggestions.
However if you remove the s and search for `Marvel Agents of S H I E L D`, [you have a suggestion](http://www.addic7ed.com/search.php?search=Marvel+Agents+of+S+H+I+E+L+D&Submit=Search).
There's not much that can be done here from a pure filename perspective there is no way to get the correct series name.
Luckily, in subliminal 2.0 (currently in develop branch) there are refiners that can help you find the exact series name by searching various refiners (TVDB mainly for episodes). Try the develop branch.

As for the downloaded subtitles, have you tried adding verbosity with `-v`?

**Comment by Diaoul** [comment]
Any updates on this?

**Comment by CyberMew** [comment]
My apologies, my server has been down recently due to a hardware failure and I wouldn't be able to replace the hardware for a couple of weeks at least. 

From what I remember, I was already on the develop branch which had all the bells and whistles, and it didn't retrieve the subtitles for marvels agents of shield. Perhaps I need to configure something for it to work?
As for the successful downloaded count, I don't think I've tried -v yet, but I will try it once my server is up.

**Comment by Diaoul** [comment]
A lot changed lately and refiners were added in the CLI just yesterday so that may fix the marvel issue. As for the number of downloaded subtitles I'll check the code

**Comment by CyberMew** [comment]
Oh great that's awesome! I'll try and let you know how it goes when my server is back up again :)

**Comment by Diaoul** [comment]
Please reopen if you still have the issue after testing.
