### ISSUE TITLE
Season required from guessit

### ISSUE THREAD

**Issue by sides** [Diaoul/subliminal#590]
Some series, especially documentaries, do not have seasons, and filenames reflect that such as "Planet Earth - 01 - From Pole to Pole.mkv" (raises `ValueError('Insufficient data to process the guess')` [here](https://github.com/Diaoul/subliminal/blob/master/subliminal/video.py#L173)). I tried changing the "01" part to "1x01" so `guessit`ing it returns a `season` and that works fine, so maybe it could just default to `1` internally if no `season` is supplied? I wouldn't know about the other subtitle databases, but opensubtitles seems to classify these types of series to just be season 1.

I'm aware I could just change my filename scheme but it would be convenient to have this work.

**Comment by Diaoul** [comment]
See #577
