### ISSUE TITLE
Add option to use original/alternative filename when guessing movie/episode properties

### ISSUE THREAD

**Issue by ratoaq2** [Diaoul/subliminal#593]
If I understood correctly, refiners will enhance the set of information of our video.
The initial info that exists is the video path. Using the video path:
- guessit will create the initial set of information from the file path / file name.
- the metadata refiner will try to get more details about the video (for mkv containers),
- then omdb will obtain more movie details
- and then tvdb will obtain more tv shows details

Even guessit (1st step) could have been a "refiner".

Each one organize movies and series in a different way, and most of the time, file renaming is used.
In my case, I usually keep some metadata files alongside the video file, including a file that contains the original filename of the video. Initially I wasn't keeping the quality, release group and other info in the filename:
```
Foo Bar/Season 01/Foo Bar S01E01 - Super Title.mkv
Foo Bar/Season 01/Foo Bar S01E01 - Super Title.meta
```
```
$> cat "Foo Bar/Season 01/Foo Bar S01E01 - Super Title.meta"
Foo.Bar.S01E01.Super.Title.720p.WEBRip.AAC2.0.H.264-RGROUP
```

It would be really nice to have an additional refiner that enhances the guessit properties of your video based on some additional file/information that's present.

This is just an idea and a use case. I believe that file renaming is quite common and this can give us more flexibility when organizing our library.

**Comment by Diaoul** [comment]
Everything could be a refiner basically. What you need is the minimal information though, so you can "enrich" it from other sources.

You have to start with something. Given that videos are files, subliminal uses this fact to build an initial set of `Video` objects. Hence the `scan_video`, `scan_archive` and `scan_videos` functions.
One is free to build `Video` objects by other means and still can "enrich" them with refiners.

So basically if you want to start with something else than video files (not ideal IMO), you can't use the CLI and need to implement your own scanning mechanism based on whatever suits you. There may be a way to plug this with click in the current subliminal CLI but that seems like a lot of overhead.
The other solution is to let subliminal do the initial scanning and add your own refiner thanks to the `subliminal.refiners` entrypoint. Currently there is no way to specify refiners to use with the CLI but that's something I want to implement, the same way you can select your provider.

**Comment by ratoaq2** [comment]
My original idea was not to start with something else other than videos. I'll continue to scan videos, but when enhancing the video information, this extra refiner will check if there's a file present with the same video name but different extension and do what I have described.

It would be perfect to have an easy way to plug in refiners using the command line interface.

I'm also thinking in a way to keep the video metadata (maybe stored in a simple json file) cached somewhere to avoid scanning/parsing the video all the time and spinning up the HDD every time I'm searching for subtitles, so I can increase the search frequency. In the end the video object is just a dictionary with known keys.

**Comment by Diaoul** [comment]
If a daemon were running we could use filesystem notification to search
videos on modification.
I will make some changes to the CLI and document how to plug in refiners.

Also be careful not to search to much or you can get banned from providers.

**Comment by ratoaq2** [comment]
That's great. It will be very much appreciated.

Just to clarify my second use case: I already have the video and its location is fixed and well known, but no subtitle is available. From time to time I need to search for subtitles and perform a `scan_video` (spinning up the HDD) just to create the video object with the very same information every time, just to search for subtitles. I could manage myself to keep the video data cached in a separate location and every time recreate the video instance with that information and perform the search. The HDD will only spin up when a subtitle is found and saved alongside the video.

**Comment by Diaoul** [comment]
Option in CLI implented with 91267191f10e478c2b334cd7a3153528aa61932e

**Comment by ratoaq2** [comment]
Thank you for that.

I still have a question about refiners: what is/will be the policy about refiners? Do you plan to keep a small set of refiners and keep them as generic as possible to fit most of user needs? Or you are  willing to have some specific refiners in subliminal that users could enable as they need?

I'm asking that question because I did create one specific refiner based on the use case that I explained in this topic: You can take a look at it [here](https://github.com/ratoaq2/SickRageSickRage/blob/subliminal-release-refiner/sickbeard/refiners/release.py).

This refiner will "enrich" the video information based on the release_name (in scenarios where the video file was renamed and its name doesn't represent the release name). The release_name can be passed as an argument of the refiner or the refiner will look for a .release file that contains the release_name.
At my local installation I use both cases: SickRage keeps the original release_name in its database, so when searching for subtitles for a specific video the release_name is passed as parameter:
`refine(video, release_name=release_name)`, but in other softwares I'm using the `<video name>.release` file.

If you think that this should/could be part of subliminal, I could create a PR for it. If not, no problem at all since this is like an extra-script/extra-plugin that I've created for my needs using subliminal API.

**Comment by Diaoul** [comment]
Generic refiners are accepted but you have an edge case here. For a library use I suggest you post process the result of `scan_videos` function rather than using a refiner to do that, it's less overhead. If this way of storing metadata becomes a standard I will reconsider adding this kind of refiner.

**Comment by Diaoul** [comment]
Feel free to reopen if I did not answer all your questions.
