### ISSUE TITLE
Support for aRGENTeaM

### ISSUE THREAD

**Issue by tanoabeleyra** [Diaoul/subliminal#595]
**aRGENTeaM** is community that provides subtitles in Spanish (Latin America).
They have a public API and I made a Python script that makes use of it to download subtitles: [argenteam-sub.py](https://gist.github.com/tanoabeleyra/4b6b30acd17f9d18040b)

I hope you can add it as a provider, people from Latin America (especially Argentina) will really appreciate it.

Regards.
##

**Comment by ratoaq2** [comment]
Since you did create a python script for it, you could try and create a provider for it as well. It's not difficult and there are several examples. With a public API, it makes your life easier.
I can support you if you need any help.

**Comment by t4n017** [comment]
The truth is that I used someone else's code as base and it's the first time I coded in Python, but I'm gonna take a look into it (just for learning purposes and contribution) as soon as I get a bit of free time.

**Comment by lardissone** [comment]
+1

**Comment by felipelerena** [comment]
I want aRGENTeaM as provider for https://github.com/touchandgo-devs/touchandgo (this is the issue:  https://github.com/touchandgo-devs/touchandgo/issues/81) so I will try to do the provider. Where is the doc to create a new provider?
