### ISSUE TITLE
Downloaded subtitle file name format.

### ISSUE THREAD

**Issue by arjunmayilvaganan** [Diaoul/subliminal#599]
I've tried reading the docs and also both of the open and closed issues. But I couldn't figure out how to retain the downloaded subtitle file name as `INPUTFILENAME.srt` instead of `INPUTFILENAME.en.srt`.

Any help would be appreciated.

**Comment by Diaoul** [comment]
Use `-s` or `--single`.
See http://subliminal.readthedocs.org/en/latest/user/cli.html
