### ISSUE TITLE
TVDB refiner pick wrong series

### ISSUE THREAD

**Issue by ratoaq2** [Diaoul/subliminal#603]
For the latest develop version (2.0-rc1)
For CSI tvdb refiner pick the wrong series.

```
subliminal.py --debug --legendastv pass user download -f -l pt-BR -p legendastv -m 97 CSI.S15E18.720p.HDTV.X264.DIMENSION.mkv
Collecting videos  [####################################]  100%  CSI.S15E18.720p.HDTV.X264.DIMENSION.mkvDEBUG:subliminal.cli:Collecting path CSI.S15E18.720p.HDTV.X264.DIMENSION.mkv
INFO:subliminal.core:Refining video with metadata
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'CSI'
DEBUG:subliminal.refiners.tvdb:Found 9 results
DEBUG:subliminal.refiners.tvdb:Found result for original series without year
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'', u'status': u'Continuing', u'added': u'2011-10-30 01:27:22', u'airsTime': u'20:00', u'network': u'TV Nova', u'rating': u'', u'overview': u'Crimi series inspired by real cases.', u'lastUpdated': 1440591672, u'zap2itId': u'', u'seriesName': u'CSI Andel', u'siteRating': 6, u'firstAired': u'2008-09-01', u'addedBy': 8907, u'networkId': u'', u'genre': [u'Drama'], u'airsDayOfWeek': u'Monday', u'runtime': u'55', u'banner': u'graphical/253208-g.jpg', u'id': 253208, u'imdbId': u'tt1322074', u'aliases': []}
INFO:subliminal.refiners.tvdb:Getting series episode 15x18
WARNING:subliminal.refiners.tvdb:No results for episode
```

Later in the logs:
```
INFO:subliminal.providers.legendastv:Searching title u'csi andel'
```

**Comment by Diaoul** [comment]
What 's the good one on tvdb?

**Comment by ratoaq2** [comment]
id = 72546

**Comment by Diaoul** [comment]
From the filename it's clear subliminal cannot find a clear match on tvdb for this. I think I can reject candidates based on a maximal Levenshtein distance which could be something like `max(int(0.2*len(title)), 2)`
So the match title cannot differ too much from the original title.
Levenshtein distance might not be best suited for that as I don't want words to differ, CSI cannot be CSA.
So maybe use the length of the intersection of the set of words in each titles.

**Comment by ratoaq2** [comment]
Probably you have realised that tvdb response has an `aliases` key that has a list with all known aliases for that show. It's a perfect fit for this case.

The algorithm that you described could still be used to sort entries when there's no simple match with name or aliases

**Comment by Diaoul** [comment]
Please test with latest develop and clear cache. On second thought I think it's best not to do wild guesses and stick with exact matches. Trust the guess.
