### ISSUE TITLE
Problems with DSM 6 . can't open parameters or directories

### ISSUE THREAD

**Issue by kanaweb1** [Diaoul/subliminal#607]
Hi,

I was using subliminal from several years on my nas synology but after a crash, i upgraded it from DSM5 to DSM 6. 
And now I can't write anything in parameters . I found a workaround (I hope) in editing config.ini and it seems to work but I don't know how to edit directories to be scanned. Indeed, when I click on Directories and Add , I can't browse any directory.

Can someone help me ?

Best regards,
Fabrice

**Comment by Diaoul** [comment]
Please report to spksrc

**Comment by kanaweb1** [comment]
Désolé , je ne savais pas où poster ...
J'ai donc posté au bon endroit désormais .
