### ISSUE TITLE
[ltv] ValueError('Not a valid archive')

### ISSUE THREAD

**Issue by fernandog** [Diaoul/subliminal#608]
@ratoaq2
$ subliminal --debug download -l pt-BR -p legendastv /media/SAMSUNG/media/downloaded/series/Better.Call.Saul.S02E07.1080p.HDTV.x264-BRISK.mkv
Collecting videos  [####################################]  100%  /media/SAMSUNG/media/downloaded/series/Better.Call.Saul.S02E07.1080p.HDTV.x264-BRISK.mkvDEBUG:subliminal.cli:Collecting path /media/SAMSUNG/media/downloaded/series/Better.Call.Saul.S02E07.1080p.HDTV.x264-BRISK.mkv
INFO:subliminal.core:Scanning video 'Better.Call.Saul.S02E07.1080p.HDTV.x264-BRISK.mkv' in '/media/SAMSUNG/media/downloaded/series'
DEBUG:subliminal.core:Size is 1940067082
DEBUG:subliminal.core:Computed hashes {'opensubtitles': 'b2afa92b82b45566', 'thesubdb': '4d7d60cb1f944ff7821d97a85a91166f', 'napiprojekt': '2b9646f0d0576bdbbd15328f658a958b'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found resolution 1080p
DEBUG:subliminal.refiners.metadata:Found video_codec h264
DEBUG:subliminal.refiners.metadata:Found audio_codec AC3
DEBUG:subliminal.refiners.metadata:Found embedded subtitle set([<Language [en]>])
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'Better Call Saul'
DEBUG:subliminal.refiners.tvdb:Found 1 results
DEBUG:subliminal.refiners.tvdb:Found result for original series without year
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'193443', u'status': u'Continuing', u'added': u'2013-09-12 09:23:01', u'airsTime': u'10:00 PM', u'network': u'AMC', u'rating': u'TV-14', u'overview': u"We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is \u2018fixer\u2019 Mike Erhmantraut. The series tracks Jimmy's transformation into the man who puts \u2018criminal\u2019 in \u2018criminal lawyer\u2019.", u'lastUpdated': 1459546153, u'id': 273181, u'seriesName': u'Better Call Saul', u'firstAired': u'2015-02-08', u'addedBy': 323281, u'banner': u'graphical/273181-g10.jpg', u'networkId': u'', u'genre': [u'Comedy', u'Crime', u'Drama'], u'airsDayOfWeek': u'Monday', u'runtime': u'45', u'siteRating': 8.8, u'zap2itId': u'EP01863210', u'imdbId': u'tt3032476', u'aliases': []}
INFO:subliminal.refiners.tvdb:Getting series episode 2x7
DEBUG:subliminal.refiners.tvdb:Found episode {u'seriesId': 273181, u'airsAfterSeason': None, u'dvdEpisodeNumber': None, u'productionCode': u'', u'overview': u"When Mike's hand is forced, he can no longer hide his frustration; he and Jimmy work together to keep the peace.", u'thumbAdded': u'2016-03-28 20:48:01', u'episodeName': u'Inflatable', u'airedSeason': 2, u'airsBeforeSeason': None, u'showUrl': u'', u'id': 5551774, u'dvdDiscid': u'', u'filename': u'episodes/273181/5551774.jpg', u'dvdSeason': None, u'writers': [u'Gordon Smith'], u'airedEpisodeNumber': 7, u'absoluteNumber': 17, u'thumbHeight': u'225', u'imdbId': u'tt4462684', u'lastUpdated': 1459454796, u'director': u'Colin Bucksey', u'lastUpdatedBy': 451966, u'dvdChapter': None, u'airsBeforeEpisode': None, u'language': {u'overview': u'en', u'episodeName': u'en'}, u'thumbAuthor': 449963, u'firstAired': u'2016-03-28', u'guestStars': [], u'siteRating': 8.3, u'thumbWidth': u'400'}
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:No need to search
Collecting videos  [####################################]  100%
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Better.Call.Saul.S02E07.1080p.HDTV.x264-BRISK.mkvINFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages set([<Language [pt-BR]>])
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.providers.legendastv:Releases not found in cache
INFO:subliminal.providers.legendastv:Downloading archive 56ff9bc188945
ERROR:subliminal.core:Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py", line 408, in list_subtitles
    return [s for l in languages for s in self.query(l, title, season=season, episode=episode, year=video.year)]
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py", line 368, in query
    self.download_archive(a)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py", line 308, in download_archive
    raise ValueError('Not a valid archive')
ValueError: Not a valid archive
INFO:subliminal.core:Discarding provider legendastv
Downloading subtitles  [####################################]  100%
Some providers have been discarded due to unexpected errors: legendastv
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider legendastv
Downloaded 0 subtitle

**Comment by Diaoul** [comment]
Legendastv returned something that isn't either rar or zip. That's unexpected. What is it?

**Comment by ratoaq2** [comment]
The archive with that id (`56ff9bc188945`) is valid: http://legendas.tv/download/56ff9bc188945
