### ISSUE TITLE
[ltv] HTTPError: 400 Client Error: Bad Request for url:

### ISSUE THREAD

**Issue by fernandog** [Diaoul/subliminal#609]
two issues in one.

@Diaoul why do you discard provider for all following searchers if the issue is in that result only (AuthenticationError i agree is should stop search. but if the error is related to search item, it shouldn't right?). Is it possible to return the error exception when checking if provider is in the discared list? enabling subliminal logs in SickRage would spam the log with unneeded messages for final user. thanks!

@ratoaq2

subliminal --debug download -l pt-BR -p legendastv /media/SAMSUNG/media/downloaded/series/The.100.S03E09.Stealing.Fire.1080p.WEB-DL.DD5.1.H264-RARBG.mkv
Collecting videos  [####################################]  100%  /media/SAMSUNG/media/downloaded/series/The.100.S03E09.Stealing.Fire.1080p.WEB-DL.DD5.1.H264-RARBG.mkvDEBUG:subliminal.cli:Collecting path /media/SAMSUNG/media/downloaded/series/The.100.S03E09.Stealing.Fire.1080p.WEB-DL.DD5.1.H264-RARBG.mkv
INFO:subliminal.core:Scanning video 'The.100.S03E09.Stealing.Fire.1080p.WEB-DL.DD5.1.H264-RARBG.mkv' in '/media/SAMSUNG/media/downloaded/series'
DEBUG:subliminal.core:Size is 1810278210
DEBUG:subliminal.core:Computed hashes {'opensubtitles': 'd79eef41970ac430', 'thesubdb': 'e71e026a917e445c7a47ef3e5d8f6cc8', 'napiprojekt': '71395f3b4ceb5292c1a364b0c2a33b93'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found video_codec h264
DEBUG:subliminal.refiners.metadata:Found audio_codec AC3
DEBUG:subliminal.refiners.metadata:Found embedded subtitle set([<Language [und]>])
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'The 100'
DEBUG:subliminal.refiners.tvdb:Found 48 results
DEBUG:subliminal.refiners.tvdb:Found result for original series without year
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'', u'status': u'Continuing', u'added': u'2013-08-10 11:43:14', u'airsTime': u'', u'network': u'', u'rating': u'', u'overview': u'Planet Earth is stacked with amazing feats of engineering and construction, a dazzling array of machines and vehicles, an awe inspiring great outdoors and a near limitless number super skilled, super humans\r\nWhat we want to know exactly how much of all this we\u2019ve got, where it all is and what it exactly it does\u2026\r\nIn each episode we will carry out the ultimate, exhaustive stock take of that particular category (from skyscrapers to mountains, boats to special forces, railways to fire-fighters\u2026discovering exactly where every single example is located and in doing so answer those questions we have about the world that have never been answered until now.\r\nA fast paced entertaining mix of graphics, archive and location reports together will be the ultimate information countdown.', u'lastUpdated': 1385372430, u'zap2itId': u'', u'seriesName': u'100%', u'siteRating': 0, u'firstAired': u'', u'addedBy': 391110, u'networkId': u'', u'genre': [u'Documentary'], u'airsDayOfWeek': u'', u'runtime': u'1', u'banner': u'graphical/272209-g.jpg', u'id': 272209, u'imdbId': u'', u'aliases': []}
ERROR:subliminal.core:Failed to refine video
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 541, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/refiners/tvdb.py", line 306, in refine
    video.year = datetime.strptime(result['firstAired'], '%Y-%m-%d').year
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
**ValueError: time data '' does not match format '%Y-%m-%d'**

INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:Found 127 results
DEBUG:subliminal.refiners.omdb:Found result for original series without year
DEBUG:subliminal.refiners.omdb:Found series {u'imdbID': u'tt0314970', u'Year': u'1997\u20132001', u'Type': u'series', u'Poster': u'N/A', u'Title': u'100%'}
Collecting videos  [####################################]  100%                                                                                              
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  The.100.S03E09.Stealing.Fire.1080p.WEB-DL.DD5.1.H264-RARBG.mkvINFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages set([<Language [pt-BR]>])
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.providers.legendastv:Searching title u'100%'
ERROR:subliminal.core:Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py", line 408, in list_subtitles
    return [s for l in languages for s in self.query(l, title, season=season, episode=episode, year=video.year)]
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py", line 312, in query
    titles = self.search_titles(sanitize(title))
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1053, in decorate
    should_cache_fn)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 657, in get_or_create
    async_creator) as value:
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/local/lib/python2.7/dist-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 625, in gen_value
    created_value = creator()
  File "/usr/local/lib/python2.7/dist-packages/dogpile/cache/region.py", line 1049, in creator
    return fn(*arg, **kw)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py", line 203, in search_titles
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
**raise HTTPError(http_error_msg, response=self)**
**HTTPError: 400 Client Error: Bad Request for url: http://legendas.tv/legenda/sugestao/100%**
INFO:subliminal.core:Discarding provider legendastv
Downloading subtitles  [####################################]  100%
Some providers have been discarded due to unexpected errors: legendastv
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider legendastv
Downloaded 0 subtitle

**Comment by Diaoul** [comment]
There shouldn't be such uncatched exception that are specific to one search. If so please provide more details.

**Comment by ratoaq2** [comment]
There are 2 issues here:
- You're searching subtitles for "The 100" and the tvdb refiner selected another series "100%". There's another bug open for that.
- The second issue is that the  http://legendas.tv/legenda/sugestao/ doesn't support `%` as a path parameter. That should be encoded or stripped out. I'm not aware of any other series (apart from this `100%` which came from tvdb) that contains `%`. What is interesting is that other characters like `&` doesn't result in a HTTP 400.

**Comment by Diaoul** [comment]
I solved first two issues locally and I am currently writing more tests. The tvdb refiner doesn't work as expected for Marvel's Agents of S.H.I.E.L.D. due to https://github.com/guessit-io/guessit/issues/278.

**Comment by fernandog** [comment]
Ok thanks!

**Comment by Diaoul** [comment]
I think I won't solve the `%` issue, it's really a legendastv issue which you can reproduce in a browser, not subliminal.
Searching for `100` doesn't even return `100%`.

Other issues are solved please use latest develop and clear cache.

**Comment by fernandog** [comment]
@Diaoul this case for example, we are discarding provider because of something related to that search only:

```
INFO:subliminal.providers.legendastv:Searching title u'the americans'
DEBUG:subliminal.providers.legendastv:Found 4 titles
INFO:subliminal.providers.legendastv:Getting archives for title 40227 and language 1
DEBUG:subliminal.providers.legendastv:Found 7 archives
INFO:subliminal.providers.legendastv:Releases not found in cache
INFO:subliminal.providers.legendastv:Downloading archive 570708aada394
ERROR:subliminal.core:Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py", line 437, in list_subtitles
    return [s for l in languages for s in self.query(l, title, season=season, episode=episode, year=video.year)]
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py", line 397, in query
    self.download_archive(a)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py", line 333, in download_archive
    raise ValueError('Not a valid archive')
ValueError: Not a valid archive
INFO:subliminal.core:Discarding provider legendastv
Downloading subtitles  [####################################]  100%
Some providers have been discarded due to unexpected errors: legendastv
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider legendastv
Downloaded 0 subtitle
```
