### ISSUE TITLE
Unable to detect episode

### ISSUE THREAD

**Issue by CyberMew** [Diaoul/subliminal#613]
There is no problem for The.100.S03E08.720p.HDTV.x264-AVS.mkv, but The.100.S03E09.720p.HDTV.x264-AVS.mkv does not work. Here is the debug for that file:

ERROR:subliminal.core:Failed to refine video
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/subliminal/core.py", line 541, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "build/bdist.linux-x86_64/egg/subliminal/refiners/tvdb.py", line 306, in refine
    video.year = datetime.strptime(result['firstAired'], '%Y-%m-%d').year
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d'
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:Found 127 results
DEBUG:subliminal.refiners.omdb:Found result for original series without year
DEBUG:subliminal.refiners.omdb:Found series {u'imdbID': u'tt0314970', u'Title': u'100%', u'Type': u'series', u'Poster': u'N/A', u'Year': u'1997\u20132001'}
Collecting videos  [####################################]  100%                 
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  The.100.S03E09.720p.HDTV.x264-AVS.mkvINFO:subliminal.core:Listing subtitles with provider 'addic7ed' and languages set([<Language [en]>])
INFO:subliminal.core:Initializing provider addic7ed
INFO:subliminal.providers.addic7ed:Logging in
DEBUG:subliminal.providers.addic7ed:Logged in
DEBUG:subliminal.providers.addic7ed:Getting show id with year
DEBUG:subliminal.providers.addic7ed:Getting show id
WARNING:subliminal.providers.addic7ed:Series not found in show ids
ERROR:subliminal.providers.addic7ed:No show id found for u'100%' ({'country': None, 'year': 1997})
Downloading subtitles  [####################################]  100%             
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider addic7ed
INFO:subliminal.providers.addic7ed:Logging out
DEBUG:subliminal.providers.addic7ed:Logged out
0 subtitle downloaded for The.100.S03E09.720p.HDTV.x264-AVS.mkv

I'm assuming there is no specific English version that listed AVS, but the KILLERS version exists and the notes did mention compatible with AVS. Either way, I think if no exact version is found, it should download the next best English sub (with HI if option set) available.

edit: I'm doing a check against my whole tv shows folder, and addic7ed is telling me to come back later (too many requests), but I've only downloaded 40 subtitles within 2 hours (or a day) instead of 80. Not sure how that would would trigger it.

update: still have issue finding for this episode. Also, is there any chance that it is querying addic7ed for each file more than once?

**Comment by Diaoul** [comment]
Please test with latest master and make sure to clear cache (`subliminal cache --clear-subliminal` with CLI)

**Comment by CyberMew** [comment]
I assume you mean develop branch. git pulled, cache cleared, and tested with E10:

INFO:subliminal.core:Scanning video 'The.100.S03E10.720p.HDTV.x264-AVS.mkv' in '/mnt/user/TV Shows/US/Series/The 100'
DEBUG:subliminal.core:Size is 1217228521
DEBUG:subliminal.core:Computed hashes {'opensubtitles': '7ec9a774f0b2c634', 'thesubdb': '0ac30cb592c9d449bd07b8b3c1a14a76', 'napiprojekt': '2d5731b8630e40ff3f0ddf1e80d47b49'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found resolution 720p
DEBUG:subliminal.refiners.metadata:Found video_codec h264
DEBUG:subliminal.refiners.metadata:Found audio_codec AC3
DEBUG:subliminal.refiners.metadata:MKV has no subtitle track
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'The 100'
DEBUG:subliminal.refiners.tvdb:Found 48 results
DEBUG:subliminal.refiners.tvdb:Found result for original series without year
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'', u'status': u'Continuing', u'added': u'2013-08-10 11:43:14', u'airsTime': u'', u'network': u'', u'rating': u'', u'overview': u'Planet Earth is stacked with amazing feats of engineering and construction, a dazzling array of machines and vehicles, an awe inspiring great outdoors and a near limitless number super skilled, super humans\r\nWhat we want to know exactly how much of all this we\u2019ve got, where it all is and what it exactly it does\u2026\r\nIn each episode we will carry out the ultimate, exhaustive stock take of that particular category (from skyscrapers to mountains, boats to special forces, railways to fire-fighters\u2026discovering exactly where every single example is located and in doing so answer those questions we have about the world that have never been answered until now.\r\nA fast paced entertaining mix of graphics, archive and location reports together will be the ultimate information countdown.', u'lastUpdated': 1385372430, u'zap2itId': u'', u'seriesName': u'100%', u'siteRating': 0, u'firstAired': u'', u'addedBy': 391110, u'networkId': u'', u'genre': [u'Documentary'], u'airsDayOfWeek': u'', u'runtime': u'1', u'banner': u'graphical/272209-g.jpg', u'id': 272209, u'imdbId': u'', u'aliases': []}
ERROR:subliminal.core:Failed to refine video
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/subliminal/core.py", line 541, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "build/bdist.linux-x86_64/egg/subliminal/refiners/tvdb.py", line 306, in refine
    video.year = datetime.strptime(result['firstAired'], '%Y-%m-%d').year
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d'
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:Found 127 results
DEBUG:subliminal.refiners.omdb:Found result for original series without year
DEBUG:subliminal.refiners.omdb:Found series {u'imdbID': u'tt0314970', u'Year': u'1997\u20132001', u'Type': u'series', u'Poster': u'N/A', u'Title': u'100%'}
Collecting videos  [####################################]  100%                 
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  The.100.S03E10.720p.HDTV.x264-AVS.mkvINFO:subliminal.core:Listing subtitles with provider 'addic7ed' and languages set([<Language [en]>])
INFO:subliminal.core:Initializing provider addic7ed
INFO:subliminal.providers.addic7ed:Logging in
DEBUG:subliminal.providers.addic7ed:Logged in
INFO:subliminal.providers.addic7ed:Getting show ids
DEBUG:subliminal.providers.addic7ed:Found 3842 show ids
DEBUG:subliminal.providers.addic7ed:Getting show id with year
DEBUG:subliminal.providers.addic7ed:Getting show id
WARNING:subliminal.providers.addic7ed:Series not found in show ids
INFO:subliminal.providers.addic7ed:Searching show ids with {'search': u'100%', 'Submit': 'Search'}
WARNING:subliminal.providers.addic7ed:Show id not found: suggestion does not match
ERROR:subliminal.providers.addic7ed:No show id found for u'100%' ({'country': None, 'year': 1997})
Downloading subtitles  [####################################]  100%             
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider addic7ed
INFO:subliminal.providers.addic7ed:Logging out
DEBUG:subliminal.providers.addic7ed:Logged out
0 subtitle downloaded for The.100.S03E10.720p.HDTV.x264-AVS.mkv


Also tested on E09:
DEBUG:subliminal.core:Size is 1339005841
DEBUG:subliminal.core:Computed hashes {'opensubtitles': '2593b81550f420ea', 'thesubdb': '0484b9dd0db9abbf9a0922c9ddc4207a', 'napiprojekt': '10db7be6d768323b7f42184b204044f4'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found resolution 720p
DEBUG:subliminal.refiners.metadata:Found video_codec h264
DEBUG:subliminal.refiners.metadata:Found audio_codec AC3
DEBUG:subliminal.refiners.metadata:MKV has no subtitle track
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'The 100'
DEBUG:subliminal.refiners.tvdb:Found 48 results
DEBUG:subliminal.refiners.tvdb:Found result for original series without year
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'', u'status': u'Continuing', u'added': u'2013-08-10 11:43:14', u'airsTime': u'', u'network': u'', u'rating': u'', u'overview': u'Planet Earth is stacked with amazing feats of engineering and construction, a dazzling array of machines and vehicles, an awe inspiring great outdoors and a near limitless number super skilled, super humans\r\nWhat we want to know exactly how much of all this we\u2019ve got, where it all is and what it exactly it does\u2026\r\nIn each episode we will carry out the ultimate, exhaustive stock take of that particular category (from skyscrapers to mountains, boats to special forces, railways to fire-fighters\u2026discovering exactly where every single example is located and in doing so answer those questions we have about the world that have never been answered until now.\r\nA fast paced entertaining mix of graphics, archive and location reports together will be the ultimate information countdown.', u'lastUpdated': 1385372430, u'id': 272209, u'seriesName': u'100%', u'firstAired': u'', u'addedBy': 391110, u'banner': u'graphical/272209-g.jpg', u'networkId': u'', u'genre': [u'Documentary'], u'airsDayOfWeek': u'', u'runtime': u'1', u'siteRating': 0, u'zap2itId': u'', u'imdbId': u'', u'aliases': []}
ERROR:subliminal.core:Failed to refine video
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/subliminal/core.py", line 541, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "build/bdist.linux-x86_64/egg/subliminal/refiners/tvdb.py", line 306, in refine
    video.year = datetime.strptime(result['firstAired'], '%Y-%m-%d').year
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d'
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:Found 127 results
DEBUG:subliminal.refiners.omdb:Found result for original series without year
DEBUG:subliminal.refiners.omdb:Found series {u'imdbID': u'tt0314970', u'Title': u'100%', u'Type': u'series', u'Poster': u'N/A', u'Year': u'1997\u20132001'}
Collecting videos  [####################################]  100%                 
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  The.100.S03E09.720p.HDTV.x264-AVS.mkvINFO:subliminal.core:Listing subtitles with provider 'addic7ed' and languages set([<Language [en]>])
INFO:subliminal.core:Initializing provider addic7ed
INFO:subliminal.providers.addic7ed:Logging in
DEBUG:subliminal.providers.addic7ed:Logged in
DEBUG:subliminal.providers.addic7ed:Getting show id with year
DEBUG:subliminal.providers.addic7ed:Getting show id
WARNING:subliminal.providers.addic7ed:Series not found in show ids
ERROR:subliminal.providers.addic7ed:No show id found for u'100%' ({'country': None, 'year': 1997})
Downloading subtitles  [####################################]  100%             
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider addic7ed
INFO:subliminal.providers.addic7ed:Logging out
DEBUG:subliminal.providers.addic7ed:Logged out
0 subtitle downloaded for The.100.S03E09.720p.HDTV.x264-AVS.mkv

**Comment by ratoaq2** [comment]
You're not using the latest develop

Looking at your traceback I can see this part (tvdb.py line 306):
`File "build/bdist.linux-x86_64/egg/subliminal/refiners/tvdb.py", line 306, in refine`

And the latest develop tvdb.py line 306 is just a return:
https://github.com/Diaoul/subliminal/blob/develop/subliminal/refiners/tvdb.py#L306

**Comment by CyberMew** [comment]
My bad. I forgot to reinstall setup.py after the pull. Seems to be working now but I'm getting too many requests error for addic7ed (I'm getting these quite often for no reason), so can't download subtitle for testing. Will report back if it doesn't work. Thank you all!
