### ISSUE TITLE
Problem with Addic7ed authentication

### ISSUE THREAD

**Issue by PhunkyBob** [Diaoul/subliminal#616]
Hello,

I haven't changed my password for Addic7ed, and my account is still valid, but when I make a search, I have the following error:

[http://pastebin.com/exrwnBQt](url)

**Comment by Diaoul** [comment]
This part hasn't changed for a while, [see for yourself](https://github.com/Diaoul/subliminal/blame/develop/subliminal/providers/addic7ed.py#L96-L110). I believe that's either a temporary but in addic7ed or addic7ed blocking you or subliminal.

**Comment by CyberMew** [comment]
Addic7ed working well for me using login.

**Comment by SeeDborg** [comment]
I have the same error than @PhunkyBob
