### ISSUE TITLE
why can't i go further then 30days of movie date?

### ISSUE THREAD

**Issue by ward0** [Diaoul/subliminal#618]
Like subject is asking.. I have movies that are older and subliminal doesn't download them :(

**Comment by Diaoul** [comment]
I'm not sure I understand the question. There is no limit on date unless you specify an `--age` parameter.

**Comment by ward0** [comment]
I'm on a synology , in the general parameters i have this parameter:
http://www.synology-forum.nl/download-mods/subliminal-9605/?action=dlattach;attach=600;image

Maximum age(in days), if i go further then 30 days i get the message that a max of 30 is allowed.

**Comment by Diaoul** [comment]
Please report to spksrc
