### ISSUE TITLE
Log error: movie skipped

### ISSUE THREAD

**Issue by Rebsiont** [Diaoul/subliminal#620]
Hey Diaoul and others

I got a little issue with subliminal (love the program tho dude really thnx for that :p )
but I have alot of older movies (older than 30days) and subliminal wont download subs for those movies... Is there a way to bypass that rule of subliminal?
Or can you add it in the next release that we can chose that for ourselfs cause I want subs for all my movies ofc :)

Kind regards

**Comment by ratoaq2** [comment]
Please take a look here: #618 

I think you have the same issue and it's related to another github repository: https://github.com/SynoCommunity/spksrc/issues/1561

**Comment by Rebsiont** [comment]
thnx @ratoaq2
