### ISSUE TITLE
Caching strategy for legendastv provider

### ISSUE THREAD

**Issue by ratoaq2** [Diaoul/subliminal#624]
Removing caching when listing archives
 > when an episode or a movie is released, you'll have a growing list of archives for the next couple of days. If we cache this URL (carrega_legendas_busca_filme) we might wait for a long time to get a subtitle that was added after your initial search. This page **doesn't** show an episode list. It shows subtitles list and caching it for days 3 days (EPISODE_EXPIRATION_TIME) is not appropriate.

Changing release names cache to 15 min
>It's a common practice that the uploaders re-upload the archivers adding more releases to it. And that happens in a high frequency for the first couple of days after the release. This cache should be invalidated when the archive changes; or its expiration time should be short.

Related PR: #612 

I've created issues for each PR that I have submitted to keep track and a open discussion since they are blocking me to use legendastv provider on my daily tasks. I'm really looking forward for the 2.0 release with all the great features that were added. Really good work :+1:

**Comment by miigotu** [comment]
@ratoaq2 if you want I can add you to the SickRage/subliminal repo so we can combine efforts. That way we can iron out the details and get the better changes into SickRage a bit sooner (and tested a bit more before they are merged upstream). And won't have dupe PR's either =P
