### ISSUE TITLE
Download from subscenter is not working

### ISSUE THREAD

**Issue by myakove** [Diaoul/subliminal#625]
Collecting videos  [####################################]  100%                          
10 videos collected / 0 video ignored / 0 error
Downloading subtitles  [###---------------------------------]   10%  DCs.Legends.of.Tomorrow.S01E03.720p.HDTV.X264-DIMENSION.mkvINFO:subliminal.api:Listing subtitles with provider 'subscenter' and languages set([<Language [he]>])
INFO:subliminal.api:Initializing provider subscenter
DEBUG:subliminal.providers.subscenter:Logging in
INFO:subliminal.providers.subscenter:Logged in
INFO:subliminal.providers.subscenter:Searching title name for u'DCs Legends of Tomorrow'
DEBUG:subliminal.providers.subscenter:Found 0 suggestions
DEBUG:subliminal.providers.subscenter:Getting the list of subtitles
ERROR:subliminal.api:Unexpected error in provider 'subscenter', discarding it
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/subliminal/api.py", line 116, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "/usr/lib/python2.7/site-packages/subliminal/providers/subscenter.py", line 212, in list_subtitles
    return [s for s in self.query(series, season, episode, title) if s.language in languages]
  File "/usr/lib/python2.7/site-packages/subliminal/providers/subscenter.py", line 169, in query
    r.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: http://subscenter.cinemast.com/he/cinemast/data/series/sb/None/1/3/
Downloading subtitles  [#######-----------------------------]   20%  0d 00:00:09  DCs.Legends.of.Tomorrow.S01E10.720p.HDTV.X264-DIMENSION.mkvDEBUG:subliminal.api:Skipping discarded provider 'subscenter'
Downloading subtitles  [##########--------------------------]   30%  0d 00:00:08  DCs.Legends.of.Tomorrow.S01E02.720p.HDTV.X264-DIMENSION.mkvDEBUG:subliminal.api:Skipping discarded provider 'subscenter'
Downloading subtitles  [##############----------------------]   40%  0d 00:00:07  DCs.Legends.of.Tomorrow.S01E05.720p.HDTV.X264-DIMENSION.mkvDEBUG:subliminal.api:Skipping discarded provider 'subscenter'
Downloading subtitles  [##################------------------]   50%  0d 00:00:06  DCs.Legends.of.Tomorrow.S01E08.720p.HDTV.X264-DIMENSION.mkvDEBUG:subliminal.api:Skipping discarded provider 'subscenter'
Downloading subtitles  [#####################---------------]   60%  0d 00:00:05  DCs.Legends.of.Tomorrow.S01E06.720p.HDTV.X264-DIMENSION.mkvDEBUG:subliminal.api:Skipping discarded provider 'subscenter'
Downloading subtitles  [#########################-----------]   70%  0d 00:00:04  DCs.Legends.of.Tomorrow.S01E07.720p.HDTV.X264-DIMENSION.mkvDEBUG:subliminal.api:Skipping discarded provider 'subscenter'
Downloading subtitles  [############################--------]   80%  0d 00:00:03  DCs.Legends.of.Tomorrow.S01E04.720p.HDTV.X264-DIMENSION.mkvDEBUG:subliminal.api:Skipping discarded provider 'subscenter'
Downloading subtitles  [################################----]   90%  0d 00:00:02  DCs.Legends.of.Tomorrow.S01E09.720p.HDTV.X264-DIMENSION.mkvDEBUG:subliminal.api:Skipping discarded provider 'subscenter'
Downloading subtitles  [####################################]  100%  DCs.Legends.of.Tomorrow.S01E01.720p.HDTV.X264-DIMENSION.mkv             DEBUG:subliminal.api:Skipping discarded provider 'subscenter'
Downloading subtitles  [####################################]  100%                                                                          
DEBUG:subliminal.api:Terminating initialized providers
INFO:subliminal.api:Terminating provider subscenter
INFO:subliminal.providers.subscenter:Logging out
INFO:subliminal.providers.subscenter:Logged out
Downloaded 0 subtitle

**Comment by Diaoul** [comment]
Fixed with 70a647813bf0f58f0cdcc3fcae0d7e3387d6d6bd
