### ISSUE TITLE
Error in series identification in tvdb

### ISSUE THREAD

**Issue by SkipCool33** [Diaoul/subliminal#627]
Hello,
I've got a bug when searching some subtitle for the 100 serie.
When I search in the tvdb website, I found the good one : id 268592 with the same name :
http://thetvdb.com/?tab=series&id=268592&lid=7
In debug log, it seems to be identify as "100%" : id 272209.

Extract from debug log

INFO:subliminal.refiners.tvdb:Searching series 'The 100'
DEBUG:subliminal.refiners.tvdb:Found 48 results
DEBUG:subliminal.refiners.tvdb:Found result for original series without year
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'', u'status': u'Continuing', u'added': u'2013-08-10 11:43:14', u'airsTime': u'', u'network': u'', u'rating': u'', u'overview': u'Planet Earth is stacked with amazing feats of engineering and construction, a dazzling array of machines and vehicles, an awe inspiring great outdoors and a near limitless number super skilled, super humans\r\nWhat we want to know exactly how much of all this we\u2019ve got, where it all is and what it exactly it does\u2026\r\nIn each episode we will carry out the ultimate, exhaustive stock take of that particular category (from skyscrapers to mountains, boats to special forces, railways to fire-fighters\u2026discovering exactly where every single example is located and in doing so answer those questions we have about the world that have never been answered until now.\r\nA fast paced entertaining mix of graphics, archive and location reports together will be the ultimate information countdown.', u'lastUpdated': 1385372430, u'zap2itId': u'', u'seriesName': u'100%', u'siteRating': 0, u'firstAired': u'', u'addedBy': 391110, u'networkId': u'', u'genre': [u'Documentary'], u'airsDayOfWeek': u'', u'runtime': u'1', u'banner': u'graphical/272209-g.jpg', u'id': 272209, u'imdbId': u'', u'aliases': []}
ERROR:subliminal.core:Failed to refine video
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 541, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/refiners/tvdb.py", line 306, in refine
    video.year = datetime.strptime(result['firstAired'], '%Y-%m-%d').year
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d'

Any help ? Anything to do to have the right show ? Thanks :)

**Comment by ratoaq2** [comment]
This issue should be already fixed by the latest development version as is related to the issue described here: #609
