### ISSUE TITLE
Addic7ed is not getting the subtitles for some series

### ISSUE THREAD

**Issue by lodoss5** [Diaoul/subliminal#633]
Hi,
First, thanks for this beautiful tool.
I am using subliminal lib from last version of sickrage (https://github.com/SickRage/SickRage). I compared addic7ed.py and file from my sickrage is the same that the one on subliminal master repo.
I configured it to use my account on addic7ed site and my profile on this site is configured to display subtitles of all languages.
It works pretty well except for 2 series where it gets nothing for both my languages (FR, EN) while there are files on addic7ed for the languages with same release group:
- The 100 - id=268592
- Scandal (2012) - id=248841

Log shows it didn't find any file:
```
2016-04-11 22:23:29 DEBUG    Thread-13 :: 248841: No subtitles downloaded for Scandal (2012) S05E15
2016-04-11 22:23:29 DEBUG    Thread-13 :: No subtitles found for Scandal (2012) S05E15
2016-04-11 22:18:13 DEBUG    Thread-13 :: Checking subtitle candidates for Scandal (2012) S05E15 (Scandal.US.S05E15.SDTV-lol.mp4)
```

**Comment by lodoss5** [comment]
Last update of Sickrage fixed my issue.
I am now very happy :)

**Comment by lodoss5** [comment]
Issue is back with last commit "Update subliminal to 14707b6"
https://github.com/SickRage/SickRage/commit/079958e620920214e79fb42944306c64ae83d0ed

**Comment by lodoss5** [comment]
Maybe issue is different this time.
For "The.Flash.2014.S02E22.SDTV-lol.mkv", I get following log:
2016-05-25 09:40:36 DEBUG Thread-13 :: [addic7ed] Subtitle score for updated/8/112311/0 is: 100 (min=198)
While subtitle on Addic7ed looks perfect:
2	22	Invincible	French	LOL	Completed		✔	✔	Download

**Comment by Diaoul** [comment]
Please report to SickReage or see [Contributing rules](https://github.com/Diaoul/subliminal/blob/master/CONTRIBUTING.md). I need debug logs.
