### ISSUE TITLE
Subliminal automator workflow on mac os x to auto download srt from specific folder

### ISSUE THREAD

**Issue by ankitduseja** [Diaoul/subliminal#638]
I am looking for a way to auto download srt files using subliminal on mac os x. Can someone share an automator workflow or an alternative for this?
##

**Comment by jesperryom** [comment]
1. Open Automator and choose _Folder Action_
2. Choose a folder via the dropdown menu -> _Other..._
3. Add a _Run Shell Script_-action (search for "shell script" in the search bar to the left)
4. Clear and add this: **/usr/local/bin/subliminal download -l en "$@"** (assuming you want english subs)
5. Set _Pass input_ to _as arguments_
6. Save and you're done. The script triggers every time you place a new file/folder in the chosen folder.

**Comment by thagorastos** [comment]
I would prefer this as a Quick Action as it would allow selecting a folder(s) or file(s) from Finder.

1. Open Automator, select Quick Action
2. Set Workflow receives current '_files and folders_' in _Finder_
3. Add a _Run Shell Script-action_ (search for "shell script" in the search bar to the left)
4. Clear and add this: /usr/local/bin/subliminal download -l en "$@" (assuming you want english subs)
5. Set Pass input to as _arguments_
6. Save it and name it

![Screenshot 2020-05-05 at 12 11 47 PM](https://user-images.githubusercontent.com/5054585/81051117-dcab3580-8ec9-11ea-9fea-f36cf633d7a0.jpg)


Now, every time you open Finder you can select one or more files or/and folder, right click the selection and go to Quick Actions -> [whatever you named the quick action in step 6]
