### ISSUE TITLE
Subliminal not using guessit 2.X

### ISSUE THREAD

**Issue by Con7e** [Diaoul/subliminal#641]
Hello,

Would it be possible to update subliminal to use guessit 2.X?

**Comment by pchaigno** [comment]
[The `develop` branch is already using guessit 2.X](https://github.com/Diaoul/subliminal/blob/develop/setup.py#L30), so I'm guessing it'll be shipped in the next 2.0 release.

**Comment by Diaoul** [comment]
Duplicate #550
