### ISSUE TITLE
Any way to leave out the .en. ?

### ISSUE THREAD

**Issue by p1r473** [Diaoul/subliminal#643]
I run TVRenamer as a daily task to clean up my TV shows that were downloaded. It renames the subtitles to the exact same filename as the TV show itself, except with .srt instead of whatever extension the movie was.
However, when I run subliminal the next day, it redownloads the subtitles, because TVRenamer got rid of the .en extension, and subliminal thinks the file hasn't been downloaded yet

Even if it were not for TVRenamer, I would still wish for a way to not have .en attached to my subtitles. I only use english and I want to clean it up by not displaying what language it is downloaded in... because I dont use any other languages, I dont need to see that it is .en

Thanks

**Comment by Diaoul** [comment]
Yes it's possible, use the `--single` or `-s` option. Also search close issues this has been asked many times.

**Comment by p1r473** [comment]
When I try to do DownloadSubtitles.py --single it doesn't seem to work. Are you talking about using the script with the command or am I missing something?

**Comment by Diaoul** [comment]
I'm not the author of that script so I cannot answer that. Please ask the author of DownloadSubtitles.py.

**Comment by p1r473** [comment]
Do you know who the author is?
