### ISSUE TITLE
Problem with 'solid' rar files

### ISSUE THREAD

**Issue by ratoaq2** [Diaoul/subliminal#644]
```
commit 67a48e07a2246a798abc52ec6cbb64be7fee4cbb
Author: Antoine Bertin <diaoulael@gmail.com>
Date:   Thu Apr 14 01:13:59 2016 +0200

    Use original series name for tvdb refiner
```

When executing:
`subliminal --legendastv user pass download -f -l pt-BR -p legendastv -m 97 Once.Upon.a.Time.S01E01.720p.HDTV.X264-DIMENSION.mkv`

We get the following exception:
```
ERROR:subliminal.core:Unexpected error in provider 'legendastv', discarding it
Traceback (most recent call last):
  File "/home/user/workspace/git/subliminal/subliminal/core.py", line 171, in download_subtitle
    self[subtitle.provider_name].download_subtitle(subtitle)
  File "/home/user/workspace/git/subliminal/subliminal/providers/legendastv.py", line 448, in download_subtitle
    subtitle.content = fix_line_ending(subtitle.archive.content.read(subtitle.name))
  File "build/bdist.linux-x86_64/egg/rarfile.py", line 657, in read
    f = self.open(fname, 'r', psw)
  File "build/bdist.linux-x86_64/egg/rarfile.py", line 642, in open
    return self._open_unrar(self.rarfile, inf, psw)
  File "build/bdist.linux-x86_64/egg/rarfile.py", line 1189, in _open_unrar
    raise ValueError("Cannot use unrar directly on memory buffer")
ValueError: Cannot use unrar directly on memory buffer
WARNING:subliminal.core:Provider 'legendastv' is discarded
WARNING:subliminal.core:Provider 'legendastv' is discarded
```

When looking at `rarfile.py:636` source:
```
        # now extract
        if inf.compress_type == RAR_M0 and (inf.flags & RAR_FILE_PASSWORD) == 0:
            return self._open_clear(inf)
        elif use_hack:
            return self._open_hack(inf, psw)
        else:
            return self._open_unrar(self.rarfile, inf, psw)
```
The last condition can only extract real files (no in-memory file like)

The file that leads to this error: `http://legendas.tv/download/03ae4d4d7b3fb193ce58ca4abcb946dc`

I cannot say how many files can lead to this problem, but they are very rare in legendastv. After long time, this is the first one that I encountered.

**Comment by ratoaq2** [comment]
In this case, the problem happens when the rarfile is solid:

`rarfile.py:625
```
        elif self._main.flags & (RAR_MAIN_SOLID | RAR_MAIN_PASSWORD):
            use_hack = 0
```

**Comment by Diaoul** [comment]
Do you have a suggested fix for this? I think the error isn't clear, it works for most archives from in memory streams and in this case it doesn't. It should be up to rarfile to keep a consistent API and save this memory stream somewhere and do the job or at least give users means to know this beforehand.

**Comment by ratoaq2** [comment]
I agree that rarfile API should be consistent. Right now it's a rare case, so I don't know if you're willing to have a workaround for it or just wait for a reply/feedback from markokr/rarfile.

If you go for a workaround, I would say to check the flags and just skip the file.

**Comment by Coacher** [comment]
Hello.

rarfile-2.8 was released a couple of days ago.
It supports solid rar files: https://github.com/markokr/rarfile/commit/e51d6aaf868b7bfa9bb760bf8a3a81ac811bbb60

**Comment by Diaoul** [comment]
Great news!

**Comment by Diaoul** [comment]
I think this is fixed with latest rarfile.

**Comment by Coacher** [comment]
Shouldn't setup.py have minimum rarfile version bumped?

**Comment by Diaoul** [comment]
For requirements I focus on API compatibility. I cannot keep track of every bug on every dependency.

**Comment by Coacher** [comment]
@Diaoul, fair enough. Thanks for the reply.
