### ISSUE TITLE
List if subtitles are already present

### ISSUE THREAD

**Issue by CyberMew** [Diaoul/subliminal#647]
Currently, when searching normally we get something like these:
0 subtitle downloaded for Brooklyn.Nine-Nine.S03E23.720p.HDTV.x264-AVS.mkv
0 subtitle downloaded for The.Flash.2014.S02E18.720p.HDTV.X264-DIMENSION.mkv
0 subtitle downloaded for Supergirl.S01E20.720p.HDTV.X264-DIMENSION-BUYMORE.mkv

However, some of them already previous have subtitles, and it would be great to know if those files already have the external/embedded subtitle in them already, so we don't attempt to redownload the subtitles again. I'm hoping if more information is present, or don't even show 0 subtitle downloaded text if they have no need to download. i.e. to show the user difference between 0 download due to subtitles not uploaded, or if subtitles are already detected to be present.
##

**Comment by ratoaq2** [comment]
Fixed by 7b55bc0196247e7911a7e12e456adbf5e0c985c1

```
subliminal --debug download --provider opensubtitles --refiner tvdb --language en "Charmed (2018) - s01e08 - Bug A Boo.mkv"
DEBUG:subliminal.cli:Collecting path Charmed (2018) - s01e08 - Bug A Boo.mkv
DEBUG:subliminal.core:Found subtitles {'Charmed (2018) - s01e08 - Bug A Boo.en.srt': <Language [en]>}
DEBUG:subliminal.core:All languages set([<Language [en]>]) exist
0 video collected / 0 video ignored / 0 error
```
