### ISSUE TITLE
Download again on better match

### ISSUE THREAD

**Issue by MrJackJonesIII** [Diaoul/subliminal#648]
Hi,
I'm not sure if this might already been handled in any way but I can't find any information about it. I'd like to have subliminal download the best matching subtitle in a first step and have it look for a even better match later. Sometimes when I watch an episode there will be a sub available but not for the exact release. So I will have to adjust the timing and so on. If I watch the episode a day later there might be a better matching sub available but I will already have downloaded the inferior one the day before. So... Is there any way to tell subliminal to go have a second look for a better match and download that over the previous one? 
Thanks!

**Comment by Diaoul** [comment]
No, there's currently no way to do that because subliminal doesn't store subtitles metadata. .srt cannot be used to store metadata as there are no comment inside. One way to do it would be to have an sqlite database to store this kind of stuff.

**Comment by MrJackJonesIII** [comment]
In my case I guess it would be sufficient to just force the new search and download whatever match it gets then. I don't have that many new episodes and my age filter is set to 7 days. I understand there is this -force option for downloading the sub again. But as I understand from some info from the plex subliminal plugin subliminal is not gonna search again in that case but will just download the same release again.

**Comment by Diaoul** [comment]
It depends on how it is implemented by the Plex developer but as a library force means that a new search will be triggered.

**Comment by MrJackJonesIII** [comment]
Ok, thanks for that info! I'll try it with -force then for the time being. And thanks for your hard work on this software. Working great here.
