### ISSUE TITLE
Removed provider - Itasa

### ISSUE THREAD

**Issue by RDgiuliom** [Diaoul/subliminal#649]
Hi, I sadly noticed that less than a month after Itasa provider addition, it has been removed. Is there a particular reason? It worked like a charm in SickRage until it suddenly disappeared.

Thanks.

**Comment by Diaoul** [comment]
It was never added in subliminal, only in SickRage, ask SickRage developers.

**Comment by RDgiuliom** [comment]
SickRage developers told me to ask you 😂️

Ok I'll get back on the other repo.

Thanks
