### ISSUE TITLE
Subliminal Nautilus error installing

### ISSUE THREAD

**Issue by theman480** [Diaoul/subliminal#650]
Im using:

```
wget https://raw.githubusercontent.com/Diaoul/nautilus-subliminal/master/install.sh -O - | sudo sh
```
 to install the nautilus subliminal but i have the following error everytime:

`Installing python requirements...
Collecting subliminal>=2.0 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement subliminal>=2.0 (from -r requirements.txt (line 1)) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 1.0, 1.0.1, 1.1, 1.1.1, 2.0rc1)
No matching distribution found for subliminal>=2.0 (from -r requirements.txt (line 1))
Error: failed to install requirements
`

OS is ubuntu 15.10, any help please?

**Comment by Diaoul** [comment]
2.0 isn't released yet so nautilus integration is pending for 2.0. I will release this week.

**Comment by theman480** [comment]
Ok, thank you Diauol, i love your tool.

Is there anyway to add a subtitle provider from my country? Like Legendas.tv?
