### ISSUE TITLE
Cosmetic: Missing newline after "Progress bar"

### ISSUE THREAD

**Issue by fernandog** [Diaoul/subliminal#655]
Using: subliminal, version 2.0.rc1

Progress bar its not adding adding `newline` making the next log message in the same line as progress bar

https://github.com/Diaoul/subliminal/blob/develop/subliminal/cli.py#L395

Downloading subtitles  [##----------------------------------]    6%  *.S01E01.1080p.WEB-DL.DD5.1.H.264-Abc.mkvINFO:subliminal.core:Listing subtitles with provider '*' and languages set([<Language [*]>])

**Comment by Diaoul** [comment]
I think you should report this to click but I don't know if adding a newline character would solve the issue without other consequences. Have you tried it?

**Comment by fernandog** [comment]
Im not sure how to fix it
If "Listing subtitles" its always the next log line maybe adding a new line before "\nListing subtitles"

**Comment by Diaoul** [comment]
If you want to dissociate debug logs from output, save it to a file: `subliminal --debug [...] 2> debug.log`
