### ISSUE TITLE
Please ship nautilus extension in the tarball

### ISSUE THREAD

**Issue by emillon** [Diaoul/subliminal#656]
Hello,

I am making a Debian package for the nautilus extension (see [this Debian bug](https://bugs.debian.org/821455)), but the `examples/` directory is not present in the tarball present on pypi, so it cannot be used directly.

Can you please put it in the tarball? This should only be a matter of adding `examples` to `MANIFEST.in`.

(FWIW in the meantime I copied the source and the extension will be in the next version!)

:sparkles: Thanks! :sparkles:

**Comment by Diaoul** [comment]
For 2.0 I've separated the nautilus part from subliminal itself. It's now in its own repository: https://github.com/Diaoul/nautilus-subliminal
2.0 will be released within a few weeks.

Let me know if that suits your needs.

**Comment by emillon** [comment]
Sure, if there are no 1.x releases planned then this totally works!
