### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by theman480** [Diaoul/subliminal#657]
Hello diaoul, any news about the 2.0 ? I really want to use the nautilus integration, thank you in advice!

**Comment by anderbytes** [comment]
I'm also looking forward to this... so many improvements...

**Comment by felipesalomao** [comment]
I also would like to knowthat  because legendas.tv  subtitle support..

**Comment by martinp** [comment]
`pip` supports installing directly from a Git repository, so if you want the latest changes from the `develop` branch, you can do:
`pip install -U git+https://github.com/Diaoul/subliminal.git@develop`

**Comment by Diaoul** [comment]
I wanted to release earlier but work kept me really busy lately. I plan to release next week.

**Comment by Diaoul** [comment]
:tada:
