### ISSUE TITLE
Make aliases available to be used by providers

### ISSUE THREAD

**Issue by ratoaq2** [Diaoul/subliminal#659]
This is a **feature request** to make aliases information available to be used by providers.

The [use case](https://github.com/pymedusa/SickRage/issues/505) is `Marverl's Agents of S.H.I.E.L.D` in LegendasTv provider.

Legendas.TV website data is not consistent. Some Marvel's series doesn't have `Marvel's` in their name, others do. Some of them use `Marvels`, others use `Marvel's`.

MAoS can only be searched using its alias: `Agents of S.H.I.E.L.D`
http://legendas.tv/legenda/sugestao/agents%20of%20s.h.i.e.l.d
Using its official name `Marvel's Agents of S.H.I.E.L.D` returns no result
http://legendas.tv/legenda/sugestao/marvel's%20agents%20of%20s.h.i.e.l.d

But `Marvel's Jessica Jones` can be search using the official name:
http://legendas.tv/legenda/sugestao/marvel's%20jessica%20jones

My suggestion is to enrich the video object with aliases information when running tvdb refiner, so any provider can make use of them when needed (e.g.: when no series search result is found)
##

**Comment by fernandog** [comment]
this will be good at Medusa/SickRage because we store `scene exceptions` for each show

**Comment by h3llrais3r** [comment]
A similar use case would be aliases for release groups.
Certain subtitles of 1 release group will always be in sync with another release group (example: LOL and DIMENSION)
If aliases could be defined on release group level, it would also improve the matching.
This is certainly useful where subliminal is used in library mode and certain criteria must match before a subtitle is downloaded. If for example a subtitle is available under 'LOL' but the not under 'DIMENSION', it would be nice that 'DIMENSION' is also matched for 'LOL'. 
So making it possible to provide 'aliases' for certain video fields would be a good idea.
@ratoaq2 If you think it's not related to your case, I'll create a separate issue for it :wink:

**Comment by Diaoul** [comment]
Yes please create a separate issue for release groups. This should be done in scoring I think with some exception logic. Alias is overkill here and cannot cover all the possibilities.

As for making the aliases available, that's a good idea indeed. Some properties like `alternative_titles` for Movie and `alternative_series` for Episode would do I think.

**Comment by Diaoul** [comment]
Are aliases unique? I don't want to flood the servers with 5+ aliases searches that will sometimes end up returning no result.
I'm not sure subliminal needs fixing here, the provider does. At least a search should return the correct series.

**Comment by ratoaq2** [comment]
The providers will unlikely be changed (e.g.: legendastv website).
I didn't check tvdb to see how often series have aliases.
Subliminal providers could make use of aliases only when no series/tv show information is found using the main/official title. That way it will not flood the servers and it will handle these exceptional cases.

**Comment by fernandog** [comment]
the aliases are also for scene releases. We call that `scene_exception` in sickbeard/Medusa

like: `TURN: Washington's Spies` and `TURN`
