### ISSUE TITLE
Big problem

### ISSUE THREAD

**Issue by theman480** [Diaoul/subliminal#662]
So i m using subliminal 2.0, trying to install the nautilus integration .
But i have the following error;
`  Could not find a version that satisfies the requirement subliminal>=2.0 (from -r requirements.txt (line 1)) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 1.0, 1.0.1, 1.1, 1.1.1, 2.0rc1)
No matching distribution found for subliminal>=2.0 (from -r requirements.txt (line 1))
`

**Comment by Diaoul** [comment]
See #650
