### ISSUE TITLE
Scoring calculation

### ISSUE THREAD

**Issue by h3llrais3r** [Diaoul/subliminal#664]
Would it be possible to change the values of the video scoring?
Currently the following scores are used:

`episode_scores = {'hash': 215, 'series': 108, 'year': 54, 'season': 18, 'episode': 18, 'release_group': 9,
                  'format': 4, 'audio_codec': 2, 'resolution': 1, 'hearing_impaired': 1, 'video_codec': 1}`

`movie_scores = {'hash': 71, 'title': 36, 'year': 18, 'release_group': 9,
                'format': 4, 'audio_codec': 2, 'resolution': 1, 'hearing_impaired': 1, 'video_codec': 1}`

I have a problem with the hearing_impaired score. I would like to have it the lowest score. This means that no other video property should have an equal score.

I am using subliminal in api mode and I can configure which video properties must match before the subtitle is downloaded.
I also have an option to indicate if I want to download hearing_impaired subs or not. If enabled, they can be donwloaded, but no preference. If disabled, they should not be downloaded. Therefore, I'm putting the flag to false, which will add a match when the subtitle is not hearing impaired and increase the score with 1.
However, since the score is 1, it can also be considered a video_codec or resolution match, which messes up required video properties to match.

I hope it's a bit clear what I like to accomplish. This was working fine with the previous version (<2.0.0) . I now have this problem because the hearing_impaired is included in the scoring algorithm.

It would be nice if the default scoring could be adapted. IMHO a non video property should always have a lower score than a video property so it couldn't influence the matching.
The non video property (hearing_impaired) should only be used to increase the score with 1 if required.
-> hearing_impaired can stay 1
-> resolution and video_codec should become 2
-> recalculate the rest...

Is this feasible or are there other ways?

**Comment by pannal** [comment]
Thanks for the changes. What are the most sane minimum scores for TV series and movies compared to subliminal v1?

Sub-Zero currently uses (with V1) 23 for movies and 85 for series.


Thank you in advance!

**Comment by h3llrais3r** [comment]
This is how I'm using it: https://github.com/h3llrais3r/Auto-Subliminal/commit/1dc13045dc3eb96d5fd2139b0da39177cf5a9c26

See the changes in autosubliminal/config.py
