### ISSUE TITLE
ImportError: No module named dogpile.util.readwrite_lock

### ISSUE THREAD

**Issue by luigino** [Diaoul/subliminal#669]
I think [this](https://github.com/Diaoul/subliminal/blob/master/subliminal/cli.py#L18) should be
`from dogpile.core.readwrite_lock import ReadWriteMutex`
instead.

**Comment by Diaoul** [comment]
You need to update dogpile.cache to 0.6.0. It's in the requirements.

**Comment by Diaoul** [comment]
See 5d28f1497883cec52e1d48cf63f64610534fe682
