### ISSUE TITLE
Subliminal has to be run as root or crash

### ISSUE THREAD

**Issue by Kia0ra** [Diaoul/subliminal#674]
Hi,

I am having a weird issue with subliminal 2.0.3 running on Raspbian Jessie.
Subliminal crash when I run it as a normal user 
`pi@rpi ~ $ subliminal --version
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 7, in <module>
    from subliminal.cli import subliminal
  File "/usr/local/lib/python2.7/dist-packages/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 13, in <module>
    from guessit import guessit
ImportError: cannot import name guessit
`

But works fine when run run as root 
`pi@rpi ~ $ sudo subliminal --version
subliminal, version 2.0.3
`
Thanks for your help

**Comment by Diaoul** [comment]
It seems you are missing some dependencies as your normal user.

**Comment by Kia0ra** [comment]
Hmm weird, it was working perfectly fine a few weeks ago.
I fix it using by installing it true : `pip install --user subliminal` but I am not really pleased as I would like to install it system wide / for all users.

**Comment by Diaoul** [comment]
Not sure there is anything I can do here, something's wrong with your setup somehow.
