### ISSUE TITLE
Subliminal should consider a valid match when audio_codec in AC3, DolbyDigital

### ISSUE THREAD

**Issue by ratoaq2** [Diaoul/subliminal#677]
This is a subtle bug.

For the latest subliminal (2.0.3) and latest guessit (2.0.5):

Given the following release name:
`Show Name S09E17 Episode Title 720p WEB-DL DD5.1 H.264-Group.mkv`

guessit will guess `audio_codec=DolbyDigital`:

```
episode "Show Name S09E17 Episode Title 720p WEB-DL DD5.1 H.264-Group.mkv"
For: Show Name S09E17 Episode Title 720p WEB-DL DD5.1 H.264-Group.mkv
GuessIt found: {
    "title": "Show Name", 
    "season": 9, 
    "episode": 17, 
    "episode_title": "Episode Title", 
    "screen_size": "720p", 
    "format": "WEB-DL", 
    "audio_codec": "DolbyDigital", 
    "audio_channels": "5.1", 
    "video_codec": "h264", 
    "release_group": "Group", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}
```

But metadata refiner in subliminal will refine the video and it will change the audio codec to AC3:

```
Scanning video Show Name S09E17 Episode Title 720p WEB-DL DD5.1 H.264-Group.mkv...
Scanning video 'Show Name S09E17 Episode Title 720p WEB-DL DD5.1 H.264-Group.mkv' in '/library/series/Show Name/Season 09'
Size is 623365155
Computed hashes {'itasa': '2c513d0db9f0c8956d31b0db0794a12e', 'opensubtitles': '25cfac4916a6c550', 'shooter': 'da6834f15e3ac2cf49a4ad58a533ef86;c208e6628389e0ac22743c3bc2dce53d;391b136e34ef4cc464cfe5d125891bf8;3da5a8c2106c499e2fee15b1d58afef3', 'thesubdb': '5798326df09752cf0e077fde122cdd75', 'napiprojekt': '2c513d0db9f0c8956d31b0db0794a12e'}
Refining video with metadata
Found video_codec h264
Found audio_codec AC3
Found embedded subtitle set([<Language [und]>])
```

The video object has its audio_codec changed to AC3, but the subtitle in each provider will be guessed using the release name (which will lead to DolbyDigital) and audio_codec will never match.

Hope my explanation is not too confuse.
##

**Comment by Diaoul** [comment]
Nice catch indeed. What is your suggested fix? Maybe not changing the audio_codec with the metadata refiner if it is already here would help.

**Comment by ratoaq2** [comment]
IMO, it shouldn't overwrite existing values.
But I don't know why guessit considers AC3 and DolbyDigital two different things. Aren't they the same thing?

The match should consider AC3 equivalent to DD as well. Imagine that you have a renamed file without any codec information, only series title, season and episode info. Then metadata refiner will enhance the video information correctly, but when the subtitle score is computed there will be no audio_codec match.

**Comment by Diaoul** [comment]
If they are the same, shouldn't guessit report them as the same and return AC3 when it finds DolbyDigital in the filename?

**Comment by Toilal** [comment]
I'm not sure I understand, but it seems guessit only finds DolbyDigital from the filename, and from what I can read it seems valid.

Then Subliminal finds AC3 by reading file content metadata.

But I do agree @ratoaq2, I think data refiner should be used only if guessit didn't found any value for `audio_codec` / `video_codec`.

**Comment by ratoaq2** [comment]
My first assumption is that AC3 and DolbyDigital are actually the same thing (as far as I know. but I'm not an expert here). If they aren't the same thing, they refers to the same thing. Like x264 and h264 where guessit returns `h264`: where the second one is the video_codec and the first one is the encoder name.

If that's true, then guessit should always return 1 of them. I would say that AC3 and DD should always return `AC3`

The other discussion is: should the refiner overwrite the values that are already present in the video object? I believe so (since the real video file always have more accurate information), The cons: if you mislabel a release, the refiner will always use the correct info from the video, but the subtitle will always have the wrong information from the release name, which affects proper subtitle scoring.

Still, I don't have a strong opinion on these 2 topics.

**Comment by Toilal** [comment]
I've just created this issue : https://github.com/guessit-io/guessit/issues/330

From what I can read on wikipedia, it seems you are right : DolbyDigital seems to be some kind of commercial name for AC3 encoding.

**Comment by fernandog** [comment]
@ratoaq2 is this fixed now after guessit 330?

**Comment by ratoaq2** [comment]
Fixed with guessit 3
