### ISSUE TITLE
INFO:subliminal.core:Skipping provider 'addic7ed': no language to search for

### ISSUE THREAD

**Issue by CyberMew** [Diaoul/subliminal#683]
> ....
> INFO:subliminal.core:Refining video with metadata
> DEBUG:subliminal.refiners.metadata:Found resolution 720p
> DEBUG:subliminal.refiners.metadata:Found video_codec h264
> DEBUG:subliminal.refiners.metadata:Found audio_codec AC3
> DEBUG:subliminal.refiners.metadata:Found embedded subtitle set([<Language [en]>])
> INFO:subliminal.core:Refining video with tvdb
> INFO:subliminal.refiners.tvdb:Searching series 'Dark Matter'
> DEBUG:subliminal.refiners.tvdb:Found 2 results
> DEBUG:subliminal.refiners.tvdb:Found exact match on series u'Dark Matter'
> DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'', u'rating': u'TV-14', u'overview': u'The six-person crew of a derelict spaceship awakens from stasis in the farthest reaches of space. Their memories wiped clean, they have no recollection of who they are or how they got on board. The only clue to their identities is a cargo bay full of weaponry and a destination: a remote mining colony that is about to become a war zone. With no idea whose side they are on, they face a deadly decision. Will these amnesiacs turn their backs on history, or will their pasts catch up with them?', u'firstAired': u'2015-06-13', u'id': 292174, u'aliases': [], u'networkId': u'', u'network': u'Space', u'zap2itId': u'EP02164263', u'seriesName': u'Dark Matter', u'status': u'Continuing', u'added': u'2015-02-16 15:46:41', u'imdbId': u'tt4159076', u'lastUpdated': 1471083307, u'addedBy': 63541, u'genre': [u'Drama', u'Mystery', u'Science-Fiction'], u'banner': u'graphical/292174-g2.jpg', u'airsTime': u'10:00 PM', u'siteRatingCount': 50, u'airsDayOfWeek': u'Friday', u'runtime': u'45', u'siteRating': 8.3}
> INFO:subliminal.refiners.tvdb:Getting series episode 2x8
> DEBUG:subliminal.refiners.tvdb:Found episode {u'seriesId': 292174, u'airsAfterSeason': None, u'dvdEpisodeNumber': 8, u'productionCode': u'', u'overview': u'A Blink Drive test goes awry, propelling the Raza to a parallel reality.', u'airedSeasonID': 648603, u'thumbAdded': u'', u'episodeName': u'Stuff to Steal, People to Kill', u'airedSeason': 2, u'airsBeforeSeason': None, u'showUrl': u'', u'id': 5443966, u'dvdDiscid': u'', u'filename': u'', u'dvdSeason': 2, u'writers': [], u'airedEpisodeNumber': 8, u'absoluteNumber': 21, u'thumbHeight': None, u'imdbId': u'tt5578258', u'lastUpdated': 1471434806, u'director': u'', u'lastUpdatedBy': 348094, u'dvdChapter': None, u'airsBeforeEpisode': None, u'language': {u'overview': u'en', u'episodeName': u'en'}, u'thumbAuthor': 1, u'siteRatingCount': 0, u'directors': [], u'firstAired': u'2016-08-19', u'guestStars': [], u'siteRating': 0, u'thumbWidth': None}
> INFO:subliminal.core:Refining video with omdb
> DEBUG:subliminal.refiners.omdb:No need to search
> Collecting videos  [####################################]  100%
> 
> 1 video collected / 0 video ignored / 0 error
> Downloading subtitles  [####################################]  100%  Dark.Matter.S02E08.720p.HDTV.x264-FLEET.mkvINFO:subliminal.core:Skipping provider 'addic7ed': no language to search for
> Downloading subtitles  [####################################]  100%  
> DEBUG:subliminal.core:Terminating initialized providers
> 0 subtitle downloaded for Dark.Matter.S02E08.720p.HDTV.x264-FLEET.mkv

`subliminal --debug --addic7ed username password download "pathtodarkmatterhere" -p addic7ed -l en -v -hi -a 2d`

Unable to get subtitle for this file:  Dark.Matter.S02E08.720p.HDTV.x264-FLEET.mkv

This is the addic7ed site it's getting from: http://www.addic7ed.com/serie/Dark_Matter/2/8/Stuff_to_Steal%2C_People_to_Kill

This started happening since several episodes back, not sure what is the issue

**Comment by Diaoul** [comment]
I cannot reproduce this. I think this might be related to #684. Please try with latest develop.

What I think happened is that the video as added to the list of videos to search subtitles for despite the fact that there was already an external subtitle due to the aforementioned bug.
Then the filesystem was searched and an external subtitle found for English language.
When addic7ed is triggered, there is no language left to search for as an external English subtitle was present.

**Comment by CyberMew** [comment]
It was a new episode, there wasn't any subtitles. I had to manually add it. I will try again with latest develop and see. Thanks!

**Comment by CyberMew** [comment]
Seems to work with the new episode released today, thank you for the fix :+1:  Will monitor how it goes

**Comment by CyberMew** [comment]
I'm getting this same error for: Dark.Matter.S02E11.720p.HDTV.x264-FLEET.mkv

`1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Dark.Matter.S02E11.720p.HDTV.x264-FLEET.mkvINFO:subliminal.core:Skipping provider 'addic7ed': no language to search for
Downloading subtitles  [####################################]  100%             
`
Which is funny because only FLEET existed on there currently, and I had the SVA version and it downloaded fine.

**Comment by Diaoul** [comment]
Which version are you using? This was fixed a few days ago.

**Comment by CyberMew** [comment]
7eb7a53fe6bcaf3e01a6b44c8366faf7c96f7f1b

**Comment by Diaoul** [comment]
Please give more details: https://github.com/Diaoul/subliminal/blob/master/CONTRIBUTING.md

**Comment by CyberMew** [comment]
> DEBUG:subliminal.cli:Collecting path /mnt/user/TV Shows/Dark Matter/Dark.Matter.S02E11.720p.HDTV.x264-FLEET.mkv
> INFO:subliminal.core:Scanning video 'Dark.Matter.S02E11.720p.HDTV.x264-FLEET.mkv' in '/mnt/user/TV Shows/Dark Matter'
> DEBUG:subliminal.core:Size is 1030768130
> DEBUG:subliminal.core:Computed hashes {'thesubdb': 'be57f697f859eab6e7963141bfb3ff3d', 'opensubtitles': 'f8149a8884b01dcc', 'shooter': 'a157cd6575592fe8b9f141de1a6bc3ef;300340f564f228b0a93ba1d27b91b730;228aebab92f2015be828aabb473f3616;52bbf2138f5ead959e44ada1c041d6fa', 'napiprojekt': '988427957fda65eff721cb7471d53646'}
> DEBUG:subliminal.core:Found subtitles {}
> INFO:subliminal.core:Refining video with metadata
> DEBUG:subliminal.refiners.metadata:Found resolution 720p
> DEBUG:subliminal.refiners.metadata:Found video_codec h264
> DEBUG:subliminal.refiners.metadata:Found audio_codec AC3
> DEBUG:subliminal.refiners.metadata:Found embedded subtitle set([<Language [en]>])
> INFO:subliminal.core:Refining video with tvdb
> INFO:subliminal.refiners.tvdb:Searching series 'Dark Matter'
> DEBUG:subliminal.refiners.tvdb:Found 2 results
> DEBUG:subliminal.refiners.tvdb:Found exact match on series u'Dark Matter'
> DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'', u'rating': u'TV-14', u'overview': u'The six-person crew of a derelict spaceship awakens from stasis in the farthest reaches of space. Their memories wiped clean, they have no recollection of who they are or how they got on board. The only clue to their identities is a cargo bay full of weaponry and a destination: a remote mining colony that is about to become a war zone. With no idea whose side they are on, they face a deadly decision. Will these amnesiacs turn their backs on history, or will their pasts catch up with them?', u'firstAired': u'2015-06-13', u'id': 292174, u'aliases': [], u'networkId': u'', u'network': u'Space', u'zap2itId': u'EP02164263', u'seriesName': u'Dark Matter', u'status': u'Continuing', u'added': u'2015-02-16 15:46:41', u'imdbId': u'tt4159076', u'lastUpdated': 1473539038, u'addedBy': 63541, u'genre': [u'Drama', u'Mystery', u'Science-Fiction'], u'banner': u'graphical/292174-g2.jpg', u'airsTime': u'10:00 PM', u'siteRatingCount': 56, u'airsDayOfWeek': u'Friday', u'runtime': u'45', u'siteRating': 8.2}
> INFO:subliminal.refiners.tvdb:Getting series episode 2x11
> DEBUG:subliminal.refiners.tvdb:Found episode {u'seriesId': 292174, u'airsAfterSeason': None, u'dvdEpisodeNumber': 11, u'productionCode': u'', u'overview': u'The crew races against time to track down and locate a missing Three and Five before the Galactic Authority gets to them first.', u'airedSeasonID': 648603, u'thumbAdded': u'2016-09-09 23:37:32', u'episodeName': u"Wish I'd Spaced You When I Had the Chance", u'airedSeason': 2, u'airsBeforeSeason': None, u'showUrl': u'', u'id': 5595978, u'dvdDiscid': u'', u'filename': u'episodes/292174/5595978.jpg', u'dvdSeason': 2, u'writers': [u'Joseph Mallozzi'], u'airedEpisodeNumber': 11, u'absoluteNumber': 24, u'thumbHeight': u'225', u'imdbId': u'tt5716584', u'lastUpdated': 1473518327, u'director': u'Mairzee Almas', u'lastUpdatedBy': 375826, u'dvdChapter': None, u'airsBeforeEpisode': None, u'language': {u'overview': u'en', u'episodeName': u'en'}, u'thumbAuthor': 345634, u'siteRatingCount': 0, u'directors': [u'Mairzee Almas'], u'firstAired': u'2016-09-09', u'guestStars': [], u'siteRating': 0, u'thumbWidth': u'400'}
> INFO:subliminal.core:Refining video with omdb
> DEBUG:subliminal.refiners.omdb:No need to search
> INFO:subliminal.core:Skipping provider 'addic7ed': no language to search for
> DEBUG:subliminal.core:Terminating initialized providers
> 

pip list

> appdirs (1.4.0)
> babelfish (0.5.5)
> beautifulsoup4 (4.5.1)
> chardet (2.3.0)
> click (6.6)
> dogpile.cache (0.6.2)
> enzyme (0.4.1)
> futures (3.0.5)
> git-remote-helpers (0.1.0)
> guessit (2.0.5)
> pbr (1.10.0)
> pip (8.1.2)
> pyOpenSSL (0.15.1)
> pysrt (1.1.1)
> python-dateutil (2.5.1)
> pytz (2016.6.1)
> rarfile (2.8)
> rebulk (0.7.3)
> requests (2.11.1)
> setuptools (26.1.1)
> six (1.10.0)
> stevedore (1.17.1)
> subliminal (2.1.0.dev0)

**Comment by Diaoul** [comment]
What command line did you use exactly?

**Comment by CyberMew** [comment]
`subliminal --debug --addic7ed user pass download /mnt/user/TV\ Shows/Dark\ Matter/Dark.Matter.S02E11.720p.HDTV.x264-FLEET.mkv -p addic7ed -l en -v -hi -a 2d`

`subliminal --debug --addic7ed user pass download /mnt/user/TV\ Shows/Dark\ Matter/ -p addic7ed -l en -v -hi -a 2d`

(you might need to adjust the 2d accordingly since 2 days has already passed)

Curious to know if it worked for you using the same command line and pip setup

**Comment by ratoaq2** [comment]
This issue is related to embedded subtitles. Your video has an embedded english subtitle: 

` DEBUG:subliminal.refiners.metadata:Found embedded subtitle set([<Language [en]>])`

And since you're not using `--force`, subliminal is assuming that there's no remaining language:
`INFO:subliminal.core:Skipping provider 'addic7ed': no language to search for`

 So it's not related to Addic7ed.
