### ISSUE TITLE
--force-if-better parameter for the CLI

### ISSUE THREAD

**Issue by woulf** [Diaoul/subliminal#685]
In order for a CRON job to properly work it would be nice to have a parameter for the CLI that would replace the already downloaded subtitle only if subliminal find a better one (IE: better score).
Therefore, if a better subtitle is released after some days, and you haven't watched the file you'll end up with the best subtitle, without flooding the providers with downloads (only with requests).

**Comment by Diaoul** [comment]
There is no way to reliably store metadata (like score, provider, etc.) on a SubRip file. I'm working on a universal subtitle file format converter and better integration within subliminal and plan to support VTT on which I can store metadata.

Another solution would be to integrate this within the CLI module only and maintain a database of downloaded subtitles with their information. This would allow plenty additional features but is kinda out of scope for the basic CLI that subliminal provides.

Yet another solution is to make a web interface for subliminal with those kind of features.

**Comment by getzze** [comment]
Closing for now, it would be better to implement this feature in another package.
