### ISSUE TITLE
test_opensubtitles.py: CannotOverwriteExistingCassetteException: No match for the request

### ISSUE THREAD

**Issue by Coacher** [Diaoul/subliminal#687]
Hello.

It seems that issue #666 has returned. I can reproduce the following testsuite results with Python-3.5:
- subliminal-2.0.3: [PASS](http://bpaste.net/show/2f24cdc4c680)
- subliminal-2.0.4: [PASS](http://bpaste.net/show/2ca1d50f5476)
- subliminal-2.0.5: [FAIL](http://bpaste.net/show/d8c0e896fb25)
- subliminal-git @ 7eb7a53 [PASS](http://bpaste.net/show/9361195d54fa)

None of python packages were changed or updated between the tests.

Please fix.

**Comment by Diaoul** [comment]
This is because the cassettes on the master branch are made for v2.1 and the version is still v2.0.

**Comment by Coacher** [comment]
Ok, but this leads to problems with distros that run packages' testsuites regularly, e.g. Gentoo.
Could you please fix this problem for 2.0.x series (unless you are planning to release 2.1 soon)?

**Comment by Diaoul** [comment]
Fixed by dd74383d1cba82829ce720f2e439a65d13ffe7ef

**Comment by Coacher** [comment]
Could you please make another 2.0.x release with this change? It's a rather big commit to backport.
I was hoping before that you'll make 2.1.x release somewhat soon, but it didn't happen (which is fine :)).
