### ISSUE TITLE
Kodi

### ISSUE THREAD

**Issue by firewater2** [Diaoul/subliminal#708]
Anyone uses Subliminal along with Kodi? Because [this is my experience](https://github.com/vayan/autosub-mpv/issues/1).

I run Windows.

**Comment by Diaoul** [comment]
I'm not sure I understand the issue. I use Kodi and can perfectly play videos with subtitles that are downloaded by subliminal.

Now if you try to automate download of subtitles with Kodi, that's not a subliminal issue but a problem within your integration.

**Comment by firewater2** [comment]
The issue is that I can't download the subtitles when I open the video from Kodi. If I open the video from the File Explorer with MPV and download the subtitle, and then I open it on Kodi, of course it works. It's the process of opening it with Kodi, and then running the subliminal script that collides.

I've now asked the developers of Kodi, of the script, and of subliminal, and nobody seems to have an answer. I blame this on Kodi, but they're devs never listen to these sort of concerns "because why not just use our awful integrated player and use that instead of this Rube Goldberg machine!", so before I get stuck forever, I'll ask here one more time: can you try opening a video from Kodi, with MPV as the external player, and then successfully run the script linked on my first post?
