### ISSUE TITLE
pt-BR extension

### ISSUE THREAD

**Issue by brenosabino** [Diaoul/subliminal#711]
Is it possible to specify every pt-BR subtitle to output as ".por" extension instead of "pt-BR"? That way my Plex server understands it as "Portuguese" instead of "Unknown", I know that the Sub-Zero channel is supposed to fix this issue but it's not working for me for subtitles inserted externally.

**Comment by duramato** [comment]
`por` is pt-PT not pt-BR

**Comment by brenosabino** [comment]
I know, but since Plex doesn't support the pt-BR code I would need to treat it as pt-PT and rename it to ".por". Right now the only solution would be to run a renamer in a scheduled job.

**Comment by Diaoul** [comment]
You can rename it manually after you run subliminal, if you rename the subtitle to .por you will loose the country information and it will be considered as Portuguese and thus downloaded again when you run subliminal the second time as Portuguese (Brazil) will be missing.
