### ISSUE TITLE
Script / Cron Help

### ISSUE THREAD

**Issue by brenosabino** [Diaoul/subliminal#716]
I need to write a bash script that will search for a folder check all files with .mkv .avi or .mp4 extension then check if it has a file with the same name but the lang.srt extension next to it and if not run subliminal for that specific video file. And a cron job that will run that script once an hour.

Could anyone help me with that?

I know that for searching the video and executing the command would be something like that

`#!/bin/sh
find /mnt/data/tv/ \( -iname "*.mkv" -or -iname "*.avi" -or -iname "*.mp4" \) -exec subliminal -l pt-BR -- "{}" \;​`

And the cron would be something like

`0 * * * * sh /mnt/data/tvsubs.sh`

I just need to filter out the specific files I need so subliminal only runs for the necessary files.
Also would be nice to exclude certain folders that I know that doesnt have subtitles available for them.

**Comment by Diaoul** [comment]
Subliminal already does all that by default. Please refer to the documentation: http://subliminal.readthedocs.io/en/latest/user/usage.html#cli.

Also every hour is overkill and will likely get you banned from subtitles providers. I suggest you run that once or twice a day and use the `--age` parameter.
