### ISSUE TITLE
Check if is Movie or TV Show

### ISSUE THREAD

**Issue by luco** [Diaoul/subliminal#717]
Hey guys, thanks for this awesome script.
I was thinking, is there a way to check if the video is a Movie or a TV Show?

Also, is refining really necessary? I mean, it takes long time to me.

Thanks!

**Comment by ratoaq2** [comment]
A Video is either a Movie object or a Episode object. You can differentiate them with isinstance() 

Like the providers, you can choose which refiners to use in the command line or via subliminal config file
