### ISSUE TITLE
Subtitle search not working for "This is Us"

### ISSUE THREAD

**Issue by brenosabino** [Diaoul/subliminal#718]
I have the latest develop branch installed and its not working for one of the shows called "This is Us" the tvdb refiner is looking up to "This is" only, heres the debug:

`
Collecting videos  [####################################]  100%  This.Is.Us.S01E02.1080p.WEB-DL.DD5.1.H264-RARBG[rarbg].mkv
DEBUG:subliminal.cli:Collecting path This.Is.Us.S01E02.1080p.WEB-DL.DD5.1.H264-RARBG[rarbg].mkv
INFO:subliminal.core:Scanning video 'This.Is.Us.S01E02.1080p.WEB-DL.DD5.1.H264-RARBG[rarbg].mkv' in ''
DEBUG:subliminal.core:Size is 1813427403
DEBUG:subliminal.core:Computed hashes {'thesubdb': '505474ccadbe3b466a3c04babe164277', 'opensubtitles': '1a23db8567e81e02', 'shooter': 'dcd3b85ced83cdb705323b17520d52b8;41d7f02e9fe19d244f400d6a1a6d44cd;1de9c83c60683252c18b4f2e537d3bff;bb60ccab85f274f82814e31ee4545e8b', 'napiprojekt': 'f2a73ed5e140c1a29d2185ea5e4d8f4d'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found resolution 1080p
DEBUG:subliminal.refiners.metadata:Found video_codec h264
DEBUG:subliminal.refiners.metadata:Found audio_codec AC3
DEBUG:subliminal.refiners.metadata:Found embedded subtitle set([<Language [und]>])
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'This Is'
DEBUG:subliminal.refiners.tvdb:Found 43 results
DEBUG:subliminal.refiners.tvdb:Discarding series name u'This is Your Life' mismatch on year 1955
ERROR:subliminal.refiners.tvdb:No matching series found
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:Found 97 results
WARNING:subliminal.refiners.omdb:No matching series found
Collecting videos  [####################################]  100%
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  This.Is.Us.S01E02.1080p.WEB-DL.DD5.1.H264-RARBG[rarbg].mkvINFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages set([<Language [pt-BR]>])
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.providers.legendastv:Logging in
DEBUG:subliminal.providers.legendastv:Logged in
Downloading subtitles  [####################################]  100%
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider legendastv
INFO:subliminal.providers.legendastv:Logging out
DEBUG:subliminal.providers.legendastv:Logged out
0 subtitle downloaded for This.Is.Us.S01E02.1080p.WEB-DL.DD5.1.H264-RARBG[rarbg].mkv

`

**Comment by fernandog** [comment]
Issue from guessit:
https://github.com/guessit-io/guessit/issues/358

**Comment by ratoaq2** [comment]
Create an `options.json` or `options.yaml` file in `<user_home>/.config/guessit/` or `<user_home>/.guessit/`


options.json
```
{
  "expected_title": [
    "This is Us"
  ]
}
```

options.yaml:
```
expected_title:
  - This is Us
```

Or a `guessit.options.json` or `guessit.options.yaml` (with same contents as above) in the current directory when running subliminal
