### ISSUE TITLE
Support for YIFY Movies

### ISSUE THREAD

**Issue by skypce** [Diaoul/subliminal#726]
Hi, will be great if you add as source : 
http://www.yifysubtitles.com/

I use popcorntime community edition (is is a application for watch movies) and sadly do not have the option for download the subtitle. 
http://popcorntime.ag/
Happy new year.

**Comment by dufferzafar** [comment]
Yeah, having support for YIFY subtitles would be great. The other subs usually have sync issues when played with YTS movies.

**Comment by ratoaq2** [comment]
Same as #363
