### ISSUE TITLE
Guessit usage for Plex environment

### ISSUE THREAD

**Issue by pannal** [Diaoul/subliminal#732]
Please use `guessit(path, options={})` in `subliminal/core.py:380`. With `options=None` argparse tries to interpret custom argv contents induced by Plex environment, and fails, such as:

```
['--server-version', '1.3.3.3148-b38628e', '/bulk/Library/Application Support/Plex Media Server/Plug-ins/Sub-Zero.bundle']
```

**Comment by Diaoul** [comment]
I don't think this is the intended behavior, guessit should not try to parse args within the library API. /cc @Toilal your opinion?

**Comment by pannal** [comment]
Oh noes, guessit is dead!

**Comment by Toilal** [comment]
I just woke up from my tomb and performed this [commit](https://github.com/guessit-io/guessit/commit/3fd27df36fc7ce94753ef12d8fc4c139866664a0) that fix the issue.

While waiting the next release, using `options={}` is the right workaround.

**Comment by pannal** [comment]
Thanks!
