### ISSUE TITLE
Install stuck at Collecting guessit>=2.0.1 (from subliminal)

### ISSUE THREAD

**Issue by schumi2004** [Diaoul/subliminal#734]
I'm installing Subliminal on a new Synology using python (2.7) virtualenv but during install it's stuck at 

Collecting guessit>=2.0.1 (from subliminal)
  Using cached guessit-2.1.1.tar.gz

It's there for 15 minutes now without any progress.
Any ideas?

**Comment by h3llrais3r** [comment]
Can you try with guessit=2.0.5?
I run it in my tool with this version and it's working fine.

**Comment by ratoaq2** [comment]
I believe the issue is not related to subliminal, most probably some local environment issue
