### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by Ganfoud** [Diaoul/subliminal#738]
I'm using subliminal through cli and crop, and suddenly I started having an error message without having changed anything in the configuration. However, it seems that the subtitles are correctly downloaded at the end. 
Here is the message:

/usr/local/lib/python2.7/dist-packages/subliminal/refiners/omdb.py:162: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  results = [r for r in results if sanitize(r['Title']) == sanitize(video.title)]
/usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py:351: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if sanitize(t['title']) != sanitize(title):
/usr/local/lib/python2.7/dist-packages/subliminal/providers/podnapisi.py:69: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if video.title and sanitize(self.title) == sanitize(video.title):
/usr/local/lib/python2.7/dist-packages/subliminal/subtitle.py:224: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if video.title and 'title' in guess and sanitize(guess['title']) == sanitize(video.title):

**Comment by Ganfoud** [comment]
here is the full debug log:
http://chopapp.com/#x2e5hkat
[debug.txt](https://github.com/Diaoul/subliminal/files/816277/debug.txt)
let me know if you need more!

**Comment by fernandog** [comment]
podnapisi should be fixed in develop. they changed their search to allow unicode
