### ISSUE TITLE
CLI docker help

### ISSUE THREAD

**Issue by G1zm0** [Diaoul/subliminal#739]
I'm trying to run subliminal in a docker on my synology

This is the command I use:
`docker run --rm --name subliminal -v subliminal_cache:/subliminal/cache -v /tvshows:/tvshows -it diaoulael/subliminal download -l nl "/video/Serie/Grimm/Season 06/Grimm.S06E01.720p.HDTV.x264-AVS.mkv"`

This is the response:
`docker: Error response from daemon: stat /tvshows: no such file or directory.`
But I have no idea were the `/tvshows:/tvshows` stands for.

Generally: What is the command to run subliminal from a docker?

**Comment by Diaoul** [comment]
This is the correct command but you need to mount the appropriate volume inside the docker container. That's the `-v /tvshows:/tvshows` part. This will mount /tvshows on your NAS to /tvshows inside the docker container. I don't think this is appropriate in your case.
See the relevant help section: https://docs.docker.com/engine/tutorials/dockervolumes/

Given your command, I think this would work:
```
docker run --rm --name subliminal -v subliminal_cache:/subliminal/cache -v /video/Serie:/tvshows -it diaoulael/subliminal download -l nl "/tvshows/Grimm/Season 06/Grimm.S06E01.720p.HDTV.x264-AVS.mkv"
```

**Comment by G1zm0** [comment]
Thanks, this did the trick.
It will create a seperate container every time this command is called.
I'm now finetuning this to close the container and add the age and provider info.

**Comment by Diaoul** [comment]
This is not a problem to create a container each time as you replace the old one with the same name anyway (`--rm`). You can add the rest of the command at the end.
```
docker run --rm --name subliminal -v subliminal_cache:/subliminal/cache -v /video/Serie:/tvshows -it diaoulael/subliminal
```
Is just a replacement for plain old `subliminal` CLI, try `--help` ;)

**Comment by G1zm0** [comment]
I'm used to working with version 0.7.5 so this is a huge upgrade. (this is a compliment :-) )

For your information I found out that the -it arg works in cli, but you need the -i when using this in a cron

**Comment by G1zm0** [comment]
This issue can be closed it is working as it schould.
I have a task scheduler running that calls the script.
The command looks like this:
`sudo docker run --rm --name subliminal -v subliminal_cache:/subliminal/cache -v /path/to/video:/tvshows -i diaoulael/subliminal download -l nl -a 2w -v -v "/tvshows/"`
