### ISSUE TITLE
Failed to refine video

### ISSUE THREAD

**Issue by digadri** [Diaoul/subliminal#741]
After message:

`Downloading subtitles  [####################################]  100%      `  

system continues freeze for 5 minutes

After CONTROL  + C, these message are displayed

`ERROR:subliminal.core:Failed to refine video`

`ERROR:subliminal.core:Unexpected error in provider 'addic7ed'`

`Some providers have been discarded due to unexpected errors: addic7ed`

Command arguments:

`$ subliminal --debug download -l pt Two\ And\ A\ Half\ Men\ S11E14\ -\ \ Three\ Fingers\ of\ Crème\ de\ Menthe\ -\ Ehhhh.mkv `

[subliminal1.txt](https://github.com/Diaoul/subliminal/files/836469/subliminal1.txt)

**Comment by fernandog** [comment]
i think this will be handled in https://github.com/Diaoul/subliminal/pull/779

**Comment by Diaoul** [comment]
I don't see how those are related, #779 only deals with logs issues, here it seems like tvdb hanged for too long. Maybe some timeout issue?

**Comment by fernandog** [comment]
Oh I see.

**Comment by getzze** [comment]
There has been no response for a long time, this can be closed. Open a new issue if the problem persists.
