### ISSUE TITLE
opensubtitles not working

### ISSUE THREAD

**Issue by dkarnout** [Diaoul/subliminal#745]
I got the following error:
Some providers have been discarded due to unexpected errors: opensubtitles
although the site opensubtitles works.
 
Debug output:
Collecting videos  [####################################]  100%  1961. La Viaccia [Mauro Bolognini].aviDEBUG:subliminal.cli:Collecting path 1961. La Viaccia [Mauro Bolognini].avi  
INFO:subliminal.core:Scanning video '1961. La Viaccia [Mauro Bolognini].avi' in ''
DEBUG:subliminal.core:Size is 693121024
DEBUG:subliminal.core:Computed hashes {'thesubdb': '6f090bac5319f16a3c4026a5f3ba8d92', 'opensubtitles': 'ee109a2a3962ccc1', 'napiprojekt': 'a6fffaafc1d9d1aaab5aa4078ee846eb', 'shooter': '68dce1b0553475f096e32005fc5a4867;852ae5a7d6e4b650f8c4b0d4d96d631a
;6b15a6661b3f5389a7e4148c77afe0b8;3779bd76dd8035c5c6d6df5c418841f7'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Unsupported video extension .avi  
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:Found 1 results
DEBUG:subliminal.refiners.omdb:Found result with matching year
DEBUG:subliminal.refiners.omdb:Found movie {'Year': '1961', 'imdbID': 'tt0056657', 'Title': 'La viaccia', 'Type': 'movie', 'Poster': 'https://images-na.ssl-images-amazon.com/images/M/MV5BYWU3NGIwYTktZjdhYy00ODdhLTkyMzAtOTE2ZWZhZWE1ZjgwXkEyXkFqcGdeQXVyMzYyNjE5NDY@._V1_SX300.jpg'}
Collecting videos  [####################################]  100%
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  1961. La Viaccia [Mauro Bolognini].aviINFO:subliminal.core:Skipping provider 'tvsubtitles': not a valid video
INFO:subliminal.core:Skipping provider 'thesubdb': no language to search for                                                  
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [el]>}                          
INFO:subliminal.core:Initializing provider opensubtitles                                                                      
INFO:subliminal.providers.opensubtitles:Logging in                                                                            
INFO:subliminal.core:Listing subtitles with provider 'podnapisi' and languages {<Language [el]>}                              
INFO:subliminal.core:Initializing provider podnapisi                                                                          
INFO:subliminal.providers.podnapisi:Searching subtitles {'sY': 1961, 'sL': 'el', 'sXML': 1, 'sK': 'La viaccia'}               
INFO:subliminal.core:Skipping provider 'subscenter': no language to search for                                                
INFO:subliminal.core:Skipping provider 'legendastv': no language to search for                                                
INFO:subliminal.core:Skipping provider 'addic7ed': not a valid video                                                          
INFO:subliminal.core:Skipping provider 'shooter': no language to search for                                                   
DEBUG:subliminal.providers.podnapisi:No subtitles found                                                                       
ERROR:subliminal.core:Provider 'opensubtitles' timed out                                                                      
INFO:subliminal.core:Discarding provider opensubtitles                                                                        
Downloading subtitles  [####################################]  100%                                                           
Some providers have been discarded due to unexpected errors: opensubtitles
DEBUG:subliminal.core:Terminating initialized providers                                                                       
INFO:subliminal.core:Terminating provider podnapisi                                                                           
0 subtitle downloaded for 1961. La Viaccia [Mauro Bolognini].avi

**Comment by Wesleyl89** [comment]
Same here

**Comment by n3mur1t0r** [comment]
opensubtitles was down during the weekend, should be working again.

**Comment by leobragatti** [comment]
Hello,
I've tried to use OpenSubtitles, but I've got this message:

```
ERROR:subliminal.utils:Unexpected error. Provider opensubtitles
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/subliminal/core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/local/lib/python3.8/dist-packages/subliminal/core.py", line 67, in __getitem__
    provider.initialize()
  File "/usr/local/lib/python3.8/dist-packages/subliminal/providers/opensubtitles.py", line 129, in initialize
    response = checked(self.server.LogIn(self.username, self.password, 'eng', self.user_agent))
  File "/usr/local/lib/python3.8/dist-packages/subliminal/providers/opensubtitles.py", line 278, in checked
    raise Unauthorized
subliminal.providers.opensubtitles.Unauthorized
INFO:subliminal.core:Discarding provider opensubtitles
Some providers have been discarded due to unexpected errors: opensubtitles
DEBUG:subliminal.core:Terminating initialized providers
```

Anyone can help?

**Comment by avinassh** [comment]
@leobragatti this tip worked for me: https://github.com/Diaoul/subliminal/issues/1008#issuecomment-704756165
