### ISSUE TITLE
How deploy Subliminal heroku (python) and call it from nodejs

### ISSUE THREAD

**Issue by qadirsuh** [Diaoul/subliminal#746]
I have successfully deployed the Subliminal on my heroku app, here is log

`-----> Python app detected
 !     Warning: Your application is missing a Procfile. This file tells Heroku how to run your application.
 !     Learn more: https://devcenter.heroku.com/articles/procfile
-----> Installing requirements with pip
       Obtaining file:///tmp/build_c3865efa1ab82135436227fd159d2d5e/honato11-qSubtitles-6a1f8271001c9e1745484ff50ec90269d4a470f3 (from -r /tmp/build_c3865efa1ab82135436227fd159d2d5e/honato11-qSubtitles-6a1f8271001c9e1745484ff50ec90269d4a470f3/requirements.txt (line 1))
       Installing collected packages: subliminal
       Successfully installed subliminal
-----> Discovering process types
       Procfile declares types -> (none)
-----> Compressing...
       Done: 43.2M
-----> Launching...
       Released v5
       https://qjamesbot-subliminal-subtitles.herokuapp.com/ deployed to Heroku`

Now I want to call the below function
`$ subliminal download -l en the.Matrix.mp4`
from a separate nodeJS process ([child_process](https://nodejs.org/api/child_process.html#child_process_child_process))

Is this possible.

**Comment by qadirsuh** [comment]
I have done it myself.

**Configuration: First**

- I had to create two buildpacks on heroku, snapshot here
http://prntscr.com/exr6yb

- Create a `requirements.txt` file on the root with text containing
`subliminal==2.0.5`

- Define the Profile on the root pointing to your server listing, like in my case.
`web: sh -c 'cd ./heroku/ && node index.js' // web: sh -c 'cd ./dir/ && app_name' `

**Calling Subliminal From Node**

- Here is the code how I have called subliminal from node.
`
'use strict';

const express = require('express');
const app = express();

app.get('/get_subtitles', function (req, res) {

    console.log("get_subtitles : called");
    var movie_name = getFormatedMovie(req.query.movie_name);

    var exec = require('child_process').exec;
    var cmd = 'subliminal download -l en '+movie_name+'.mp4';
    
    exec(cmd, function(error, stdout, stderr) {
        // command output is in stdout
        if(error != null){
            console.log("Error: "+error);
        }else{
            console.log("Output: "+stdout);
        }

    });
    res.send("Downloading in progress...")
})`

and All done.

Issue closed :)

**Comment by moutasem-abdullatif** [comment]
Did you add the python/nodejs code in the same directory? or in different projects ?

**Comment by qadirsuh** [comment]
@moutasem-abdullatif My project is basically nodeJS and do not have any python code. I have called subliminal command in child_process via nodeJs. sample code is given above.
