### ISSUE TITLE
Get subtitles of movie/TV_series via imdb_id

### ISSUE THREAD

**Issue by qadirsuh** [Diaoul/subliminal#747]
How can I get the movie/TV series subtitles using the imdb_id.

I only know the way to download subtitles is. 
`subliminal download -l en the-matrix.mp4`

I know there is something refiners in subliminal lib. I don't know how to use them. I want to download movie/TV_series subtitles by their imdb_id.

**Comment by ratoaq2** [comment]
How would you like to pass the imdb to subliminal?

**Comment by qadirsuh** [comment]
@ratoaq2 thank you for your response after a long time :)
Its basically a question. Can I search/download subtitles by their imdbID rather by movie name?
Something like
`subliminal download -l en imdbid=275458`
where  `imdbid=275458` is imdb ID of a certain movie i.e The Matrix
Is this possible? If yes then how?

**Comment by ratoaq2** [comment]
Currently it's not possible. The whole cli and api design is around folder and file paths.

**Comment by qadirsuh** [comment]
Okay, BTW from where subliminal downloads the subtitles?

**Comment by ratoaq2** [comment]
From multiple providers:
https://subliminal.readthedocs.io/en/latest/user/how_it_works.html#providers
