### ISSUE TITLE
Subtitles downloaded without a match on TV series name even though correct title in filename

### ISSUE THREAD

**Issue by xandian** [Diaoul/subliminal#750]
I've noticed that for some TV series, the wrong subtitles get downloaded. When looking at the extra verbose output I can clearly see that Subliminal couldn't match on the TV series name, which in this case exists in the filename as "Into.the.Badlands".

![image](https://cloud.githubusercontent.com/assets/27766499/25301973/75d9d09c-2733-11e7-8f81-a0c6cc268f3d.png)

I tried adding the release year to the filename, so the TV series name instead would read as "Into.the.Badlands.2015". When running Subliminal on this name the name of the TV series could be matched and the correct subtitles gets downloaded.

![image](https://cloud.githubusercontent.com/assets/27766499/25302002/fc7fea6e-2733-11e7-83e6-7e7a38f3aba6.png)

The hash matching, which I know have been a problem in several other issues here at Github before, is not the issue here. During my testing I got the same problem on the real video file, as well as a blank text file only renamed to "Into.the.Badlands.S02E01.Tiger.Pushes.Mountain.WEBDL-1080p.x264.AC3.tt3865236-RARBG.mkv", to force the match on filename.

The problem here is simply that the release year is needed in the filename for making the match on the TV series name, which is a problem since the TV series name is simply "Into the Badlands", without the release year in the title, on e.g. The TVDB. This simply makes it impossible right now to rename the file automatically with for instance Sonarr, as the release year cannot be forced into the filename during renaming.
I don't know if the fact that two older movies with the title "Into the Badlands" exist on IMDB causes this problem, but Subliminal does recognize both episode and season from the filename, so I think a match should only be made towards TV series anyway.

**Comment by ratoaq2** [comment]
This seems to not be a problem anymore in latest develop:

```
DEBUG:subliminal.cli:Collecting path Into.the.Badlands.S02E01.Tiger.Pushes.Mountain.WEBDL-1080p.x264.AC3.tt3865236-RARBG.mkv
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with hash
WARNING:subliminal.refiners.hash:Size is lower than 10MB: hashes not computed
INFO:subliminal.core:Refining video with metadata
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'Into the Badlands'
DEBUG:subliminal.refiners.tvdb:Found 1 results
DEBUG:subliminal.refiners.tvdb:Found exact match on series u'Into the Badlands'
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'27749', u'rating': u'TV-14', u'overview': u'A mighty warrior and a young boy search for enlightenment in a ruthless territory controlled by feudal barons.', u'firstAired': u'2015-11-15', u'id': 289079, u'aliases': [u'Badlands'], u'networkId': u'', u'network': u'AMC', u'zap2itId': u'SH02278173', u'seriesName': u'Into the Badlands', u'status': u'Continuing', u'added': u'2014-12-07 22:05:02', u'imdbId': u'tt3865236', u'lastUpdated': 1549803030, u'addedBy': 307101, u'genre': [u'Action', u'Drama'], u'banner': u'graphical/289079-g4.jpg', u'slug': u'into-the-badlands', u'airsTime': u'10:00 PM', u'siteRatingCount': 28, u'airsDayOfWeek': u'Sunday', u'runtime': u'45', u'siteRating': 8}
INFO:subliminal.refiners.tvdb:Getting series episode 2x1
1 video collected / 0 video ignored / 0 error
DEBUG:subliminal.refiners.tvdb:Found episode {u'seriesId': 289079, u'airsAfterSeason': None, u'dvdEpisodeNumber': 1, u'productionCode': u'', u'overview': u'Six months after the Season 1 finale, Sunny finds a new foe, as well as a new, unexpected ally, while MK learns about his gift in a mysterious place.', u'airedSeasonID': 696341, u'thumbAdded': u'2017-03-20 03:52:19', u'episodeName': u'Tiger Pushes Mountain', u'airedSeason': 2, u'airsBeforeSeason': None, u'showUrl': u'', u'id': 5928292, u'dvdDiscid': u'', u'filename': u'episodes/289079/5928292.jpg', u'dvdSeason': 2, u'writers': [u'Alfred Gough', u'Miles Millar'], u'airedEpisodeNumber': 1, u'absoluteNumber': 7, u'thumbHeight': u'225', u'imdbId': u'tt5543760', u'lastUpdated': 1499796569, u'director': u'Nick Copus', u'lastUpdatedBy': 396427, u'dvdChapter': None, u'airsBeforeEpisode': None, u'language': {u'overview': u'en', u'episodeName': u'en'}, u'thumbAuthor': 459860, u'siteRatingCount': 7, u'directors': [u'Nick Copus'], u'firstAired': u'2017-03-19', u'guestStars': [], u'siteRating': 7.9, u'thumbWidth': u'400'}
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:No need to search
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages set([<Language [en]>])
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging in
...
```

Feel free to reopen the issue otherwise
