### ISSUE TITLE
Download next subtitle (different from the previous one)

### ISSUE THREAD

**Issue by jjnilton** [Diaoul/subliminal#752]
Is there an option to download the next subtitle, a different subtitle to replace the previous one? 

Sometimes the subtitle is not good, so I wanted to ignore that subtitle for the next search, is there an option for that?

I saw that there's the `-f` option, but I'm not sure if it's downloading the same subtitle over and over again.

```
$ subliminal --version
subliminal, version 2.0.5
```

**Comment by gothicx** [comment]
Yes, the -f option is for that.

@click.option('-f', '--force', is_flag=True, default=False, help='Force download even if a subtitle already exist.')

**Comment by fernandog** [comment]
@jjnilton if that subtitle you previously downloaded still has the higher score, it will be downloaded again

Btw do you pass min_score? Maybe that's the reason you are getting wrong subtitles
for episodes pass -m 98
for movies pass -m 96

**Comment by jjnilton** [comment]
@fernandog I don't pass min_score, but even if I pass it, it will download the subtitle with the higher score, right? So it will download the same subtitle over and over again, I guess.

The idea would be to make sure the same subtitle won't be downloaded again.

**Comment by getzze** [comment]
Since #1160, you can skip a subtitle with the CLI option `--ignore-subtitles=5gth4dh`, where `5gth4dh` is the subtitle id, that appears in the command line output with the debug option.
