### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by iFEARR** [Diaoul/subliminal#756]
I'm doing something wrong ?
![image](https://cloud.githubusercontent.com/assets/6118215/25970707/4109625a-36a2-11e7-8a83-f9c877cd5632.png)

**Comment by Sjneugent** [comment]
You have to import the dependencies with pip.

**Comment by iFEARR** [comment]
Can you tell me how to do that ? I know very little about python

**Comment by Sjneugent** [comment]
Well, you have python obviously.  Find the pip executable I think the default is C:\Python27\Scripts

open a command prompt as an administrator, navigate to where the pip file is
run pip install subliminal 

and then I think you should be able to run subliminal from the commandline.  I use it on linux tho

**Comment by iFEARR** [comment]
That's exactly what I did. Still doesn't work.
![image](https://cloud.githubusercontent.com/assets/6118215/26014628/1aedc240-3766-11e7-95dd-c6b04e313304.png)

**Comment by Diaoul** [comment]
Try `pip install -U subliminal`

**Comment by iFEARR** [comment]
It trow back some errors, but now its working. Thank you!
![image](https://cloud.githubusercontent.com/assets/6118215/26015489/d2cf3af8-3769-11e7-8744-dc6e3b46ea42.png)
