### ISSUE TITLE
How to check if subtitles were saved to disk?

### ISSUE THREAD

**Issue by elieobeid7** [Diaoul/subliminal#768]
How to check if subtitles were successfully saved to disk?

`if (save_subtitles(video, subtitles[video])): `

Or something else?

**Comment by ratoaq2** [comment]
It would really help if the saved subtitle keeps the stored location (path):

Something like this:
```
for subtitle in subtitles:
  if subtitle.path:
    print(subtitle.path)
```

**Comment by ratoaq2** [comment]
Now you can get the subtitle path using the method:

```
subtitle.get_path(self, video, single=False)
```

3e3e410a0132faf17a3ed79b0934196a31a72983


So, you can easily check if the path exists
