### ISSUE TITLE
[OpenSubtitles] Wrong subtitle downloaded although episode matched by hash

### ISSUE THREAD

**Issue by kohanyirobert** [Diaoul/subliminal#784]
Hi, I'm a Plex/Sub-Zero user and I've noticed that SZ downloads wrong subtitles for episodes from OpenSubtitles.org. I've created an issue for that [here](https://github.com/pannal/Sub-Zero.bundle/issues/303#issuecomment-313115645).

However, I've tried using the latest, standalone Subliminal version (2.0.5) to see if it's a Plex/SZ issue or not.
I think it's a Subliminal thing, so I'm creating this issue.

So. Executing this

```
subliminal --debug download -v -f -l hu -p opensubtitles mr.robot.s01e01.720p.bluray.x264-demand.mkv
```

results in [this output](https://pastebin.com/raw/aciwQPyr).

In the log it says that for OpenSubtitles.org tha calculated hash is `a67fbdf9a1b23499`. If I search with this hash and narrow by 'Hungarian' language [I get this](https://www.opensubtitles.org/en/search/sublanguageid-hun/moviehash-a67fbdf9a1b23499). Two subtitles. Both of them matches the video perfectly.

The problem is that none of these subs are downloaded, instead some random subtitle is picked which is completely unrelated for the series (it's not for another episode).

Not sure how to proceed. Any idea?

**Comment by pannal** [comment]
I've tried the manual fetch on OS's API - it returns the correct subtitle.

I'll debug this further when I have the time.

**Comment by kohanyirobert** [comment]
Just for reference, [this](https://pastebin.com/raw/Zxyhr7u7) would be the correct subtitle (the first one out of the two - I'm simply using OS's homepage _very advanced search_ and I filter by the hash and _hun_ language).

The actual subtitle downloaded for the episode right now is [this](https://pastebin.com/raw/9DtDj3f0).

It downloads incorrect subs from OS for English too, so no need to use Hungarian actually (for easier debuggin). [This is the English sub](https://pastebin.com/raw/fX3fpMLU) (incorrect) downloaded right now the episode.

_Right now_, because yesterday it downloaded something else.

I'm using subliminal from a seedbox through SSH. This behavior happens on that box.

I'm checking Subliminal on Windows right now. It works ... not sure why. [Here's the log](https://pastebin.com/raw/az9AKqmZ) for the same command as in the first post.

At first glance looking at logs the only difference is that on the seedbox (using Python 2.7, it runs in the Netherlands) "refiners fail with exceptions", on my laptop (Python 3, Hungary) there are no exceptions.

What does a refiner do?
Is it possible that the IP Subliminal accesses OS through is _blocked_? However it's obviously not blocked, because there is no mention of that in the logs. Is it possible that instead of blocking OS just returns rubbish subtitle? Just to mess with users? Using their API instead of their website means that we're circumvent their advertisement platform ...

**Comment by pannal** [comment]
I've used their API tester: http://trac.opensubtitles.org/projects/opensubtitles/wiki/XML-RPC-debugger

May it be that the seedbox uses some kind of caching proxy imposed by the provider? So the wrong subtitle was posted initially, then updated later, and you still have the old version in cache?

**Comment by kohanyirobert** [comment]
> Your refiners fail? Can you attach a debug log of that?
I did, [here](https://pastebin.com/raw/aciwQPyr). This is from the execution on the seedbox.

I've created a little script to test the OpenSubtitle.org API on my laptop and on the seedbox.

[os.zip](https://github.com/Diaoul/subliminal/files/1127983/os.zip)

Running `bash os.sh` downloads the first sub based on this hash: `a67fbdf9a1b23499` and outputs the first few lines and also the download URL.

On my laptop it output's the correct sub.
On the seedbox it's a different sub, but the DL url is the same.

Essentially this command

```
curl -s http://dl.opensubtitles.org/en/download/src-api/vrf-19ab0c58/sid-XuNoOzC4RVBFzuXMpbr7xqr1Ty9/filead/1955027189.gz | gunzip | head
````

results in different outputs on the seedbox and on my laptop (the latter correct).

Sooo it's not a Subliminal or SZ issue. :( I'll contact support on my seedbox. Any ideas are welcome.

**Comment by kohanyirobert** [comment]
Quote from my seedbox provider.

> Yes, opensubtitles has blacklisted many of our ips, and serves in purpose wrong subtitles to these IPs. We have contacted their support many times about this, but the refuse to even respond to our requests. I am not quite sure why they do this. It is our understanding, that they do this in purpose to other seedbox providers as well, to blackmail for "VIP"opensubtitles accounts in order to lift the ip ban.
> So yeah, it's a proper ass move. Returning 404 instead of downloading crap subs would be way nicer.

**Comment by kohanyirobert** [comment]
I've contacted OpenSubtitles.org about this on their forum. My topic got "disapproved" and I got a message.

> SimplyTheBOSS wrote:
> The reason is that you are propably using "Bad" IP.

"Bad"

**Comment by sanggfroid** [comment]
Fault code: [5] Reason: 'Didn't receive 200 OK from remote server. (HTTP/1.1 400 Bad Request)'
