### ISSUE TITLE
Installing latest subliminal version on Ubuntu 16.04

### ISSUE THREAD

**Issue by ComputingFroggy** [Diaoul/subliminal#786]
Hello,

I've been using **subliminal** for a while ... but recently it does not return any subtitles any more.

I had installed it from the packages (_sudo apt install subliminal_) and looking at the version (_subliminal --version_), I realised it was quite old (0.7.4).

So I removed it (_sudo apt remove subliminal_).

And I installed **subliminal** with _pip_ and that went ok. But when I type _subliminal_, I get the following message (translated from French):

> bash: /usr/bin/subliminal: No file or folder of that type

I've uninstalled and reinstall **subliminal** (still with _pip_) and I still get the same error message.

Any ideas, any one ?
L@u

**Comment by fernandog** [comment]
Run: which sublimimal

You will get the path where is installed

**Comment by ComputingFroggy** [comment]
Thanks, that was it. A refresh (rehash) was needed.
I forgot to close the issue.
