### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by dima-vy** [Diaoul/subliminal#788]
I started recently get this too many requests error from Addic7ed.
 'addic7ed' and languages set([<Language [en]>])
DEBUG:subliminal.providers.addic7ed:Getting show id with year
DEBUG:subliminal.providers.addic7ed:Getting show id
INFO:subliminal.providers.addic7ed:Getting the page of show id 6441, season 1
ERROR:subliminal.core:Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "/opt/lib/python2.7/site-packages/subliminal-2.0.5-py2.7.egg/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/opt/lib/python2.7/site-packages/subliminal-2.0.5-py2.7.egg/subliminal/providers/addic7ed.py", line 273, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/opt/lib/python2.7/site-packages/subliminal-2.0.5-py2.7.egg/subliminal/providers/addic7ed.py", line 238, in query
    raise TooManyRequests()
TooManyRequests

Tried to change my source ip address, but it didn't help. I'm running subliminal twice in a hour (scheduled in cron), and i'm running it this way several years. Any ideas will be appreciated

Thank you

**Comment by zombieagain** [comment]
I started having the same exact problem...

**Comment by fernandog** [comment]
I think addi7ed is blocking some requests based on user-agent. 
Subliminal uses:
https://github.com/Diaoul/subliminal/blob/master/subliminal/providers/addic7ed.py#L100

**Comment by dima-vy** [comment]
So can it be replaced with any other user-agent?

**Comment by dima-vy** [comment]
Looks like it started to work again...

**Comment by CyberMew** [comment]
It happens on and off for me.

**Comment by Diaoul** [comment]
Web scrapping already suffers bad reputation. Subliminal makes itself known thanks to User-Agent so providers can easily block us if they wish to do so.
If you experience issues with a provider, the best is to complain to the provider itself.

**Comment by CyberMew** [comment]
Understood. Also, I realised that once an error has occured, all the rest of the videos are skipped and no downloads will be done, instead of skipping the file and continuing to the next file.
So basically it could be happily downloading a bunch of subs, hit an error for one of the video, discards the downloaded subs, and then ignore (not attempt) the rest of the unchecked videos. Is that intended? Or maybe I should create a new issue for this?

**Comment by Diaoul** [comment]
Please open another issue

**Comment by fernandog** [comment]
Its because you have only that provider enabled and when this error happens provider is discarded
