### ISSUE TITLE
Download from third-party providers?

### ISSUE THREAD

**Issue by ghost** [Diaoul/subliminal#790]
I download from a website that requires an account to download content. The account is free and you just need a username and a password to render the download links but I don't know if subliminal even let you download from websites that are not coded inside the script itself.

**Comment by Diaoul** [comment]
Not sure I understand what you need but it is possible to create your own provider as a plugin using setuptool's entry points to declare it to subliminal.
Is that what you're looking for?

**Comment by hhiru** [comment]
This may be the case. This is the public RSS link with the latest subtitles available on the website: http://feeds.feedburner.com/ITASA-Ultimi-Sottotitoli

Do you by chance provide instructions. I don't know Python but if I just have to fill a config file with entries maybe I can do that on my own!

**Comment by fernandog** [comment]
@hhiru there is already a code in works for ITASA

**Comment by hhiru** [comment]
I see, good to know but do you think I can set a temporary config file on my own since I don't know what progresses have been made by the ITASA "plugin" author?

**Comment by fernandog** [comment]
@hhiru
If you are a linux user, you can install this branch but as its not official

First uninstall subliminal then run:
pip install https://github.com/Elettronik/subliminal/archive/develop-itasa.zip

If windows, unzip and inside the extracted folder run: 
python setup.py install

Any issues related to itasa you find you **must** reply here:
https://github.com/Diaoul/subliminal/pull/722
