### ISSUE TITLE
Option to remove laguage (.en) from filename of saved subtitle?

### ISSUE THREAD

**Issue by macmeister1967** [Diaoul/subliminal#801]
I am using this script - 

https://gist.github.com/fullmetalsheep/28c397b200a7348027d983f31a7eddfa

...(only manual for now), but all the downloaded subs have ".en" in the title, which will not work with my movie collection (none of my filenames have .en in the title). Without this small problem, the files are named perfectly and work perfectly.

Any thoughts? I cannot see how I would do this in the original autodownload script?

PS. I am using macOS.

**Comment by nateshmbhat** [comment]
You can do one thing , as soon as the subtitle is obtained from subliminal , you can rename it with the code : 

```
for file in os.listdir( ):
    if file.rfind('.en.srt'):
            os.rename(file , file.replace('.en.srt' , '.srt' ) ; 

```

**Comment by fernandog** [comment]
@macmeister1967 
Use this param:

```
  -s, --single                    Save subtitle without language code in the
                                  file name, i.e. use .srt extension. Do not
                                  use this unless your media player requires
                                  it.
```

I saw you call subliminal with "-s" but somehow is not working in your script
try calling subliminal manually with "-s" and you will see it works

**Comment by macmeister1967** [comment]
I added -s again, and it seems to be working for most movies, the one it
did not work on already had embedded subs (MKV).

Cheers. Mark this as solved :-)

**Comment by fernandog** [comment]
@macmeister1967 Just close it
