### ISSUE TITLE
Subliminal doesn't work when the code is converted to a compiled executable

### ISSUE THREAD

**Issue by nateshmbhat** [Diaoul/subliminal#803]
subliminal module in python which is used to get subtitles , doesn't work when compiled to an executable using pyinstaller. here is my complete code

    import subliminal
    import sys,os,requests
    import argparse;
    import logging;
    from babelfish import Language
    import dbm.dumb
    
    
    # configure the cache
    subliminal.region.configure('dogpile.cache.dbm', arguments={'filename': 'cachefile.dbm'})
    
    
    parser = argparse.ArgumentParser()
    parser.add_argument('--Path' , type=str , default=None,help="Path for the video or a directory of videos.")
    args=parser.parse_args()
    
    if not args.Path:
    	args.Path = input("Enter the path for the video file or a directory containing videos : ") ;
    
    if os.path.isfile(args.Path):
    	videos = [subliminal.scan_video(args.Path)];
    else:
    	videos = subliminal.scan_videos(args.Path) ;
    
    subs = subliminal.download_best_subtitles(videos,{Language('eng')} ) ;
    print(list(subs.values()))
    for v in videos:
    	subliminal.save_subtitles(v, subs[v]) ;

The subtitle downloads perfectly when run from IDE or console directly. But it fails to get any subtitle , after compiling .

**EDIT 1 :**
_______________

I found that when i call the `pool.list_subtitles( ) `  , the self.providers list in the argument is empty and so , none of the subtitles are donwnloaded.

**Comment by Diaoul** [comment]
Have you tried to run pyinstaller on the CLI?

**Comment by embryo10** [comment]
Did you find a solution?
I have the same problem.
Looking also at #2747 and #802 I couldn't see a way to fix this.

First the error was that it missed the `alpha3b` module from `babelfish`
I imported all the modules myself but now I'm stuck with this:
```python
Traceback (most recent call last):
  File "secondary.py", line 152, in process
  File "lib\site-packages\subliminal\core.py", line 581, in list_subtitles
  File "lib\site-packages\subliminal\core.py", line 144, in list_subtitles
  File "lib\site-packages\subliminal\core.py", line 105, in list_subtitles_provider
  File "lib\site-packages\stevedore\extension.py", line 326, in __getitem__
KeyError: u'podnapisi'
```

**Comment by nateshmbhat** [comment]
I had success in making it work . THE ISSUE IS WITH how Pyinstaller Handles Entry Points in different modules . 

When you go to the python packages folder of subliminal it has a entry points.txt file . There is a configuration file available from pyinstaller which address this issue with entrypoints

**Comment by embryo10** [comment]
Thank you for the answer!!
I found the `entry points.txt` file but I can't find the pyinstaller's configuration file that uses the entrypoints (or maybe I do not understand what the solution is and what to do with the text at the first place :o)
Any more info or instructions?
TIA

**Comment by embryo10** [comment]
I suppose that the configuration file that you are referring to is [this recipe](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Setuptools-Entry-Point).
I copied the code to my `".spec"` script and added an
```python
a = Entrypoint('main.py', 'console_scripts', 'myEntryPoint',
               pathex=['D:\\Apps\\DEV\\PROJECTS\\4Build\\Subber'],
               excludes=['_tkinter'])
```
entry, instead of the
```python
a = Analysis(['main.py'],
             pathex=['D:\\Apps\\DEV\\PROJECTS\\4Build\\Subber'],
             hiddenimports=[],
             hookspath=None,
             runtime_hooks=None,
             excludes=['_tkinter'])
```
but I still cant understand what values I should use for the `'console_scripts', 'myEntryPoint'` arguments or how to use the `entry_points.txt` variables...
Any help will be appreciated!

**Comment by nateshmbhat** [comment]
Here is my spec file contents : 


```
block_cipher = None
options = [('v',None,'OPTION')]

a = Analysis(scripts=['main.py',r'subtitle_entry_points.py'],
      pathex=[r'C:\Users\Natesh\Documents\Myprojectfolder','C:\Program Files\Python35\Lib\site-packages'],
             binaries=[],
             datas=['guessit/tlds', 'guessit/tlds'), ('babelfish/data', 'babelfish/data') , '.')],
             hiddenimports=['dogpile.cache.backends.file','subliminal','dogpile.cache','stevedore','appdirs'],
             hookspath=['.'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
       
       
pyz = PYZ(a.pure,  
  a.zipped_data,
  cipher=block_cipher)


exe = EXE(pyz,
          a.scripts,
        exclude_binaries=True,
          name='Subtitler',
          debug=True,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
              a.binaries,
              a.zipfiles,
              a.datas,
              strip=False,
              upx=True,
              name='Subtitler')

```

As you can see in the Analysis function arguments , I have used the "subtltle_entry_points.py" file . Make this same file in your project folder and paste the below code inside the "subtitle_entry_points.py" file . Then you are good to go with using the above spec code to compile . Make sure that you have guessit and babelfish folders also in your project folder (as mentioned in many other sites addressing this issue)

```
import subliminal.providers.shooter
subliminal.providers.shooter.ShooterProvider()

import subliminal.providers.addic7ed
subliminal.providers.addic7ed.Addic7edProvider()

import subliminal.providers.legendastv
subliminal.providers.legendastv.LegendasTVProvider()

import subliminal.providers.opensubtitles
subliminal.providers.opensubtitles.OpenSubtitlesProvider()

import subliminal.providers.podnapisi
subliminal.providers.podnapisi.PodnapisiProvider()

import subliminal.providers.subscenter
subliminal.providers.subscenter.SubsCenterProvider()


import subliminal.providers.thesubdb
subliminal.providers.thesubdb.TheSubDBProvider()


import subliminal.providers.tvsubtitles
subliminal.providers.tvsubtitles.TVsubtitlesProvider()


import subliminal.converters.legendastv
subliminal.converters.legendastv.LegendasTVConverter()

import subliminal.converters.addic7ed
subliminal.converters.addic7ed.Addic7edConverter()

import subliminal.converters.thesubdb
subliminal.converters.thesubdb.TheSubDBConverter()

import subliminal.converters.tvsubtitles
subliminal.converters.tvsubtitles.TVsubtitlesConverter()


import subliminal.converters.shooter
subliminal.converters.shooter.ShooterConverter()
```

**Comment by embryo10** [comment]
Thank you for your help, but it didn't work :o(
I changed my `spec` file like this:
```python
# -*- mode: python -*-

a = Analysis(['main.py', 'entry_points.py'],
             pathex=[r'D:/Apps/DEV/PROJECTS/4Build/Subber',
                     r'D:/Apps/DEV/PYTHON/Python27/Lib/site-packages'],
             datas=[(r'D:/Apps/DEV/PYTHON/Python27/Lib/site-packages/langdetect/profiles', r'langdetect/profiles'),
                    (r'D:/Apps/DEV/PYTHON/Python27/Lib/site-packages/langdetect/utils', r'langdetect/utils'),
                    (r'D:/Apps/DEV/PYTHON/Python27/Lib/site-packages/babelfish/data', r'babelfish/data')],
             hiddenimports=['dogpile.cache.backends.file','subliminal','dogpile.cache','stevedore','appdirs'],
             hookspath=None,
             runtime_hooks=None,
             excludes=['_tkinter', 'Crypto'])

pyz = PYZ(a.pure)

exe = EXE(pyz, a.scripts,
          exclude_binaries=True,
          name='Subber.exe',
          icon='Subber.ico',
          debug=False,
          strip=None,
          version='Subber.version.py',
          upx=False,
          console=False)

coll = COLLECT(exe, Tree('D:\\Apps\\DEV\\PROJECTS\\4Build\\Subber\\z'),
               a.binaries,
               a.zipfiles, a.datas,
               strip=None,
               upx=False,
               name='Subber')
```
and although i builds OK with all the needed files (I add some more dependencies)  when I run it and try to search I get this error:
```python
Application started at 2017-12-24 19:35:36
Traceback (most recent call last):
  File "secondary.py", line 153, in process
  File "Lib\site-packages\subliminal\core.py", line 581, in list_subtitles
  File "Lib\site-packages\subliminal\core.py", line 144, in list_subtitles
  File "Lib\site-packages\subliminal\core.py", line 105, in list_subtitles_provider
  File "Lib\site-packages\stevedore\extension.py", line 326, in __getitem__
KeyError: u'podnapisi'
```
I only use podnapisi from subliminal, nothing else..
Can you spot any errors in the `spec`?
I also tried to import your `entry_points.py` in the `main.py` with no results. 
Is it possible that it will not work with python 2.7.13?

**Comment by nateshmbhat** [comment]
You have not included any data which I had included in my Wi-Fi and if you are still not getting with this method try to pinpoint the location where error is occurring in compiled binary by using logging module and see the objects which are not eating properly initialised because of entrypoint issues. You can save Python objects inside file using python's pickle module

**Comment by embryo10** [comment]
I think that the problem is not with the data (I got all the dependencies) but with the stevedore library.
It uses the extension.py to dynamically create the providers when asked but it doesn't, so there is no "podnapisi" provider and I get a KeyError.
I'll try to fake the provider obj and see what happens.
Thank you for your help anyway...

**Comment by nateshmbhat** [comment]
Yes ur right, what I'm saying is while ur debugging and ur flow reaches that extention.py, save the entire object or data as a file using pickle module and add this code directly in that extention.py . U can then take that file directly and read it and get the object in ur code. U need to do this carefully in the extention.py itself or any other place which needs that object...

**Comment by embryo10** [comment]
Yes, that is what I did and it seems to be working (for now ;o)

**Comment by nateshmbhat** [comment]
can u please tell me the line number in extention.py and which object i should save using pickle ? i have forgotten that where i did previously.

**Comment by embryo10** [comment]
Well, its been some time and I have forgotten everything too..
Looking at the code I use, I can see a couple of changes to the `stevedore.extension.py`
The first is where I load the object in `class ExtensionManager` before the `__init__` as a class variable. (It could be anywhere actually):
```python
    with open("podnapisi_obj.txt") as pod_file:  # This is a hack for PyInstaller
        PODNAPISI = cPickle.loads(pod_file.read())
```
The other is in the `__get_item__`:
```python
        if name == "podnapisi":  # This is a hack for PyInstaller
            return self.PODNAPISI
```
The object is this:
[podnapisi_obj.txt](https://github.com/Diaoul/subliminal/files/2553273/podnapisi_obj.txt)
I don't remember how I got it, but it should be what the `__get_item__` returned normally...

**Comment by nateshmbhat** [comment]
I tried using it , still no luck. is it possible to send your extention.py file and hopefully all the related files so that i can just copy what u have edited ?

**Comment by nateshmbhat** [comment]
I saved all the object files not just for podnapisi . and even after i returned the object that is returned from saved pickle object , i still get empty dict_values[] (no subtitles )

**Comment by embryo10** [comment]
Can you check just with the Podnapisi at first, to make sure there is not something else wrong?

**Comment by nateshmbhat** [comment]
I copied ur code . Changed the required code to work for python3 .( just some prints and cpickle to pickle) . Its working in python directly . can u share your spec file config so that i can compile it like u did and check it ?

**Comment by embryo10** [comment]
Here you go [Subber.zip](https://github.com/Diaoul/subliminal/files/2553888/Subber.zip)

**Comment by embryo10** [comment]
Remember to add the pickled object to the app's path..
