### ISSUE TITLE
Doesn't pick the right subtitles

### ISSUE THREAD

**Issue by IKIKN** [Diaoul/subliminal#805]
Hi,

I'm trying to download the srt for a single episode on addic7ed, and it doesn't work. A "TooManyRequests " error is always raised. Here is the console output :

`
ikikn@ns388153:~/media/TV Shows/The Strain/Season 04$ subliminal --debug download -l FR -p addic7ed -v -v The\ Strain\ -\ S04E04\ -\ New\ Horizons.mkv
Collecting videos  [####################################]  100%  The Strain - S04E04 - New Horizons.mkvDEBUG:subliminal.cli:Collecting path The Strain - S04E04 - New Horizons.mkv
INFO:subliminal.core:Scanning video 'The Strain - S04E04 - New Horizons.mkv' in ''
DEBUG:subliminal.core:Size is 2510461241
DEBUG:subliminal.core:Computed hashes {'thesubdb': '55e2792391ffbcaa88970288417dfd94', 'opensubtitles': '577ecf8a9ba0d776', 'shooter': '33c8b676e095704cba9983402d87a7c2;91fcbec67e793ccd097b814ca7b16d27;b93bc722f4298cadb95bd257dadd79d3;8bf25dd00fe4fc9af19cc52759f3ebd4', 'napiprojekt': 'ba136c5063b40570bb978cdb25004b49'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found resolution 1080p
DEBUG:subliminal.refiners.metadata:Found video_codec h264
DEBUG:subliminal.refiners.metadata:MKV has no subtitle track
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'The Strain'
DEBUG:subliminal.refiners.tvdb:Found 5 results
DEBUG:subliminal.refiners.tvdb:Found exact match on series u'The Strain'
DEBUG:subliminal.refiners.tvdb:Discarding series name u'The Andromeda Strain' mismatch on year 2008
DEBUG:subliminal.refiners.tvdb:Found series {u'seriesId': u'179638', u'rating': u'TV-14', u'overview': u'A mysterious viral outbreak with hallmarks of an ancient and evil strain of vampirism ravages the city of New York.\r\n', u'firstAired': u'2014-07-13', u'id': 276564, u'aliases': [], u'networkId': u'', u'network': u'FX (US)', u'zap2itId': u'EP01836850', u'seriesName': u'The Strain', u'status': u'Continuing', u'added': u'2013-12-26 18:25:50', u'imdbId': u'tt2654620', u'lastUpdated': 1502988009, u'addedBy': 10110, u'genre': [u'Drama', u'Horror', u'Thriller'], u'banner': u'graphical/276564-g11.jpg', u'airsTime': u'10:00 PM', u'siteRatingCount': 80, u'airsDayOfWeek': u'Sunday', u'runtime': u'45', u'siteRating': 8}
INFO:subliminal.refiners.tvdb:Getting series episode 4x4
DEBUG:subliminal.refiners.tvdb:Found episode {u'seriesId': 276564, u'airsAfterSeason': None, u'dvdEpisodeNumber': 4, u'productionCode': u'', u'overview': u'Dutch is forced to make a deal with Desai while she plots to escape a strigoi breeding facility. Eph and Alex seek to uncover the dark secrets behind the Partnership\u2019s new plan but face the repercussion of their last attack. Gus and Creem face off against a gang encroaching on their turf.', u'airedSeasonID': 699886, u'thumbAdded': u'2017-08-06 23:55:32', u'episodeName': u'New Horizons', u'airedSeason': 4, u'airsBeforeSeason': None, u'showUrl': u'', u'id': 6040885, u'dvdDiscid': u'', u'filename': u'episodes/276564/6040885.jpg', u'dvdSeason': 4, u'writers': [u'Mickey Fisher'], u'airedEpisodeNumber': 4, u'absoluteNumber': 40, u'thumbHeight': u'225', u'imdbId': u'tt6141524', u'lastUpdated': 1502704192, u'director': u'Kevin Dowling', u'lastUpdatedBy': 348094, u'dvdChapter': None, u'airsBeforeEpisode': None, u'language': {u'overview': u'en', u'episodeName': u'en'}, u'thumbAuthor': 345634, u'siteRatingCount': 5, u'directors': [u'Kevin Dowling'], u'firstAired': u'2017-08-06', u'guestStars': [], u'siteRating': 7.4, u'thumbWidth': u'400'}
INFO:subliminal.core:Refining video with omdb
DEBUG:subliminal.refiners.omdb:No need to search
Collecting videos  [####################################]  100%
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  The Strain - S04E04 - New Horizons.mkvINFO:subliminal.core:Listing subtitles with provider 'addic7ed' and languages set([<Language [fr]>])
INFO:subliminal.core:Initializing provider addic7ed
DEBUG:subliminal.providers.addic7ed:Getting show id with year
DEBUG:subliminal.providers.addic7ed:Getting show id
INFO:subliminal.providers.addic7ed:Getting the page of show id 4584, season 4
ERROR:subliminal.core:Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "build/bdist.linux-x86_64/egg/subliminal/providers/addic7ed.py", line 273, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "build/bdist.linux-x86_64/egg/subliminal/providers/addic7ed.py", line 238, in query
    raise TooManyRequests()
TooManyRequests
INFO:subliminal.core:Discarding provider addic7ed
Downloading subtitles  [####################################]  100%
Some providers have been discarded due to unexpected errors: addic7ed
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider addic7ed
0 subtitle downloaded for The Strain - S04E04 - New Horizons.mkv
`

What can I do ? I really need to use Addic7ed because when using other providers, it always downloads unsynced subtitles :(

Thanks !

**Comment by IKIKN** [comment]
Hi,

Turns out that today it seems to work, BUT it doesn't pick the right subtitles. I'm trying to dl the subtitles for the S04E04 episode of The Strain, in french, and there are 2 available subtitles for it on addic7ed :

- SVA Version
- STRiFE Version

My episode is the Strife version, and it always picks the SVA subtitles. Is there a way to "help" subliminal to choose the right subtitles ? Thanks

**Comment by fernandog** [comment]
Addic7ed blocks access that's why that happens

**Comment by fernandog** [comment]
Which min score are you passing to subliminal?

**Comment by IKIKN** [comment]
The wrong subtitles that are found have a score of 91.

**Comment by fernandog** [comment]
pass -m or --min-score to subliminal command line (0 to 100). Try passing 98 as min score. 
Did you try with opensubtitles?

**Comment by IKIKN** [comment]
When I input 98, it doesn't download any subtitles :(

**Comment by fernandog** [comment]
What is the score of the subtitle you want?

**Comment by IKIKN** [comment]
Well I want the highest score available on the provider I type. I don't understand why it ALWAYS pick the wrong subtitles.

**Comment by fernandog** [comment]
@IKIKN because you need a min_score that matches at least release group, series, season and episode and format

Enabled debug logs and notice the score calculation
It is based on format, release group, season, episode, etc
As a subtitle user, you know if release_group doesn't match, subs have high chances of being wrong.
