### ISSUE TITLE
subliminal-script.py location?

### ISSUE THREAD

**Issue by bengalih** [Diaoul/subliminal#807]
Sorry if this is a dumb python-use question (or doesn't belong here...I couldn't find forums).  While the documentation page exists, there are a lot of tutorials and old git-hub issues that seem to reference stuff I can't find.

For instance, I found this issue which allowed for creation of a log file:
https://github.com/Diaoul/subliminal/issues/283

But no such option exists.  Also references to subliminal-script.py.
It think this may all be old information?

I am installed with Python 2.7 on Windows 7 using "pip install subliminal" and all I have is a sublminal.exe and stuff in lib\site-packages\sublminal.

Is this correct?  Should I have sublminal in .py format that is newer and/or accepts more switches than the .exe does?

Is there any way to get logging?  Or to do so I would need to write my own python script importing the sublminal package and and do my own logging?

thanks

**Comment by Diaoul** [comment]
The CLI code is [here](https://github.com/Diaoul/subliminal/blob/master/subliminal/cli.py), you don't need to access it directly though, just use the subliminal binary installed with pip. You can do `subliminal --help` to get help or see the CLI documentation [here](https://subliminal.readthedocs.io/en/latest/user/cli.html).

I think what you're looking for is `subliminal --debug ...` or `subliminal download -v -v ...` or combine both. The [Contribution Guide](https://github.com/Diaoul/subliminal/blob/master/CONTRIBUTING.md) explains that already and should be read before opening an issue.

**Comment by bengalih** [comment]
Thanks.  The old documentation/issue I reference looked like there is (or used to be) an actual parameter which will log to file as opposed to just produce debug data that can be redirected from stout/stderr.

When running the CLI there is the progress bar next to each title being checked which produces a nice visual glance of what is going on.  I have been unable to redirect these particular streams into a log file which is why I was curious if a built-in file logger might do this.

Not a biggie though...thanks.
