### ISSUE TITLE
provider order when specified (or not) and login credential behavior

### ISSUE THREAD

**Issue by bengalih** [Diaoul/subliminal#808]
another question here (sorry, can't see how to tag this as a question myself instead of an issue).

It seems the program works without specifying a provider.  Or, if I specify a provider like opensubtitles it appears to work without providing credentials.

1) I would like to know what the default behavior is if no provider is specified.  Do all providers get checked?  In what order?

2) When specifying providers, do they get checked in the order listed?

3) Which download gets chosen when multiple providers are specified?  IOW, what is the general flow for how a subtitle gets selected from all available options on all checked providers?

4) Depending on above answers...is there a way to prefer a certain provider, but get whatever we can if not available from preferred?

5) What exactly is the point of having to provide credentials to some providers when it appears you can access the data without them?

thank you

**Comment by Diaoul** [comment]
Please read the documentation before opening an issue. In particular the [How it works](https://subliminal.readthedocs.io/en/latest/user/how_it_works.html) section seems to answer most of your questions here.

4. Run subliminal two times with different parameters
5. The most common reason is increased subtitle download cap (OS & Addic7ed)

**Comment by bengalih** [comment]
Thank you..I had read that documentation page but focused on it again based on your answer.

Best I can gather is that it doesn't matter _which_ order the providers are checked since all results go into a pool to score and the highest score is picked.  Is this accurate?

I also didn't see any explicit answer to my first question, but I'm to assume that all providers are checked if none are specified?
