### ISSUE TITLE
video.subtitle_languages always return empty set

### ISSUE THREAD

**Issue by morpheus65535** [Diaoul/subliminal#810]
Is there something that I don't understand or video.subtitle_languages always return an empty set?

```
import os
from babelfish import *
from subliminal import *

video = scan_video('/path/to/file')

print video.subtitle_languages
```

Even if there's an embedded or external subtitle, it always give me: `set([])`

Thanks for your help!

**Comment by Diaoul** [comment]
Does your video have embedded subtitles or a subtitle file with the same name next to it?

**Comment by Diaoul** [comment]
You need to use (`refine`)[https://github.com/Diaoul/subliminal/blob/master/subliminal/core.py#L520] to get more informations about the video. This is where the metadata parsing is done.

**Comment by morpheus65535** [comment]
The documentation doesn't talk about refine in the usage guide: http://subliminal.readthedocs.io/en/latest/user/usage.html

How am I suppose to use it?

Thanks!

P.S.: On peut passer au français si c'est plus simple. :-)

**Comment by morpheus65535** [comment]
@Diaoul Some help would really be appreciated on this one. I'm stuck on this problem for days... :-/

Thank you!
