### ISSUE TITLE
Parsing CLI input incorrectl

### ISSUE THREAD

**Issue by howardjohn** [Diaoul/subliminal#812]
I've run into a few issues with the CLI (seems like argument parsing issues? Some examples below 

```
$ subliminal download -l en .
Traceback (most recent call last):
  File "/usr/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/lib/python3/dist-packages/subliminal/cli.py", line 85, in subliminal
    args.languages = {babelfish.Language.fromietf(l) for l in args.languages}
  File "/usr/lib/python3/dist-packages/subliminal/cli.py", line 85, in <setcomp>
    args.languages = {babelfish.Language.fromietf(l) for l in args.languages}
  File "/usr/lib/python3/dist-packages/babelfish/language.py", line 126, in fromietf
    language = cls(language_subtag)
  File "/usr/lib/python3/dist-packages/babelfish/language.py", line 82, in __init__
    raise ValueError('%r is not a valid language' % language)
ValueError: '.' is not a valid language
```
```
$ subliminal cache
usage: subliminal -l LANGUAGE [LANGUAGE ...] [-s] [-c CACHE_FILE]
                  [-p PROVIDER [PROVIDER ...]] [-m MIN_SCORE] [-a AGE] [-h]
                  [-f] [--addic7ed-username USERNAME]
                  [--addic7ed-password PASSWORD] [-q | -v] [--color] [--debug]
                  [--version] [--help]
                  PATH [PATH ...]
subliminal: error: the following arguments are required: -l/--languages
```
```
$ subliminal download -l en en en a
Traceback (most recent call last):
  File "/usr/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/lib/python3/dist-packages/subliminal/cli.py", line 85, in subliminal
    args.languages = {babelfish.Language.fromietf(l) for l in args.languages}
  File "/usr/lib/python3/dist-packages/subliminal/cli.py", line 85, in <setcomp>
    args.languages = {babelfish.Language.fromietf(l) for l in args.languages}
  File "/usr/lib/python3/dist-packages/babelfish/language.py", line 126, in fromietf
    language = cls(language_subtag)
  File "/usr/lib/python3/dist-packages/babelfish/language.py", line 82, in __init__
    raise ValueError('%r is not a valid language' % language)
ValueError: 'a' is not a valid language
```

It seems like the argument parsing is corrupted. In the last example it looks like it doesn't recognize `en en a` as the path but instead thinks they are all languages.

Running on Ubuntu 16.04 on Windows 10, Python 3.5, Subliminal 2.0.5.

Is this the correct usage of the command?

**Comment by Diaoul** [comment]
Maybe this is a bug in click, please try to update all subliminal dependencies and try again. Also, are you using bash or some exotic shell or terminal? Maybe the argument passing from your terminal doesn't go properly through click.

**Comment by markcroft1975** [comment]
i am having the same problem on linux mint..

 $ subliminal download -l en The.Big.Bang.Theory.S05E18.HDTV.x264-LOL.mp4
Traceback (most recent call last):
  File "/usr/bin/subliminal", line 9, in <module>
    load_entry_point('subliminal==0.7.4', 'console_scripts', 'subliminal')()
  File "/usr/lib/python3/dist-packages/subliminal/cli.py", line 85, in subliminal
    args.languages = {babelfish.Language.fromietf(l) for l in args.languages}
  File "/usr/lib/python3/dist-packages/subliminal/cli.py", line 85, in <setcomp>
    args.languages = {babelfish.Language.fromietf(l) for l in args.languages}
  File "/usr/lib/python3/dist-packages/babelfish/language.py", line 126, in fromietf
    language = cls(language_subtag)
  File "/usr/lib/python3/dist-packages/babelfish/language.py", line 82, in __init__
    raise ValueError('%r is not a valid language' % language)
ValueError: 'the.big.bang.theory.s05e18.hdtv.x264' is not a valid language

i have purged off subliminal a couple of times and did fresh install

sudo -H pip download  subliminal
that does not install anything


 have to install with command sudo apt-get install subliminal
installs this version  -  subliminal (0.7.4-1) 


s $ sudo apt install subliminal
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed
  subliminal
0 to upgrade, 1 to newly install, 0 to remove and 1 not to upgrade.
Need to get 3,366 B of archives.
After this operation, 42.0 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/universe amd64 subliminal all 0.7.4-1 [3,366 B]
Fetched 3,366 B in 0s (52.7 kB/s)      
Selecting previously unselected package subliminal.
(Reading database ... 258179 files and directories currently installed.)
Preparing to unpack .../subliminal_0.7.4-1_all.deb ...
Unpacking subliminal (0.7.4-1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up subliminal (0.7.4-1) ...
markcroft@markcroft-i5 ~/torrents $

**Comment by ratoaq2** [comment]
@markcroft1975 You're using a very old subliminal version: 0.7.4-1 and subliminal is currently in 2.0.5

I believe @howardjohn is also using an old version of subliminal

**Comment by ratoaq2** [comment]
```
usage: subliminal -l LANGUAGE [LANGUAGE ...] [-s] [-c CACHE_FILE]
                  [-p PROVIDER [PROVIDER ...]] [-m MIN_SCORE] [-a AGE] [-h]
                  [-f] [--addic7ed-username USERNAME]
                  [--addic7ed-password PASSWORD] [-q | -v] [--color] [--debug]
                  [--version] [--help]
                  PATH [PATH ...]
```
This clearly shows it's using a very old subliminal version
You should uninstall the subliminal provided by the linux distribution (e.g.: `apt-get remove subliminal`)

This is how the latest version looks like:
```
subliminal --help
Usage: subliminal [OPTIONS] COMMAND [ARGS]...

  Subtitles, faster than your thoughts.

Options:
  --addic7ed USERNAME PASSWORD    Addic7ed configuration.
  --legendastv USERNAME PASSWORD  LegendasTV configuration.
  --opensubtitles USERNAME PASSWORD
                                  OpenSubtitles configuration.
  --omdb APIKEY                   OMDB API key.
  --cache-dir DIRECTORY           Path to the cache directory.  [default:
                                  /home/jones/.cache/subliminal]
  --debug                         Print useful information for debugging subliminal and for
                                  reporting bugs.
  --version                       Show the version and exit.
  --help                          Show this message and exit.

Commands:
  cache     Cache management.
  download  Download best subtitles.

  Suggestions and bug reports are greatly appreciated: https://github.com/Diaoul/subliminal/

$ subliminal --version
subliminal, version 2.1.0.dev
```
