### ISSUE TITLE
CLI question / clarification

### ISSUE THREAD

**Issue by vulcanjedi** [Diaoul/subliminal#819]
The help screen shows:
 -p, --provider [addic7ed|legendastv|opensubtitles|podnapisi|shooter|thesubdb|tvsubtitles]
                                  Provider to use (can be used multiple
                                  times).

Is this just for those you have logons for or do you have to specific each individual one you want to check for only? Can you check a provider you dont have an account with?

**Comment by Diaoul** [comment]
By default all possible (compatible with your language and kind of video) providers are searched. If you want to restrict to some providers only you can use this.

Some providers lift download limits when you are logged in so it may improve your experience to login wherever possible.
