### ISSUE TITLE
Cachefile in home folder.

### ISSUE THREAD

**Issue by oppsig** [Diaoul/subliminal#820]
This three files usally always resides in my homefolder. (/home/kodi)
Is this normal?
nzbget is at /opt/ppscripts/nzbget-subliminal

The files are.
cachefile.dbm
cachefile.dbm.dogpile.lock  
cachefile.dbm.rw.lock

**Comment by Diaoul** [comment]
You should report the issue to `nzbget-subliminal`, subliminal's CLI module uses `appdirs` cache directory, not the home : https://github.com/Diaoul/subliminal/blob/master/subliminal/cli.py#L223-L224

**Comment by oppsig** [comment]
Ahh sorry, thought i did :)
