### ISSUE TITLE
Https error with Python

### ISSUE THREAD

**Issue by lilp69** [Diaoul/subliminal#821]
Hi, I've this error  : 
`SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning`

I try to update Python, but I've latest version.

**Comment by fernandog** [comment]
@lilp69 please try this: https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2
