### ISSUE TITLE
I coded a new spanish provider: tusubtitulo.com

### ISSUE THREAD

**Issue by porzino** [Diaoul/subliminal#825]
Hi,

I'm sorry to open this like an issue, but I have never work with github.
I have developed a new spanish provider, tusubtitulo.com. 
I have tested it for days and it works fine.

Is it possible to merge the code into the develop branch? If yes, how can I do it?

Thanks

**Comment by getzze** [comment]
See https://github.com/Diaoul/subliminal/pull/826
