### ISSUE TITLE
Change URL of Podnapisi.NET provider

### ISSUE THREAD

**Issue by MasterMind2k** [Diaoul/subliminal#829]
Hi.

I would like to ask, if URL of the Podnapisi.NET provider to be changed to https://www.podnapisi.net/, since we are enforcing SSL.

Thanks.

**Comment by pannal** [comment]
Sub-Zero already uses the https version for quite some time and it's been stable.

@Diaoul you're good to go :)

**Comment by fernandog** [comment]
Already in develop:
https://github.com/Diaoul/subliminal/commit/712cdb46ca0f72bea4a189e61244bfea42c12b5c

**Comment by fernandog** [comment]
Next week the commit will be 1 year old lol

**Comment by MasterMind2k** [comment]
There are some urls with missing `www.` in front.

Just as a side note. the domain `podnapisi.eu` will expire on 31 Dec 2017 and will be gone.
