### ISSUE TITLE
Missing country data

### ISSUE THREAD

**Issue by shlomiLan** [Diaoul/subliminal#840]
[here ](https://github.com/Diaoul/subliminal/blob/master/subliminal/video.py#L168) you create an `Episode` object, but you don't try to save the country data that is returned by `guessit`. why is that? this information could be helpful when trying to find the correct show in TVDB.

**Comment by fernandog** [comment]
@shlomiLan do you have an idea in mind ? feel free to do a PR to `develop` branch

**Comment by ratoaq2** [comment]
Fixed by 676354ca8b341432e416e42d8d8500a96d0af398
