### ISSUE TITLE
imdb and tvdb ID data

### ISSUE THREAD

**Issue by shlomiLan** [Diaoul/subliminal#845]
`video = Video.fromname(episode.name)` when I use this function I always get `None` for 
`tvdb_id`, `imdb_id` and `series_imdb_id`.
In the code, it looks like this information should get from `guessit`, but it has no support for this information,  am I missing anything? it there a flag or a function call that I can use to add this info?

**Comment by fernandog** [comment]
@shlomiLan AFAIK it should come from the refiner. The OMDB requires an API now so Subliminal can't use for now

**Comment by shlomiLan** [comment]
@fernandog the `refine` is only been used when running in CLI mode, is that right?

**Comment by fernandog** [comment]
It's runs in commans line too. You should see a traceback that wasn't able to connect to omdb

**Comment by shlomiLan** [comment]
When I look at the source code the only places where the `tvdb refine` function is been called is in the `test_tvdb.py`. Can I try and add it to `video.py` inside the `fromguess` function. I think it should do the job.

**Comment by shlomiLan** [comment]
I added `TVDB` and `IMDB` ID's in commit: 85e2f5f

**Comment by ratoaq2** [comment]
refiners are registered as extensions like the providers and they always run (cli or library)
