### ISSUE TITLE
Download subtitles from opensubtitles don't match even in the TV show

### ISSUE THREAD

**Issue by daniesteban** [Diaoul/subliminal#846]
subliminal, version 2.0.5 on Linux Debian testing

Many of downloaded subtitles from opensubtitles are from another TV Show than the episode searched and even have different length that the video.
For download I use the command: subliminal --debug  --opensubtitles  user password download -f -v -l es -p opensubtitles "Young Sheldon/Season 1/S01E01.mkv"
Use -r option don't affect the result. The same search for english subtitltes works nice.

I attach debug log for spanish search [log_es.txt](https://github.com/Diaoul/subliminal/files/1523681/log_es.txt) (error) and english search
[log_en.txt](https://github.com/Diaoul/subliminal/files/1523680/log_en.txt) (ok)

Apparently both know the TV show and the episode and do the same search but spanish download don't work well.

**Comment by daniesteban** [comment]
I've done a bunch of tests with Young Sheldon S1 E7, **currently there isn't any subtitle in opensubtitles for this episode**.
When I pass to subliminal the episode name in format **S01E07.mkv it downloads wrong english subtitle** (remind there isn't any subtitle at all in opensubtitle yet), looking into the subtitle it seems to be some of "The Last Kingdom" Episode #1.7 subtitles English (https://www.opensubtitles.org/en/search/sublanguageid-eng/imdbid-4817240).
Nevertheless, when I pass to subliminal the _original_ name **Young.Sheldon.S01E07.720p.HDTV.x264-AVS [rarbg].mkv** it straight away finishes with _No subtitles found_ message, which **is right**

In both cases I use the command: _subliminal --debug --opensubtitles  [user] [password] download -r metadata -r tvdb -f -vv -l en -p opensubtitles Downloads/raspi/Shows/Young\ Sheldon/Season\ 1/[video_name.mkv]_ where [video_name.mkv] is _S01E07.mkv_ and _Young.Sheldon.S01E07.720p.HDTV.x264-AVS [rarbg].mkv_

Therefore it seems a problem for lack of information about the episode, the funny thing is that looking **in the debug information both** commands seems to looking for the same and with the same information (except tag information) **_{'query': u'Young Sheldon', 'sublanguageid': u'eng', 'episode': 7, 'season': 1}_**.

I attach the debug information of both searches:
[shortname.txt](https://github.com/Diaoul/subliminal/files/1542278/shortname.txt): _S01E07.mkv_ search
[fullname.txt](https://github.com/Diaoul/subliminal/files/1542279/fullname.txt): _Young.Sheldon.S01E07.720p.HDTV.x264-AVS [rarbg].mkv_ search

**Comment by fernandog** [comment]
opensubtitles uses hashes and filename to search.
If you pass a filename with poor information, it will search with that
Also you are not passing min_score. So it will download ANY subtitles
min score is to needed to it will only download sub that match some criterias, including show title

Try adding this to command line -m 98

@Diaoul we should really think about setting a default min_score. This is the second issue related to this
min score should at least match title, season and episode

**Comment by daniesteban** [comment]
Thank you very much @fernandog if I add -m 98 to search, it does what I expected. I totally agree with you in _min score should at least match title, season and episode_ is completely useless that with _{'query': u'Young Sheldon', 'sublanguageid': u'eng', 'episode': 7, 'season': 1}_ subliminal downloads subtitles from another show.

In any case I don't understand how the min score works, can you help me?. The higher value the more confidence a subtitle must be, right? and its value can be from 0 (any subtitle) to 100 (max accuracy). I suppose the number in the log when download is the actual score for that subtitle, in this case 93:
_**[ 93.0]** English subtitle from opensubtitles (match on series, year, episode, season, audio_codec, video_codec)_
if the log says _{'query': u'Young Sheldon', 'sublanguageid': u'eng', 'episode': 7, 'season': 1}_ (it means, despite the poor file name information , it knows show name, episode and season) how is possible that a subtitle from another show have a 93 score?

**Comment by fernandog** [comment]
@daniesteban its complicated but it uses this score dictionary

#: Scores for episodes
episode_scores = {'hash': 359, 'series': 180, 'year': 90, 'season': 30, 'episode': 30, 'release_group': 15,
                  'format': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}

it does all the math and then normalize into a 0-100 score

I Don't think that 93 is the score.
Enable debug logs and you will see this:
`Computed score 303 with final matches set(['hearing_impaired', 'year', 'series_imdb_id', 'series', 'video_codec', 'season'])`

Max score before normalize is 360.

**Comment by daniesteban** [comment]
Perfect, knowing the score use and no default score value it seem works well. 
In future maybe you should have a look at score system, according to the log, subtitle's score of the wrong show is actually 93.
_INFO:subliminal.core:Saving <OpenSubtitlesSubtitle '1954974993' [en]> to 'Downloads/raspi/Shows/Young Sheldon/Season 1/S01E07.en.srt'_
_1 subtitle downloaded for S01E07.mkv
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1954974993' [en]> for video <Episode [u'Young Sheldon', 2017, 1x7]> with {'hearing_impaired': None}_
_DEBUG:subliminal.score:Using scores {'hash': 359, 'format': 7, 'series': 180, 'audio_codec': 3, 'year': 90, 'hearing_impaired': 1, 'episode': 30, 'season': 30, 'video_codec': 2, 'resolution': 2, 'release_group': 15}_
_DEBUG:subliminal.score:Found matches set(['episode', 'series', 'season', 'audio_codec', 'year', 'video_codec'])_
_INFO:subliminal.score:**Computed score 335** with final matches set(['episode', 'series', 'season', 'audio_codec', 'year', 'video_codec'])_

335 out of 360 is effectively 93 out of 100

Thank you again for the support.

**Comment by fernandog** [comment]
notice the `release_group` , '`format` and `resolution` are missing from the matches set. If you add the score it will be 359

a web-dl subtitle doesn't "work" for HDTV

**Comment by daniesteban** [comment]
Only one last question. Is there any way to pass, using subliminal CLI, the name of the original file to add metadata to the S0nE0n search?
Maybe -r metadata? I've found this similar idea https://github.com/Diaoul/subliminal/issues/593  where it speaks of refiner's CLI implementation but I couldn't find a comprehensive explanation for this type of use, sorry.
I really appreciate your help.

**Comment by fernandog** [comment]
@daniesteban I never used the cli.

@Diaoul help here?

**Comment by daniesteban** [comment]
@Diaoul can you lend a hand with https://github.com/Diaoul/subliminal/issues/846#issuecomment-351069804 please? Thank you
