### ISSUE TITLE
How to use provider_configs with the API?

### ISSUE THREAD

**Issue by morpheus65535** [Diaoul/subliminal#848]
The docs seems to be light on that one or I just don't understand it (that's probably the what's happening here...).

How can I use the provider_configs argument with the download_best_subtitles function? I understand that this argument require a dictionary but how to format it?

Thanks!

**Comment by morpheus65535** [comment]
Ok, finally found it by myself:

    providers_list = ['addic7ed','legendastv','opensubtitles']
    providers_auth = {'addic7ed': {'username': 'test', 'password': 'test'},'legendastv': {'username': 'test', 'password': 'test'},'opensubtitles': {'username': 'test', 'password': 'test'}}

    download_best_subtitles([video], {Language('eng')}, providers=providers_list, provider_configs=providers_auth)

Hope it help other in the future!

**Comment by mohammad-aqajani** [comment]
it does not work for me? version 2.0.5
download_best_subtitle needs class_pool argument from ProviderPool class, which is not callable from the subliminal core.
