### ISSUE TITLE
No data returned from provider addic7ed provider

### ISSUE THREAD

**Issue by xp-1000** [Diaoul/subliminal#851]
Hello here,
I try to download subtitle with subliminal from addic7ed for tvshow "Lucifer" but it does not seem to find the existing subtitle : 

> subliminal --addic7ed user pass --debug download -p addic7ed -l en  -l fr Lucifer.S03E08.720p.HDTV.x264.mkv -v -v  -f
> Collecting videos  [####################################]  100%  Lucifer.S03E08.720p.HDTV.x264.mkvDEBUG:subliminal.cli:Collecting path Lucifer.S03E08.720p.HDTV.x264.mkv
> INFO:subliminal.core:Scanning video 'Lucifer.S03E08.720p.HDTV.x264.mkv' in ''
> DEBUG:subliminal.core:Size is 1336962048
> DEBUG:subliminal.core:Computed hashes {'opensubtitles': 'f754cec48b0c67ad', 'shooter': 'f0cb47a9a029eaa47e77f8f9f5e82129;3e5b97a28988cde50a5056dfda526160;327863ea27be74353ca5572617f17844;d042bb653b5f8698e0a7185bdcf0f835', 'thesubdb': '787d94ae2fa930d43a242a15d349fe77', 'napiprojekt': 'f2057e5afc49d562c62dda82be171e66'}
> INFO:subliminal.core:Refining video with metadata
> DEBUG:subliminal.refiners.metadata:Found resolution 720p
> DEBUG:subliminal.refiners.metadata:Found video_codec h264
> DEBUG:subliminal.refiners.metadata:Found audio_codec AC3
> DEBUG:subliminal.refiners.metadata:MKV has no subtitle track
> INFO:subliminal.core:Refining video with tvdb
> INFO:subliminal.refiners.tvdb:Searching series 'Lucifer'
> DEBUG:subliminal.refiners.tvdb:Found 2 results
> DEBUG:subliminal.refiners.tvdb:Found exact match on series 'Lucifer'
> DEBUG:subliminal.refiners.tvdb:Found series {'id': 295685, 'seriesName': 'Lucifer', 'aliases': [], 'banner': 'graphical/295685-g5.jpg', 'seriesId': '196146', 'status': 'Continuing', 'firstAired': '2016-01-25', 'network': 'FOX (US)', 'networkId': '', 'runtime': '45', 'genre': ['Crime', 'Fantasy'], 'overview': "Lucifer is the charming, charismatic and handsome-as-hell original fallen angel, who, bored and unhappy in Hell, takes refuge in Los Angeles, where he uses his gift of persuasion to punish bad guys. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.", 'lastUpdated': 1512413484, 'airsDayOfWeek': 'Monday', 'airsTime': '8:00 PM', 'rating': 'TV-14', 'imdbId': 'tt4052886', 'zap2itId': 'EP02183864', 'added': '2015-05-11 05:59:47', 'addedBy': 379124, 'siteRating': 8.3, 'siteRatingCount': 71}
> INFO:subliminal.refiners.tvdb:Getting series episode 3x8
> DEBUG:subliminal.refiners.tvdb:Found episode {'id': 6275104, 'airedSeason': 3, 'airedSeasonID': 714272, 'airedEpisodeNumber': 8, 'episodeName': 'Chloe Does Lucifer', 'firstAired': '2017-11-20', 'guestStars': ['Mikaela Hoover', 'Michael Rady'], 'director': 'Louis Milito', 'directors': ['Louis Milito'], 'writers': ['Julia Fontana'], 'overview': 'When a murder is connected to a celebrity dating app, Lucifer and Chloe question all they know about the world of social media in order to solve the case. Meanwhile, Ella tries to avoid Charlotte, and Amenadiel helps Linda deal with the death of her ex-husband.', 'language': {'episodeName': 'en', 'overview': 'en'}, 'productionCode': 'T13.20755', 'showUrl': '', 'lastUpdated': 1511869791, 'dvdDiscid': '', 'dvdSeason': 3, 'dvdEpisodeNumber': 8, 'dvdChapter': None, 'absoluteNumber': 39, 'filename': 'episodes/295685/6275104.jpg', 'seriesId': 295685, 'lastUpdatedBy': 458706, 'airsAfterSeason': None, 'airsBeforeSeason': None, 'airsBeforeEpisode': None, 'thumbAuthor': 450357, 'thumbAdded': '2017-11-21 17:16:16', 'thumbWidth': '400', 'thumbHeight': '225', 'imdbId': 'tt6552842', 'siteRating': 8, 'siteRatingCount': 5}
> INFO:subliminal.core:Refining video with omdb
> DEBUG:subliminal.refiners.omdb:No need to search
> Collecting videos  [####################################]  100%
> 1 video collected / 0 video ignored / 0 error
> Downloading subtitles  [####################################]  100%  Lucifer.S03E08.720p.HDTV.x264.mkvINFO:subliminal.core:Listing subtitles with provider 'addic7ed' and languages {<Language [en]>}
> INFO:subliminal.core:Initializing provider addic7ed
> INFO:subliminal.providers.addic7ed:Logging in
> DEBUG:subliminal.providers.addic7ed:Logged in
> DEBUG:subliminal.providers.addic7ed:Getting show id with year
> DEBUG:subliminal.providers.addic7ed:Getting show id
> INFO:subliminal.providers.addic7ed:Getting the page of show id 5346, season 3
> DEBUG:subliminal.providers.addic7ed:No data returned from provider
> Downloading subtitles  [####################################]  100%
> DEBUG:subliminal.core:Terminating initialized providers
> INFO:subliminal.core:Terminating provider addic7ed
> INFO:subliminal.providers.addic7ed:Logging out
> DEBUG:subliminal.providers.addic7ed:Logged out
> 0 subtitle downloaded for Lucifer.S03E08.720p.HDTV.x264.mkv

As you can see it found the right tv show from the file name and associate the right id and season for addict7d (5346) but the result is "No data returned from provider".

However subtitles exist : http://www.addic7ed.com/show/5346
Other providers like opensubtitles works fine.

> subliminal --version
> subliminal, version 2.1.0.dev

Thanks for help.

**Comment by fernandog** [comment]
Addic7ed is blocking subliminal. Need to wait and try again later
