### ISSUE TITLE
[Docker] UNRAR tool not available

### ISSUE THREAD

**Issue by febox6** [Diaoul/subliminal#853]
legendastv is not working in docker version of subliminal:

  File "/usr/src/app/subliminal/providers/legendastv.py", line 175, in __init__
    raise ConfigurationError('UNRAR tool not available')
subliminal.exceptions.ConfigurationError: UNRAR tool not available
INFO:subliminal.core:Discarding provider legendastv

How can I fix this? Thanks.

**Comment by fernandog** [comment]
@febox6 it needs the unrar tool to extract the .rar files from ltv. Who created the image? you need to ask to add the unrar

**Comment by febox6** [comment]
It's the official container by Diaoul: https://hub.docker.com/r/diaoulael/subliminal/

**Comment by fernandog** [comment]
I will ask him

**Comment by febox6** [comment]
ok,thanks

**Comment by abescalamis** [comment]
I'm having this same issue too, Hope that Diaol adds the unrar tool soon.

**Comment by fernandog** [comment]
@Diaoul can you add please?

**Comment by ratoaq2** [comment]
I fixed the Dockerfile with b98ae76bf2d89aacc49eaeb2d516c83e7014e1e1
I believe the docker images will be updated automatically.

**Comment by ratoaq2** [comment]
@diaoul could you update the docker image? Or make it to build automatically?

**Comment by Diaoul** [comment]
It should already build automatically, I'll check

**Comment by ratoaq2** [comment]
No, it's not updating automatically. Last one was Nov 2018

**Comment by Diaoul** [comment]
I've triggered one manually and linked my GH account as GitHub Services have been deprecated and don't work anymore.

**Comment by ratoaq2** [comment]
Thanks,
Fixed with b98ae76

`docker pull diaoulael/subliminal`
