### ISSUE TITLE
[Info request] Discarding providers

### ISSUE THREAD

**Issue by h3llrais3r** [Diaoul/subliminal#854]
I'm currently using subliminal in API mode and I'm using the provider pool with OpenSubtitles and Addic7ed.
When I start a search (let's say on about 50 video files), the discarded providers are reset to be able to start with a clean pool.
At the end of each run, almost each time both providers are discarded...
In the beginning of the run, both providers are working fine, but after some time (after checking for certain video files) they are discarded (probably due to too many requests in short period of time?).
The problem I have now is that the last video files are never checked, because the providers are already discarded at the time they are searched...

In the past I was not using the pool for the complete batch run, but a clean pool for each individual video subtitle check. This makes sure that for each video file at least a search is done. But this also slows down the process a lot because each provider must be initialized each time. This gives also a lot more discarded provider errors in the logs for a complete batch run...

Any idea on how I could improve this?

**Comment by Diaoul** [comment]
With subliminal 3.0 with coroutines and throttling. Don't hold your breath though.

**Comment by h3llrais3r** [comment]
Thanks, but any idea with the current (develop) version?
Or can I only implement the throttling myself for now?

**Comment by Diaoul** [comment]
There will be the option to use a token bucket or leaky bucket algorithm depending on the provider. This should avoid a lot of discarding providers.

**Comment by h3llrais3r** [comment]
Thanks again. Will have a look at it myself to implement this myself for now until 3.0 is available.
Looking forward to this release.
