### ISSUE TITLE
[Info request] Addic7ed provider 304 responses

### ISSUE THREAD

**Issue by h3llrais3r** [Diaoul/subliminal#856]
I notice that I get a lot of 304 responses from the Addic7ed provider.
The last develop version of subliminal, already takes care of this for not discarding the provider.
However, a 304 always gives an empty response, so no content is returned.
Since I'm using subliminal in api mode, I want to get the response anyway, even with a 304.
I propose to implement a caching on the requets for Addic7ed, which should cache the responses as long as the server would return a 304. 
Does anyone have an idea how long it takes until Addic7ed returns a 200 again instead of a 304?
If yes, we can use requests_cache for this, which makes sure that we always get a response (also for a 304 because the 200 will have been cached before)

Changes in addic7ed.py provider
```
from requests_cache import CachedSession
...
def initialize(self):
    self.session = CachedSession(cache_name='subliminal.addic7ed.cache', expire_after=600)
    self.session.headers['User-Agent'] = 'Subliminal/%s' % __short_version__
```

What do you think of this proposal? If you agree, I can make the PR.
I already tested it in my tool, and I get now the cached response in case of a 304.

The only thing left is the timeout (I took now 10 minutes)...Does anyone has an idea?

PS: I only checked it on Addic7ed because that's the one I'm using. I don't know if this also happens on other providers. If yes, perhaps we can make it global for all providers?

**Comment by fernandog** [comment]
The 304 with no content is addic7ed blocking the subliminal

**Comment by h3llrais3r** [comment]
Ok, so wouldn't the cache be a solution for that?

**Comment by fernandog** [comment]
How cache something you never got a valid response? The block can be in any request, include de sub download

**Comment by h3llrais3r** [comment]
I've just changed the 'User-Agent' and I'm still getting the 304... So how is Addic7ed knowing it's still subliminal?

**Comment by h3llrais3r** [comment]
Only changing the user agent seems to fix the 304 responses temporarily.
