### ISSUE TITLE
[question] Is it possible to specify a different score (--min-score) for TV series and movies ?

### ISSUE THREAD

**Issue by marcelpaulo** [Diaoul/subliminal#857]
I assume that `--min-score` aplies equally to both TV series and movies. Is it possible to specify a different minimum score for TV series and movies ? It has happened to me that, by specifying a very stringent minimum score, such as `--min-score 98`, to ensure that TV series such as _Chance_ or _Happy_ get the correct subtitles, I fail to get subtitles for movies. I get the impression that the ideal scenario would be to use a higher minimum score for TV series and a lower one for movies.

**EDIT:** I should confess that I never quite understood the meaning of the number used in `--min-score`, since the scores calculated by subliminal, as I see when I run `subliminal --debug`, are not in the 0—100 range

**Comment by fernandog** [comment]
@marcelpaulo this is how score is calculated:

#: Scores for episodes
episode_scores = {'hash': 359, 'series': 180, 'year': 90, 'season': 30, 'episode': 30, 'release_group': 15,
                  'format': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}

#: Scores for movies
movie_scores = {'hash': 119, 'title': 60, 'year': 30, 'release_group': 15,
                'format': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}

Each property that "match" it sums. Max score for episodes is 349 and for movies is 119.
Later subliminal calculates the 0-100 score

A good score for movies it would be: title + year + release_group + format + video_codec = 114, so in 114/119 = 95

The resolution is not mandatory as a subtitle for 720p is the same for 1080p. Audio codec is not mandatory too

**Comment by marcelpaulo** [comment]
Hey @fernandog, thank you so much for taking the time to explain this ! I didn't realize that `--min-score` is actually a percentage.

So, following your reasoning, a good score for an episode would be = series + year + season + episode + release_group + format + video_codec = 354, but this would yield a score of 101. Wouldn't the maximum score for episodes be the sum of all components but the hash = 360, so that a good score for an episode would then be 354/360*100 = 98 ?

If 96 would be a good score for a movie and 98 for an episode, is there a way to specify them like that, a different score for each type of video ? Since, if I specify 96 for both, an episode subtitle wouldn't need to match series + year + season + episode + release_group + format + video_codec.

**Comment by fernandog** [comment]
@marcelpaulo yes, for episodes my suggestion is 98. 

about different score per type, you can't now.
But I suggest keeping episodes in one folder and movies in other
And call subliminal for each directory using different min_scores

**Comment by marcelpaulo** [comment]
Thanks once again, @fernandog ! Good idea about segregating movies/episodes in different folders, I'll do that. I use `mc` with a single user menu action calling subliminal, so I'll split it in 2 actions, each one with a different `--min-score`.
