### ISSUE TITLE
Subliminal cannot handle files with multi episodes with OpenSubtitles provider

### ISSUE THREAD

**Issue by h3llrais3r** [Diaoul/subliminal#858]
When using subliminal in combination with the latest guessit version, there is a problem when the series contains multiple episodes.
Guessit returns a list of episodes, while an int is expected in the ```Video``` class.
Example file: ```Marvels.Agents.of.S.H.I.E.L.D.S05E01-E02.720p.HDTV.x264-AVS.mkv```
```
guessit Marvels.Agents.of.S.H.I.E.L.D.S05E01-E02.720p.HDTV.x264-AVS

For: Marvels.Agents.of.S.H.I.E.L.D.S05E01-E02.720p.HDTV.x264-AVS
GuessIt found: {
    "title": "Marvels Agents of S.H.I.E.L.D.",
    "season": 5,
    "episode": [
        1,
        2
    ],
    "screen_size": "720p",
    "format": "HDTV",
    "video_codec": "h264",
    "release_group": "AVS",
    "type": "episode"
}
```

When searching subtitles with subliminal in combination with opensubtitles provider:

![image](https://user-images.githubusercontent.com/1945295/34260317-bf0b064a-e665-11e7-944c-eb4324a11286.png)

Stack trace:
```
2017-12-21 15:43:32,500 ERROR Unexpected error in provider u'opensubtitles'
Traceback (most recent call last):
  File "C:\Tools\GitHub\Auto-Subliminal\lib\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Tools\GitHub\Auto-Subliminal\lib\subliminal\providers\opensubtitles.py", line 228, in list_subtitles
    query=query, season=season, episode=episode, tag=os.path.basename(video.name))
  File "C:\Tools\GitHub\Auto-Subliminal\lib\subliminal\providers\opensubtitles.py", line 183, in query
    response = checked(self.server.SearchSubtitles(self.token, criteria))
  File "C:\Tools\GitHub\Auto-Subliminal\lib\subliminal\providers\opensubtitles.py", line 295, in checked
    raise OpenSubtitlesError(response['status'])
OpenSubtitlesError: 408 Invalid parameters; episode is not number
```

Addic7ed does not seem to have a problem with it. I did not test other providers.

**Comment by fernandog** [comment]
@opensubtitles hey, how should we handle this? API expect a number but video file is multi-episode, so the parameter `episode` is a list.

**Comment by opensubtitles** [comment]
we are strictly following IMDB numbering. I think it is this: http://www.imdb.com/title/tt2364582/episodes?season=5&ref_=tt_eps_sn_5

There is not possible to add there "1,2". I think correct solution is to query lower number for episode, so 1. The best would be using moviehash of course.
