### ISSUE TITLE
Age filtering when scanning files should use creation date

### ISSUE THREAD

**Issue by MoshiMoshi0** [Diaoul/subliminal#860]
Currently they are filtered by modified date [here](https://github.com/Diaoul/subliminal/blob/develop/subliminal/core.py#L546), but doesn't creation date make more sense? 

If you put/copy new files into the scanned folder they should be treated as new. The modified date will never change unless you re-encode, and that would probably also change the hash and break subtitle detection.

The creation date is platform dependent but I found [this](https://stackoverflow.com/a/39501288) stackoverflow answer with cross-platform code.

edit: Probably better to use creation and modified dates and pick the latest?
So just `max(os.path.getmtime(path), os.path.getctime(path))`

**Comment by ratoaq2** [comment]
The modified date will only change if change the file contents. And as soon you get the file, it will have the current time as modified date (unless you fake it)

So, I still see no reason to not use modification time. It's simpler, cross platform and fits the use case in subliminal

**Comment by huuub** [comment]
And as soon you get the file, it will have the current time as modified date (unless you fake it) -> this is not the default behaviour I see.

**Comment by devcompl** [comment]
> The modified date will only change if change the file contents. 
Exactly, so if you copy a file that you encoded a long time ago subliminal will not pick it up because only the creation time will change.

> And as soon you get the file, it will have the current time as modified date (unless you fake it)
That does not seem to be the case when for example extracting using 7z or winrar. The files have their original modified date and a current creation date.

**Comment by huuub** [comment]
Does anybody have a nice workaround for this?

**Comment by ratoaq2** [comment]
A workaround would be to extract and touch the files
