### ISSUE TITLE
[Q] Not possible to install develop branch.

### ISSUE THREAD

**Issue by darzur** [Diaoul/subliminal#862]
Hi,

Readme says that to install subliminal one have to do:
[sudo] pip install subliminal
This way, sadly, I can only install very outdated 2.0.5 version. Is there a simple way to install develop branch on Raspbian? Have no idea how to do it as it's not listed on PyPi...

**Comment by Diaoul** [comment]
Pip can install from GitHub branch, see [this SO](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch).
