### ISSUE TITLE
Is the filename used to guess the best subtitle for a given movie?

### ISSUE THREAD

**Issue by msdos** [Diaoul/subliminal#863]
I'm using `subliminal` for downloading subtitles and [`Filebot`](https://www.filebot.net) to rename and download metadata. Suppose the following movies:

`A.Bad.Moms.Christmas.2017.1080p.WEB-DL.DD5.1.H264-FGT`

`The.Shape.of.Water.2017.DVDScr.XVID.AC3.HQ.Hive-CM8`

Does subliminal extract all this info from filename ('DVDScr', 'XVID', 'AC3', 'HQ', 'Hive', 'CM8', 'FGT', etc) when trying to guess the best subtitle from all providers? I'm asking this to know if it's better to rename `The.Shape.of.Water.2017.DVDScr.XVID.AC3.HQ.Hive-CM8` to `The Shape of Water (2017)` before or after running subliminal.

**Comment by Diaoul** [comment]
Yes it does [here](http://subliminal.readthedocs.io/en/latest/api/score.html) are the properties extracted to match subtitles. Keeping release groups and quality (source) can significantly improve subliminal's quality.
