### ISSUE TITLE
What does the stable docker image tag correspond to?

### ISSUE THREAD

**Issue by coaxial** [Diaoul/subliminal#864]
The docker image has two tags: stable and latest.

Which version is stable? I couldn't find it in the release or the tags.

Also, would you consider adding more tags, like `latest`, `stable`, `1`, and `2`? This makes it easier when writing docker-compose files: you can pin the version and make sure that if you run it later you won't run into API breaking changes by major version bumps.

**Comment by Diaoul** [comment]
I would say that latest is the develop branch and stable is master but I need to check that.
