### ISSUE TITLE
What are the plans for the fututure?

### ISSUE THREAD

**Issue by morpheus133** [Diaoul/subliminal#865]
Hi!
What are the plans for the next releases? Or is this project dead?
Latest release was  Sep 3 2016 and since that there are a lot of Pull requests.
Are you waiting for something?

**Comment by fernandog** [comment]
@morpheus133 develop is being updated.  @Diaoul is designing the v3 with will improve a lof of code for providers

**Comment by msdos** [comment]
What about doing a release with what's already in the `develop` branch?

**Comment by morpheus65535** [comment]
I second. Doing a version 2.1.0 with a new PYPI package would be much appreciated. 2.0.5 is quite old and users would benefit of improvement.

**Comment by paranoidi** [comment]
Updates would be nice. Current pypi version is broken, has been for couple days, omdbapi returns error 524.

**Comment by varac** [comment]
Ping

**Comment by ratoaq2** [comment]
I'll try to address the issues in the develop branch. I have no permission to do a pypi release.

**Comment by msdos** [comment]
Hi @ratoaq2. Will you receive permission to do a pypi release? I'm not trying to rush things, I'm just interested.

**Comment by Diaoul** [comment]
I can grant you, give me your handle.

**Comment by ratoaq2** [comment]
@diaoul ratoaq2

**Comment by pkuczynski** [comment]
@Diaoul and @ratoaq2 any plans for a new release?

**Comment by diogocp** [comment]
@ratoaq2 any chance you can do a (pre-)release soon? :pray:

**Comment by ratoaq2** [comment]
I don't have an account and rights to do a release. I only have commit rights

**Comment by kronn** [comment]
@ratoaq2 could you create an account on pypi? it seems like @Diaoul is willing to give you permission to release (https://github.com/Diaoul/subliminal/issues/865#issuecomment-487459024). (maybe I read it wrong...)

**Comment by ratoaq2** [comment]
I already mentioned my account in this PR

**Comment by Diaoul** [comment]
:heavy_check_mark: Added collaborator 'ratoaq2'

**Comment by ratoaq2** [comment]
@Diaoul Travis is also disabled:
```
 This is not an active repository

You don't have sufficient rights to enable this repo on Travis.
Please contact the admin to enable it or to receive admin rights yourself. 
```

**Comment by Diaoul** [comment]
Should be ok now. Let me know.
