### ISSUE TITLE
Cannot catch TooManyRequests exception using "try:"

### ISSUE THREAD

**Issue by morpheus65535** [Diaoul/subliminal#875]
I'm trying to catch TooManyRequests exception but I cannot get it to work:

    from subliminal.exceptions import TooManyRequests
    try:
        subtitles = list_subtitles([video], {Language(language)}, providers=providers, provider_configs=providers_auth)
    except TooManyRequests:
            print 'There is a problem...'

I get this in command line:

    Scanning video u'Kaamelott.S01E004.FRENCH.720p.HDTV.x264-MiND.mkv' in u'\\\\serveur\\media\\Series TV\\Kaamelott\\Livre I'
    Listing subtitles for <Episode [u'Kaamelott', 1x4]>
    Listing subtitles with provider u'addic7ed' and languages set([<Language [en]>])
    Initializing provider addic7ed
    Getting the page of show id 3785, season 1
    Unexpected error in provider u'addic7ed'
    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\subliminal\core.py", line 118, in list_subtitles_provider
        return self[provider].list_subtitles(video, provider_languages)
      File "C:\Python27\lib\site-packages\subliminal\providers\addic7ed.py", line 273, in list_subtitles
        return [s for s in self.query(video.series, video.season, video.year)
      File "C:\Python27\lib\site-packages\subliminal\providers\addic7ed.py", line 238, in query
        raise TooManyRequests()
    TooManyRequests
    Discarding provider addic7ed
    Found 0 subtitle(s)
    Terminating provider addic7ed

No trace of my print... what am I doing wrong? Even if a do a general `except`, the exception isn't catched.

**Comment by fernandog** [comment]
We don't raise that anymore in develop branch

**Comment by morpheus65535** [comment]
What if I want to be informed to stop calling this provider for a certain amount of time?

**Comment by fernandog** [comment]
Throttling and other stuff will be available in subliminal v3.
For now we can't

**Comment by morpheus65535** [comment]
Thanks! I look forward this new version... any ETA? 2018? First half? ;-)

**Comment by fernandog** [comment]
Don't know. Diaoul will do it. I'm just helping maintain v2

**Comment by morpheus65535** [comment]
No problem, thanks!
