### ISSUE TITLE
API: is it possible to get the subtitles filename from the provider?

### ISSUE THREAD

**Issue by morpheus65535** [Diaoul/subliminal#899]
Is there a way to get trough the API the filename of a subtitles like it is on the provider website?

Thanks!

**Comment by ratoaq2** [comment]
Added info property in subtitle class.
For some providers it's the filename, for others it's a release info, for others just a hash. 

Fixed by https://github.com/Diaoul/subliminal/commit/40b3c5ba4f0b192bcc68dca6deaed6bc36e8c5e6
