### ISSUE TITLE
ValueError: Insufficient data to process the guess

### ISSUE THREAD

**Issue by lhrique** [Diaoul/subliminal#900]
I have a working environment with Raspberry Pi, Transmission (2.84 - 14307), Flexget (2.11.2) and Subliminal (2.0.5) -- with GuessIt 2.0.4 -- which has been handling all my series downloads and subtitling very well. Nevertheless, a recent download has made a problem arise: "ValueError: Insufficient data to process the guess". I am not sure about why this is hapening with these specific series files, since it is working fine with different ones, but I am failing to figure out what should be done to correct/avoid the problem. Here is one debug output example:

`/usr/local/bin/subliminal --debug --legendastv user pass download -l pt-BR -p legendastv -s -z -v  "/mnt/NAS/NoSubsTVShows/Babylon 5/Season 01/Ep. 02 - Soul Hunter"

Collecting videos  [####################################]  100%  /mnt/NAS/NoSubsTVShows/Babylon 5/Season 01/Ep. 02 - Soul HunterDEBUG:subliminal.cli:Collecting path /mnt/NAS/NoSubsTVShows/Babylon 5/Season 01/Ep. 02 - Soul Hunter

DEBUG:subliminal.core:Walking directory '/mnt/NAS/NoSubsTVShows/Babylon 5/Season 01/Ep. 02 - Soul Hunter'

INFO:subliminal.core:Scanning video 'Babylon5.S01E02.x264.DD.5.1.mkv' in '/mnt/NAS/NoSubsTVShows/Babylon 5/Season 01/Ep. 02 - Soul Hunter'

ERROR:subliminal.core:Error scanning video

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 502, in scan_videos
    video = scan_video(filepath)

  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 380, in scan_video
    video = Video.fromguess(path, guessit(path))

  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 93, in fromguess
    return Episode.fromguess(name, guess)

  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 166, in fromguess
    raise ValueError('Insufficient data to process the guess')

ValueError: Insufficient data to process the guess

Collecting videos  [####################################]  100%     
                                                            
0 video collected / 0 video ignored / 0 error`

**Comment by ratoaq2** [comment]
This is a guessit bug: not able to guess the episode:
guessit "/mnt/NAS/NoSubsTVShows/Babylon 5/Season 01/Ep. 02 - Soul Hunter"
For: /mnt/NAS/NoSubsTVShows/Babylon 5/Season 01/Ep. 02 - Soul Hunter
GuessIt found: {
    "season": 1, 
    "title": "Ep 02", 
    "episode_title": "Soul Hunter", 
    "type": "episode"
}

I'll open a bug in guessit

**Comment by ratoaq2** [comment]
Fixed by latest guessit develop: https://github.com/guessit-io/guessit/issues/590
