### ISSUE TITLE
API get saved subtitles path?

### ISSUE THREAD

**Issue by morpheus65535** [Diaoul/subliminal#901]
Is there a way to get the path of the saved subtitles when saving it with the episode file?

Here's the subtitle_path variable should contain what I need:
https://github.com/Diaoul/subliminal/blob/dd74383d1cba82829ce720f2e439a65d13ffe7ef/subliminal/core.py#L689

**Comment by ratoaq2** [comment]
It's on the top of my list

**Comment by morpheus65535** [comment]
I have it through episode.storage_path in subliminal_patch from Sub-Zero.

**Comment by ratoaq2** [comment]
Now you can get the subtitle path using the method:

```
subtitle.get_path(self, video, single=False)
```

3e3e410a0132faf17a3ed79b0934196a31a72983

**Comment by morpheus65535** [comment]
Thanks!
