### ISSUE TITLE
Too much time is spent here according to profiler.

### ISSUE THREAD

**Issue by gabox01** [Diaoul/subliminal#909]
https://github.com/Diaoul/subliminal/blob/dd74383d1cba82829ce720f2e439a65d13ffe7ef/subliminal/utils.py#L68

Hello. I've tried to run subliminal for a large library and concluded that it is way too slow. Profiler shows that about 90% of the CPU time is spent here. Is it really necessary to generate the hash on 10MB data? If so, could we just leave napiprojekt out from the default configuration?

**Comment by ratoaq2** [comment]
You're right. Subliminal could just compute hashes for the enabled providers

**Comment by ratoaq2** [comment]
Hashes are only computed for requested providers
Fixed by eec2c3211fe876159ccc3f80e43dc5c0bf91191c
