### ISSUE TITLE
Develop branch on Synology

### ISSUE THREAD

**Issue by Fossil01** [Diaoul/subliminal#911]
I installed subliminal using pip on my Synology NAS which results in version 2.0.5 which is very old. I see the develop branch is recently updated. How do I get this on my NAS?

Is there some way to build a pip package?

**Comment by abescalamis** [comment]
I also did install the subliminal using pip, then I realized that it was not working that well, then I tried the Doker version and that one worked way better and has the option to install the developer version.

**Comment by Fossil01** [comment]
I downloaded the repo and ran setup.py, this worked on my stock Synology so all is good.
