### ISSUE TITLE
Searching for "Futurama - S00E03" on Podnapisi takes an unusually long time

### ISSUE THREAD

**Issue by hachel** [Diaoul/subliminal#915]
Hello,

I know this isn't a very detailed description of an issue, but that's because I can't quite figure out what's happening.

Check my log file below for that episode. It's a special episode for the show. If I search it manually on podnapisi I get no results.

If I use subliminal like this: `subliminal --debug download --language en "Futurama - S00E03"` once it gets to podnapisi as a provider it seems to scroll all of the available pages and then starts scoring some results for about 15 minutes.
I don't know what it finds and why it takes so long.

Any help?

Thank you

Here is the debug.log: https://paste.drhack.net/?d2453c65376c48c2#WXAU4HXfYnINy7ulIJAG3n9a1n33X4qdjsqNkE0mBzY=

**Comment by ratoaq2** [comment]
Fixed by #956
