### ISSUE TITLE
Podnapisi.NET JSON API

### ISSUE THREAD

**Issue by MasterMind2k** [Diaoul/subliminal#916]
Hi.

We are experimenting with a JSON api, currently we have these four endpoints ready for JSON response:
  * `/subtitles/search/`
  * `/subtitles/search/advanced` (should be the same as above, only HTML differs)
  * `/subtitles/search/<slug-optional>/<moviedb-publish-id>` (same as first, only exact movie search)
  * `/moviedb/search/`

In short, if requesting a GET call without any additional headers, it will return HTML representation. If adding the header "Accept:application/json" it willl return the results in JSON. A list of supported filters can be seen on the endpoint's HTML page itself. For the "basic" search use that "plus" sign right of "active filters" above the search results.

Please give it a test drive and let us know what is missing, compared to `/ppodnapisi/search` endpoint.

Also note, the basic search has a "smart" keyword parser, the old endpoint does not have it.

**Comment by ratoaq2** [comment]
Is there any documentation about these endpoints?

**Comment by MasterMind2k** [comment]
No official yet.

But all filters can be seen through web search and then apply the Accept header.

**Comment by ratoaq2** [comment]
Fixed by #956
