### ISSUE TITLE
ImportError: cannot import name download_best_subtitles

### ISSUE THREAD

**Issue by eran101** [Diaoul/subliminal#920]
The script in the readme file fails to run with the following error.
Ubuntu 18.04 LTS

> $ python subliminal.py
> Traceback (most recent call last):
>   File "subliminal.py", line 6, in <module>
>     from subliminal import download_best_subtitles, region, save_subtitles, scan_videos
>   File "/home/eran/Downloads/subliminal.py", line 6, in <module>
>     from subliminal import download_best_subtitles, region, save_subtitles, scan_videos
> ImportError: cannot import name download_best_subtitles

**Comment by morpheus65535** [comment]
Personally, I just import the whole subliminal module and it works:

    from subliminal import *
    best_subtitles = download_best_subtitles(...)
