### ISSUE TITLE
Subliminal can`t find subtitle for S.W.A.T. show on legendastv provider

### ISSUE THREAD

**Issue by marcoacarvalho** [Diaoul/subliminal#922]
`subliminal --debug --legendastv username password download /storage/series/S\ W\ A\ T\ 2017/Season\ 01/S.W.A.T.2017.S01E16.READNFO.720p.HDTV.x264-KILLERS.mkv -l pt-BR -p legendastv -s -z -v
Collecting videos  [####################################]  100%  /storage/series/S W A T 2017/Season 01/S.W.A.T.2017.S01E16.READNFO.720p.HDTV.x264-KILLERS.mkvDEBUG:subliminal.cli:Collecting path /storage/series/S W A T 2017/Season 01/S.W.A.T.2017.S01E16.READNFO.720p.HDTV.x264-KILLERS.mkv
INFO:subliminal.core:Scanning video 'S.W.A.T.2017.S01E16.READNFO.720p.HDTV.x264-KILLERS.mkv' in '/storage/series/S W A T 2017/Season 01'
DEBUG:subliminal.core:Size is 1227988978
DEBUG:subliminal.core:Computed hashes {'opensubtitles': '18304087c209f44c', 'shooter': '7c6f048f2182b76ecf4614acac7bbb49;a4af15585435abd17989a5d8328c3fb7;e6b0a08ae730be20c44c541d09a5f2ed;f854562db3d068b6be7e750395ef02e2', 'thesubdb': '6ae7f5f04bc7137ec18382c9d2fb26ca', 'napiprojekt': 'd99a07a2d6ff5247e8ad416b514ba3d9'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found resolution 720p
DEBUG:subliminal.refiners.metadata:Found video_codec h264
DEBUG:subliminal.refiners.metadata:Found audio_codec AC3
DEBUG:subliminal.refiners.metadata:MKV has no subtitle track
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'S W.A.T.'
WARNING:subliminal.refiners.tvdb:No results for series
INFO:subliminal.core:Refining video with omdb
WARNING:subliminal.refiners.omdb:No results for series
Collecting videos  [####################################]  100%
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  S.W.A.T.2017.S01E16.READNFO.720p.HDTV.x264-KILLERS.mkvINFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages {<Language [pt-BR]>}
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.providers.legendastv:Logging in
DEBUG:subliminal.providers.legendastv:Logged in
Downloading subtitles  [####################################]  100%
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider legendastv
INFO:subliminal.providers.legendastv:Logging out
DEBUG:subliminal.providers.legendastv:Logged out
0 subtitle downloaded for S.W.A.T.2017.S01E16.READNFO.720p.HDTV.x264-KILLERS.mkv
`

**Comment by ratoaq2** [comment]
Fixed by latest guessit develop cdea6741f5698ea26f674289260a2220e888d96a
