### ISSUE TITLE
Feature request: parameter to choose between normal and forced subtitles

### ISSUE THREAD

**Issue by morpheus65535** [Diaoul/subliminal#925]
Would it be possible to have a parameter in download_best_subtitles() to return only forced subtitles? You know those that only appear when they speak in a foreign language during a movie or episode?

It's been asked by users there:
https://github.com/morpheus65535/bazarr/issues/88
https://github.com/morpheus65535/bazarr/issues/89

Thanks!

**Comment by jackjohnsonuk** [comment]
Yes, I'd love this too please!
Thanks in advance

**Comment by goose-ws** [comment]
+1 for would really appreciate this feature.

I don't need subtitles for the entire Game Of Thrones episodes, just the parts in Dothraki / Valyrian / other non-english languages.

**Comment by JakeShirley** [comment]
I would also like this.  If this is supposed to be a legit acquisition platform this will be necessary.

**Comment by spaceboy76** [comment]
a setting for forced subs would make this complete

**Comment by PieMistake** [comment]
Looks like someone has written a patch to support it, but it’s failed. 

Any chance someone could take a look? It would be great if we could get support for foreign part (forced) subtitles only.

**Comment by timcoop3r** [comment]
+1
With Plex killing off plugins and no more updates for SubZero I was hoping subliminal supported this so I could use FlexGet to pull in subs instead. I suspect more and more people will now be having these issues unless Plex implements something themselves for Forced subs

**Comment by morpheus65535** [comment]
@timcoop3r if you are using Sonarr or Radarr, you can take a look at Bazarr.

**Comment by JakeShirley** [comment]
@morpheus65535 I tried using Bazarr and ended up here.  The dev won't implement forced subtitles because it uses this package (subliminal) to fetch subtitles and subliminal doesn't support forced subtitles only.

**Comment by morpheus65535** [comment]
@JakeShirley I’m Bazarr main dev and it support forced subtitles since v0.8.0.

**Comment by getzze** [comment]
completed in #1175
