### ISSUE TITLE
(dsm 6.2) user subliminal created by package still in authentication file after uninstall

### ISSUE THREAD

**Issue by yulbeast** [Diaoul/subliminal#927]
This is subliminal package for synology (sorry if wrong place for the issue).

I uninstalled subliminal some time ago, but now I'm getting a critical alert from the new security advisor, pointing that there is an anomalous user in the authentication file: subliminal.

It seems subliminal didn't clean properly after uninstall. 

The user is not in the interface user list ... I supose with command line something could be done, but I don't want to risk corrupting anything.
Would appreciate also any hint on securely removing the user from the auth file.

**Comment by ratoaq2** [comment]
Sorry, wrong repo
This is not the subliminal package for DSM.
