### ISSUE TITLE
pt-BR work with CLI but not with download_best_subtitles()

### ISSUE THREAD

**Issue by morpheus65535** [Diaoul/subliminal#930]
Is there something I am missing?

CLI:
```
subliminal download -l pt-BR "12.Monkeys.S04E01.720p.HDTV.x264-KILLERS[rarbg].mkv"
Collecting videos  [####################################]  100%
1 video collected / 0 video ignored / 0 error
```

Python call to download_best_subtitles():
```
Traceback (most recent call last):
 File "get_subtitle.py", line 39, in download_subtitle
  best_subtitles = download_best_subtitles([video], {Language('pt-BR')}, providers=None)
 File "C:\\Python27\\lib\\site-packages\\babelfish\\language.py", line 82, in __init__
  raise ValueError(\%r is not a valid language\ % language)
ValueError: \pt-BR\ is not a valid language
```

**Comment by morpheus65535** [comment]
If I use this instead, it work but it's strange that CLI and python module do not accept the same thing ('pt-BR'):

    {Language('por', 'BR')}

Maybe something to fix?

**Comment by morpheus65535** [comment]
Even if I use this, providers return me PT subs. There is definitely something wrong.

**Comment by ratoaq2** [comment]
@morpheus65535 this looks odd. I'm a pt-BR native speaker and subliminal works for me without any issues.

**Comment by morpheus65535** [comment]
Did you try this code snippet?
`best_subtitles = download_best_subtitles([video], {Language('pt-BR')}, providers=None)`

**Comment by ratoaq2** [comment]
`Language('pt-BR')` is invalid... it should be `Language('por, 'BR')`
I didn't try it yet

**Comment by morpheus65535** [comment]
Then why does it work with CLI and not with API?

**Comment by ratoaq2** [comment]
The cli uses a static method to parse the language from ietf code: https://github.com/Diaoul/subliminal/blob/develop/subliminal/cli.py#L173

The language constructor doesn't work with ietf. You could use the same : `Language.fromietf('pt-BR')` instead the constructor.

The constructor uses 3-letter ISO-639-3 code
https://github.com/Diaoul/babelfish/blob/f403000dd63092cfaaae80be9f309fd85c7f20c9/babelfish/language.py#L68

**Comment by morpheus65535** [comment]
So this is a normal behavior? It surprising but if it’s normal... ;-)

**Comment by ratoaq2** [comment]
I don't get why it's surprising... cli accepts string and the best way to define a language is ietf code.
Using it as a library, you can create a language object the way you want using the constructor that accepts multiple parameters, or any of the static methods. This is your choice, how to create the language object.

**Comment by morpheus65535** [comment]
Definitely me misunderstanding but based on documentation, I was expecting both CLI and API to be using the same syntaxe for language code. Anyway, I had it working a long time ago using the mentioned fix. Thanks.
