### ISSUE TITLE
ImportError: cannot import name 'NotRarFile'

### ISSUE THREAD

**Issue by kitten77** [Diaoul/subliminal#937]
File "/home/muad/workbench/SickGear/venv/lib/python3.6/site-packages/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/home/muad/workbench/SickGear/venv/lib/python3.6/site-packages/subliminal/core.py", line 14, in <module>
    from rarfile import NotRarFile, RarCannotExec, RarFile
ImportError: cannot import name 'NotRarFile'

**Comment by ratoaq2** [comment]
Reinstall subliminal.
rarfile is a required dependency and it's installed during the installation process

**Comment by ratoaq2** [comment]
Ah, you're using it in sickgear. Open a bug it their repo since they have a missing dependency

**Comment by kitten77** [comment]
I was playing with the idea of upgrading sickgear to python3.x  

```
(tonder37) muad@debian:~/workbench/tonder$ python 
Python 3.7.2+ (default, Feb 27 2019, 15:41:59) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subliminal
>>>
```

Checking with a clean FreeBSD install
 ```
[py_test] muad@home:~ % uname -a
FreeBSD home 12.0-RELEASE-p2 FreeBSD 12.0-RELEASE-p2 GENERIC  amd64
[py_test] muad@home:~ % python
Python 3.7.3 (default, Mar 28 2019, 01:08:45) 
[Clang 6.0.0 (tags/RELEASE_600/final 326565)] on freebsd11
Type "help", "copyright", "credits" or "license" for more information.
>>> import subliminal
>>> 
```
Yeah must be a sickgear problem
