### ISSUE TITLE
Tests fail with guessit >= 3.0.0

### ISSUE THREAD

**Issue by Coacher** [Diaoul/subliminal#938]
Hello.

Steps to reproduce:
- install guessit >= 3.0.0 (current is 3.0.3)
- run subliminal testsuite

Actual results:
- many test failures

Expected results:
- tests pass

Additional info:
OS Gentoo amd64.

**Comment by medariox** [comment]
This is now fixed with: https://github.com/Diaoul/subliminal/pull/936
