### ISSUE TITLE
ValueError: u\'.mk3d\' is not a valid video extension

### ISSUE THREAD

**Issue by smathev** [Diaoul/subliminal#939]
Hi all.

In short, I'm seeing this error in my logs:
subliminal/core.py", line 424, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: u\'.mk3d\' is not a valid video extension'

**To Reproduce**
Create (or have) a movie-file with the extension .mk3d and scan that folder. The error should be in the logs after the scan.

**Software** 
- Bazarr: v0.6.7.1
- OS: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-34-generic x86_64)

Full disclosure, I'm using Bazarr in this test, and the full error is:

|ERROR|BAZARR Error trying to get video information for this file: ("MOVIENAME").mk3d|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 48, in download_subtitle\n    video = scan_video(path)\n  File "/app/bazarr/bazarr/../libs/subliminal/core.py", line 424, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: u\'.mk3d\' is not a valid video extension'|

I was told at Bazarr, that the issue was related to Subliminal so that's why I'm asking here:
https://github.com/morpheus65535/bazarr/issues/240

**Comment by ratoaq2** [comment]
Fixed by 908bc3a885bf89eeeef3348c2b0131befcee918a
