### ISSUE TITLE
CLI question

### ISSUE THREAD

**Issue by edilAraujo** [Diaoul/subliminal#940]
I'm trying to use my opensubtitles login but I think I have the syntax wrong?
This is what I'm trying and getting in return:

`subliminal --language en --opensubtitles "test_user" "password1" download ./Game\ of\ Thrones\ -\ S04E02\ -\ The\ Lion\ and\ the\ Rose.mp4 
Usage: subliminal [OPTIONS] COMMAND [ARGS]...
Try "subliminal --help" for help.

Error: no such option: --language`

**Comment by ratoaq2** [comment]
Just put language parameter after download option:

`subliminal --opensubtitles "test_user" "password1" download --language en ./Game\ of\ Thrones\ -\ S04E02\ -\ The\ Lion\ and\ the\ Rose.mp4`
