### ISSUE TITLE
Use the VIP API server for Opensubtitles VIP Members

### ISSUE THREAD

**Issue by darthShadow** [Diaoul/subliminal#952]
According to the official [docs](http://trac.opensubtitles.org/projects/opensubtitles/wiki/XMLRPC#LogIn), there is a separate API server for VIP members which is supposed to be much more stable and faster. Using this should result in fewer error responses due to server load.

**Comment by ratoaq2** [comment]
I could check and make the required changes, but that will require testing.
Is someone able to test this?

**Comment by darthShadow** [comment]
I do have a VIP account but I am not sure how to go about testing this other than no errors?
