### ISSUE TITLE
How make Subliminal work on docker?

### ISSUE THREAD

**Issue by edjalmobf** [Diaoul/subliminal#954]
I install Docker via LibreELEC repository, and do a `docker pull diaoulael/subliminal` to install.

Until then, okay. But after I do a `docker run --rm --name subliminal diaoulael/subliminal download -p opensubtitles -l en Spider-Man\ Into\ the\ Spider-Verse\ \(2018\)\ WEBDL-1080p.mkv` to download a subtitles, for exemple, and it show this

```
standard_init_linux.go:207: exec user process caused "exec format error"
```
How I can make it work? 
I'm a total noob in Docker, I installed this way because is it the only way I found to install it in LibreELEC. So I just install it with the first command, and did nothing more. I need to do something more to make it work? I don't know how add my user/password in opensubtitles, for exemple.

**Comment by ratoaq2** [comment]
This could be related to libreelec.
Could you provide more info about your env? OS version, docker version, x64 or armhf?

**Comment by edjalmobf** [comment]
My hardware is a Raspberry Pi 3b.
Using LibreELEC v9.0.0
Doing a `uname -a` command show `Linux LibreELEC 4.19.17 #1 SMP Tue Jan 29 11:27:55 EST 2019 armv7l GNU/Linux`
Docker version 18.09.1

So, after do `docker pull diaoulael/subliminal` I need do nothing more configurations? Just use?

**Comment by ratoaq2** [comment]
Just use... I have a pi 3, but with Debian. I'll check if I face the same issue

**Comment by edjalmobf** [comment]
RIght! So when I do `docker pull diaoulael/subliminal` it install python pip too? It need to make work, right?
How I add my user/password in opensubtitles?

**Comment by edjalmobf** [comment]
I searched for this error and the answers is always something like _"seems that the service was of the wrong architecture"_.

**Comment by ratoaq2** [comment]
Currently, the subliminal docker images are not for arm architecture.

**Comment by edjalmobf** [comment]
There's a way to change make an arm version? Because I only find this way to install on LibreELEC. 
LibreELEC dont permit commands like apt-get.

**Comment by edjalmobf** [comment]
I found [this](https://github.com/dtroncy/docker-rpi-subliminal) and it work on Raspberry Pi.
But when I do a command like this `docker run - -rm --name subliminal -v subliminal_cache:/usr/src/cache -it dtroncy/rpi-subliminal download -l en Creed\ \(2015\)\ Bluray-1080p.mkv` (I'm in the folder of the file) it show this
```
Collecting videos  [####################################]  100%  Creed (2015) BlCollecting videos  [####################################]  100%                               
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Creed (2015Downloading subtitles  [####################################]  100%                               
Some providers have been discarded due to unexpected errors: opensubtitles, legendastv
Downloaded 1 subtitle
```
but no subtitles appeared in the folder. Where is download?

**Comment by ratoaq2** [comment]
You need to map a folder inside the container to a folder outside the container

docker run --rm --name subliminal -v subliminal_cache:/usr/src/cache **-v /tvshows:/tvshows** -it dtroncy/rpi-subliminal download -l en **/tvshows/The.Big.Bang.Theory.S05E18.HDTV.x264-LOL.mp4**

**Comment by edjalmobf** [comment]
Yeah! It work :) Thank!

But this message is always shown
`Some providers have been discarded due to unexpected errors: opensubtitles, shooter, legendastv `
I try to make login this way
```
docker run --rm --name subliminal -v subliminal_cache:/usr/src/cache -v /var/media/Seagate\ Backup\ Plus/Kodi/Seriados/The\ Office\ \(US\)/Season\ 8:/var/media/Seagate\ Backup\ Plus/Kodi/Seriados/The\ Office\ \(US\)/Season\ 8 -it dtroncy/rpi-subliminal download -p legendastv username password -l pt-BR /var/media/Seagate\ Backup\ Plus/Kodi/Seriados/The\ Office\ \(US\)/Season\ 8
```
(To see more clearly **download -p legendastv username password -l pt-BR**)

But don't download the subtitle and shows this 
```
Some providers have been discarded due to unexpected errors: legendastv
Downloaded 0 subtitle
```
I'm making login wrong?

**Comment by ratoaq2** [comment]
You need to use the correct command line:

```
subliminal --help
Usage: subliminal [OPTIONS] COMMAND [ARGS]...

  Subtitles, faster than your thoughts.

Options:
  --addic7ed USERNAME PASSWORD    Addic7ed configuration.
  --legendastv USERNAME PASSWORD  LegendasTV configuration.
  --opensubtitles USERNAME PASSWORD
                                  OpenSubtitles configuration.
  --omdb APIKEY                   OMDB API key.
  --cache-dir DIRECTORY           Path to the cache directory.  [default:
                                  /home/jones/.cache/subliminal]
  --debug                         Print useful information for debugging subliminal and for
                                  reporting bugs.
  --version                       Show the version and exit.
  --help                          Show this message and exit.

Commands:
  cache     Cache management.
  download  Download best subtitles.

  Suggestions and bug reports are greatly appreciated: https://github.com/Diaoul/subliminal/
```

```
subliminal download --help
Usage: subliminal download [OPTIONS] PATH...

  Download best subtitles.

  PATH can be an directory containing videos, a video file path or a video file name. It can be
  used multiple times.

  If an existing subtitle is detected (external or embedded) in the correct language, the
  download is skipped for the associated video.

Options:
  -l, --language LANGUAGE         Language as IETF code, e.g. en, pt-BR (can be used multiple
                                  times).  [required]
  -p, --provider [addic7ed|argenteam|legendastv|opensubtitles|podnapisi|shooter|thesubdb|tvsubtitles]
                                  Provider to use (can be used multiple times).
  -r, --refiner [hash|metadata|omdb|tvdb]
                                  Refiner to use (can be used multiple times).
  -a, --age AGE                   Filter videos newer than AGE, e.g. 12h, 1w2d.
  -d, --directory DIR             Directory where to save subtitles, default is next to the video
                                  file.
  -e, --encoding ENC              Subtitle file encoding, default is to preserve original
                                  encoding.
  -s, --single                    Save subtitle without language code in the file name, i.e. use
                                  .srt extension. Do not use this unless your media player
                                  requires it.
  -f, --force                     Force download even if a subtitle already exist.
  -hi, --hearing-impaired         Prefer hearing impaired subtitles.
  -m, --min-score INTEGER RANGE   Minimum score for a subtitle to be downloaded (0 to 100).
  -w, --max-workers INTEGER RANGE
                                  Maximum number of threads to use.
  -z, --archives / -Z, --no-archives
                                  Scan archives for videos (supported extensions: .rar).
                                  [default: True]
  -v, --verbose                   Increase verbosity.
  --help                          Show this message and exit.

```

So, the provider authentication comes first:
`subliminal --legendastv username password`

Then you specify the command: `download`:
`subliminal  --legendastv username password download`

Then you specify the command options/args:
`subliminal  --legendastv username password download -l pt-BR /var/media/Seagate\ Backup\ Plus/Kodi/Seriados/The\ Office\ \(US\)/Season\ 8`

Since you're running the docker image, so you need to have the docker command before:
`docker run --rm --name subliminal -v subliminal_cache:/usr/src/cache -v /var/media:/var/media -it dtroncy/rpi-subliminal`


The final command:
`docker run --rm --name subliminal -v subliminal_cache:/usr/src/cache -v /var/media:/var/media -it dtroncy/rpi-subliminal  --legendastv username password download -l pt-BR /var/media/Seagate\ Backup\ Plus/Kodi/Seriados/The\ Office\ \(US\)/Season\ 8`

**Comment by edjalmobf** [comment]
Thanks for explanation, this shortened my command :) but this issue persists
If I put to download only from this provider
`docker run --rm --name subliminal -v subliminal_cache:/usr/src/cache -v /var/media:/var/media/ -it dtroncy/rpi-subliminal --legendastv username password download -l pt-BR -p legendastv /var/media/Seagate\ Backup\ Plus/Kodi/Seriados/The\ Office\ \(US\)/Season\ 8`
It show
```
Some providers have been discarded due to unexpected errors: legendastv
Downloaded 0 subtitle
```
The same with opensubtitles. And if I not make any login this is showed
`Some providers have been discarded due to unexpected errors: opensubtitles, legendastv`

[I working with @dtroncy](https://github.com/dtroncy/docker-rpi-subliminal/issues/2) and he tested and got the same issue. Look what he said.

> ...I just tested at home but I obtained the same message. After switching to debug mode, I could see the following error:
> SSLError:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)

You know what causing this?

**Comment by ratoaq2** [comment]
Please, post the full debug logs

**Comment by edjalmobf** [comment]
How can I get debugs?

**Comment by ratoaq2** [comment]
`docker run --rm --name subliminal -v subliminal_cache:/usr/src/cache -v /var/media:/var/media -it dtroncy/rpi-subliminal --debug --legendastv username password download -l pt-BR /var/media/Seagate\ Backup\ Plus/Kodi/Seriados/The\ Office\ \(US\)/Season\ 8`

**Comment by edjalmobf** [comment]
Here debug: https://pastebin.com/9S4bYR86

**Comment by ratoaq2** [comment]
Opensubtitles error is related to SSL (https connection), most likely the docker image has no certificates at all, and can't validate any SSL connections.
The legendastv is because `unrar` is not installed in the docker image as well.

So maybe, you could reach the image creator and ask about those 2

**Comment by edjalmobf** [comment]
Thank you very much. 
I asked him for solve and add this. Hope it work to mark this like solved :)

**Comment by edjalmobf** [comment]
@ratoaq2 he fix the SSL issue with opensubtitles and now it's working!
He add unrar too on container but legendastv don't work yet, see the new debug: https://pastebin.com/GRJ57XHq
Can you help?

**Comment by ratoaq2** [comment]
I tried locally and was able to successfully download the subtitle:
```
INFO:subliminal.core:Saving <LegendasTVSubtitle '5a5ab9b04f79b-the office s08e01 720p bluray x265 hevc-frogperson- the list.srt' [pt-BR]> to 'The Office (US) S08E01 720p BluRay x265 HEVC-FrogPerson- The List.pt-BR.srt'
Downloaded 1 subtitle
```

Try to clean the subliminal cache, since it might be conflicting with the cache from the previous release:
```
docker run --rm --name subliminal -v subliminal_cache:/usr/src/cache -v /var/media:/var/media -it dtroncy/rpi-subliminal cache --clear-subliminal
```

**Comment by edjalmobf** [comment]
You're right!
I clean cache and legendastv work!
Thank your very much!

**Comment by edjalmobf** [comment]
The last question.: I noticed a slight delay in a download of a subtitle. I went to look at my provider account and saw that he downloaded several subtitles of the same title to select one. This is normal?
![captura de tela 2019-02-28 as 20 50 03](https://user-images.githubusercontent.com/42322017/53606783-c9e8f280-3b9a-11e9-98e0-69ebde84ea1a.png)
