### ISSUE TITLE
possible to have subtitles scanned on change date instead of Modified

### ISSUE THREAD

**Issue by huuub** [Diaoul/subliminal#958]
I could download a movie. That still has the original "modified" date.
The "changed" date tells me that I just have it, and that I want to have a subtitle for it.
Maybe a nice feature to be able to use the change date instead of the modify?

example : 
```
stat Ratatouille\ -\ 2007\ -\ Bluray-1080p.mkv
  File: Ratatouille - 2007 - Bluray-1080p.mkv
  Size: 7044010134	Blocks: 13757848   IO Block: 4096   regular file
Device: 801h/2049d	Inode: 84935986    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  jeroen)   Gid: (  997/  docker)
Access: 2019-02-25 01:25:20.066981384 +0100
Modify: 2018-11-26 23:40:11.000000000 +0100
Change: 2019-02-25 01:25:14.103183034 +0100
 Birth: -
```

**Comment by ratoaq2** [comment]
Duplicate #860

**Comment by ratoaq2** [comment]
Sorry, this is not a duplicate. It's just related. 
The other issue relates to the creation/birth date.

This one relates to change date. And change date relates to changes in the inode of the file. Every time you change owner or permission, that changes. Why that's better than the modified date?

**Comment by huuub** [comment]
I downloaded this a few days ago. However the modified date (that subliminal uses) is from what is in the zipped files. So I will not get subtitles for it.
That is the point I want to make.
I am not changing permissions a lot, nor the owner. And if it would change it is not a big deal to get the subtitles again.
At this point it does not get them at all :(

**Comment by getzze** [comment]
Definitely related to #860
