### ISSUE TITLE
ImportError: cannot import name download_best_subtitles

### ISSUE THREAD

**Issue by Toniohec** [Diaoul/subliminal#962]
Hi there,
I'm totally new in coding.
I tried to install Subliminal on my Synology DS 418 (DSM 6.2)
I think I succeeded installing pip and thought it was ok with Subliminal but when I run the bash to try it : 
`python /volume1/homes/Toniohec/subliminal.py
`

 it fails with that error :  
```
Traceback (most recent call last):
  File "/volume1/homes/Toniohec/subliminal.py", line 3, in <module>
    from subliminal import download_best_subtitles, region, save_subtitles, scan_videos
  File "/volume1/homes/Toniohec/subliminal.py", line 3, in <module>
    from subliminal import download_best_subtitles, region, save_subtitles, scan_videos
ImportError: cannot import name download_best_subtitles
```

Any idea ?
Cheers !

**Comment by morpheus65535** [comment]
How did you install Subliminal? `pip install subliminal`? It looks like you downloaded source to a directory and just run them from there.

**Comment by ratoaq2** [comment]
Closing this issue since no response to get further info
