### ISSUE TITLE
Refiners: OMDB/TVDB not using timeout for requests

### ISSUE THREAD

**Issue by pannal** [Diaoul/subliminal#965]
OMDB/TVDB refiners implement `Session.timeout` by setting `session.timeout`. `requests.Session` doesn't support an attributed named `timeout`. It expects the timeout to be passed in as a kwarg with the `request` (or supers) method.

Thus, those refiners don't use an explicit timeout at all for their HTTP requests, at the moment.

Using this instead of `requests.Session`, for example, yields the expected result:
```
class TimeoutSession(requests.Session):
    timeout = 10

    def request(self, method, url, *args, **kwargs):
        if kwargs.get('timeout') is None:
            kwargs['timeout'] = self.timeout

        return super(TimeoutSession, self).request(method, url, *args, **kwargs)
```

**Comment by getzze** [comment]
This is fixed in `develop`. Thanks for bringing this up.
