### ISSUE TITLE
Addic7ed not working

### ISSUE THREAD

**Issue by ishigo974** [Diaoul/subliminal#966]
Hi,

I'm using subliminal version 2.0.5 and every time I use it, I have an unexpected error when it comes to retrieve the subtitles from addic7ed. I tried with 2 different accounts, 2 different IP addresses and it's been weeks that it's not working anymore.

This is the error message I get:
```Some providers have been discarded due to unexpected errors: addic7ed```

Do you know what could cause this issue?

Thanks for your help,
Maxime

**Comment by h3llrais3r** [comment]
Same cause as https://github.com/Diaoul/subliminal/issues/964

**Comment by ishigo974** [comment]
So I just have to remove every addic7ed related params from my command? Will it still try with this provider?

**Comment by h3llrais3r** [comment]
You'll have to exclude it from the providers that you are using.

**Comment by ratoaq2** [comment]
Can someone provide more info if Addict7ed is still an issue?

**Comment by marcelpaulo** [comment]
I had stopped using addic7ed. Have tried just now and got this:

```
ERROR:subliminal.utils:Unexpected error. Provider addic7ed
Traceback (most recent call last):
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/core.py", line 67, in __getitem__
    provider.initialize()
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/providers/addic7ed.py", line 107, in initialize
    raise AuthenticationError(self.username)
subliminal.exceptions.AuthenticationError: marcelpaulo
INFO:subliminal.core:Discarding provider addic7ed
```

The command line I used (omitting relevant data):

```
subliminal --debug --addic7ed marcelpaulo xxx --opensubtitles marcelpaulo xxx --legendastv paulo.mc.aragao xxx --omdb xxx download -l en -m 96 -s ./For.Life.S01E11.HDTV.H.264.SVA[EZTV].mkv
```

User/passsord are correct, I managed to log in on their website.

**Comment by halali** [comment]
Addic7ed require captcha now

**Comment by coptere** [comment]
Plugin is broken because of captcha but i submit a patch to use alternative method. Useragent needs to be change and sign in and regexp too. See #973
