### ISSUE TITLE
Remove OpenSubtitles advertising from downloaded subtitles

### ISSUE THREAD

**Issue by 07416** [Diaoul/subliminal#968]
OpenSubtitles adds ad lines to their subtitles:

```
 1
00:00:06,000 --> 00:00:12,074
Advertise your product or brand here
contact www.OpenSubtitles.org today
```

```
295
00:23:31,305 --> 00:23:37,260
Support us and become VIP member 
to remove all ads from www.OpenSubtitles.org
```

Please remove this advertising by default.

The first line advertises third-party domains or promotes the marketing options on OpenSubtitles (as seen in the example).

**Comment by FraMecca** [comment]
I made this for the same reason:
https://github.com/FraMecca/subtitle_cleaner

**Comment by 07416** [comment]
@FraMecca Can you try submitting a pull request for subliminal? I currently clear the ads and do much, much more with [Subtitle Edit](https://www.nikse.dk/SubtitleEdit/).

**Comment by FraMecca** [comment]
I don't think there is any need for a PR. My tool can be used in conjunction with subliminal seamlessly.

**Comment by ratoaq2** [comment]
This is out of scope for subliminal. An external tool can do that.
