### ISSUE TITLE
How better download subtitles?

### ISSUE THREAD

**Issue by edjalmobf** [Diaoul/subliminal#970]
Hello!
I'm having a little bit problem.

Usually new movies are released first in Web-DL quality, so when I download a movie in bluray quality, soon that is released, the subtitles that are available are as of Web-DL version (generally not synced). Subliminal don't wait for bluray subtitles, it downloads the Web-DL versions. There's a way I can prevent this happend? 
If the files has "bluray" in filenames it only download subtitles that has "bluray" in filenames too. This is possible?
Thanks!

**Comment by ratoaq2** [comment]
Subliminal uses a score system. So subtitles that don't match the `source` will get a lower score for the ones that matches. So you should define a minimum score in order to only download the correct subtitles

```
-m, --min-score INTEGER RANGE   Minimum score for a subtitle to be downloaded (0 to 100).
```
