### ISSUE TITLE
Several times got wrong subtitle language and out of sync

### ISSUE THREAD

**Issue by deshah10** [Diaoul/subliminal#980]
Even though I specifically specify, for it to capture English subtitles, i.e.

`subtitles = download_best_subtitles(videos, {Language('eng')})`

Many of the subtitles it obtained were of a foreign language.

Subtitles are also often out of sync.

Please provide instructions, on how I could use this module to make it search for a single video at a time, instead of a whole folder.

**Comment by ratoaq2** [comment]
You first need to define a minimum score to avoid downloading subtitles out of sync:
```
-m, --min-score INTEGER RANGE   Minimum score for a subtitle to be downloaded (0 to 100).
```

And you should also provide debug logs for us to understand which provider is given subtitles in the wrong language.

**Comment by getzze** [comment]
There has been no response for a long time, this can be closed. Open a new issue if the problem persists.
