### ISSUE TITLE
Finding wrong subtitles on some shows

### ISSUE THREAD

**Issue by fuloating** [Diaoul/subliminal#982]
For example  Star_Trek-S1E07-The_Naked_Time-Xvid-5_1-128abrMP3-Slaytanic.avi

I tried `subliminal download -l ja -f -v Star_Trek-S1E07-The_Naked_Time-Xvid-5_1-128abrMP3-Slaytanic.avi`

`subliminal download -l en -f -v Star_Trek-S1E07-The_Naked_Time-Xvid-5_1-128abrMP3-Slaytanic.avi`

`subliminal download -l fi -f -v Star_Trek-S1E07-The_Naked_Time-Xvid-5_1-128abrMP3-Slaytanic.avi`

`subliminal download -l en -w 10 -f -v Star_Trek-S1E07-The_Naked_Time-Xvid-5_1-128abrMP3-Slaytanic.avi`

`subliminal download -l en -f -v "Star Trek S01 E07 The Naked Time"`

`subliminal download -l en -f -v Star_Trek-S1E07-The_Naked_Time` 

but I keep getting some subtitles of a wrong episode. They mention Agmar there, I tried to google out of curiosity what episode that is but I couldn't find. Also the finnish, japanese and english subtitles all seemed to from a different episode, or agmar wasn't mentioned in the finnish subtitle file at least.

How can I get the right ep? I saw the -w flag  and tried with -w 10 and -w 20 and didn't change anything, no idea what's a big value or a default value, saw it mentioned here https://subliminal.readthedocs.io/en/latest/user/cli.html

Also with -v I get same output as without it:
`subliminal download -l en -w 20 -f -v Star_Trek-S1E07-The_Naked_Time-Xvid-5_1-128abrMP3-Slaytanic.avi 
Collecting videos  [####################################]  100%  Star_Trek-S1E07-The_Naked_Time-Xvid-5_1-128abrMP3-SlayCollecting videos  [####################################]  100%                                                                 
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  Star_Trek-S1E07-The_Naked_Time-Xvid-5_1-128abrMP3-Downloading subtitles  [####################################]  100%                                                                 
1 subtitle downloaded for Star_Trek-S1E07-The_Naked_Time-Xvid-5_1-128abrMP3-Slaytanic.avi`

Also interestingly downloading the episodes 1-5 the subtitles were one episode off. The 01 ep srt was the 02 episode and so on. Now after a while I tried downloading 6-10, but they are not one off but sometihng else now...

I haven't logged into any subtitle services with subliminal.

Same problem is with the Outer Limits season 2 at least.

I have an old mini PC with bad processor.

**Comment by infogrind** [comment]
This might be related to #990

**Comment by ratoaq2** [comment]
You need to use the option:
`-m, --min-score INTEGER RANGE   Minimum score for a subtitle to be downloaded (0 to 100).`
