### ISSUE TITLE
not handling spaces in file names

### ISSUE THREAD

**Issue by maityimankalyan** [Diaoul/subliminal#984]
original filename: "D:\Movies\#New\BlacKkKlansman (2018)\BlacKkKlansman (2018).mkv"
used: subliminal.scan_videos(path)
Returned file list: ['D:\\Movies\\#New\\BlacKkKlansman', '(2018)']
* there is no file named "(2018)" in the directory
It's not handling the space in the file name, "...BlacKkKlansman (2018)..."
Can you please fix the issue

**Comment by ratoaq2** [comment]
I'm pretty sure there's no issue.
Most likely the path variable is not a string, but a list. 
Also there's no mention about which subliminal version, which python version and how you're calling subliminal.

**Comment by maityimankalyan** [comment]
Yes, sorry. My bad, you are right, the path was not in a string.
Thanks.
