### ISSUE TITLE
Automatic Sync in subtitle for removing delay

### ISSUE THREAD

**Issue by saurabhjadhav1911** [Diaoul/subliminal#985]
as some subtitles are out of sync from the video file
to correct the time difference between video and subtitle-
we can use cross correlation between the audio of the target video and an audio track of subtitle stored in the server 

the calculated time difference will be notified to server and the subtitle would be rated on the basis of statistics (ie. subtitle which has notified by minimal time differance)

**Comment by ratoaq2** [comment]
I believe this is out of scope for subliminal. Subliminal uses its scoring system to download the proper subtitle for your release. Any subtitle editing or fixing should be done in a separate tool.
