### ISSUE TITLE
Some providers have been discarded due to unexpected errors: podnapisi, addic7ed

### ISSUE THREAD

**Issue by Moltkex** [Diaoul/subliminal#986]
`Some providers have been discarded due to unexpected errors: podnapisi, addic7ed` 
I get that message every time, the program works and it finds the subs but I've no idea why that message appears.

**Comment by MeD93** [comment]
Addicted does not work anymore because of captcha I think with autentification.

**Comment by ratoaq2** [comment]
Please provide debug logs
