### ISSUE TITLE
Guide for writing tests for new provider?

### ISSUE THREAD

**Issue by avraham** [Diaoul/subliminal#988]
I'm coding a new subtitle provider  but I have no clue how to write the tests files. I believe I need to use vcr.py, but that's all I know.
[subdivx provider](https://github.com/avraham/subliminal/tree/add_subdivx)

Any guidelines available?
Thanks

**Comment by ratoaq2** [comment]
When I wrote my first subliminal provider, I just followed the subliminal code as an example. At that time I learned python, pytest and vcr. I would recommend to clone subliminal code and add your provider and tests just following the other providers and tests as an example
