### ISSUE TITLE
Cannot build subliminal GUI with Tkinter and py2app

### ISSUE THREAD

**Issue by LouisBertin** [Diaoul/subliminal#989]
Hi,

I'm trying to build a simple GUI with Tkinter to share subliminal to a large number of people. 

But, when I add subliminal as an import in a Tkinter project (Python 3.7.6) and try to compile it with the latest version of py2app, the generated app crashed immediately. 

Any ideas?

**Comment by ratoaq2** [comment]
Without more information, crash logs, etc... it's hard for people to jump in and help
