### ISSUE TITLE
Opensubtitles returning subtitles for several different episodes for same hash

### ISSUE THREAD

**Issue by infogrind** [Diaoul/subliminal#990]
When debugging why subliminal would download the wrong subtitles for an episode (might be the same issue as observed in https://github.com/Diaoul/subliminal/issues/982), I enabled logging of the XML request (passing `verbose=True` to `xmlrpclib.ServerProxy()`).

I found that for a given hash, opensubtitles will return several movies, with different season/episode numbers. An example can be found in [this gist](https://gist.github.com/infogrind/a74cdb5ee376a90fe25f8bd76209bd88) (search for the hash value `8048bbe7f64448b2` in the response and look at the different names).

I was able to add a simple check for this to the subliminal code by comparing season and episode # of the episode and of the subtitle, and issue a warning if they differ. I think the proper way to address this would be to extend the scoring logic in subliminal to reduce the score if episode and/or season don't match; I think this would improve the subtitle detection quality. (I will do it myself if I get around to it, just wanted to document the issue here first for others to see.)

**Comment by ratoaq2** [comment]
I understand what you explained, but I still don't get why it's actually an issue, since subliminal has a score system and episode and season has a higher score than any quality / source info:

```
episode_scores = {'hash': 809, 'series': 405, 'year': 135, 'country': 135, 'season': 45, 'episode': 45,
                  'release_group': 15, 'streaming_service': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2,
                  'video_codec': 2, 'hearing_impaired': 1}
``` 

So, when you're downloading subtitles a match of series + season + episode will score 495, so you can provide that as a minimum match for you.

**Comment by ratoaq2** [comment]
Sorry, now I understood the issue.
The hash match should be discarded, and let the scoring system handle the rest

**Comment by ratoaq2** [comment]
Could you provide your file name and tell me which of those results is the correct one? I only have the file hash and no way to know which episode number is the right one
